// UI-tekster på bokmål. nn.ts må ha nøyaktig de samme nøklene (sjekkes av typesjekken).
// Plassholdere skrives {navn} og fylles inn av t().
import { arbeidstidNb } from './moduler/arbeidstid.nb.ts';
import { fagNb } from './moduler/fag.nb.ts';
import { laereplanverketNb } from './moduler/laereplanverket.nb.ts';
import { lovNb } from './moduler/lov.nb.ts';
import { opplaeringslopNb } from './moduler/opplaeringslop.nb.ts';

export const nb = {
  app: {
    hoppTilInnhold: 'Hopp til innhold',
    tilbake: 'Tilbake',
    hovedmeny: 'Hovedmeny',
    lasterInn: 'Laster inn …',
    lastefeil: 'Siden kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    provIgjen: 'Prøv igjen',
    tilToppen: 'Til toppen',
    tittelMal: '{side} – {app}',
  },
  nav: {
    hjem: 'Hjem',
    sok: 'Søk',
    favoritter: 'Favoritter',
    innstillinger: 'Innstillinger',
  },
  forside: {
    tittel: 'Forside',
    sokEtikett: 'Søk i {app}',
    sokPlassholder: 'Søk etter tema, begrep eller fag',
    sokKnapp: 'Søk',
    favoritter: 'Favoritter',
    ingenFavoritter: 'Du har ingen favoritter ennå. Trykk på stjernen ved en funksjon eller et begrep for å legge den til her.',
    flere: 'Flere',
    moduler: 'Innhold',
    seAlle: 'Se alle i {kategori}',
    ingenModuler: 'Innholdet er under arbeid. Nye deler kommer etter hvert.',
    stedMerknad: 'Du ser nasjonalt innhold. Lokale regler i fylket eller på skolen kan også gjelde.',
    stedValgt: 'Viser også innhold for {sted}.',
    velgSted: 'Velg fylke og skole',
    forbehold: '{app} er utviklet privat, og opplysningene i appen kan være uriktige.',
  },
  kategorier: {
    arbeidstid: 'Arbeidstid',
    fag: 'Læreplanverket',
    elev: 'Elever og opplæring',
    skolemiljo: 'Skolemiljø',
    felles: 'Oppslag',
    kategoriside: 'Alt i {kategori}',
  },
  sok: {
    tittel: 'Søk',
    etikett: 'Søk etter tema, begrep eller fag',
    plassholder: 'For eksempel «årsramme» eller «skulereglar»',
    skrivForASoke: 'Skriv minst to tegn for å søke. Søket forstår både bokmål og nynorsk.',
    lasterIndeks: 'Gjør klar søket …',
    indeksFeil: 'Søket er ikke tilgjengelig akkurat nå.',
    ingenTreff: 'Ingen treff på «{sok}».',
    antallTreff: '{antall} treff',
    etTreff: '1 treff',
    typer: {
      modul: 'Del av appen',
      funksjon: 'Funksjon',
      begrep: 'Begrep',
      regel: 'Regel',
      fag: 'Fag',
      tilbud: 'Tilbud',
      laereplanverk: 'Overordnet del',
      lov: 'Lov og forskrift',
      side: 'Side',
    },
  },
  favoritter: {
    tittel: 'Favoritter',
    tom: 'Du har ingen favoritter ennå. Trykk på stjernen ved en funksjon, et fag eller et begrep for å legge det til.',
    flyttOpp: 'Flytt «{navn}» opp',
    flyttNed: 'Flytt «{navn}» ned',
    fjern: 'Fjern «{navn}» fra favoritter',
    leggTil: 'Legg til i favoritter',
    fjernKort: 'Fjern fra favoritter',
    utilgjengelig: 'Ikke lenger tilgjengelig',
  },
  innstillinger: {
    tittel: 'Innstillinger',
    malform: {
      legend: 'Målform',
      nb: 'Bokmål',
      nn: 'Nynorsk',
      merknad: 'Lov-, forskrifts- og læreplantekst vises alltid i målformen den er vedtatt i.',
    },
    tema: {
      legend: 'Utseende',
      system: 'Følg systemet',
      lys: 'Lyst',
      mork: 'Mørkt',
    },
    sted: {
      legend: 'Fylke og skole',
      forklaring: 'Velg fylke og skole for å se lokale regler og avtaler der de finnes. Valget lagres bare på denne enheten.',
      fylke: 'Fylke',
      skole: 'Skole',
      ikkeValgt: 'Ikke valgt',
      velgFylkeForst: 'Velg fylke først',
      skoleFritekst: 'Skolens navn',
      skoleFritekstHjelp: 'Skolelisten er ikke tilgjengelig. Skriv inn navnet på skolen.',
      bareNasjonalt: 'Uten valgt fylke vises bare nasjonalt innhold. Lokale regler kan likevel gjelde.',
      fjern: 'Fjern fylke og skole',
      kilde: 'Skolelisten er hentet fra Nasjonalt skoleregister (Udir).',
    },
    data: {
      legend: 'Dine data',
      forklaring: 'Innstillinger og favoritter lagres bare på denne enheten. Du kan ta en kopi og flytte den til en annen enhet.',
      eksporter: 'Last ned kopi',
      importer: 'Hent inn kopi',
      slett: 'Slett alle lokale data',
      slettBekreft: 'Vil du slette innstillinger og favoritter på denne enheten?',
      slettet: 'Lokale data er slettet.',
      importBekreft: 'Vil du erstatte innstillinger og favoritter med innholdet i filen?',
      importOk: 'Kopien er hentet inn.',
      importFeil: 'Filen kunne ikke leses. Velg en fil som er lastet ned fra {app}.',
    },
    lagring: {
      bareMinne: 'Innstillingene kan ikke lagres på denne enheten (for eksempel i privat nettlesing). De gjelder til du lukker appen.',
    },
  },
  om: {
    tittel: 'Om appen',
    versjon: 'Versjon {versjon}',
    innledning:
      '{app} hjelper skoleledere og lærere i videregående opplæring å regne ut, forstå og forklare regelverket rundt lærerstillinger og skolens drift.',
    erklaering: {
      tittel: 'Brukserklæring',
      privat:
        '{app} er utviklet privat. Appen er ikke utgitt av en arbeidsgiver, en fylkeskommune, en arbeidstaker- eller arbeidsgiverorganisasjon eller en offentlig myndighet.',
      garanti:
        'Appen gir ingen garantier. Beregninger og forklaringer kan inneholde feil, være ufullstendige eller bygge på en tolkning som ikke passer i din sak. Appen er ikke en juridisk fasit. Ved tvil eller uenighet gjelder alltid lover, forskrifter og avtaler slik de er vedtatt, og de lokale avtalene og rutinene der du arbeider. Arbeidsplanfunksjonene er illustrasjoner og kalkulatorer, ikke ekte arbeidsplaner.',
      ki: 'Utvikleren har fått støtte fra en KI-assistent for programmering (Claude Code fra Anthropic). Assistenten har skrevet programkoden og testene, lest og sammenstilt kildene og skrevet tekstene, etter bestilling fra utvikleren. Utvikleren har bestemt hva appen skal gjøre, avgjort hvordan reglene skal forstås der de er uklare, og godkjent regneeksemplene som beregningene testes mot. Ikke alle tekster og verdier er gjennomgått av utvikleren i detalj. Appen bruker ikke kunstig intelligens mens du bruker den: tekstene og reglene ligger fast i appen, og de samme tallene gir alltid det samme svaret.',
      grunnlag:
        'Samtidig er appen laget i god tro, som et redskap og et hjelpemiddel. Beregningene og forklaringene bygger på kilder: lover og forskrifter, tariffavtaler, læreplaner og data fra Utdanningsdirektoratet. Hver utregning kan vises trinn for trinn med kilden til hver verdi, slik at du kan kontrollere den selv. Beregningene testes mot regneeksemplene før hver ny versjon, og kildene sjekkes automatisk for endringer hver uke.',
      innspill:
        'Innspill til funksjonaliteten og beskjed om feil tas imot med takk. Du kan melde fra på GitHub (krever en GitHub-konto) eller gi beskjed til den som delte appen med deg.',
      innspillLenke: 'Meld fra på GitHub',
    },
    personvern: {
      tittel: 'Personvern',
      tekst:
        'Appen samler ikke inn opplysninger om deg. Den har ingen innlogging, ingen informasjonskapsler og ingen analyseverktøy. Innstillinger og favoritter lagres bare på enheten din.',
    },
    kreditering: {
      tittel: 'Kreditering',
      tekst:
        'Appen inneholder data fra Utdanningsdirektoratet og Lovdata, tilgjengeliggjort under Norsk lisens for offentlige data (NLOD) 2.0.',
      nlod: 'Les NLOD 2.0',
    },
    kilder: {
      tittel: 'Kilder',
      lenke: 'Se alle kilder og kildestatus',
    },
    kildekode: 'Kildekoden er åpen på GitHub.',
    kildekodeLenke: 'Se kildekoden',
    teknisk: {
      tittel: 'Teknisk informasjon',
      forklaring: 'Nyttig hvis noe ser feil ut på skjermen. Ta gjerne et skjermbilde og send det til appens eier.',
      skjerm: 'Skjerm',
      visning: 'Visningsområde',
      synlig: 'Synlig område',
      kanter: 'Sikre kanter (topp, høyre, bunn, venstre)',
      installert: 'Åpnet som installert app',
      ja: 'ja',
      nei: 'nei',
    },
  },
  kildestatus: {
    tittel: 'Kilder og kildestatus',
    indikator: 'Kildestatus: {status}',
    status: {
      ok: 'alt i orden',
      endret: 'kilde endret',
      feilet: 'sjekk feilet',
      utdatert: 'utdatert',
      ukjent: 'ukjent',
      ikkeSjekket: 'sjekkes ikke ennå',
      skjult: 'varsel skjult',
    },
    forklaring:
      'En automatisk jobb sjekker kildene hver uke. Endrer en kilde seg, blir appens eier varslet og går gjennom innholdet. Innholdet i appen endres aldri automatisk.',
    sistKjort: 'Sist sjekket {dato}.',
    nesteSjekk: 'Neste planlagte sjekk: {dato}.',
    skjulVarsel: 'Skjul varselet til neste sjekk',
    visVarsel: 'Vis varselet igjen',
    skjultForklaring: 'Varselet er skjult på denne enheten til neste kildesjekk.',
    eier: {
      tittel: 'For appens eier',
      tekst: 'Kildesjekken kan kjøres med en gang fra GitHub (krever tilgang til repoet). Statusen her oppdateres noen minutter etter at sjekken er ferdig.',
      lenke: 'Kjør kildesjekken på GitHub',
    },
    utdatertForklaring: 'Det er mer enn {dager} dager siden kildene ble sjekket. Statusen kan være gammel.',
    ingenData: 'Kildestatus er ikke tilgjengelig akkurat nå.',
    merknadEndret: 'Kilden er endret etter at dette ble kontrollert.',
    utgiver: 'Utgiver: {utgiver}',
    lisens: 'Lisens: {lisens}',
    nivaa: 'Nivå: {niva}',
    aapneKilde: 'Åpne kilden',
  },
  komponenter: {
    forklaring: {
      vis: 'Vis forklaring',
      skjul: 'Skjul forklaring',
    },
    hjelp: {
      vis: 'Forklaring: {tema}',
    },
    resultat: {
      kopier: 'Kopier',
      kopiert: 'Kopiert',
      kopierFeilet: 'Kunne ikke kopiere. Marker teksten og kopier den selv.',
      kopiTekst: 'Kopi av utregningen',
      tilResultat: 'Gå til resultatet',
      beregnet: 'Regnet ut med {app} {dato}.',
      forbehold: '{app} er utviklet privat, og opplysningene kan være uriktige.',
      visUtregning: 'Vis utregning',
      skjulUtregning: 'Skjul utregning',
      utregning: 'Utregning',
      formel: 'Formel',
      kilde: 'Kilder',
    },
    tallfelt: {
      ugyldig: 'Skriv inn et tall, for eksempel 12,5.',
      forLite: 'Tallet må være minst {min}.',
      forStort: 'Tallet kan ikke være større enn {maks}.',
    },
    niva: {
      nasjonal: 'Nasjonal',
      fylke: 'Fylke',
      skole: 'Skole',
      lokalVerdi: 'Lokal verdi ({niva})',
    },
    status: {
      kontrollert: 'Kontrollert {dato}',
      kilde_endret: 'Kilden er endret',
      bor_kontrolleres: 'Bør kontrolleres på nytt',
    },
    kilde: {
      punkt: 'punkt {punkt}',
      ukjent: 'Ukjent kilde',
    },
  },
  oppdatering: {
    klar: 'Ny versjon er klar.',
    oppdater: 'Oppdater',
    lukk: 'Senere',
    offlineKlar: 'Appen kan nå brukes uten nett.',
  },
  moduler: {
    laereplanverket: {
      navn: 'Overordnet del',
      beskrivelse: 'Verdier, prinsipper, ferdigheter og temaer.',
    },
    opplaeringslop: {
      navn: 'Opplæringsløp',
      beskrivelse: 'Fag- og timefordelingen: tilbud og timer.',
    },
    begreper: {
      navn: 'Begreper',
      beskrivelse: 'Forklaringer av sentrale begreper.',
    },
    lov: {
      navn: 'Lov og forskrift',
      beskrivelse: 'Opplæringslova, forskriften og andre regler.',
    },
    fag: {
      navn: 'Fag og læreplaner',
      beskrivelse: 'Kompetansemål, vurdering og timer.',
    },
    arbeidstid: {
      navn: 'Arbeidstid (SFS 2213)',
      beskrivelse: 'Arbeidsplan, beskjeftigelse, vikartimer og overtid.',
    },
  },
  arbeidstid: arbeidstidNb,
  fag: fagNb,
  opplaeringslop: opplaeringslopNb,
  laereplanverket: laereplanverketNb,
  lov: lovNb,
  begreper: {
    tittel: 'Begreper',
    filtrer: 'Filtrer begreper',
    ingen: 'Det er ingen begreper her ennå.',
    ingenTreff: 'Ingen begreper passer med «{filter}».',
    ikkeFunnet: 'Fant ikke begrepet.',
    kilder: 'Kilder',
    relatert: 'Se også',
    kildetekst: 'Fra kilden ({spraak})',
    lokalt: 'Gjelder {sted}',
    kodeliste: {
      tittel: {
        fagmerknader: 'FAM-kodene',
        vitnemalsmerknader: 'VMM-kodene',
      },
      sok: 'Søk på kode eller tekst',
      antall: '{antall} koder',
      ingenTreff: 'Ingen gjeldende koder passer med søket.',
      utgatte: 'Utgåtte koder ({antall})',
      grunnskole: 'Grunnskole',
      videregaende: 'Videregående',
      fagopplaering: 'Fagopplæring',
      vitnemal: 'Vitnemål',
      kompetansebevis: 'Kompetansebevis',
      vedlegg: 'Krever vedlegg',
      fraVigo: 'Kodene og tekstene er fra VIGO Kodeverksbase, hentet {dato}.',
      lasterFeil: 'Kodene kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    },
  },
  ikkeFunnet: {
    tittel: 'Fant ikke siden',
    tekst: 'Siden finnes ikke, eller den er ikke tilgjengelig ennå.',
    tilForsiden: 'Til forsiden',
  },
  spraak: {
    nb: 'bokmål',
    nn: 'nynorsk',
    se: 'nordsamisk',
    en: 'engelsk',
  },
  felles: {
    kilder: 'Kilder',
    lukk: 'Lukk',
    eksternLenke: '(åpnes på {nettsted})',
  },
  utvikling: {
    tittel: 'Komponentkatalog',
    innledning: 'Eksempler på felles komponenter. Siden finnes bare i utvikling og testing.',
    forklaringTittel: 'Hva er en årsramme?',
    forklaringTekst: 'Eksempeltekst som er skjult til brukeren åpner den.',
    tallfeltEtikett: 'Timer per uke',
    tallfeltEnhet: 'timer',
    resultatTittel: 'Stillingsprosent',
    resultatSteg1: 'Årstimer delt på årsramme',
    resultatSteg2: 'Gjort om til prosent',
  },
};
