// UI-tekster på bokmål. nn.ts må ha nøyaktig de samme nøklene (sjekkes av typesjekken).
// Plassholdere skrives {navn} og fylles inn av t().
import { arbeidstidNb } from './moduler/arbeidstid.nb.ts';
import { fagNb } from './moduler/fag.nb.ts';
import { laereplanverketNb } from './moduler/laereplanverket.nb.ts';
import { fylkerNb } from './moduler/fylker.nb.ts';
import { kalenderNb } from './moduler/kalender.nb.ts';
import { lovNb } from './moduler/lov.nb.ts';
import { opplaeringslopNb } from './moduler/opplaeringslop.nb.ts';
import { inntakNb } from './moduler/inntak.nb.ts';
import { eksamenNb } from './moduler/eksamen.nb.ts';
import { statistikkNb } from './moduler/statistikk.nb.ts';
import { skolemiljoNb } from './moduler/skolemiljo.nb.ts';
import { tilretteleggingNb } from './moduler/tilrettelegging.nb.ts';
import { vurderingNb } from './moduler/vurdering.nb.ts';

export const nb = {
  app: {
    hoppTilInnhold: 'Hopp til innhold',
    testversjon: 'Testversjon. Den er ikke publisert, og innstillingene her lagres for seg.',
    tilbake: 'Tilbake',
    hovedmeny: 'Hovedmeny',
    lasterInn: 'Laster inn …',
    lastefeil: 'Siden kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    provIgjen: 'Prøv igjen',
    tilToppen: 'Til toppen',
    tittelMal: '{side} – {app}',
  },
  nav: {
    sok: 'Søk',
    innstillinger: 'Innstillinger',
  },
  forside: {
    sidekolonne: 'Sidekolonne',
    panel: {
      legend: 'Vis øverst',
      navn: 'Kalender og tall',
      navnMedNyheter: 'Kalender, nyheter og tall',
      neste: 'Kalender',
      nyheter: 'Nyheter',
      itall: 'I tall',
      nyheterTittel: 'Siste nytt',
      nyheterSammendrag: 'Kommer i fase 7b',
      nyheterSkisse: 'Skisse: Her kommer de siste nyhetene fra Udir, Lovdata og de andre kildene, med tittel, dato og lenke (fase 7b).',
    },
    visISidekolonne: 'Vis {gruppe} i sidekolonnen',
    tittel: 'Forside',
    sokEtikett: 'Søk i {app}',
    sokPlassholder: 'Søk etter tema, begrep eller fag',
    sokKnapp: 'Søk',
    favoritter: 'Favoritter',
    ingenFavoritter: 'Du har ingen favoritter ennå. Trykk på stjernen ved en funksjon eller et begrep for å legge den til her.',
    flere: 'Flere',
    moduler: 'Innhold',
    seAlle: 'Se alle i {kategori}',
    ingenModuler: 'Innholdet er under arbeid. Nye deler kommer etter hvert.',
    stedKort: 'Nasjonalt innhold',
    stedValgt: 'Viser også innhold for {sted}.',
    velgSted: 'Velg fylke og skole',
    forbehold: '{app} er utviklet privat, og opplysningene i appen kan være uriktige.',
    vis: 'Vis på forsiden',
    visAlt: 'Alt innhold',
    visAltKort: 'Alt',
    visFavoritter: 'Bare favoritter',
    visFavoritterKort: 'Favoritter',
    endreRekkefolgeI: 'Endre rekkefølgen i {gruppe}',
    endreFerdig: 'Ferdig',
    enFavoritt: '1 favoritt',
    antallFavoritter: '{antall} favoritter',
    tilpass: {
      knapp: 'Tilpass',
      ferdig: 'Ferdig',
      tittel: 'Tilpass forsiden',
      hjelp: 'Dra i håndtaket for å flytte en gruppe, eller bruk pilene. Trykk på overskriften til en gruppe på forsiden for å lukke eller åpne den. Favorittene sorteres med «Endre rekkefølge» der de står.',
      grupper: 'Gruppene',
      sidekolonne: 'Sidekolonnen',
      sidekolonneHjelp: 'På stor skjerm står kalenderen, nyhetene, tallene og favorittene i en egen kolonne til høyre.',
      visninger: 'Kalender, nyheter og tall',
      visningerHjelp: 'Velg hva du kan veksle mellom øverst på forsiden, eller øverst i sidekolonnen på stor skjerm. Er bare én valgt, står den uten bryter.',
      visning: {
        neste: 'Neste datoer fra kalenderen',
        nyheter: 'Nyheter',
        itall: 'Videregående i tall',
      },
      nullstill: 'Standard rekkefølge, alle grupper åpne',
    },
  },
  kategorier: {
    arbeidstid: 'Arbeidstid',
    fag: 'Læreplanverket',
    inntak: 'Inntak og opplæringstilbud',
    elev: 'Elever og opplæring',
    skolemiljo: 'Skolemiljø',
    felles: 'Oppslag',
    kategoriside: 'Alt i {kategori}',
  },
  sok: {
    tittel: 'Søk',
    etikett: 'Søk etter tema, begrep eller fag',
    plassholder: 'For eksempel «årsramme» eller «skulereglar»',
    skrivForASoke: 'Skriv minst to tegn for å søke. Søket forstår både bokmål og nynorsk.',
    lasterIndeks: 'Gjør klar søket …',
    indeksFeil: 'Søket er ikke tilgjengelig akkurat nå.',
    ingenTreff: 'Ingen treff på «{sok}».',
    antallTreff: '{antall} treff',
    etTreff: '1 treff',
    tom: 'Tøm søket',
    lukk: 'Lukk søket',
    visFlere: 'Vis flere treff ({antall} til)',
    filter: {
      etikett: 'Vis treff fra',
      alle: 'Alle',
      sider: 'Sider',
      regelverk: 'Regelverk',
      fag: 'Fag',
      begreper: 'Begreper',
      tilbud: 'Tilbud og skoler',
      fylkeForklaring: 'Viser bare skoler, kontor og lokale forskrifter i {fylke}. Trykk for å se alle fylkene.',
    },
    typer: {
      modul: 'Del av appen',
      veiviser: 'Veiviser',
      kalkulator: 'Kalkulator',
      tidslinje: 'Kalender',
      begrep: 'Begrep',
      fagmerknad: 'Fagmerknad',
      vitnemalsmerknad: 'Vitnemålsmerknad',
      sokerstatus: 'Status på søkerønske',
      kode: 'Karakter/statuskode',
      regel: 'Regel',
      fag: 'Fag',
      tilbud: 'Tilbud',
      laereplanverk: 'Overordnet del',
      lov: 'Regelverk',
      side: 'Side',
      skole: 'Skole',
      kontor: 'Opplæringskontor',
    },
  },
  sorterbar: {
    flyttOpp: 'Flytt «{navn}» opp',
    flyttNed: 'Flytt «{navn}» ned',
  },
  favoritter: {
    tittel: 'Favoritter',
    fjern: 'Fjern «{navn}» fra favoritter',
    leggTil: 'Legg til i favoritter',
    fjernKort: 'Fjern fra favoritter',
    utilgjengelig: 'Ikke lenger tilgjengelig',
  },
  innstillinger: {
    tittel: 'Innstillinger',
    malform: {
      legend: 'Målform',
      nb: 'Bokmål',
      nn: 'Nynorsk',
      merknad: 'Lov-, forskrifts- og læreplantekst vises alltid i målformen den er vedtatt i.',
    },
    tema: {
      legend: 'Utseende',
      system: 'Følg systemet',
      lys: 'Lyst',
      mork: 'Mørkt',
    },
    sted: {
      legend: 'Fylke og skole',
      forklaring: 'Velg fylke og skole for å se lokale regler og avtaler der de finnes. Valget lagres bare på denne enheten.',
      fylke: 'Fylke',
      skole: 'Skole',
      ikkeValgt: 'Ikke valgt',
      velgFylkeForst: 'Velg fylke først',
      skoleFritekst: 'Skolens navn',
      skoleFritekstHjelp: 'Skolelisten er ikke tilgjengelig. Skriv inn navnet på skolen.',
      bareNasjonalt: 'Uten valgt fylke vises bare nasjonalt innhold. Lokale regler kan likevel gjelde.',
      fjern: 'Fjern fylke og skole',
      kilde: 'Skolelisten er hentet fra Nasjonalt skoleregister (Udir).',
      privatskole: 'Privatskole',
      privatskoleHjelp: 'Vis reglene som gjelder privatskoler (privatskolelova og forskriften til den), der de er ulike fra reglene for fylkeskommunale skoler.',
      privatskoleNsr: 'Skolen er en privatskole i Nasjonalt skoleregister. Reglene for privatskoler vises der de er ulike.',
      privatskoleOffentlig: 'Skolen er en offentlig skole i Nasjonalt skoleregister. Slå på bryteren hvis du vil se reglene for privatskoler.',
    },
    data: {
      legend: 'Dine data',
      forklaring: 'Innstillinger og favoritter lagres bare på denne enheten. Du kan ta en kopi og flytte den til en annen enhet.',
      eksporter: 'Last ned kopi',
      importer: 'Hent inn kopi',
      slett: 'Slett alle lokale data',
      slettBekreft: 'Vil du slette innstillinger og favoritter på denne enheten?',
      slettet: 'Lokale data er slettet.',
      importBekreft: 'Vil du erstatte innstillinger og favoritter med innholdet i filen?',
      importOk: 'Kopien er hentet inn.',
      importFeil: 'Filen kunne ikke leses. Velg en fil som er lastet ned fra {app}.',
    },
    lagring: {
      bareMinne: 'Innstillingene kan ikke lagres på denne enheten (for eksempel i privat nettlesing). De gjelder til du lukker appen.',
    },
  },
  flytting: {
    tekst: '{app} har fått ny adresse: {adresse}. Åpne appen der. Innstillingene og favorittene dine blir med. Har du lagt appen på hjemskjermen, legger du den til på nytt fra den nye adressen og sletter den gamle.',
    apne: 'Åpne den nye adressen',
    bekreft: 'Vil du ta med innstillingene og favorittene fra den gamle adressen? Det som er lagret her, blir erstattet.',
    ok: 'Innstillingene og favorittene fra den gamle adressen er tatt med.',
    feil: 'Innstillingene fra den gamle adressen kunne ikke leses. Last ned en kopi der, og hent den inn her.',
  },
  tilbakemelding: {
    tittel: 'Tilbakemelding',
    tekst: 'Har du et spørsmål, et innspill eller funnet en feil? Send en e-post. Skriv ikke navn eller andre personopplysninger om elever eller ansatte.',
    skriv: 'Skriv e-post',
    kopier: 'Kopier adressen',
    kopiert: 'E-postadressen er kopiert. Lim den inn i e-postprogrammet ditt.',
    kopierFeil: 'Adressen kunne ikke kopieres. Bruk «Skriv e-post».',
    emne: 'Tilbakemelding på {app} {versjon}',
    mal: 'Skriv tilbakemeldingen her:',
    versjon: 'Versjon: {versjon}',
    side: 'Siden: {side}',
    fylke: 'Fylket: {fylke}',
  },
  om: {
    tittel: 'Om appen',
    versjon: 'Versjon {versjon}',
    innledning:
      '{app} hjelper skoleledere og lærere i videregående opplæring å regne ut, forstå og forklare regelverket rundt lærerstillinger og skolens drift.',
    erklaering: {
      tittel: 'Brukserklæring',
      privat:
        '{app} er utviklet privat. Appen er ikke utgitt av en arbeidsgiver, en fylkeskommune, en arbeidstaker- eller arbeidsgiverorganisasjon eller en offentlig myndighet.',
      garanti:
        'Appen gir ingen garantier. Beregninger og forklaringer kan inneholde feil, være ufullstendige eller bygge på en tolkning som ikke passer i din sak. Appen er ikke en juridisk fasit. Ved tvil eller uenighet gjelder alltid lover, forskrifter og avtaler slik de er vedtatt, og de lokale avtalene og rutinene der du arbeider. Arbeidsplanfunksjonene er illustrasjoner og kalkulatorer, ikke ekte arbeidsplaner.',
      ki: 'Utvikleren har fått støtte fra en KI-assistent for programmering (Claude Code fra Anthropic). Assistenten har skrevet programkoden og testene, lest og sammenstilt kildene og skrevet tekstene, etter bestilling fra utvikleren. Utvikleren har bestemt hva appen skal gjøre, avgjort hvordan reglene skal forstås der de er uklare, og godkjent regneeksemplene som beregningene testes mot. Ikke alle tekster og verdier er gjennomgått av utvikleren i detalj. Appen bruker ikke kunstig intelligens mens du bruker den: tekstene og reglene ligger fast i appen, og de samme tallene gir alltid det samme svaret.',
      grunnlag:
        'Samtidig er appen laget i god tro, som et redskap og et hjelpemiddel. Beregningene og forklaringene bygger på kilder: lover og forskrifter, tariffavtaler, læreplaner og data fra Utdanningsdirektoratet. Hver utregning kan vises trinn for trinn med kilden til hver verdi, slik at du kan kontrollere den selv. Beregningene testes mot regneeksemplene før hver ny versjon, og kildene sjekkes automatisk for endringer hver uke.',
      innspill:
        'Innspill til funksjonaliteten og beskjed om feil tas imot med takk, på e-post under «Tilbakemelding» nedenfor.',
    },
    personvern: {
      tittel: 'Personvern',
      tekst:
        'Appen samler ikke inn opplysninger om deg. Den har ingen innlogging, ingen informasjonskapsler og ingen analyseverktøy. Innstillinger og favoritter lagres bare på enheten din.',
    },
    kreditering: {
      tittel: 'Kreditering',
      tekst:
        'Appen inneholder data fra Utdanningsdirektoratet og Lovdata, tilgjengeliggjort under Norsk lisens for offentlige data (NLOD) 2.0.',
      elevundersokelsen: 'Resultatene fra Elevundersøkelsen i Skolemiljø og nøkkeltallene fra Udirs statistikkbank: Inneholder data under NLOD, tilgjengeliggjort på data.udir.no.',
      utdanning: 'Yrkene og utdanningsbeskrivelsene i Opplæringstilbud er basert på åpne data fra utdanning.no og er underlagt Norsk lisens for offentlige data (NLOD). Teksten vedlikeholdes på utdanning.no.',
      ndla: 'Navnene på fagene på NDLA er fra Nasjonal digital læringsarena (NDLA), lisensiert under Creative Commons Navngivelse 4.0 (CC BY 4.0).',
      ccby: 'Les CC BY 4.0',
      nlod: 'Les NLOD 2.0',
    },
    kilder: {
      tittel: 'Kilder',
      lenke: 'Se alle kilder og kildestatus',
    },
    kildekode: 'Kildekoden er åpen på GitHub.',
    kildekodeLenke: 'Se kildekoden',
    teknisk: {
      tittel: 'Teknisk informasjon',
      forklaring: 'Nyttig hvis noe ser feil ut på skjermen. Ta gjerne et skjermbilde og send det til appens eier.',
      skjerm: 'Skjerm',
      visning: 'Visningsområde',
      synlig: 'Synlig område',
      kanter: 'Sikre kanter (topp, høyre, bunn, venstre)',
      installert: 'Åpnet som installert app',
      ja: 'ja',
      nei: 'nei',
    },
  },
  kildestatus: {
    tittel: 'Kilder og kildestatus',
    indikator: 'Kildestatus: {status}',
    status: {
      ok: 'alt i orden',
      endret: 'kilde endret',
      feilet: 'sjekk feilet',
      utdatert: 'utdatert',
      ukjent: 'ukjent',
      ikkeSjekket: 'sjekkes ikke ennå',
      skjult: 'varsel skjult',
    },
    forklaring:
      'En automatisk jobb sjekker kildene hver uke. Endrer en kilde seg, blir appens eier varslet og går gjennom innholdet. Innholdet i appen endres aldri automatisk.',
    sistKjort: 'Sist sjekket {dato}.',
    nesteSjekk: 'Neste planlagte sjekk: {dato}.',
    skjulVarsel: 'Skjul varselet til neste sjekk',
    visVarsel: 'Vis varselet igjen',
    skjultForklaring: 'Varselet er skjult på denne enheten til neste kildesjekk.',
    eier: {
      tittel: 'For appens eier',
      tekst: 'Kildesjekken kan kjøres med en gang fra GitHub (krever tilgang til repoet). Statusen her oppdateres noen minutter etter at sjekken er ferdig.',
      lenke: 'Kjør kildesjekken på GitHub',
    },
    utdatertForklaring: 'Det er mer enn {dager} dager siden kildene ble sjekket. Statusen kan være gammel.',
    ingenData: 'Kildestatus er ikke tilgjengelig akkurat nå.',
    merknadEndret: 'Kilden er endret etter at dette ble kontrollert.',
    utgiver: 'Utgiver: {utgiver}',
    lisens: 'Lisens: {lisens}',
    nivaa: 'Nivå: {niva}',
    aapneKilde: 'Åpne kilden',
  },
  komponenter: {
    privatskole: {
      tittel: 'For privatskoler',
      kilderByttet: 'For privatskoler står paragrafene i privatskoleforskrifta.',
      harMerknad: 'Har egne regler for privatskoler',
    },
    veiviser: {
      prosessen: 'Prosessen',
      heleProsessen: 'Hele prosessen',
      kartHjelp: 'Stegene i hver fase, og hvor veien kan ende, avhengig av svarene. Velg et steg for å gå rett dit. Steg med frist har et merke med klokke.',
      kilder: 'Kilder ({antall})',
      faseAv: 'Fase {nr} av {antall}: {fase}',
      faser: 'Fasene i prosessen',
      faseFerdig: 'ferdig',
      faseGjeldende: 'du er her',
      faseSenere: 'senere',
      steg: 'Steg {nr}',
      utfall: 'Her ender veien',
      kanEnde: 'Veien kan ende her',
      veienHit: 'Veien hit',
      tilbakeTil: 'Gå tilbake til «{steg}»',
      ansvar: 'Ansvar',
      dokumentasjon: 'Dokumentasjon',
      frist: 'Frist',
      regelverk: 'I regelverket',
      merOm: 'Mer om dette steget',
      svar: 'Svar',
      dittSvar: 'Svar: {svar}',
      startPaaNytt: 'Start på nytt',
      korrigert: 'Lenken passet ikke helt med veiviseren. Du står på det siste steget lenken førte fram til.',
      oppsummering: 'Oppsummering',
      kopier: 'Kopier oppsummeringen',
      kopiert: 'Kopiert',
      kopierFeilet: 'Kunne ikke kopiere. Marker teksten og kopier den selv.',
      kopiOverskrift: '{tittel} – oppsummering',
      kopiLaget: 'Laget med {app} {dato}. Sjekk kildene før du bruker oppsummeringen.',
      laereplaner: 'Læreplanene ({antall})',
      kompetansegivende: 'Kompetansegivende',
      ikkeKompetansegivende: 'Ikke kompetansegivende',
      vurdering: 'Vurdering: {uttrykk}',
      fagkodene: 'Fagkodene',
      antallFag: '{antall} fag',
      lokalt: 'I {sted}',
      lesHele: 'Les hele steget',
      visMindre: 'Vis mindre',
      tilSporsmalet: 'Til spørsmålet',
      tilSlutten: 'Til der veien ender',
      harLokalt: 'Har lokale regler for {sted}',
      regelverkAntall: 'I regelverket ({antall})',
      visHeleVeien: 'Vis hele veien ({antall} valg til)',
      faseliste: 'Fasene: {faser}',
      antallFaser: '{antall} faser',
      malgruppe: { elever: 'For elever', voksne: 'For voksne' },
    },
    forklaring: {
      vis: 'Vis forklaring',
      skjul: 'Skjul forklaring',
    },
    hjelp: {
      vis: 'Forklaring: {tema}',
    },
    resultat: {
      kopier: 'Kopier',
      kopiert: 'Kopiert',
      kopierFeilet: 'Kunne ikke kopiere. Marker teksten og kopier den selv.',
      kopiTekst: 'Kopi av utregningen',
      tilResultat: 'Gå til resultatet',
      beregnet: 'Regnet ut med {app} {dato}.',
      forbehold: '{app} er utviklet privat, og opplysningene kan være uriktige.',
      visUtregning: 'Vis utregning',
      skjulUtregning: 'Skjul utregning',
      utregning: 'Utregning',
      formel: 'Formel',
      kilde: 'Kilder',
    },
    tallfelt: {
      ugyldig: 'Skriv inn et tall, for eksempel 12,5.',
      forLite: 'Tallet må være minst {min}.',
      forStort: 'Tallet kan ikke være større enn {maks}.',
    },
    niva: {
      nasjonal: 'Nasjonal',
      fylke: 'Fylke',
      skole: 'Skole',
      lokalVerdi: 'Lokal verdi ({niva})',
    },
    status: {
      kontrollert: 'Kontrollert {dato}',
      kilde_endret: 'Kilden er endret',
      bor_kontrolleres: 'Bør kontrolleres på nytt',
    },
    kilde: {
      punkt: 'punkt {punkt}',
      ukjent: 'Ukjent kilde',
      iAppen: 'Les i appen',
    },
  },
  oppdatering: {
    klar: 'Ny versjon er klar.',
    oppdater: 'Oppdater',
    lukk: 'Senere',
    offlineKlar: 'Appen kan nå brukes uten nett.',
  },
  moduler: {
    inntak: {
      navn: 'Inntak',
      beskrivelse: 'Søkerkategorier, rettigheter og frister ved inntak.',
    },
    skolemiljo: {
      navn: 'Skolemiljø',
      beskrivelse: 'Aktivitetsplikten, skoleregler og Elevundersøkelsen.',
    },
    tilrettelegging: {
      navn: 'Tilrettelegging',
      beskrivelse: 'Tilpasset opplæring, individuell tilrettelegging og språkopplæring.',
    },
    vurdering: {
      navn: 'Vurdering',
      beskrivelse: 'Underveis- og sluttvurdering, grunnlag, fravær og orden.',
    },
    eksamen: {
      navn: 'Eksamen og klage',
      beskrivelse: 'Eksamen, fag- og svenneprøven, klage på karakter og datoene.',
    },
    laereplanverket: {
      navn: 'Overordnet del',
      beskrivelse: 'Verdier, prinsipper, ferdigheter og temaer.',
    },
    opplaeringslop: {
      navn: 'Opplæringstilbud',
      beskrivelse: 'Utdanningsprogram og løp, skoler og opplæringskontorer.',
    },
    begreper: {
      navn: 'Begreper',
      beskrivelse: 'Forklaringer av sentrale begreper.',
    },
    kalender: {
      navn: 'Kalender',
      beskrivelse: 'Frister og datoer, med skoleruta.',
    },
    statistikk: {
      navn: 'Videregående i tall',
      beskrivelse: 'Søkere, elever, læreplass, gjennomføring og eksamen.',
    },
    fylker: {
      navn: 'Fylkene',
      beskrivelse: 'Fylkets sider, forskrifter og skoler.',
    },
    lov: {
      navn: 'Regelverk',
      beskrivelse: 'Lov, forskrift og avtaler.',
    },
    fag: {
      navn: 'Fag og læreplaner',
      beskrivelse: 'Kompetansemål, vurdering og timer.',
    },
    arbeidstid: {
      navn: 'Arbeidstid (SFS 2213)',
      beskrivelse: 'Arbeidsplan, beskjeftigelse, vikartimer og overtid.',
    },
  },
  arbeidstid: arbeidstidNb,
  fag: fagNb,
  opplaeringslop: opplaeringslopNb,
  laereplanverket: laereplanverketNb,
  fylker: fylkerNb,
  kalender: kalenderNb,
  lov: lovNb,
  tilrettelegging: tilretteleggingNb,
  skolemiljo: skolemiljoNb,
  vurdering: vurderingNb,
  eksamen: eksamenNb,
  statistikk: statistikkNb,
  inntak: inntakNb,
  begreper: {
    tittel: 'Begreper',
    filtrer: 'Filtrer begreper',
    ingen: 'Det er ingen begreper her ennå.',
    ingenTreff: 'Ingen begreper passer med «{filter}».',
    tema: {
      etikett: 'Vis begreper om',
      vis: 'Tema: {tema}',
      alle: 'Alle',
      inntak: 'Inntak og tilbud',
      fag: 'Læreplanverket',
      tilrettelegging: 'Tilrettelegging',
      vurdering: 'Vurdering og eksamen',
      skolemiljo: 'Skolemiljø',
      arbeidstid: 'Arbeidstid',
      forvaltning: 'Regelverk',
      ingen: 'Ingen begreper har dette temaet.',
    },
    ikkeFunnet: 'Fant ikke begrepet.',
    kilder: 'Kilder',
    relatert: 'Se også',
    kildetekst: 'Fra kilden ({spraak})',
    lokalt: 'Gjelder {sted}',
    kodegrupper: {
      tittel: 'Kodene',
    },
    kodeliste: {
      tittel: {
        fagmerknader: 'FAM-kodene',
        vitnemalsmerknader: 'VMM-kodene',
        sokerstatuser: 'Statuskodene',
      },
      sok: 'Søk på kode eller tekst',
      antall: '{antall} koder',
      enKode: '1 kode',
      ingenTreff: 'Ingen gjeldende koder passer med søket.',
      utgatte: 'Utgåtte koder ({antall})',
      grunnskole: 'Grunnskole',
      videregaende: 'Videregående',
      fagopplaering: 'Fagopplæring',
      vitnemal: 'Vitnemål',
      kompetansebevis: 'Kompetansebevis',
      elevplass: 'Elevplass',
      laereplass: 'Læreplass',
      vedlegg: 'Krever vedlegg',
      fraVigo: 'Kodene og tekstene er fra VIGO Kodeverksbase, hentet {dato}.',
      lasterFeil: 'Kodene kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    },
  },
  ikkeFunnet: {
    tittel: 'Fant ikke siden',
    tekst: 'Siden finnes ikke, eller den er ikke tilgjengelig ennå.',
    tilForsiden: 'Til forsiden',
  },
  spraak: {
    nb: 'bokmål',
    nn: 'nynorsk',
    se: 'nordsamisk',
    en: 'engelsk',
  },
  felles: {
    plassering: 'Plassering',
    kilder: 'Kilder',
    lukk: 'Lukk',
    eksternLenke: '(åpnes på {nettsted})',
  },
  utvikling: {
    tittel: 'Komponentkatalog',
    innledning: 'Eksempler på felles komponenter. Siden finnes bare i utvikling og testing.',
    forklaringTittel: 'Hva er en årsramme?',
    forklaringTekst: 'Eksempeltekst som er skjult til brukeren åpner den.',
    tallfeltEtikett: 'Timer per uke',
    tallfeltEnhet: 'timer',
    resultatTittel: 'Stillingsprosent',
    resultatSteg1: 'Årstimer delt på årsramme',
    resultatSteg2: 'Gjort om til prosent',
  },
};
