// UI-tekster på bokmål. nn.ts må ha nøyaktig de samme nøklene (sjekkes av typesjekken).
// Plassholdere skrives {navn} og fylles inn av t().

export const nb = {
  app: {
    hoppTilInnhold: 'Hopp til innhold',
    tilbake: 'Tilbake',
    hovedmeny: 'Hovedmeny',
    lasterInn: 'Laster inn …',
    lastefeil: 'Siden kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    provIgjen: 'Prøv igjen',
    tittelMal: '{side} – {app}',
  },
  nav: {
    hjem: 'Hjem',
    sok: 'Søk',
    favoritter: 'Favoritter',
    innstillinger: 'Innstillinger',
  },
  forside: {
    tittel: 'Forside',
    sokEtikett: 'Søk i {app}',
    sokPlassholder: 'Søk etter tema, begrep eller fag',
    sokKnapp: 'Søk',
    favoritter: 'Favoritter',
    ingenFavoritter: 'Du har ingen favoritter ennå. Trykk på stjernen ved en funksjon eller et begrep for å legge den til her.',
    alleFavoritter: 'Alle favoritter',
    hurtig: 'Hurtigkalkulatorer',
    moduler: 'Innhold',
    seAlle: 'Se alle i {kategori}',
    ingenModuler: 'Innholdet er under arbeid. Nye deler kommer etter hvert.',
    stedMerknad: 'Du ser nasjonalt innhold. Lokale regler i fylket eller på skolen kan også gjelde.',
    stedValgt: 'Viser også innhold for {sted}.',
    velgSted: 'Velg fylke og skole',
  },
  kategorier: {
    arbeidstid: 'Arbeidstid',
    fag: 'Fag og vurdering',
    elev: 'Elever og opplæring',
    skolemiljo: 'Skolemiljø',
    felles: 'Oppslag',
    kategoriside: 'Alt i {kategori}',
  },
  sok: {
    tittel: 'Søk',
    etikett: 'Søk etter tema, begrep eller fag',
    plassholder: 'For eksempel «årsramme» eller «skulereglar»',
    skrivForASoke: 'Skriv minst to tegn for å søke. Søket forstår både bokmål og nynorsk.',
    lasterIndeks: 'Gjør klar søket …',
    indeksFeil: 'Søket er ikke tilgjengelig akkurat nå.',
    ingenTreff: 'Ingen treff på «{sok}».',
    antallTreff: '{antall} treff',
    etTreff: '1 treff',
    typer: {
      modul: 'Del av appen',
      funksjon: 'Funksjon',
      begrep: 'Begrep',
      regel: 'Regel',
      fag: 'Fag',
      side: 'Side',
    },
  },
  favoritter: {
    tittel: 'Favoritter',
    tom: 'Du har ingen favoritter ennå. Trykk på stjernen ved en funksjon, et fag eller et begrep for å legge det til.',
    flyttOpp: 'Flytt «{navn}» opp',
    flyttNed: 'Flytt «{navn}» ned',
    fjern: 'Fjern «{navn}» fra favoritter',
    leggTil: 'Legg til i favoritter',
    fjernKort: 'Fjern fra favoritter',
    utilgjengelig: 'Ikke lenger tilgjengelig',
  },
  innstillinger: {
    tittel: 'Innstillinger',
    malform: {
      legend: 'Målform',
      nb: 'Bokmål',
      nn: 'Nynorsk',
      merknad: 'Lov-, forskrifts- og læreplantekst vises alltid i målformen den er vedtatt i.',
    },
    tema: {
      legend: 'Utseende',
      system: 'Følg systemet',
      lys: 'Lyst',
      mork: 'Mørkt',
    },
    sted: {
      legend: 'Fylke og skole',
      forklaring: 'Velg fylke og skole for å se lokale regler og avtaler der de finnes. Valget lagres bare på denne enheten.',
      fylke: 'Fylke',
      skole: 'Skole',
      ikkeValgt: 'Ikke valgt',
      velgFylkeForst: 'Velg fylke først',
      skoleFritekst: 'Skolens navn',
      skoleFritekstHjelp: 'Skolelisten er ikke tilgjengelig. Skriv inn navnet på skolen.',
      bareNasjonalt: 'Uten valgt fylke vises bare nasjonalt innhold. Lokale regler kan likevel gjelde.',
      fjern: 'Fjern fylke og skole',
      kilde: 'Skolelisten er hentet fra Nasjonalt skoleregister (Udir).',
    },
    data: {
      legend: 'Dine data',
      forklaring: 'Innstillinger og favoritter lagres bare på denne enheten. Du kan ta en kopi og flytte den til en annen enhet.',
      eksporter: 'Last ned kopi',
      importer: 'Hent inn kopi',
      slett: 'Slett alle lokale data',
      slettBekreft: 'Vil du slette innstillinger og favoritter på denne enheten?',
      slettet: 'Lokale data er slettet.',
      importBekreft: 'Vil du erstatte innstillinger og favoritter med innholdet i filen?',
      importOk: 'Kopien er hentet inn.',
      importFeil: 'Filen kunne ikke leses. Velg en fil som er lastet ned fra {app}.',
    },
    lagring: {
      bareMinne: 'Innstillingene kan ikke lagres på denne enheten (for eksempel i privat nettlesing). De gjelder til du lukker appen.',
    },
  },
  om: {
    tittel: 'Om appen',
    versjon: 'Versjon {versjon}',
    innledning:
      '{app} hjelper skoleledere og lærere i videregående opplæring å regne ut, forstå og forklare regelverket rundt lærerstillinger og skolens drift.',
    ansvar: {
      tittel: 'Kildene gjelder foran appen',
      tekst:
        'Appen er ikke en juridisk fasit. Den forklarer regelverket og viser kildene. Ved tvil eller uenighet gjelder alltid lover, forskrifter og avtaler slik de er vedtatt. Arbeidsplanfunksjonene er illustrasjoner og kalkulatorer, ikke ekte arbeidsplaner.',
    },
    innhold: {
      tittel: 'Hvordan innholdet lages',
      tekst:
        'Alle tekster er skrevet og gjennomgått på forhånd. Appen bruker ikke kunstig intelligens mens du bruker den. Innhold som ikke er kontrollert ennå, er merket «ikke kontrollert».',
    },
    personvern: {
      tittel: 'Personvern',
      tekst:
        'Appen samler ikke inn opplysninger om deg. Den har ingen innlogging, ingen informasjonskapsler og ingen analyseverktøy. Innstillinger og favoritter lagres bare på enheten din.',
    },
    kreditering: {
      tittel: 'Kreditering',
      tekst:
        'Appen inneholder data fra Utdanningsdirektoratet og Lovdata, tilgjengeliggjort under Norsk lisens for offentlige data (NLOD) 2.0.',
      nlod: 'Les NLOD 2.0',
    },
    kilder: {
      tittel: 'Kilder',
      lenke: 'Se alle kilder og kildestatus',
    },
    kildekode: 'Kildekoden er åpen på GitHub.',
    kildekodeLenke: 'Se kildekoden',
    teknisk: {
      tittel: 'Teknisk informasjon',
      forklaring: 'Nyttig hvis noe ser feil ut på skjermen. Ta gjerne et skjermbilde og send det til appens eier.',
      skjerm: 'Skjerm',
      visning: 'Visningsområde',
      synlig: 'Synlig område',
      kanter: 'Sikre kanter (topp, høyre, bunn, venstre)',
      installert: 'Åpnet som installert app',
      ja: 'ja',
      nei: 'nei',
    },
  },
  kildestatus: {
    tittel: 'Kilder og kildestatus',
    indikator: 'Kildestatus: {status}',
    status: {
      ok: 'alt i orden',
      endret: 'kilde endret',
      feilet: 'sjekk feilet',
      utdatert: 'utdatert',
      ukjent: 'ukjent',
      ikkeSjekket: 'sjekkes ikke ennå',
      skjult: 'varsel skjult',
    },
    forklaring:
      'En automatisk jobb sjekker kildene hver uke. Endrer en kilde seg, blir appens eier varslet og går gjennom innholdet. Innholdet i appen endres aldri automatisk.',
    sistKjort: 'Sist sjekket {dato}.',
    nesteSjekk: 'Neste planlagte sjekk: {dato}.',
    skjulVarsel: 'Skjul varselet til neste sjekk',
    visVarsel: 'Vis varselet igjen',
    skjultForklaring: 'Varselet er skjult på denne enheten til neste kildesjekk.',
    eier: {
      tittel: 'For appens eier',
      tekst: 'Kildesjekken kan kjøres med en gang fra GitHub (krever tilgang til repoet). Statusen her oppdateres noen minutter etter at sjekken er ferdig.',
      lenke: 'Kjør kildesjekken på GitHub',
    },
    utdatertForklaring: 'Det er mer enn {dager} dager siden kildene ble sjekket. Statusen kan være gammel.',
    ingenData: 'Kildestatus er ikke tilgjengelig akkurat nå.',
    merknadEndret: 'Kilden er endret etter at dette ble kontrollert.',
    utgiver: 'Utgiver: {utgiver}',
    lisens: 'Lisens: {lisens}',
    nivaa: 'Nivå: {niva}',
    aapneKilde: 'Åpne kilden',
  },
  komponenter: {
    forklaring: {
      vis: 'Vis forklaring',
      skjul: 'Skjul forklaring',
    },
    resultat: {
      visUtregning: 'Vis utregning',
      skjulUtregning: 'Skjul utregning',
      utregning: 'Utregning',
      kilde: 'Kilde',
    },
    tallfelt: {
      ugyldig: 'Skriv inn et tall, for eksempel 12,5.',
      forLite: 'Tallet må være minst {min}.',
      forStort: 'Tallet kan ikke være større enn {maks}.',
    },
    niva: {
      nasjonal: 'Nasjonal',
      fylke: 'Fylke',
      skole: 'Skole',
      lokalVerdi: 'Lokal verdi ({niva})',
    },
    status: {
      utkast: 'Ikke kontrollert',
      kontrollert: 'Kontrollert {dato}',
      kilde_endret: 'Kilden er endret',
      bor_kontrolleres: 'Bør kontrolleres på nytt',
    },
    kilde: {
      punkt: 'punkt {punkt}',
      ukjent: 'Ukjent kilde',
    },
  },
  oppdatering: {
    klar: 'Ny versjon er klar.',
    oppdater: 'Oppdater',
    lukk: 'Senere',
    offlineKlar: 'Appen kan nå brukes uten nett.',
  },
  moduler: {
    begreper: {
      navn: 'Begreper',
      beskrivelse: 'Forklaringer av sentrale begreper i regelverket.',
    },
  },
  begreper: {
    tittel: 'Begreper',
    filtrer: 'Filtrer begreper',
    ingen: 'Det er ingen begreper her ennå.',
    ingenTreff: 'Ingen begreper passer med «{filter}».',
    ikkeFunnet: 'Fant ikke begrepet.',
    kilder: 'Kilder',
    relatert: 'Se også',
    kildetekst: 'Fra kilden ({spraak})',
    lokalt: 'Gjelder {sted}',
  },
  ikkeFunnet: {
    tittel: 'Fant ikke siden',
    tekst: 'Siden finnes ikke, eller den er ikke tilgjengelig ennå.',
    tilForsiden: 'Til forsiden',
  },
  spraak: {
    nb: 'bokmål',
    nn: 'nynorsk',
    se: 'nordsamisk',
    en: 'engelsk',
  },
  felles: {
    kilder: 'Kilder',
    lukk: 'Lukk',
    eksternLenke: '(åpnes på {nettsted})',
  },
  utvikling: {
    tittel: 'Komponentkatalog',
    innledning: 'Eksempler på felles komponenter. Siden finnes bare i utvikling og testing.',
    forklaringTittel: 'Hva er en årsramme?',
    forklaringTekst: 'Eksempeltekst som er skjult til brukeren åpner den.',
    tallfeltEtikett: 'Timer per uke',
    tallfeltEnhet: 'timer',
    resultatTittel: 'Stillingsprosent',
    resultatSteg1: 'Årstimer delt på årsramme',
    resultatSteg2: 'Gjort om til prosent',
  },
};
