// UI-tekstar på nynorsk. Typen Tekster gjer at ein manglande nøkkel gir byggjefeil.
import type { Tekster } from './typer.ts';
import { arbeidstidNn } from './moduler/arbeidstid.nn.ts';
import { fagNn } from './moduler/fag.nn.ts';
import { laereplanverketNn } from './moduler/laereplanverket.nn.ts';
import { lovNn } from './moduler/lov.nn.ts';
import { opplaeringslopNn } from './moduler/opplaeringslop.nn.ts';
import { inntakNn } from './moduler/inntak.nn.ts';
import { tilretteleggingNn } from './moduler/tilrettelegging.nn.ts';
import { vurderingNn } from './moduler/vurdering.nn.ts';

export const nn: Tekster = {
  app: {
    hoppTilInnhold: 'Hopp til innhald',
    testversjon: 'Testversjon. Han er ikkje publisert, og innstillingane her blir lagra for seg.',
    tilbake: 'Tilbake',
    hovedmeny: 'Hovudmeny',
    lasterInn: 'Lastar inn …',
    lastefeil: 'Sida kunne ikkje lastast. Sjekk nettsambandet og prøv igjen.',
    provIgjen: 'Prøv igjen',
    tilToppen: 'Til toppen',
    tittelMal: '{side} – {app}',
  },
  nav: {
    sok: 'Søk',
    innstillinger: 'Innstillingar',
  },
  forside: {
    tittel: 'Framside',
    sokEtikett: 'Søk i {app}',
    sokPlassholder: 'Søk etter tema, omgrep eller fag',
    sokKnapp: 'Søk',
    favoritter: 'Favorittar',
    ingenFavoritter: 'Du har ingen favorittar enno. Trykk på stjerna ved ein funksjon eller eit omgrep for å leggje han til her.',
    flere: 'Fleire',
    moduler: 'Innhald',
    seAlle: 'Sjå alle i {kategori}',
    ingenModuler: 'Innhaldet er under arbeid. Nye delar kjem etter kvart.',
    stedKort: 'Nasjonalt innhald',
    stedValgt: 'Viser også innhald for {sted}.',
    velgSted: 'Vel fylke og skule',
    forbehold: '{app} er utvikla privat, og opplysningane i appen kan vere uriktige.',
    vis: 'Vis på framsida',
    visAlt: 'Alt innhald',
    visAltKort: 'Alt',
    visFavoritter: 'Berre favorittar',
    visFavoritterKort: 'Favorittar',
    endreRekkefolgeI: 'Endre rekkjefølgja i {gruppe}',
    endreFerdig: 'Ferdig',
    enFavoritt: '1 favoritt',
    antallFavoritter: '{antall} favorittar',
    tilpass: {
      knapp: 'Tilpass',
      ferdig: 'Ferdig',
      tittel: 'Tilpass framsida',
      hjelp: 'Dra i handtaket for å flytte ei gruppe, eller bruk pilene. Trykk på overskrifta til ei gruppe på framsida for å lukke eller opne ho. Favorittane blir sorterte med «Endre rekkjefølgje» der dei står.',
      grupper: 'Gruppene',
      nullstill: 'Standard rekkjefølgje, alle grupper opne',
    },
  },
  kategorier: {
    arbeidstid: 'Arbeidstid',
    fag: 'Læreplanverket',
    inntak: 'Inntak og opplæringstilbod',
    elev: 'Elevar og opplæring',
    skolemiljo: 'Skulemiljø',
    felles: 'Oppslag',
    kategoriside: 'Alt i {kategori}',
  },
  sok: {
    tittel: 'Søk',
    etikett: 'Søk etter tema, omgrep eller fag',
    plassholder: 'Til dømes «årsramme» eller «skoleregler»',
    skrivForASoke: 'Skriv minst to teikn for å søkje. Søket forstår både bokmål og nynorsk.',
    lasterIndeks: 'Gjer klar søket …',
    indeksFeil: 'Søket er ikkje tilgjengeleg akkurat no.',
    ingenTreff: 'Ingen treff på «{sok}».',
    antallTreff: '{antall} treff',
    etTreff: '1 treff',
    tom: 'Tøm søket',
    visFlere: 'Vis fleire treff ({antall} til)',
    filter: {
      etikett: 'Vis treff frå',
      alle: 'Alle',
      sider: 'Sider',
      regelverk: 'Regelverk',
      fag: 'Fag',
      begreper: 'Omgrep',
      tilbud: 'Tilbod og skular',
    },
    typer: {
      modul: 'Del av appen',
      veiviser: 'Vegvisar',
      kalkulator: 'Kalkulator',
      tidslinje: 'Tidslinje',
      begrep: 'Omgrep',
      fagmerknad: 'Fagmerknad',
      vitnemalsmerknad: 'Vitnemålsmerknad',
      sokerstatus: 'Status på søkjarønske',
      kode: 'Karakter/statuskode',
      regel: 'Regel',
      fag: 'Fag',
      tilbud: 'Tilbod',
      laereplanverk: 'Overordna del',
      lov: 'Regelverk',
      side: 'Side',
      skole: 'Skule',
    },
  },
  sorterbar: {
    flyttOpp: 'Flytt «{navn}» opp',
    flyttNed: 'Flytt «{navn}» ned',
  },
  favoritter: {
    tittel: 'Favorittar',
    fjern: 'Fjern «{navn}» frå favorittar',
    leggTil: 'Legg til i favorittar',
    fjernKort: 'Fjern frå favorittar',
    utilgjengelig: 'Ikkje lenger tilgjengeleg',
  },
  innstillinger: {
    tittel: 'Innstillingar',
    malform: {
      legend: 'Målform',
      nb: 'Bokmål',
      nn: 'Nynorsk',
      merknad: 'Lov-, forskrifts- og læreplantekst blir alltid vist i målforma han er vedteken i.',
    },
    tema: {
      legend: 'Utsjånad',
      system: 'Følg systemet',
      lys: 'Lyst',
      mork: 'Mørkt',
    },
    sted: {
      legend: 'Fylke og skule',
      forklaring: 'Vel fylke og skule for å sjå lokale reglar og avtalar der dei finst. Valet blir berre lagra på denne eininga.',
      fylke: 'Fylke',
      skole: 'Skule',
      ikkeValgt: 'Ikkje valt',
      velgFylkeForst: 'Vel fylke først',
      skoleFritekst: 'Namnet på skulen',
      skoleFritekstHjelp: 'Skulelista er ikkje tilgjengeleg. Skriv inn namnet på skulen.',
      bareNasjonalt: 'Utan valt fylke blir berre nasjonalt innhald vist. Lokale reglar kan likevel gjelde.',
      fjern: 'Fjern fylke og skule',
      kilde: 'Skulelista er henta frå Nasjonalt skoleregister (Udir).',
    },
    data: {
      legend: 'Dataa dine',
      forklaring: 'Innstillingar og favorittar blir berre lagra på denne eininga. Du kan ta ein kopi og flytte han til ei anna eining.',
      eksporter: 'Last ned kopi',
      importer: 'Hent inn kopi',
      slett: 'Slett alle lokale data',
      slettBekreft: 'Vil du slette innstillingar og favorittar på denne eininga?',
      slettet: 'Lokale data er sletta.',
      importBekreft: 'Vil du erstatte innstillingar og favorittar med innhaldet i fila?',
      importOk: 'Kopien er henta inn.',
      importFeil: 'Fila kunne ikkje lesast. Vel ei fil som er lasta ned frå {app}.',
    },
    lagring: {
      bareMinne: 'Innstillingane kan ikkje lagrast på denne eininga (til dømes i privat nettlesing). Dei gjeld til du lukkar appen.',
    },
  },
  om: {
    tittel: 'Om appen',
    versjon: 'Versjon {versjon}',
    innledning:
      '{app} hjelper skuleleiarar og lærarar i vidaregåande opplæring å rekne ut, forstå og forklare regelverket rundt lærarstillingar og drifta av skulen.',
    erklaering: {
      tittel: 'Brukserklæring',
      privat:
        '{app} er utvikla privat. Appen er ikkje gitt ut av ein arbeidsgivar, ein fylkeskommune, ein arbeidstakar- eller arbeidsgivarorganisasjon eller ei offentleg styresmakt.',
      garanti:
        'Appen gir ingen garantiar. Utrekningar og forklaringar kan innehalde feil, vere ufullstendige eller byggje på ei tolking som ikkje passar i saka di. Appen er ikkje ein juridisk fasit. Ved tvil eller usemje gjeld alltid lover, forskrifter og avtalar slik dei er vedtekne, og dei lokale avtalane og rutinane der du arbeider. Arbeidsplanfunksjonane er illustrasjonar og kalkulatorar, ikkje ekte arbeidsplanar.',
      ki: 'Utviklaren har fått støtte frå ein KI-assistent for programmering (Claude Code frå Anthropic). Assistenten har skrive programkoden og testane, lese og samanstilt kjeldene og skrive tekstane, etter bestilling frå utviklaren. Utviklaren har bestemt kva appen skal gjere, avgjort korleis reglane skal forståast der dei er uklare, og godkjent reknedøma som utrekningane blir testa mot. Ikkje alle tekstar og verdiar er gjennomgåtte av utviklaren i detalj. Appen bruker ikkje kunstig intelligens medan du bruker han: tekstane og reglane ligg fast i appen, og dei same tala gir alltid det same svaret.',
      grunnlag:
        'Samtidig er appen laga i god tru, som ein reiskap og eit hjelpemiddel. Utrekningane og forklaringane byggjer på kjelder: lover og forskrifter, tariffavtalar, læreplanar og data frå Utdanningsdirektoratet. Kvar utrekning kan visast steg for steg med kjelda til kvar verdi, slik at du kan kontrollere ho sjølv. Utrekningane blir testa mot reknedøma før kvar ny versjon, og kjeldene blir sjekka automatisk for endringar kvar veke.',
      innspill:
        'Innspel til funksjonaliteten og melding om feil blir tekne imot med takk. Du kan melde frå på GitHub (krev ein GitHub-konto) eller gi beskjed til den som delte appen med deg.',
      innspillLenke: 'Meld frå på GitHub',
    },
    personvern: {
      tittel: 'Personvern',
      tekst:
        'Appen samlar ikkje inn opplysningar om deg. Han har inga innlogging, ingen informasjonskapslar og ingen analyseverktøy. Innstillingar og favorittar blir berre lagra på eininga di.',
    },
    kreditering: {
      tittel: 'Kreditering',
      tekst:
        'Appen inneheld data frå Utdanningsdirektoratet og Lovdata, gjorde tilgjengelege under Norsk lisens for offentlege data (NLOD) 2.0.',
      utdanning: 'Yrka og utdanningsbeskrivingane i Opplæringstilbod er baserte på opne data frå utdanning.no og er underlagde Norsk lisens for offentlege data (NLOD). Teksten blir halden ved like på utdanning.no.',
      ndla: 'Namna på faga på NDLA er frå Nasjonal digital læringsarena (NDLA), lisensierte under Creative Commons Namngjeving 4.0 (CC BY 4.0).',
      ccby: 'Les CC BY 4.0',
      nlod: 'Les NLOD 2.0',
    },
    kilder: {
      tittel: 'Kjelder',
      lenke: 'Sjå alle kjelder og kjeldestatus',
    },
    kildekode: 'Kjeldekoden er open på GitHub.',
    kildekodeLenke: 'Sjå kjeldekoden',
    teknisk: {
      tittel: 'Teknisk informasjon',
      forklaring: 'Nyttig viss noko ser feil ut på skjermen. Ta gjerne eit skjermbilete og send det til eigaren av appen.',
      skjerm: 'Skjerm',
      visning: 'Visingsområde',
      synlig: 'Synleg område',
      kanter: 'Sikre kantar (topp, høgre, botn, venstre)',
      installert: 'Opna som installert app',
      ja: 'ja',
      nei: 'nei',
    },
  },
  kildestatus: {
    tittel: 'Kjelder og kjeldestatus',
    indikator: 'Kjeldestatus: {status}',
    status: {
      ok: 'alt i orden',
      endret: 'kjelde endra',
      feilet: 'sjekken feila',
      utdatert: 'utdatert',
      ukjent: 'ukjend',
      ikkeSjekket: 'blir ikkje sjekka enno',
      skjult: 'varsel skjult',
    },
    forklaring:
      'Ein automatisk jobb sjekkar kjeldene kvar veke. Endrar ei kjelde seg, blir eigaren av appen varsla og går gjennom innhaldet. Innhaldet i appen blir aldri endra automatisk.',
    sistKjort: 'Sist sjekka {dato}.',
    nesteSjekk: 'Neste planlagde sjekk: {dato}.',
    skjulVarsel: 'Skjul varselet til neste sjekk',
    visVarsel: 'Vis varselet igjen',
    skjultForklaring: 'Varselet er skjult på denne eininga til neste kjeldesjekk.',
    eier: {
      tittel: 'For eigaren av appen',
      tekst: 'Kjeldesjekken kan køyrast med ein gong frå GitHub (krev tilgang til repoet). Statusen her blir oppdatert nokre minutt etter at sjekken er ferdig.',
      lenke: 'Køyr kjeldesjekken på GitHub',
    },
    utdatertForklaring: 'Det er meir enn {dager} dagar sidan kjeldene vart sjekka. Statusen kan vere gammal.',
    ingenData: 'Kjeldestatus er ikkje tilgjengeleg akkurat no.',
    merknadEndret: 'Kjelda er endra etter at dette vart kontrollert.',
    utgiver: 'Utgjevar: {utgiver}',
    lisens: 'Lisens: {lisens}',
    nivaa: 'Nivå: {niva}',
    aapneKilde: 'Opne kjelda',
  },
  komponenter: {
    veiviser: {
      prosessen: 'Prosessen',
      heleProsessen: 'Heile prosessen',
      kartHjelp: 'Stega i kvar fase, og kvar vegen kan ende, avhengig av svara. Vel eit steg for å gå rett dit. Steg med frist har eit merke med klokke.',
      kilder: 'Kjelder ({antall})',
      faseAv: 'Fase {nr} av {antall}: {fase}',
      faser: 'Fasane i prosessen',
      faseFerdig: 'ferdig',
      faseGjeldende: 'du er her',
      faseSenere: 'seinare',
      steg: 'Steg {nr}',
      utfall: 'Her endar vegen',
      kanEnde: 'Vegen kan ende her',
      veienHit: 'Vegen hit',
      tilbakeTil: 'Gå tilbake til «{steg}»',
      ansvar: 'Ansvar',
      dokumentasjon: 'Dokumentasjon',
      frist: 'Frist',
      regelverk: 'I regelverket',
      merOm: 'Meir om dette steget',
      svar: 'Svar',
      dittSvar: 'Svar: {svar}',
      startPaaNytt: 'Start på nytt',
      korrigert: 'Lenkja passa ikkje heilt med vegvisaren. Du står på det siste steget lenkja førte fram til.',
      oppsummering: 'Oppsummering',
      kopier: 'Kopier oppsummeringa',
      kopiert: 'Kopiert',
      kopierFeilet: 'Kunne ikkje kopiere. Merk teksten og kopier han sjølv.',
      kopiOverskrift: '{tittel} – oppsummering',
      kopiLaget: 'Laga med {app} {dato}. Sjekk kjeldene før du brukar oppsummeringa.',
      laereplaner: 'Læreplanane ({antall})',
      kompetansegivende: 'Kompetansegivande',
      ikkeKompetansegivende: 'Ikkje kompetansegivande',
      vurdering: 'Vurdering: {uttrykk}',
      fagkodene: 'Fagkodane',
      antallFag: '{antall} fag',
      lokalt: 'I {sted}',
      lesHele: 'Les heile steget',
      visMindre: 'Vis mindre',
      tilSporsmalet: 'Til spørsmålet',
      tilSlutten: 'Til der vegen endar',
      harLokalt: 'Har lokale reglar for {sted}',
      regelverkAntall: 'I regelverket ({antall})',
      visHeleVeien: 'Vis heile vegen ({antall} val til)',
      faseliste: 'Fasane: {faser}',
      antallFaser: '{antall} fasar',
      malgruppe: { elever: 'For elevar', voksne: 'For vaksne' },
    },
    forklaring: {
      vis: 'Vis forklaring',
      skjul: 'Skjul forklaring',
    },
    hjelp: {
      vis: 'Forklaring: {tema}',
    },
    resultat: {
      kopier: 'Kopier',
      kopiert: 'Kopiert',
      kopierFeilet: 'Kunne ikkje kopiere. Merk teksten og kopier han sjølv.',
      kopiTekst: 'Kopi av utrekninga',
      tilResultat: 'Gå til resultatet',
      beregnet: 'Rekna ut med {app} {dato}.',
      forbehold: '{app} er utvikla privat, og opplysningane kan vere uriktige.',
      visUtregning: 'Vis utrekning',
      skjulUtregning: 'Skjul utrekning',
      utregning: 'Utrekning',
      formel: 'Formel',
      kilde: 'Kjelder',
    },
    tallfelt: {
      ugyldig: 'Skriv inn eit tal, til dømes 12,5.',
      forLite: 'Talet må vere minst {min}.',
      forStort: 'Talet kan ikkje vere større enn {maks}.',
    },
    niva: {
      nasjonal: 'Nasjonal',
      fylke: 'Fylke',
      skole: 'Skule',
      lokalVerdi: 'Lokal verdi ({niva})',
    },
    status: {
      kontrollert: 'Kontrollert {dato}',
      kilde_endret: 'Kjelda er endra',
      bor_kontrolleres: 'Bør kontrollerast på nytt',
    },
    kilde: {
      punkt: 'punkt {punkt}',
      ukjent: 'Ukjend kjelde',
      iAppen: 'Les i appen',
    },
  },
  oppdatering: {
    klar: 'Ny versjon er klar.',
    oppdater: 'Oppdater',
    lukk: 'Seinare',
    offlineKlar: 'Appen kan no brukast utan nett.',
  },
  moduler: {
    inntak: {
      navn: 'Inntak',
      beskrivelse: 'Søkjarkategoriar, rettar og fristar ved inntak.',
    },
    tilrettelegging: {
      navn: 'Tilrettelegging',
      beskrivelse: 'Tilpassa opplæring, individuell tilrettelegging og språkopplæring.',
    },
    vurdering: {
      navn: 'Vurdering',
      beskrivelse: 'Grunnlag for vurdering, undervegs- og sluttvurdering, fritak, fråvær og orden og oppførsel.',
    },
    laereplanverket: {
      navn: 'Overordna del',
      beskrivelse: 'Verdiar, prinsipp, ferdigheiter og tema.',
    },
    opplaeringslop: {
      navn: 'Opplæringstilbod',
      beskrivelse: 'Utdanningsprogram og løp, skular og opplæringskontor.',
    },
    begreper: {
      navn: 'Omgrep',
      beskrivelse: 'Forklaringar av sentrale omgrep.',
    },
    lov: {
      navn: 'Regelverk',
      beskrivelse: 'Lov, forskrift og avtalar.',
    },
    fag: {
      navn: 'Fag og læreplanar',
      beskrivelse: 'Kompetansemål, vurdering og timar.',
    },
    arbeidstid: {
      navn: 'Arbeidstid (SFS 2213)',
      beskrivelse: 'Arbeidsplan, sysselsetjing, vikartimar og overtid.',
    },
  },
  arbeidstid: arbeidstidNn,
  fag: fagNn,
  opplaeringslop: opplaeringslopNn,
  laereplanverket: laereplanverketNn,
  lov: lovNn,
  tilrettelegging: tilretteleggingNn,
  vurdering: vurderingNn,
  inntak: inntakNn,
  begreper: {
    tittel: 'Omgrep',
    filtrer: 'Filtrer omgrep',
    ingen: 'Det er ingen omgrep her enno.',
    ingenTreff: 'Ingen omgrep passar med «{filter}».',
    ikkeFunnet: 'Fann ikkje omgrepet.',
    kilder: 'Kjelder',
    relatert: 'Sjå også',
    kildetekst: 'Frå kjelda ({spraak})',
    lokalt: 'Gjeld {sted}',
    kodegrupper: {
      tittel: 'Kodane',
    },
    kodeliste: {
      tittel: {
        fagmerknader: 'FAM-kodane',
        vitnemalsmerknader: 'VMM-kodane',
        sokerstatuser: 'Statuskodane',
      },
      sok: 'Søk på kode eller tekst',
      antall: '{antall} kodar',
      enKode: '1 kode',
      ingenTreff: 'Ingen gjeldande kodar passar med søket.',
      utgatte: 'Kodar som har gått ut ({antall})',
      grunnskole: 'Grunnskule',
      videregaende: 'Vidaregåande',
      fagopplaering: 'Fagopplæring',
      vitnemal: 'Vitnemål',
      kompetansebevis: 'Kompetansebevis',
      elevplass: 'Elevplass',
      laereplass: 'Læreplass',
      vedlegg: 'Krev vedlegg',
      fraVigo: 'Kodane og tekstane er frå VIGO Kodeverksbase, henta {dato}.',
      lasterFeil: 'Kodane kunne ikkje lastast. Sjekk nettsambandet og prøv igjen.',
    },
  },
  ikkeFunnet: {
    tittel: 'Fann ikkje sida',
    tekst: 'Sida finst ikkje, eller ho er ikkje tilgjengeleg enno.',
    tilForsiden: 'Til framsida',
  },
  spraak: {
    nb: 'bokmål',
    nn: 'nynorsk',
    se: 'nordsamisk',
    en: 'engelsk',
  },
  felles: {
    plassering: 'Plassering',
    kilder: 'Kjelder',
    lukk: 'Lukk',
    eksternLenke: '(blir opna på {nettsted})',
  },
  utvikling: {
    tittel: 'Komponentkatalog',
    innledning: 'Døme på felles komponentar. Sida finst berre i utvikling og testing.',
    forklaringTittel: 'Kva er ei årsramme?',
    forklaringTekst: 'Dømetekst som er skjult til brukaren opnar han.',
    tallfeltEtikett: 'Timar per veke',
    tallfeltEnhet: 'timar',
    resultatTittel: 'Stillingsprosent',
    resultatSteg1: 'Årstimar delt på årsramme',
    resultatSteg2: 'Gjort om til prosent',
  },
};
