// UI-tekster for arbeidstidsmodulen på bokmål. arbeidstid.nn.ts må ha de samme nøklene.
// Formlene bruker plassholdere med operandenes navn, f.eks. {arstimer}. Appen fyller dem inn to ganger:
// med navnet på størrelsen (formelen) og med tallene (utregningen).

export const arbeidstidNb = {
  tittel: 'Arbeidstid',
  innledning:
    'Kalkulatorer for arbeidstid etter SFS 2213 (arbeidstidsavtalen for undervisningspersonalet) og hovedtariffavtalen i KS-området. Hver utregning viser metoden trinn for trinn og hvor tallene kommer fra.',
  kalkulatorer: {
    tittel: 'Kalkulatorer',
    beskjeftigelse: {
      tittel: 'Beskjeftigelse',
      kort: 'Beskjeftigelse',
      beskrivelse: 'Undervisningsprosent for ett eller flere fag, også blandede grupper.',
    },
    periode: {
      tittel: 'Periodebeskjeftigelse',
      kort: 'Periode',
      beskrivelse: 'Beskjeftigelse for undervisning i en del av skoleåret.',
    },
    vikar: {
      tittel: 'Vikartimer',
      kort: 'Vikartimer',
      beskrivelse: 'Endret beskjeftigelse for ansatte, og lønn for timevikarer.',
    },
    planfestet: {
      tittel: 'Planfestet arbeidstid ved funksjoner',
      kort: 'Planfestet tid',
      beskrivelse: 'Planfestet tid og arbeidsår når undervisningen reduseres for funksjoner eller andre oppgaver.',
    },
    overtid: {
      tittel: 'Overtid ved beskjeftigelse over 100 %',
      kort: 'Overtid',
      beskrivelse: 'Overtidsbetaling for undervisning ut over hel stilling (fast overtid).',
    },
    fordeling: {
      tittel: 'Fordeling av arbeidstiden',
      kort: 'Fordeling',
      beskrivelse: 'Diagram over hvordan årsverket fordeles i en tenkt stilling.',
    },
  },
  felles: {
    periode: 'Regelverk: {periode}',
    gruppe: 'Gruppe {nr}',
    grupper: 'Fag og grupper',
    leggTilGruppe: 'Legg til fag eller gruppe',
    fjernGruppe: 'Fjern gruppe {nr}',
    arsramme: 'Fag, program og trinn (vedlegg 1)',
    arsrammeNr: 'Årsramme {nr}',
    velgArsramme: 'Velg fra vedlegg 1',
    manuellValg: 'Annen årsramme (skriv inn selv)',
    manuellEtikett: 'Årsramme i 60-minutters timer',
    manuellStjerne: 'Faget er merket * i vedlegg 1',
    blandetForklaring: 'Har timen elever fra flere program eller nivåer, legger du til årsrammene for dem. Den laveste brukes.',
    leggTilArsramme: 'Legg til program eller nivå i samme time',
    fjernArsramme: 'Fjern årsramme {nr}',
    elever: 'Faktisk antall elever i klassen',
    eleverHjelp: 'Fag merket * får høyere årsramme når klassen har 1–15 elever.',
    undervisning: 'Undervisning',
    modusArstimer: 'Årstimer',
    modusTimerPeriode: 'Timer i perioden',
    modusOkter: 'Økter per uke',
    arstimer: 'Årstimer (60-minutters timer)',
    arstimerHjelp: 'Timetallet for faget i året, slik Udir oppgir det, f.eks. 140 for engelsk Vg1.',
    okter: 'Økter per uke',
    minutter: 'Minutter per økt',
    uker: 'Antall uker',
    ukerHjelp: 'La stå tomt for hele skoleåret ({uker} uker).',
    ukerPeriode: 'Antall uker i perioden',
    timerIPerioden: 'Timer i perioden (60-minutters timer)',
    manglerInndata: 'Fyll inn feltene over for å se resultatet.',
    grupperad: 'Gruppe {nr}: {tekst}',
    optgruppe: 'Årsramme {t60}/{t45}',
    stjerne: '(*)',
  },
  resultat: {
    beskjeftigelse: 'Beskjeftigelse',
    sumBeskjeftigelse: 'Samlet beskjeftigelse',
    periodebeskjeftigelse: 'Beskjeftigelse i perioden',
    endring: 'Økning i beskjeftigelse',
    samletLonn: 'Samlet avlønning',
    planfestet: 'Planfestet arbeidstid',
    stilling: 'Stilling i alt',
    oversikt: 'Oversikt',
    perUke: 'Per uke i arbeidsåret',
    utvidelse: 'Utvidelse av arbeidsåret',
    ingenUtvidelse: 'Arbeidsåret utvides ikke.',
    kalkulertTid: 'Kalkulert tid',
    timelonn: 'Timelønn',
    lonn: 'Lønn',
    feriepenger: 'Feriepenger',
    funksjonsprosent: 'Funksjon og andre oppgaver',
    overtidstimer: 'Overtidstimer (årsrammetimer)',
    overtidsbetaling: 'Overtidsbetaling',
  },
  advarsler: {
    over_hel_stilling: 'Undervisning og funksjoner er til sammen mer enn en hel stilling.',
    motetid_for_stor: 'Undervisning og møtetid er mer enn den planfestede tiden for undervisningsdelen. Diagrammet viser da ingen annen planfestet tid.',
    mangler_elevtall: 'Faget er merket * i vedlegg 1. Skriv inn antall elever for å se om årsrammen skal økes.',
  },
  feil: {
    regel: 'Utregningen kunne ikke gjøres med regelverket for valgt dato: {melding}',
  },
  vikar: {
    type: 'Hvem tar vikartimene?',
    fast: 'Ansatt i stilling',
    timevikar: 'Timevikar',
    okter: 'Antall vikarøkter',
    lonn: 'Lønn',
    lonnGarantilonn: 'Garantilønn fra hovedtariffavtalen',
    lonnManuell: 'Egen årslønn',
    stillingsgruppe: 'Stillingsgruppe',
    ansiennitet: 'Ansiennitet',
    ansiennitetAr: '{ar} år',
    arslonn: 'Årslønn i kroner',
    arslonnHjelp: 'Brukes når læreren har høyere lønn enn garantilønnen.',
    over60: 'Vikaren er over 60 år (høyere feriepengesats)',
  },
  overtid: {
    beskjeftigelse: 'Samlet beskjeftigelse i prosent',
    beskjeftigelseHjelp: 'Undervisning og funksjoner til sammen, f.eks. 110. Det som er over 100 %, betales som overtid.',
    fag: 'Faget overtiden gjelder (vedlegg 1)',
    ingenOvertid: 'Beskjeftigelsen er ikke over 100 %, så det er ingen overtid.',
  },
  planfestet: {
    reduksjon: 'Hvor mye er undervisningen redusert?',
    iProsent: 'I prosent av full stilling',
    iArsrammetimer: 'I årsrammetimer',
    prosent: 'Reduksjon i prosent',
    prosentHjelp: 'F.eks. 20 for en funksjon på 20 %.',
    arsrammetimer: 'Reduksjon i årsrammetimer (60 min)',
    arsrammetimerHjelp: 'F.eks. 28,5 for kontaktlærer i videregående (SFS 2213 punkt 7.3 b).',
  },
  periode: {
    dager: 'Undervisningsdager i perioden',
    dagerHjelp: 'Tell dagene etter skoleruta.',
    skolear: 'Undervisningsdager i skoleåret',
    skolearHjelp: 'La stå tomt for {dager} dager.',
  },
  fordeling: {
    funksjon: 'Funksjoner og andre oppgaver',
    moter: 'Møtetid per uke (timer)',
    moterHjelp: 'Faste møter i planfestet tid, f.eks. team- og fellesmøter.',
    diagramTittel: 'Fordeling av årsverket',
    diagramBeskrivelse: 'Stolpediagram over årsverket på {timer} timer: {deler}.',
    illustrasjon: 'Illustrasjon av en tenkt stilling. Ikke en arbeidsplan.',
    planfestet: 'Planfestet tid',
    selvdisponert: 'Tid læreren disponerer selv',
    tabell: 'Tallene i diagrammet',
    del: 'Del',
    timer: 'Timer per år',
    andel: 'Andel',
    brukAvTiden: 'Hva tiden brukes til',
    deler: {
      undervisning: 'Undervisning',
      motetid: 'Møtetid',
      annen_planfestet: 'Annen planfestet tid',
      funksjonstid: 'Funksjoner og andre oppgaver',
      selvdisponert: 'Selvdisponert tid',
    },
  },
  metode: {
    tittel: 'Slik regnes det ut',
    kilder: 'Kilder',
    ikkeFunnet: 'Metodebeskrivelsen mangler.',
  },
  utregning: {
    formel: 'Formel',
    innsatt: 'Utregning',
    fra: 'Fra {kilde}',
    inndata: 'skrevet inn',
    rad: 'Vedlegg 1: {rad}',
  },
  trinn: {
    arstimer_fra_okter: { tekst: 'Økter per uke gjort om til årstimer', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    laveste_arsramme: { tekst: 'Elever fra flere program eller nivåer: laveste årsramme brukes', formel: 'laveste av {arsrammer}' },
    stjernetillegg: { tekst: 'Fag merket * med 1–15 elever: årsrammen økes', formel: '{arsramme} + {stjernetillegg}' },
    beskjeftigelse: { tekst: 'Beskjeftigelse', formel: '{arstimer} ÷ {arsramme} × 100' },
    sum_beskjeftigelse: { tekst: 'Samlet beskjeftigelse (sum av gruppene)', formel: 'summen av {beskjeftigelser}' },
    timer_i_perioden_fra_okter: { tekst: 'Økter per uke gjort om til timer i perioden', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    periodenokkel: { tekst: 'Periodenøkkel: periodens andel av skoleåret', formel: '{dager_periode} ÷ {dager_skolear}' },
    perioderamme: { tekst: 'Perioderamme: årsrammen for perioden', formel: '{arsramme} × {periodenokkel}' },
    periodebeskjeftigelse: { tekst: 'Beskjeftigelse i perioden', formel: '{timer} ÷ {perioderamme} × 100' },
    vikartimer: { tekst: 'Vikartimer gjort om til 60-minutters timer', formel: '{okter} × {minutter} ÷ 60' },
    endring_beskjeftigelse: { tekst: 'Økning i beskjeftigelse', formel: '{vikartimer} ÷ {arsramme} × 100' },
    kalkulert_tid: { tekst: 'Kalkulert tid: undervisning med for- og etterarbeid', formel: '{vikartimer} × {konstant} ÷ {arsramme}' },
    timelonn: { tekst: 'Timelønn uten feriepenger', formel: '{arslonn} ÷ {arsverk} × {teller} ÷ {nevner}' },
    lonn: { tekst: 'Lønn for vikartimene', formel: '{kalkulert_tid} × {timelonn}' },
    feriepenger: { tekst: 'Feriepenger i tillegg', formel: '{lonn} × {sats} ÷ 100' },
    samlet_lonn: { tekst: 'Samlet avlønning', formel: '{lonn} + {feriepenger}' },
    funksjonsprosent: { tekst: 'Reduksjonen i prosent av full undervisning', formel: '{reduksjon} ÷ {arsramme} × 100' },
    selvdisponert: { tekst: 'Tid læreren disponerer selv i full stilling', formel: '{arsverk} − {planfestet}' },
    planfestet_okning: { tekst: 'Selvdisponert tid reduseres like mye som undervisningen, og planfestet tid øker tilsvarende', formel: '{selvdisponert} × {funksjonsprosent} ÷ 100' },
    planfestet_ny: { tekst: 'Planfestet arbeidstid', formel: '{planfestet} + {okning}' },
    arbeidsaar_dager: { tekst: 'Arbeidsåret: elevenes skoleår og 6 dager', formel: '{skolear} + {tillegg}' },
    arbeidsaar_uker: { tekst: 'Arbeidsåret i uker', formel: '{dager} ÷ {per_uke}' },
    planfestet_maks: { tekst: 'Høyeste planfestede tid uten å utvide arbeidsåret', formel: '{uker} × {maks_uke}' },
    planfestet_per_uke: { tekst: 'Planfestet tid per uke', formel: '{planfestet} ÷ {uker}' },
    planfestet_per_uke_maks: { tekst: 'Planfestet tid per uke (høyeste tillatte)', formel: '{maks} ÷ {uker}' },
    utvidelse_timer: { tekst: 'Timer over grensen', formel: '{planfestet} − {maks}' },
    utvidelse_dager: { tekst: 'Arbeidsåret utvides med', formel: '{timer} ÷ {per_dag}' },
    stilling: { tekst: 'Stilling i alt', formel: '{beskjeftigelse} + {funksjonsprosent}' },
    arsverk_stilling: { tekst: 'Årsverket for stillingen', formel: '{arsverk} × {stilling} ÷ 100' },
    planfestet_undervisning: { tekst: 'Planfestet tid for undervisningsdelen', formel: '{planfestet} × {beskjeftigelse} ÷ 100' },
    funksjonstid: { tekst: 'Tid til funksjoner og andre oppgaver (planfestet)', formel: '{arsverk} × {funksjonsprosent} ÷ 100' },
    motetid: { tekst: 'Møtetid i skoleåret', formel: '{moter} × {uker}' },
    annen_planfestet: { tekst: 'Annen planfestet tid', formel: '{planfestet_undervisning} − {undervisning} − {motetid}' },
    selvdisponert_stilling: { tekst: 'Tid læreren disponerer selv', formel: '({arsverk} − {planfestet}) × {beskjeftigelse} ÷ 100' },
    overtidsprosent: { tekst: 'Beskjeftigelse ut over hel stilling', formel: '{beskjeftigelse} − 100' },
    overtidstimer: { tekst: 'Timene årsrammen er økt med', formel: '{overtidsprosent} × {arsramme} ÷ 100' },
    kalkulert_tid_overtid: { tekst: 'Kalkulert tid: undervisning med for- og etterarbeid', formel: '{timer} × {konstant} ÷ {arsramme}' },
    overtidsbetaling: { tekst: 'Overtidsbetaling: timelønn med 50 % tillegg', formel: '{kalkulert_tid} × {timelonn} × (100 + {tillegg}) ÷ 100' },
  },
  storrelser: {
    arstimer: 'årstimer',
    arsramme: 'årsramme',
    arsrammer: 'årsrammene',
    arsramme_justert: 'justert årsramme',
    stjernetillegg: 'tillegg',
    elever: 'elever',
    okter_per_uke: 'økter per uke',
    minutter_per_okt: 'minutter per økt',
    uker: 'uker',
    beskjeftigelse: 'beskjeftigelse',
    beskjeftigelser: 'gruppenes beskjeftigelse',
    sum_beskjeftigelse: 'samlet beskjeftigelse',
    timer_i_perioden: 'timer i perioden',
    dager_i_perioden: 'dager i perioden',
    dager_i_skolearet: 'dager i skoleåret',
    periodenokkel: 'periodenøkkel',
    perioderamme: 'perioderamme',
    periodebeskjeftigelse: 'periodebeskjeftigelse',
    vikartimer: 'vikartimer',
    antall_okter: 'økter',
    endring_beskjeftigelse: 'økning',
    timelonn_konstant: 'faktor fra § 12.4',
    kalkulert_tid: 'kalkulert tid',
    arslonn: 'årslønn',
    arsverk: 'årsverk',
    ferie_teller: 'teller',
    ferie_nevner: 'nevner',
    timelonn: 'timelønn',
    lonn: 'lønn',
    feriepengesats: 'feriepengesats',
    feriepenger: 'feriepenger',
    samlet_lonn: 'samlet avlønning',
    reduksjon_arsrammetimer: 'reduksjon',
    arsramme_funksjon: 'årsramme ved funksjon',
    funksjonsprosent: 'funksjonsprosent',
    planfestet: 'planfestet tid',
    selvdisponert: 'selvdisponert tid',
    planfestet_okning: 'økning',
    planfestet_ny: 'planfestet tid',
    skolear_dager: 'skoledager',
    arbeidsaar_tillegg: 'ekstra dager',
    arbeidsaar_dager: 'dager i arbeidsåret',
    arbeidsdager_per_uke: 'dager per uke',
    arbeidsaar_uker: 'uker i arbeidsåret',
    planfestet_maks_uke: 'timer per uke',
    planfestet_maks: 'grense',
    planfestet_per_uke: 'per uke',
    utvidelse_timer: 'timer over grensen',
    timer_per_dag: 'timer per dag',
    utvidelse_dager: 'dager',
    stilling: 'stilling',
    arsverk_stilling: 'årsverk for stillingen',
    planfestet_undervisning: 'planfestet tid for undervisningsdelen',
    funksjonstid: 'funksjonstid',
    moter_per_uke: 'møtetimer per uke',
    skolear_uker: 'uker i skoleåret',
    motetid: 'møtetid',
    annen_planfestet: 'annen planfestet tid',
    selvdisponert_stilling: 'selvdisponert tid',
    overtidsprosent: 'prosent over hel stilling',
    overtidstimer: 'overtidstimer',
    overtidstillegg: 'overtidstillegg',
    overtidsbetaling: 'overtidsbetaling',
  },
  enheter: {
    prosent: '%',
    timer: 'timer',
    arsrammetimer: 'årsrammetimer',
    timer_per_uke: 'timer per uke',
    minutter: 'minutter',
    uker: 'uker',
    dager: 'dager',
    okter: 'økter',
    elever: 'elever',
    kroner: 'kr',
    kroner_per_time: 'kr per time',
  },
};
