// UI-tekstar for arbeidstidsmodulen på nynorsk. Typen gjer at ein manglande nøkkel gir byggjefeil.
import type { arbeidstidNb } from './arbeidstid.nb.ts';

type Skjema<T> = { [K in keyof T]: T[K] extends string ? string : Skjema<T[K]> };

export const arbeidstidNn: Skjema<typeof arbeidstidNb> = {
  tittel: 'Arbeidstid',
  innledning:
    'Kalkulatorar for arbeidstid etter SFS 2213 (arbeidstidsavtalen for undervisningspersonalet) og hovudtariffavtalen i KS-området. Kvar utrekning viser metoden steg for steg og kvar tala kjem frå.',
  kalkulatorer: {
    tittel: 'Kalkulatorar',
    beskjeftigelse: {
      tittel: 'Sysselsetjing',
      kort: 'Sysselsetjing',
      beskrivelse: 'Undervisningsprosent for eitt eller fleire fag, også blanda grupper.',
    },
    periode: {
      tittel: 'Periodesysselsetjing',
      kort: 'Periode',
      beskrivelse: 'Sysselsetjing for undervisning i ein del av skuleåret.',
    },
    vikar: {
      tittel: 'Vikartimar',
      kort: 'Vikartimar',
      beskrivelse: 'Endra sysselsetjing for tilsette, og løn for timevikarar.',
    },
    planfestet: {
      tittel: 'Planfesta arbeidstid ved funksjonar',
      kort: 'Planfesta tid',
      beskrivelse: 'Planfesta tid og arbeidsår når undervisninga blir redusert for funksjonar eller andre oppgåver.',
    },
    overtid: {
      tittel: 'Overtid ved sysselsetjing over 100 %',
      kort: 'Overtid',
      beskrivelse: 'Overtidsbetaling for undervisning utover heil stilling (fast overtid).',
    },
    fordeling: {
      tittel: 'Fordeling av arbeidstida',
      kort: 'Fordeling',
      beskrivelse: 'Diagram over korleis årsverket blir fordelt i ei tenkt stilling.',
    },
  },
  felles: {
    periode: 'Regelverk: {periode}',
    gruppe: 'Gruppe {nr}',
    grupper: 'Fag og grupper',
    leggTilGruppe: 'Legg til fag eller gruppe',
    fjernGruppe: 'Fjern gruppe {nr}',
    arsramme: 'Fag, program og trinn (vedlegg 1)',
    arsrammeNr: 'Årsramme {nr}',
    velgArsramme: 'Vel frå vedlegg 1',
    manuellValg: 'Anna årsramme (skriv inn sjølv)',
    manuellEtikett: 'Årsramme i 60-minutts timar',
    manuellStjerne: 'Faget er merkt * i vedlegg 1',
    blandetForklaring: 'Har timen elevar frå fleire program eller nivå, legg du til årsrammene for dei. Den lågaste blir brukt.',
    leggTilArsramme: 'Legg til program eller nivå i same time',
    fjernArsramme: 'Fjern årsramme {nr}',
    elever: 'Faktisk tal på elevar i klassen',
    eleverHjelp: 'Fag merkte * får høgare årsramme når klassen har 1–15 elevar.',
    undervisning: 'Undervisning',
    modusArstimer: 'Årstimar',
    modusTimerPeriode: 'Timar i perioden',
    modusOkter: 'Økter per veke',
    arstimer: 'Årstimar (60-minutts timar)',
    arstimerHjelp: 'Timetalet for faget i året, slik Udir oppgir det, t.d. 140 for engelsk Vg1.',
    okter: 'Økter per veke',
    minutter: 'Minutt per økt',
    uker: 'Tal på veker',
    ukerHjelp: 'La stå tomt for heile skuleåret ({uker} veker).',
    ukerPeriode: 'Tal på veker i perioden',
    timerIPerioden: 'Timar i perioden (60-minutts timar)',
    manglerInndata: 'Fyll inn felta over for å sjå resultatet.',
    grupperad: 'Gruppe {nr}: {tekst}',
    optgruppe: 'Årsramme {t60}/{t45}',
    stjerne: '(*)',
  },
  resultat: {
    beskjeftigelse: 'Sysselsetjing',
    sumBeskjeftigelse: 'Samla sysselsetjing',
    periodebeskjeftigelse: 'Sysselsetjing i perioden',
    endring: 'Auke i sysselsetjing',
    samletLonn: 'Samla løn',
    planfestet: 'Planfesta arbeidstid',
    stilling: 'Stilling i alt',
    oversikt: 'Oversikt',
    perUke: 'Per veke i arbeidsåret',
    utvidelse: 'Utviding av arbeidsåret',
    ingenUtvidelse: 'Arbeidsåret blir ikkje utvida.',
    kalkulertTid: 'Kalkulert tid',
    timelonn: 'Timeløn',
    lonn: 'Løn',
    feriepenger: 'Feriepengar',
    funksjonsprosent: 'Funksjon og andre oppgåver',
    overtidstimer: 'Overtidstimar (årsrammetimar)',
    overtidsbetaling: 'Overtidsbetaling',
  },
  advarsler: {
    over_hel_stilling: 'Undervisning og funksjonar er til saman meir enn ei heil stilling.',
    motetid_for_stor: 'Undervisning og møtetid er meir enn den planfesta tida for undervisningsdelen. Diagrammet viser då inga anna planfesta tid.',
    mangler_elevtall: 'Faget er merkt * i vedlegg 1. Skriv inn talet på elevar for å sjå om årsramma skal aukast.',
  },
  feil: {
    regel: 'Utrekninga kunne ikkje gjerast med regelverket for valt dato: {melding}',
  },
  vikar: {
    type: 'Kven tek vikartimane?',
    fast: 'Tilsett i stilling',
    timevikar: 'Timevikar',
    okter: 'Tal på vikarøkter',
    lonn: 'Løn',
    lonnGarantilonn: 'Garantiløn frå hovudtariffavtalen',
    lonnManuell: 'Eiga årsløn',
    stillingsgruppe: 'Stillingsgruppe',
    ansiennitet: 'Ansiennitet',
    ansiennitetAr: '{ar} år',
    arslonn: 'Årsløn i kroner',
    arslonnHjelp: 'Blir brukt når læraren har høgare løn enn garantiløna.',
    over60: 'Vikaren er over 60 år (høgare feriepengesats)',
  },
  overtid: {
    beskjeftigelse: 'Samla sysselsetjing i prosent',
    beskjeftigelseHjelp: 'Undervisning og funksjonar til saman, t.d. 110. Det som er over 100 %, blir betalt som overtid.',
    fag: 'Faget overtida gjeld (vedlegg 1)',
    ingenOvertid: 'Sysselsetjinga er ikkje over 100 %, så det er inga overtid.',
  },
  planfestet: {
    reduksjon: 'Kor mykje er undervisninga redusert?',
    iProsent: 'I prosent av full stilling',
    iArsrammetimer: 'I årsrammetimar',
    prosent: 'Reduksjon i prosent',
    prosentHjelp: 'T.d. 20 for ein funksjon på 20 %.',
    arsrammetimer: 'Reduksjon i årsrammetimar (60 min)',
    arsrammetimerHjelp: 'T.d. 28,5 for kontaktlærar i vidaregåande (SFS 2213 punkt 7.3 b).',
  },
  periode: {
    dager: 'Undervisningsdagar i perioden',
    dagerHjelp: 'Tel dagane etter skuleruta.',
    skolear: 'Undervisningsdagar i skuleåret',
    skolearHjelp: 'La stå tomt for {dager} dagar.',
  },
  fordeling: {
    funksjon: 'Funksjonar og andre oppgåver',
    moter: 'Møtetid per veke (timar)',
    moterHjelp: 'Faste møte i planfesta tid, t.d. team- og fellesmøte.',
    diagramTittel: 'Fordeling av årsverket',
    diagramBeskrivelse: 'Stolpediagram over årsverket på {timer} timar: {deler}.',
    illustrasjon: 'Illustrasjon av ei tenkt stilling. Ikkje ein arbeidsplan.',
    planfestet: 'Planfesta tid',
    selvdisponert: 'Tid læraren disponerer sjølv',
    tabell: 'Tala i diagrammet',
    del: 'Del',
    timer: 'Timar per år',
    andel: 'Del av årsverket',
    brukAvTiden: 'Kva tida blir brukt til',
    deler: {
      undervisning: 'Undervisning',
      motetid: 'Møtetid',
      annen_planfestet: 'Anna planfesta tid',
      funksjonstid: 'Funksjonar og andre oppgåver',
      selvdisponert: 'Sjølvdisponert tid',
    },
  },
  metode: {
    tittel: 'Slik blir det rekna ut',
    kilder: 'Kjelder',
    ikkeFunnet: 'Metodeskildringa manglar.',
  },
  utregning: {
    formel: 'Formel',
    innsatt: 'Utrekning',
    fra: 'Frå {kilde}',
    inndata: 'skrive inn',
    rad: 'Vedlegg 1: {rad}',
  },
  trinn: {
    arstimer_fra_okter: { tekst: 'Økter per veke gjort om til årstimar', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    laveste_arsramme: { tekst: 'Elevar frå fleire program eller nivå: lågaste årsramme blir brukt', formel: 'lågaste av {arsrammer}' },
    stjernetillegg: { tekst: 'Fag merkte * med 1–15 elevar: årsramma blir auka', formel: '{arsramme} + {stjernetillegg}' },
    beskjeftigelse: { tekst: 'Sysselsetjing', formel: '{arstimer} ÷ {arsramme} × 100' },
    sum_beskjeftigelse: { tekst: 'Samla sysselsetjing (sum av gruppene)', formel: 'summen av {beskjeftigelser}' },
    timer_i_perioden_fra_okter: { tekst: 'Økter per veke gjort om til timar i perioden', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    periodenokkel: { tekst: 'Periodenøkkel: delen av skuleåret perioden utgjer', formel: '{dager_periode} ÷ {dager_skolear}' },
    perioderamme: { tekst: 'Perioderamme: årsramma for perioden', formel: '{arsramme} × {periodenokkel}' },
    periodebeskjeftigelse: { tekst: 'Sysselsetjing i perioden', formel: '{timer} ÷ {perioderamme} × 100' },
    vikartimer: { tekst: 'Vikartimar gjort om til 60-minutts timar', formel: '{okter} × {minutter} ÷ 60' },
    endring_beskjeftigelse: { tekst: 'Auke i sysselsetjing', formel: '{vikartimer} ÷ {arsramme} × 100' },
    kalkulert_tid: { tekst: 'Kalkulert tid: undervisning med før- og etterarbeid', formel: '{vikartimer} × {konstant} ÷ {arsramme}' },
    timelonn: { tekst: 'Timeløn utan feriepengar', formel: '{arslonn} ÷ {arsverk} × {teller} ÷ {nevner}' },
    lonn: { tekst: 'Løn for vikartimane', formel: '{kalkulert_tid} × {timelonn}' },
    feriepenger: { tekst: 'Feriepengar i tillegg', formel: '{lonn} × {sats} ÷ 100' },
    samlet_lonn: { tekst: 'Samla løn', formel: '{lonn} + {feriepenger}' },
    funksjonsprosent: { tekst: 'Reduksjonen i prosent av full undervisning', formel: '{reduksjon} ÷ {arsramme} × 100' },
    selvdisponert: { tekst: 'Tid læraren disponerer sjølv i full stilling', formel: '{arsverk} − {planfestet}' },
    planfestet_okning: { tekst: 'Sjølvdisponert tid blir redusert like mykje som undervisninga, og planfesta tid aukar tilsvarande', formel: '{selvdisponert} × {funksjonsprosent} ÷ 100' },
    planfestet_ny: { tekst: 'Planfesta arbeidstid', formel: '{planfestet} + {okning}' },
    arbeidsaar_dager: { tekst: 'Arbeidsåret: skuleåret til elevane og 6 dagar', formel: '{skolear} + {tillegg}' },
    arbeidsaar_uker: { tekst: 'Arbeidsåret i veker', formel: '{dager} ÷ {per_uke}' },
    planfestet_maks: { tekst: 'Høgaste planfesta tid utan å utvide arbeidsåret', formel: '{uker} × {maks_uke}' },
    planfestet_per_uke: { tekst: 'Planfesta tid per veke', formel: '{planfestet} ÷ {uker}' },
    planfestet_per_uke_maks: { tekst: 'Planfesta tid per veke (høgaste tillatne)', formel: '{maks} ÷ {uker}' },
    utvidelse_timer: { tekst: 'Timar over grensa', formel: '{planfestet} − {maks}' },
    utvidelse_dager: { tekst: 'Arbeidsåret blir utvida med', formel: '{timer} ÷ {per_dag}' },
    stilling: { tekst: 'Stilling i alt', formel: '{beskjeftigelse} + {funksjonsprosent}' },
    arsverk_stilling: { tekst: 'Årsverket for stillinga', formel: '{arsverk} × {stilling} ÷ 100' },
    planfestet_undervisning: { tekst: 'Planfesta tid for undervisningsdelen', formel: '{planfestet} × {beskjeftigelse} ÷ 100' },
    funksjonstid: { tekst: 'Tid til funksjonar og andre oppgåver (planfesta)', formel: '{arsverk} × {funksjonsprosent} ÷ 100' },
    motetid: { tekst: 'Møtetid i skuleåret', formel: '{moter} × {uker}' },
    annen_planfestet: { tekst: 'Anna planfesta tid', formel: '{planfestet_undervisning} − {undervisning} − {motetid}' },
    selvdisponert_stilling: { tekst: 'Tid læraren disponerer sjølv', formel: '({arsverk} − {planfestet}) × {beskjeftigelse} ÷ 100' },
    overtidsprosent: { tekst: 'Sysselsetjing utover heil stilling', formel: '{beskjeftigelse} − 100' },
    overtidstimer: { tekst: 'Timane årsramma er auka med', formel: '{overtidsprosent} × {arsramme} ÷ 100' },
    kalkulert_tid_overtid: { tekst: 'Kalkulert tid: undervisning med før- og etterarbeid', formel: '{timer} × {konstant} ÷ {arsramme}' },
    overtidsbetaling: { tekst: 'Overtidsbetaling: timeløn med 50 % tillegg', formel: '{kalkulert_tid} × {timelonn} × (100 + {tillegg}) ÷ 100' },
  },
  storrelser: {
    arstimer: 'årstimar',
    arsramme: 'årsramme',
    arsrammer: 'årsrammene',
    arsramme_justert: 'justert årsramme',
    stjernetillegg: 'tillegg',
    elever: 'elevar',
    okter_per_uke: 'økter per veke',
    minutter_per_okt: 'minutt per økt',
    uker: 'veker',
    beskjeftigelse: 'sysselsetjing',
    beskjeftigelser: 'sysselsetjinga i gruppene',
    sum_beskjeftigelse: 'samla sysselsetjing',
    timer_i_perioden: 'timar i perioden',
    dager_i_perioden: 'dagar i perioden',
    dager_i_skolearet: 'dagar i skuleåret',
    periodenokkel: 'periodenøkkel',
    perioderamme: 'perioderamme',
    periodebeskjeftigelse: 'periodesysselsetjing',
    vikartimer: 'vikartimar',
    antall_okter: 'økter',
    endring_beskjeftigelse: 'auke',
    timelonn_konstant: 'faktor frå § 12.4',
    kalkulert_tid: 'kalkulert tid',
    arslonn: 'årsløn',
    arsverk: 'årsverk',
    ferie_teller: 'teljar',
    ferie_nevner: 'nemnar',
    timelonn: 'timeløn',
    lonn: 'løn',
    feriepengesats: 'feriepengesats',
    feriepenger: 'feriepengar',
    samlet_lonn: 'samla løn',
    reduksjon_arsrammetimer: 'reduksjon',
    arsramme_funksjon: 'årsramme ved funksjon',
    funksjonsprosent: 'funksjonsprosent',
    planfestet: 'planfesta tid',
    selvdisponert: 'sjølvdisponert tid',
    planfestet_okning: 'auke',
    planfestet_ny: 'planfesta tid',
    skolear_dager: 'skuledagar',
    arbeidsaar_tillegg: 'ekstra dagar',
    arbeidsaar_dager: 'dagar i arbeidsåret',
    arbeidsdager_per_uke: 'dagar per veke',
    arbeidsaar_uker: 'veker i arbeidsåret',
    planfestet_maks_uke: 'timar per veke',
    planfestet_maks: 'grense',
    planfestet_per_uke: 'per veke',
    utvidelse_timer: 'timar over grensa',
    timer_per_dag: 'timar per dag',
    utvidelse_dager: 'dagar',
    stilling: 'stilling',
    arsverk_stilling: 'årsverk for stillinga',
    planfestet_undervisning: 'planfesta tid for undervisningsdelen',
    funksjonstid: 'funksjonstid',
    moter_per_uke: 'møtetimar per veke',
    skolear_uker: 'veker i skuleåret',
    motetid: 'møtetid',
    annen_planfestet: 'anna planfesta tid',
    selvdisponert_stilling: 'sjølvdisponert tid',
    overtidsprosent: 'prosent over heil stilling',
    overtidstimer: 'overtidstimar',
    overtidstillegg: 'overtidstillegg',
    overtidsbetaling: 'overtidsbetaling',
  },
  enheter: {
    prosent: '%',
    timer: 'timar',
    arsrammetimer: 'årsrammetimar',
    timer_per_uke: 'timar per veke',
    minutter: 'minutt',
    uker: 'veker',
    dager: 'dagar',
    okter: 'økter',
    elever: 'elevar',
    kroner: 'kr',
    kroner_per_time: 'kr per time',
  },
};
