// UI-tekster for arbeidstidsmodulen på bokmål. arbeidstid.nn.ts må ha de samme nøklene.
// Formlene bruker plassholdere med operandenes navn, f.eks. {arstimer}. Appen fyller dem inn to ganger:
// med navnet på størrelsen (formelen) og med tallene (utregningen).

export const arbeidstidNb = {
  tittel: 'Arbeidstid',
  innledning:
    'Kalkulatorer for arbeidstid etter SFS 2213 (arbeidstidsavtalen for undervisningspersonalet) og hovedtariffavtalen i KS-området. Hver utregning viser metoden trinn for trinn og hvor tallene kommer fra.',
  kalkulatorer: {
    tittel: 'Kalkulatorer',
    flere: 'Flere kalkulatorer',
    arbeidsplan: {
      tittel: 'Arbeidsplan',
      kort: 'Arbeidsplan',
      beskrivelse: 'Fag og funksjoner mot stillingsprosenten, med teknisk undertid eller overtid, fordelingen av arbeidstiden og årslønn.',
    },
    beskjeftigelse: {
      tittel: 'Beskjeftigelse',
      kort: 'Beskjeftigelse',
      beskrivelse: 'Undervisningsprosent for ett eller flere fag.',
    },
    periode: {
      tittel: 'Periodebeskjeftigelse',
      kort: 'Periode',
      beskrivelse: 'Beskjeftigelse når undervisningen bare gjelder en del av skoleåret.',
    },
    vikar: {
      tittel: 'Vikartimer',
      kort: 'Vikartimer',
      beskrivelse: 'Økt beskjeftigelse for ansatte, eller lønn for timevikarer.',
    },
    overtid: {
      tittel: 'Overtid over 100 %',
      kort: 'Overtid',
      beskrivelse: 'Betaling for undervisning ut over hel stilling.',
    },
  },
  felles: {
    fortsettArbeidsplan: 'Fortsett i Arbeidsplan med disse fagene',
    skrivUt: 'Skriv ut {navn} eller lagre som PDF',
    skrivUtKort: 'Skriv ut eller lagre som PDF',
    ukerHalvaar: 'F.eks. for fag som bare går et halvår.',
    kortLonn: 'Lønn og feriepenger',
    nyttVindu: 'Åpne {navn} i nytt vindu',
    nyttVinduKort: 'Åpne i nytt vindu',
    gruppe: 'Fag {nr}',
    grupper: 'Fag og grupper',
    leggTilGruppe: 'Legg til fag',
    fjernGruppe: 'Fjern fag {nr}',
    fag: 'Fag',
    fagSok: 'F.eks. engelsk vg1, R1 eller BAT',
    fagSokHjelp: 'Fag, program, trinn eller fagkode, f.eks. «engelsk vg1», «R1» eller «BAT».',
    ingenFagTreff: 'Ingen fag passer. Prøv et annet ord, eller skriv inn årsrammen selv.',
    endreFag: 'Endre',
    arsrammeKort: 'årsramme {t60}/{t45}',
    manuellValg: 'Skriv inn årsramme selv',
    manuellEtikett: 'Årsramme (60 min)',
    manuellStjerne: 'Merket * i vedlegg 1',
    tilbakeTilSok: 'Søk i vedlegg 1',
    leggTilArsramme: 'Blandet gruppe',
    blandetEtikett: 'Også i timen',
    fjernArsramme: 'Fjern',
    faaElever: '15 eller færre elever i klassen',
    faaEleverHjelp: 'Fag merket * i vedlegg 1 får høyere årsramme når klassen har 1–15 elever.',
    undervisning: 'Timer',
    modusArstimer: 'Årstimer',
    modusTimerPeriode: 'Timer',
    modusOkter: 'Økter/uke',
    arstimer: 'Antall årstimer',
    arstimerFraGrep: 'Årstimetall for elevene fra Udir ({fagkoder}). Du kan endre det.',
    timerIPerioden: 'Antall timer i perioden',
    okter: 'Antall økter per uke',
    minutter: 'Minutter per økt',
    minutterAnnet: 'Annet',
    minutterFritt: 'Minutter',
    uker: 'Uker',
    ukerStandard: 'Hele skoleåret: {uker} uker',
    endreUker: 'Endre antall uker',
    ukerPeriode: 'Uker i perioden',
    manglerInndata: 'Velg fag og fyll inn timer for å se resultatet.',
    stjerne: '*',
    timerKort: '{timer} t',
    delresultat: '{verdi} %',
  },
  resultat: {
    samletBeskjeftigelse: 'Samlet beskjeftigelse',
    undervisning: 'Undervisning',
    funksjoner: 'Funksjoner',
    stillingsprosent: 'Stilling',
    tekniskUndertid: 'Teknisk undertid',
    variabelLonn: 'Variabel lønn',
    tekniskOvertid: 'Teknisk overtid',
    iBalanse: 'Arbeidsplanen går opp',
    beskjeftigelse: 'Beskjeftigelse',
    sumBeskjeftigelse: 'Samlet beskjeftigelse',
    periodebeskjeftigelse: 'Beskjeftigelse i perioden',
    endring: 'Økning i beskjeftigelse',
    kalkulertTid: 'Kalkulert tid',
    timelonn: 'Timelønn',
    lonn: 'Lønn',
    feriepengerTillegg: 'Feriepenger i tillegg',
    utbetaltLonn: 'Lønn som utbetales',
    undervisningstimer: 'Undervisningstimer',
    overtidsbetaling: 'Overtidsbetaling',
  },
  advarsler: {
    over_hel_stilling: 'Undervisning og funksjoner er til sammen mer enn en hel stilling.',
    motetid_for_stor: 'Møtetiden er mer enn den planfestede tiden som er igjen etter undervisningen og funksjonene. Diagrammet viser da ingen annen planfestet tid.',
    uker_fra_dager:
      'Uker i perioden er regnet ut fra dagene (dager ÷ skoledager per uke). Har ukene ulikt antall skoledager eller ulik timeplan, bør du skrive inn antall uker eller timene i perioden selv.',
    mangler_elevtall: 'Faget er merket * i vedlegg 1. Skriv inn antall elever for å se om årsrammen skal økes.',
  },
  feil: {
    regel: 'Utregningen kunne ikke gjøres med regelverket for valgt dato: {melding}',
  },
  vikar: {
    kortTimer: 'Vikartimene',
    oppsummering: '{okter} økter à {minutter} min',
    type: 'Hvem tar vikartimene?',
    fast: 'Ansatt i stilling',
    timevikar: 'Timevikar',
    okter: 'Antall vikarøkter',
    lonn: 'Lønn',
    lonnGarantilonn: 'Garantilønn fra hovedtariffavtalen',
    lonnManuell: 'Egen årslønn',
    stillingsgruppe: 'Stillingsgruppe',
    ansiennitet: 'Ansiennitet',
    ansiennitetAr: '{ar} år',
    arslonn: 'Årslønn i kroner',
    over60: 'Vikaren er over 60 år (høyere feriepengesats)',
  },
  overtid: {
    beskjeftigelse: 'Samlet beskjeftigelse i prosent',
    beskjeftigelseHjelp: 'Undervisning og funksjoner til sammen, f.eks. 110. Det som er over 100 %, betales som overtid.',
    fag: 'Faget overtiden gjelder',
    ingenOvertid: 'Beskjeftigelsen er ikke over 100 %, så det er ingen overtid.',
    over60: 'Læreren er over 60 år (høyere feriepengesats)',
    forklaringTema: 'Hvorfor endrer ikke faget beløpet?',
    forklaring:
      'Overtidsprosenten gjøres først om til undervisningstimer i faget (prosent × årsramme ÷ 100). Undervisningstimene gjøres så om til kalkulert tid (timer × {konstant} ÷ årsramme), som er arbeidstimene det betales for. Årsrammen står i begge trinnene og går opp. Faget og bryteren for små klasser endrer derfor antall undervisningstimer, men ikke beløpet: 1 % over hel stilling gir alltid {perProsent} timer kalkulert tid.',
  },
  periode: {
    heleAret: 'Tilsvarer for hele skoleåret',
    ukerFraDager:
      'Tomt felt gir {uker} uker: {dager} dager ÷ {perUke} skoledager per uke. Ukene i perioden kan ha ulikt antall skoledager (fridager, ferier) eller ulik timeplan. Skriv inn antallet om det avviker.',
    ukerFyllDager: 'Fyll inn dager i perioden øverst, så regnes ukene ut. Du kan også skrive inn antallet selv.',
    dager: 'Dager i perioden',
    dagerHjelp: 'Undervisningsdager etter skoleruta.',
    skolear: 'Dager i skoleåret',
    skolearHjelp: 'Tomt felt gir {dager} dager.',
  },
  fordeling: {
    moter: 'Møtetid per uke (timer)',
    visStort: 'Vis stort',
    oppsummering: 'planfestet {planfestet} t, selvdisponert {selv} t',
    visMindre: 'Lukk stor visning',
    diagramTittel: 'Fordeling av årsverket',
    diagramBeskrivelse: 'Stolpediagram over årsverket på {timer} timer: {deler}.',
    planfestet: 'Planfestet tid',
    tabell: 'Tallene i diagrammet',
    del: 'Del',
    timer: 'Timer per år',
    andel: 'Andel',
    perUke: 'Per uke',
    sum: 'Årsverk i alt',
    perUkeForklaring: 'Per uke er timene delt på {uker} uker i arbeidsåret.',
    perUkeUtvidet:
      'Planfestet tid blir mer enn {maksUke} timer per uke i snitt. Da utvides arbeidsåret med {dager} dager (SFS 2213 punkt 5.3), og per uke er timene delt på {uker} uker.',
    brukAvTiden: 'Hva tiden brukes til',
    deler: {
      undervisning: 'Undervisning',
      motetid: 'Møtetid',
      annen_planfestet: 'Annen planfestet tid',
      funksjonstid: 'Funksjoner og andre oppgaver',
      selvdisponert: 'Selvdisponert tid',
    },
  },
  arbeidsplan: {
    illustrasjon: 'Illustrasjon – ikke en arbeidsplan. Ekte arbeidsplaner lages i skolens egne systemer.',
    stilling: 'Stillingsprosent',
    funksjoner: 'Funksjoner',
    funksjonerHjelp:
      'Funksjoner som kontaktlærer oppgis i prosent av full stilling, slik de står i stillingsplanen. En funksjon kan ha bare avsatt tid, bare tillegg (0 %) eller begge deler. Tillegg slås på ved funksjonen når lønnen regnes ut. Slå av «Utvider planfestet tid» for funksjoner som gis uten at planfestet tid utvides, f.eks. kontaktlærer der det er praksis. Det endrer bare diagrammet over arbeidstiden.',
    funksjonNr: 'Funksjon {nr}',
    funksjonNavn: 'Navn',
    funksjonNavnPlassholder: 'F.eks. kontaktlærer',
    funksjonProsent: 'Prosent',
    funksjonTimer: 'Årsrammetimer',
    funksjonEnhet: 'oppgitt i',
    enhetTimer: 'Timer',
    timerSomProsent: 'Årsrammetimer ÷ {arsramme} = {prosent} % av full stilling.',
    kontaktlaererHint: 'Kontaktlærer: minst {timer} årsrammetimer (SFS 2213 punkt 7.3 b).',
    kontaktlaererBruk: 'Bruk {timer} timer',
    leggTilFunksjon: 'Legg til funksjon',
    fjernFunksjon: 'Fjern funksjon {nr}',
    timerIFag: 'Årsrammetimer i',
    ingenFag: 'Legg inn fag for å se differansen i timer.',
    hvertFag: 'Timer i hvert fag',
    hvertFagMangler: 'For å fylle stillingen mangler det så mange årsrammetimer, regnet med årsrammen i hvert fag:',
    hvertFagForMye: 'Stillingen er overskredet med så mange årsrammetimer, regnet med årsrammen i hvert fag:',
    fagRad: '{fag} (årsramme {arsramme})',
    overtidLenke: 'Regn ut overtidsbetaling for {prosent} %',
    utvider: 'Utvider planfestet tid',
    utenUtvidelseMerknad: 'Funksjoner som ikke utvider planfestet tid ({prosent} %), er fordelt som undervisningen: en del planfestet tid og en del tid læreren disponerer selv.',
    tillegg: 'Møter og lønn',
    moterHjelp: 'Valgfritt. Faste møter i planfestet tid, til diagrammet over arbeidstiden.',
    visLonn: 'Regn ut lønn',
    arslonn: 'Årslønn i stillingen',
    arslonnStilling: 'Årslønn i {prosent} % stilling',
    lonnIAlt: 'Lønn i året',
    tilleggNavn: 'Tillegg',
    funksjonerOppsummering: '{antall} lagt inn, {prosent} %',
    moterOppsummering: 'møter {timer} t per uke',
    lonnOppsummering: 'lønn regnes ut',
    tilleggVippe: 'Tillegg i lønnen',
    tilleggFelt: 'Tillegg per år, funksjon {nr}',
    tilleggRad: 'Tillegg: {funksjon}',
    tilleggKontaktlaerer: 'Fylt inn fra SFS 2213 punkt 9.1: minst {kr} kr i året for kontaktlærer. Skriv inn et annet beløp om tillegget er høyere.',
    tilleggRadgiver: 'Fylt inn fra SFS 2213 punkt 9.1: minst {kr} kr i året for rådgiver eller sosiallærer. Skriv inn et annet beløp om tillegget er høyere.',
    tilleggUkjent: 'Fylt inn med beløpet for kontaktlærer i SFS 2213 punkt 9.1 ({kr} kr). Godtgjøring for andre funksjoner fastsettes lokalt. Skriv inn beløpet.',
    tilleggEget: 'Skrevet inn selv. Tøm feltet for å bruke beløpet fra SFS 2213 punkt 9.1.',
    tilleggHint: 'Tillegg for funksjoner slås på ved hver funksjon under Funksjoner.',
    variabelRad: 'Variabel lønn ({timer} timer kalkulert tid)',
    overtidUtenFag: 'Legg inn fag for å regne ut variabel lønn og overtidsbetaling.',
    lonnMerknad: 'Lønn, tillegg, variabel lønn og overtid er det som utbetales i året. Feriepengene regnes av dette og kommer i tillegg.',
    diagramMerknad: 'Diagrammet viser undervisningen og funksjonene som er lagt inn ({prosent} %), som er mer enn stillingen.',
    ikkeFyltMerknad: 'Delen av stillingen som ikke er fylt med fag og funksjoner ({prosent} %), er regnet med som annen planfestet tid og tid læreren disponerer selv.',
  },
  livsfase: {
    tittel: 'Redusert undervisning',
    velg: 'Livsfasetiltak (SFS 2213 punkt 6)',
    hjelp:
      'Læreren har rett til å få redusert undervisningen med inntil {nyutdannet} % det første yrkesåret etter fullført utdanning, inntil {fra57} % fra det kalenderåret læreren fyller 57 år, og inntil {fra60} % fra det kalenderåret læreren fyller 60 år. Reduksjonen regnes som en del av stillingen, som en funksjon.',
    valg: {
      ingen: 'Ingen',
      nyutdannet: 'Nyutdannet',
      fra57: '57 år',
      fra60: '60 år',
    },
    oppsummering: '{tiltak}, {prosent} %',
    prosent: 'Reduksjon',
    prosentHjelp: 'Inntil {maks} %. Tomt felt gir {maks} %.',
    planfestet: 'Den frigjorte tiden legges i planfestet tid, der den erstatter undervisning. Planfestet tid utvides ikke.',
    fra57:
      'Avtalen sier bare for nyutdannede og lærere over 60 år at den frigjorte tiden legges i planfestet tid. Appen bruker den samme regelen for 57-åringer, uten at det står uttrykkelig i avtaleteksten.',
    fra60: 'For lærere som er 60 år og eldre er årsverket {arsverk} timer (punkt 4). Forskjellen er {dager} arbeidsdager ekstra ferie, så arbeidsåret er {dager} dager kortere. Planfestet tid er samme andel av årsverket som for andre lærere. Feriepengesatsen er også høyere.',
    redusert: 'Redusert undervisning',
    feriepenger60: 'Høyere feriepengesats, fordi læreren er 60 år eller eldre (redusert undervisning).',
  },
  varianter: {
    tittel: 'Lagrede varianter',
    hjelp: 'Lagre det du har fylt ut, og sammenlign med en endring. Gi gjerne varianten et navn, f.eks. «Før endring». Du kan ha {maks} varianter per kalkulator. De lagres bare på denne enheten, og den eldste erstattes når listen er full.',
    variant: 'Variant {nr}',
    naa: 'nå {differanse}',
    hent: 'Hent',
    slett: 'Slett {navn}',
    navn: 'Navn på variant {nr}',
    endreNavn: 'Gi nytt navn: {navn}',
    lagre: 'Lagre variant',
  },
  grafikk: {
    belop: 'Stolpe for beløpet: {deler}. I alt {sum}.',
    uke: 'Stolpe for en gjennomsnittlig uke: {planfestet} timer planfestet tid og {selv} timer læreren disponerer selv, i alt {total} timer. Streken viser grensen på {maksUke} timer planfestet tid i en uke.',
    ukePlanfestet: 'Planfestet: {planfestet} t',
    ukeSelv: 'Disponerer selv: {selv} t',
    ukeTekst: 'Snitt per uke i arbeidsåret: {total} timer i alt, {planfestet} timer planfestet, det vil si {perDag} timer per dag. Enkeltuker kan ha opptil {maksUke} timer planfestet tid, og enkeltdager opptil {maksDag} timer.',
    arbeidsplan: 'Stolpe for arbeidsplanen: {deler}. Samlet {sum} %. Streken viser stillingen på {grense} %.',
    stilling: 'Stolpe for stillingen: {sum} % i alt ({deler}). Streken viser {grense} %.',
    periode: 'Perioden er {dager} av {skolear} undervisningsdager ({prosent} % av skoleåret).',
  },
  metode: {
    tittel: 'Slik regnes det ut',
    ikkeFunnet: 'Metodebeskrivelsen mangler.',
  },
  trinn: {
    sum_funksjon: { tekst: 'Funksjoner til sammen', formel: '{funksjoner}' },
    samlet_beskjeftigelse: { tekst: 'Samlet beskjeftigelse: undervisning og funksjoner', formel: '{undervisning} + {funksjon}' },
    teknisk_differanse: { tekst: 'Differanse mot stillingen: minus er teknisk undertid, pluss er teknisk overtid', formel: '{beskjeftigelse} − {stilling}' },
    teknisk_timer: { tekst: 'Differansen i årsrammetimer i faget', formel: '{differanse} × {arsramme} ÷ 100' },
    arstimer_fra_okter: { tekst: 'Økter per uke gjort om til årstimer', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    laveste_arsramme: { tekst: 'Elever fra flere program eller nivåer: laveste årsramme brukes', formel: 'laveste av {arsrammer}' },
    stjernetillegg: { tekst: 'Fag merket * med 1–15 elever: årsrammen økes', formel: '{arsramme} + {stjernetillegg}' },
    beskjeftigelse: { tekst: 'Beskjeftigelse', formel: '{arstimer} ÷ {arsramme} × 100' },
    sum_beskjeftigelse: { tekst: 'Samlet beskjeftigelse', formel: '{beskjeftigelser}' },
    uker_i_perioden: { tekst: 'Uker i perioden, regnet ut fra dagene', formel: '{dager_periode} ÷ {per_uke}' },
    timer_i_perioden_fra_okter: { tekst: 'Økter per uke gjort om til timer i perioden', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    periodenokkel: { tekst: 'Periodenøkkel: periodens andel av skoleåret', formel: '{dager_periode} ÷ {dager_skolear}' },
    perioderamme: { tekst: 'Perioderamme: årsrammen for perioden', formel: '{arsramme} × {periodenokkel}' },
    periodebeskjeftigelse: { tekst: 'Beskjeftigelse i perioden', formel: '{timer} ÷ {perioderamme} × 100' },
    vikartimer: { tekst: 'Vikartimer gjort om til 60-minutters timer', formel: '{okter} × {minutter} ÷ 60' },
    endring_beskjeftigelse: { tekst: 'Økning i beskjeftigelse', formel: '{vikartimer} ÷ {arsramme} × 100' },
    kalkulert_tid: { tekst: 'Kalkulert tid: undervisning med for- og etterarbeid', formel: '{vikartimer} × {konstant} ÷ {arsramme}' },
    timelonn: { tekst: 'Timelønn uten feriepenger', formel: '{arslonn} ÷ {arsverk} × {teller} ÷ {nevner}' },
    lonn: { tekst: 'Lønn for vikartimene', formel: '{kalkulert_tid} × {timelonn}' },
    feriepenger: { tekst: 'Feriepenger i tillegg', formel: '{lonn} × {sats} ÷ 100' },
    samlet_lonn: { tekst: 'Samlet avlønning', formel: '{lonn} + {feriepenger}' },
    funksjonsprosent: { tekst: 'Reduksjonen i prosent av full undervisning', formel: '{reduksjon} ÷ {arsramme} × 100' },
    selvdisponert: { tekst: 'Tid læreren disponerer selv i full stilling', formel: '{arsverk} − {planfestet}' },
    planfestet_okning: { tekst: 'Selvdisponert tid reduseres like mye som undervisningen, og planfestet tid øker tilsvarende', formel: '{selvdisponert} × {funksjonsprosent} ÷ 100' },
    planfestet_ny: { tekst: 'Planfestet arbeidstid', formel: '{planfestet} + {okning}' },
    arbeidsaar_dager: { tekst: 'Arbeidsåret: elevenes skoleår og 6 dager', formel: '{skolear} + {tillegg}' },
    ekstra_feriedager_60: { tekst: 'Ekstra feriedager fra 60 år: årsverket er kortere', formel: '({arsverk} − {arsverk_60}) ÷ {per_dag}' },
    arbeidsaar_dager_60: { tekst: 'Arbeidsåret: elevenes skoleår og 6 dager, minus ekstra ferie fra 60 år', formel: '{skolear} + {tillegg} − {ferie}' },
    planfestet_60: { tekst: 'Planfestet tid fra 60 år: samme andel av det kortere årsverket', formel: '{planfestet} × {arsverk_60} ÷ {arsverk}' },
    arbeidsaar_uker: { tekst: 'Arbeidsåret i uker', formel: '{dager} ÷ {per_uke}' },
    planfestet_maks: { tekst: 'Høyeste planfestede tid uten å utvide arbeidsåret', formel: '{uker} × {maks_uke}' },
    planfestet_per_uke: { tekst: 'Planfestet tid per uke', formel: '{planfestet} ÷ {uker}' },
    planfestet_per_uke_maks: { tekst: 'Planfestet tid per uke (høyeste tillatte)', formel: '{maks} ÷ {uker}' },
    utvidelse_timer: { tekst: 'Timer over grensen', formel: '{planfestet} − {maks}' },
    utvidelse_dager: { tekst: 'Arbeidsåret utvides med', formel: '{timer} ÷ {per_dag}' },
    stilling: { tekst: 'Stilling i alt', formel: '{beskjeftigelse} + {funksjonsprosent}' },
    arsverk_stilling: { tekst: 'Årsverket for stillingen', formel: '{arsverk} × {stilling} ÷ 100' },
    planfestet_undervisning: { tekst: 'Planfestet tid for undervisningsdelen', formel: '{planfestet} × {beskjeftigelse} ÷ 100' },
    funksjonstid: { tekst: 'Tid til funksjoner og andre oppgaver (planfestet)', formel: '{arsverk} × {funksjonsprosent} ÷ 100' },
    motetid: { tekst: 'Møtetid i skoleåret', formel: '{moter} × {uker}' },
    annen_planfestet: { tekst: 'Annen planfestet tid', formel: '{planfestet_undervisning} − {undervisning} − {motetid}' },
    selvdisponert_stilling: { tekst: 'Tid læreren disponerer selv', formel: '({arsverk} − {planfestet}) × {beskjeftigelse} ÷ 100' },
    motetid_i_funksjon: { tekst: 'Møtetid som ikke får plass i den planfestede tiden for undervisningen, legges i funksjonstiden', formel: '{motetid} − ({planfestet_undervisning} − {undervisning})' },
    funksjonstid_etter_moter: { tekst: 'Funksjonstid ut over møtene', formel: '{funksjonstid} − {motetid_i_funksjon}' },
    arslonn_stilling: { tekst: 'Årslønn i stillingen', formel: '{arslonn} × {stilling} ÷ 100' },
    samlet_med_reduksjon: { tekst: 'Samlet beskjeftigelse med redusert undervisning', formel: '{undervisning} + {funksjon} + {reduksjon}' },
    lonn_i_alt: { tekst: 'Lønn i alt: årslønn, tillegg, variabel lønn og overtidsbetaling', formel: '{arslonn} + {tillegg} + {variabel} + {overtid}' },
    ikke_fordelt: { tekst: 'Del av stillingen som ikke er fylt med fag og funksjoner', formel: '{stilling} − {beskjeftigelse} − {funksjoner}' },
    undervisningsdel: { tekst: 'Undervisningsdelen: undervisning og den delen som ikke er fylt', formel: '{beskjeftigelse} + {ikke_fordelt}' },
    stilling_alle_funksjoner: { tekst: 'Stilling: undervisning og alle funksjoner', formel: '{beskjeftigelse} + {funksjonsprosent} + {funksjon_uten_utvidelse}' },
    funksjonstid_uten_utvidelse: { tekst: 'Planfestet tid for funksjoner som ikke utvider planfestet tid', formel: '{planfestet} × {funksjon_uten_utvidelse} ÷ 100' },
    funksjonstid_i_alt: { tekst: 'Funksjonstid i planfestet tid i alt', formel: '{funksjonstid} + {funksjonstid_uten_utvidelse}' },
    selvdisponert_med_funksjon: {
      tekst: 'Tid læreren disponerer selv, også for funksjoner som ikke utvider planfestet tid',
      formel: '({arsverk} − {planfestet}) × ({beskjeftigelse} + {funksjon_uten_utvidelse}) ÷ 100',
    },
    planfestet_stilling: { tekst: 'Planfestet tid i stillingen', formel: '{planfestet_undervisning} + {funksjonstid}' },
    arbeidsaar_uker_utvidet: { tekst: 'Det utvidede arbeidsåret i uker', formel: '{uker} + {dager} ÷ {per_uke}' },
    variabel_prosent: { tekst: 'Variabel lønn: beskjeftigelse ut over stillingen, opp til hel stilling', formel: '100 − {stilling}' },
    variabel_prosent_differanse: { tekst: 'Variabel lønn: beskjeftigelse ut over stillingen', formel: '{beskjeftigelse} − {stilling}' },
    variabel_timer: { tekst: 'Variabel lønn i årsrammetimer', formel: '{variabel} × {arsramme} ÷ 100' },
    kalkulert_tid_variabel: { tekst: 'Kalkulert tid: arbeidstimene det betales for', formel: '{timer} × {konstant} ÷ {arsramme}' },
    variabel_lonn: { tekst: 'Variabel lønn: kalkulert tid × timelønn, som for vikartimer', formel: '{kalkulert_tid} × {timelonn}' },
    overtidsprosent: { tekst: 'Beskjeftigelse ut over hel stilling', formel: '{beskjeftigelse} − 100' },
    overtidstimer: { tekst: 'Undervisningstimer i overtid: timene årsrammen er økt med', formel: '{overtidsprosent} × {arsramme} ÷ 100' },
    kalkulert_tid_overtid: { tekst: 'Kalkulert tid: arbeidstimene det betales for', formel: '{timer} × {konstant} ÷ {arsramme}' },
    overtidsbetaling: { tekst: 'Overtidsbetaling: timelønn med 50 % tillegg', formel: '{kalkulert_tid} × {timelonn} × (100 + {tillegg}) ÷ 100' },
  },
  storrelser: {
    undervisningsprosent: 'undervisning',
    funksjon: 'funksjon',
    funksjoner: 'funksjoner',
    samlet_beskjeftigelse: 'samlet beskjeftigelse',
    teknisk_differanse: 'differanse',
    teknisk_timer: 'differanse i årsrammetimer',
    arstimer: 'årstimer',
    arsramme: 'årsramme',
    arsrammer: 'årsrammene',
    arsramme_justert: 'justert årsramme',
    stjernetillegg: 'tillegg',
    elever: 'elever',
    okter_per_uke: 'økter per uke',
    minutter_per_okt: 'minutter per økt',
    uker: 'uker',
    beskjeftigelse: 'beskjeftigelse',
    beskjeftigelser: 'gruppenes beskjeftigelse',
    sum_beskjeftigelse: 'samlet beskjeftigelse',
    timer_i_perioden: 'timer i perioden',
    dager_i_perioden: 'dager i perioden',
    dager_i_skolearet: 'dager i skoleåret',
    periodenokkel: 'periodenøkkel',
    perioderamme: 'perioderamme',
    periodebeskjeftigelse: 'periodebeskjeftigelse',
    vikartimer: 'vikartimer',
    antall_okter: 'økter',
    endring_beskjeftigelse: 'økning',
    timelonn_konstant: 'faktor fra § 12.4',
    kalkulert_tid: 'kalkulert tid',
    arslonn: 'årslønn',
    arsverk: 'årsverk',
    ferie_teller: 'teller',
    ferie_nevner: 'nevner',
    timelonn: 'timelønn',
    lonn: 'lønn',
    feriepengesats: 'feriepengesats',
    feriepenger: 'feriepenger',
    samlet_lonn: 'samlet avlønning',
    reduksjon_arsrammetimer: 'reduksjon',
    arsramme_funksjon: 'årsramme ved funksjon',
    funksjonsprosent: 'funksjonsprosent',
    planfestet: 'planfestet tid',
    selvdisponert: 'selvdisponert tid',
    planfestet_okning: 'økning',
    planfestet_ny: 'planfestet tid',
    skolear_dager: 'skoledager',
    arbeidsaar_tillegg: 'ekstra dager',
    arbeidsaar_dager: 'dager i arbeidsåret',
    arsverk_60: 'årsverk fra 60 år',
    ekstra_feriedager: 'ekstra feriedager',
    arbeidsdager_per_uke: 'dager per uke',
    arbeidsaar_uker: 'uker i arbeidsåret',
    planfestet_maks_uke: 'timer per uke',
    planfestet_maks: 'grense',
    planfestet_per_uke: 'per uke',
    utvidelse_timer: 'timer over grensen',
    timer_per_dag: 'timer per dag',
    utvidelse_dager: 'dager',
    stilling: 'stilling',
    arsverk_stilling: 'årsverk for stillingen',
    planfestet_undervisning: 'planfestet tid for undervisningsdelen',
    funksjonstid: 'funksjonstid',
    moter_per_uke: 'møtetimer per uke',
    skolear_uker: 'uker i skoleåret',
    motetid: 'møtetid',
    annen_planfestet: 'annen planfestet tid',
    selvdisponert_stilling: 'selvdisponert tid',
    motetid_i_funksjon: 'møtetid i funksjonstiden',
    funksjonstid_etter_moter: 'funksjonstid ut over møtene',
    arslonn_stilling: 'årslønn i stillingen',
    funksjon_uten_utvidelse: 'funksjoner uten utvidelse',
    ikke_fordelt: 'ikke fylt del av stillingen',
    funksjonstillegg: 'tillegg',
    redusert_undervisning: 'redusert undervisning',
    lonn_i_alt: 'lønn i alt',
    undervisningsdel: 'undervisningsdel',
    funksjonstid_uten_utvidelse: 'planfestet tid for funksjoner uten utvidelse',
    funksjonstid_i_alt: 'funksjonstid i alt',
    planfestet_stilling: 'planfestet tid i stillingen',
    arbeidsaar_uker_utvidet: 'uker i det utvidede arbeidsåret',
    variabel_prosent: 'variabel lønn',
    variabel_timer: 'årsrammetimer med variabel lønn',
    variabel_lonn: 'variabel lønn',
    overtidsprosent: 'prosent over hel stilling',
    overtidstimer: 'undervisningstimer i overtid',
    overtidstillegg: 'overtidstillegg',
    overtidsbetaling: 'overtidsbetaling',
  },
  enheter: {
    prosent: '%',
    timer: 'timer',
    arsrammetimer: 'årsrammetimer',
    timer_per_uke: 'timer per uke',
    minutter: 'minutter',
    uker: 'uker',
    dager: 'dager',
    okter: 'økter',
    elever: 'elever',
    kroner: 'kr',
    kroner_per_time: 'kr per time',
  },
};
