// UI-tekster for arbeidstidsmodulen på bokmål. arbeidstid.nn.ts må ha de samme nøklene.
// Formlene bruker plassholdere med operandenes navn, f.eks. {arstimer}. Appen fyller dem inn to ganger:
// med navnet på størrelsen (formelen) og med tallene (utregningen).

export const arbeidstidNb = {
  tittel: 'Arbeidstid',
  innledning:
    'Kalkulatorer for arbeidstid etter SFS 2213 (arbeidstidsavtalen for undervisningspersonalet) og hovedtariffavtalen i KS-området. Hver utregning viser metoden trinn for trinn og hvor tallene kommer fra.',
  kalkulatorer: {
    tittel: 'Kalkulatorer',
    flere: 'Flere kalkulatorer',
    stillingsplan: {
      tittel: 'Stillingsplan',
      kort: 'Stillingsplan',
      beskrivelse: 'Fag og funksjoner mot stillingsprosenten, med teknisk undertid eller overtid.',
    },
    beskjeftigelse: {
      tittel: 'Beskjeftigelse',
      kort: 'Beskjeftigelse',
      beskrivelse: 'Undervisningsprosent for ett eller flere fag.',
    },
    periode: {
      tittel: 'Periodebeskjeftigelse',
      kort: 'Periode',
      beskrivelse: 'Beskjeftigelse når undervisningen bare gjelder en del av skoleåret.',
    },
    vikar: {
      tittel: 'Vikartimer',
      kort: 'Vikartimer',
      beskrivelse: 'Økt beskjeftigelse for ansatte, eller lønn for timevikarer.',
    },
    planfestet: {
      tittel: 'Planfestet tid ved funksjoner',
      kort: 'Planfestet tid',
      beskrivelse: 'Hva skjer med planfestet tid når undervisningen reduseres for en funksjon?',
    },
    overtid: {
      tittel: 'Overtid over 100 %',
      kort: 'Overtid',
      beskrivelse: 'Betaling for undervisning ut over hel stilling.',
    },
    fordeling: {
      tittel: 'Fordeling av arbeidstiden',
      kort: 'Fordeling',
      beskrivelse: 'Hvordan årsverket fordeles i en tenkt stilling.',
    },
  },
  felles: {
    gruppe: 'Fag {nr}',
    grupper: 'Fag og grupper',
    leggTilGruppe: 'Legg til fag',
    fjernGruppe: 'Fjern fag {nr}',
    fag: 'Fag',
    fagSok: 'F.eks. engelsk vg1, R1 eller BAT',
    fagSokHjelp: 'Fag, program, trinn eller fagkode, f.eks. «engelsk vg1», «R1» eller «BAT».',
    ingenFagTreff: 'Ingen fag passer. Prøv et annet ord, eller skriv inn årsrammen selv.',
    fagValgt: 'Valgt fag',
    endreFag: 'Endre',
    arsrammeKort: 'årsramme {t60}/{t45}',
    manuellValg: 'Skriv inn årsramme selv',
    manuellEtikett: 'Årsramme (60 min)',
    manuellStjerne: 'Merket * i vedlegg 1',
    tilbakeTilSok: 'Søk i vedlegg 1',
    leggTilArsramme: 'Blandet gruppe',
    blandetEtikett: 'Også i timen',
    fjernArsramme: 'Fjern',
    faaElever: '15 eller færre elever i klassen',
    faaEleverHjelp: 'Fag merket * i vedlegg 1 får høyere årsramme når klassen har 1–15 elever.',
    undervisning: 'Timer',
    modusArstimer: 'Årstimer',
    modusTimerPeriode: 'Timer',
    modusOkter: 'Økter/uke',
    arstimer: 'Antall årstimer',
    arstimerFraGrep: 'Årstimetall for elevene fra Udir ({fagkoder}). Du kan endre det.',
    timerIPerioden: 'Antall timer i perioden',
    okter: 'Antall økter per uke',
    minutter: 'Minutter per økt',
    minutterAnnet: 'Annet',
    minutterFritt: 'Minutter',
    uker: 'Uker',
    ukerStandard: 'Hele skoleåret: {uker} uker',
    endreUker: 'Endre antall uker',
    ukerPeriode: 'Uker i perioden',
    manglerInndata: 'Velg fag og fyll inn timer for å se resultatet.',
    stjerne: '*',
    timerKort: '{timer} t',
    delresultat: '{verdi} %',
  },
  resultat: {
    samletBeskjeftigelse: 'Samlet beskjeftigelse',
    undervisning: 'Undervisning',
    funksjoner: 'Funksjoner',
    stillingsprosent: 'Stilling',
    tekniskUndertid: 'Teknisk undertid',
    tekniskOvertid: 'Teknisk overtid',
    iBalanse: 'Stillingsplanen går opp',
    beskjeftigelse: 'Beskjeftigelse',
    sumBeskjeftigelse: 'Samlet beskjeftigelse',
    periodebeskjeftigelse: 'Beskjeftigelse i perioden',
    endring: 'Økning i beskjeftigelse',
    planfestet: 'Planfestet arbeidstid',
    stilling: 'Stilling i alt',
    oversikt: 'Oversikt',
    perUke: 'Per uke',
    utvidelse: 'Utvidelse av arbeidsåret',
    ingenUtvidelse: 'Arbeidsåret utvides ikke.',
    kalkulertTid: 'Kalkulert tid',
    timelonn: 'Timelønn',
    lonn: 'Lønn',
    feriepenger: 'Feriepenger',
    feriepengerTillegg: 'Feriepenger i tillegg',
    utbetaltLonn: 'Lønn som utbetales',
    funksjonsprosent: 'Funksjon og andre oppgaver',
    undervisningstimer: 'Undervisningstimer',
    overtidsbetaling: 'Overtidsbetaling',
  },
  advarsler: {
    over_hel_stilling: 'Undervisning og funksjoner er til sammen mer enn en hel stilling.',
    motetid_for_stor: 'Undervisning og møtetid er mer enn den planfestede tiden for undervisningsdelen. Diagrammet viser da ingen annen planfestet tid.',
    mangler_elevtall: 'Faget er merket * i vedlegg 1. Skriv inn antall elever for å se om årsrammen skal økes.',
  },
  feil: {
    regel: 'Utregningen kunne ikke gjøres med regelverket for valgt dato: {melding}',
  },
  vikar: {
    type: 'Hvem tar vikartimene?',
    fast: 'Ansatt i stilling',
    timevikar: 'Timevikar',
    okter: 'Antall vikarøkter',
    lonn: 'Lønn',
    lonnGarantilonn: 'Garantilønn fra hovedtariffavtalen',
    lonnManuell: 'Egen årslønn',
    stillingsgruppe: 'Stillingsgruppe',
    ansiennitet: 'Ansiennitet',
    ansiennitetAr: '{ar} år',
    arslonn: 'Årslønn i kroner',
    arslonnHjelp: 'Brukes når læreren har høyere lønn enn garantilønnen.',
    over60: 'Vikaren er over 60 år (høyere feriepengesats)',
  },
  overtid: {
    beskjeftigelse: 'Samlet beskjeftigelse i prosent',
    beskjeftigelseHjelp: 'Undervisning og funksjoner til sammen, f.eks. 110. Det som er over 100 %, betales som overtid.',
    fag: 'Faget overtiden gjelder',
    ingenOvertid: 'Beskjeftigelsen er ikke over 100 %, så det er ingen overtid.',
    over60: 'Læreren er over 60 år (høyere feriepengesats)',
    forklaringTema: 'Hvorfor endrer ikke faget beløpet?',
    forklaring:
      'Overtidsprosenten gjøres først om til undervisningstimer i faget (prosent × årsramme ÷ 100). Undervisningstimene gjøres så om til kalkulert tid (timer × {konstant} ÷ årsramme), som er arbeidstimene det betales for. Årsrammen står i begge trinnene og går opp. Faget og bryteren for små klasser endrer derfor antall undervisningstimer, men ikke beløpet: 1 % over hel stilling gir alltid {perProsent} timer kalkulert tid.',
  },
  planfestet: {
    reduksjon: 'Hvor mye er undervisningen redusert?',
    iProsent: 'I prosent av full stilling',
    iArsrammetimer: 'I årsrammetimer',
    prosent: 'Reduksjon i prosent',
    arsrammetimer: 'Reduksjon i årsrammetimer (60 min)',
    arsrammetimerHjelp: 'F.eks. 28,5 for kontaktlærer i videregående (SFS 2213 punkt 7.3 b).',
  },
  periode: {
    dager: 'Dager i perioden',
    dagerHjelp: 'Undervisningsdager etter skoleruta.',
    skolear: 'Dager i skoleåret',
    skolearHjelp: 'Tomt felt gir {dager} dager.',
  },
  fordeling: {
    grunnlag: 'Regn ut fra',
    grunnlagFag: 'Fag',
    grunnlagStilling: 'Stillingsprosent',
    stilling: 'Undervisning i prosent av full stilling',
    stillingHjelp: 'F.eks. 100 for en vanlig lærerstilling uten funksjoner.',
    arsramme: 'Årsramme (vedlegg 1)',
    velgNiva: 'Velg årsramme',
    nivaValg: '{t60}/{t45} – f.eks. {eksempler}',
    funksjon: 'Funksjoner og andre oppgaver',
    moter: 'Møtetid per uke (timer)',
    moterHjelp: 'Faste møter i planfestet tid, f.eks. team- og fellesmøter.',
    diagramTittel: 'Fordeling av årsverket',
    diagramBeskrivelse: 'Stolpediagram over årsverket på {timer} timer: {deler}.',
    illustrasjon: 'Illustrasjon av en tenkt stilling. Ikke en arbeidsplan.',
    planfestet: 'Planfestet tid',
    selvdisponert: 'Tid læreren disponerer selv',
    tabell: 'Tallene i diagrammet',
    del: 'Del',
    timer: 'Timer per år',
    andel: 'Andel',
    perUke: 'Per uke',
    sum: 'Årsverk i alt',
    perUkeForklaring: 'Per uke er timene delt på {uker} uker i arbeidsåret.',
    brukAvTiden: 'Hva tiden brukes til',
    deler: {
      undervisning: 'Undervisning',
      motetid: 'Møtetid',
      annen_planfestet: 'Annen planfestet tid',
      funksjonstid: 'Funksjoner og andre oppgaver',
      selvdisponert: 'Selvdisponert tid',
    },
  },
  stillingsplan: {
    stilling: 'Stillingsprosent',
    stillingHjelp: 'Stillingen læreren er ansatt i.',
    funksjoner: 'Funksjoner',
    funksjonerHjelp: 'Funksjoner som kontaktlærer oppgis i prosent av full stilling, slik de står i stillingsplanen.',
    funksjonNr: 'Funksjon {nr}',
    funksjonNavn: 'Navn',
    funksjonNavnPlassholder: 'F.eks. kontaktlærer',
    funksjonProsent: 'Prosent',
    leggTilFunksjon: 'Legg til funksjon',
    fjernFunksjon: 'Fjern funksjon {nr}',
    timerIFag: 'Årsrammetimer i',
    ingenFag: 'Legg inn fag for å se differansen i timer.',
    hvertFag: 'Timer i hvert fag',
    hvertFagMangler: 'For å fylle stillingen mangler det så mange årsrammetimer, regnet med årsrammen i hvert fag:',
    hvertFagForMye: 'Stillingen er overskredet med så mange årsrammetimer, regnet med årsrammen i hvert fag:',
    fagRad: '{fag} (årsramme {arsramme})',
    overtidLenke: 'Regn ut overtidsbetaling for {prosent} %',
  },
  grafikk: {
    stillingsplan: 'Stolpe for stillingsplanen: {deler}. Samlet {sum} %. Streken viser stillingen på {grense} %.',
    stilling: 'Stolpe for stillingen: {sum} % i alt ({deler}). Streken viser {grense} %.',
    periode: 'Perioden er {dager} av {skolear} undervisningsdager ({prosent} % av skoleåret).',
    planfestet: 'Planfestet tid {grunn} timer, økning {okning} timer. Grensen er {maks} timer; {over} timer over grensen utvider arbeidsåret.',
  },
  metode: {
    tittel: 'Slik regnes det ut',
    kilder: 'Kilder',
    ikkeFunnet: 'Metodebeskrivelsen mangler.',
  },
  utregning: {
    formel: 'Formel',
    innsatt: 'Utregning',
    fra: 'Fra {kilde}',
    inndata: 'skrevet inn',
    rad: 'Vedlegg 1: {rad}',
  },
  trinn: {
    sum_funksjon: { tekst: 'Funksjoner til sammen', formel: '{funksjoner}' },
    samlet_beskjeftigelse: { tekst: 'Samlet beskjeftigelse: undervisning og funksjoner', formel: '{undervisning} + {funksjon}' },
    teknisk_differanse: { tekst: 'Differanse mot stillingen: minus er teknisk undertid, pluss er teknisk overtid', formel: '{beskjeftigelse} − {stilling}' },
    teknisk_timer: { tekst: 'Differansen i årsrammetimer i faget', formel: '{differanse} × {arsramme} ÷ 100' },
    arstimer_fra_okter: { tekst: 'Økter per uke gjort om til årstimer', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    laveste_arsramme: { tekst: 'Elever fra flere program eller nivåer: laveste årsramme brukes', formel: 'laveste av {arsrammer}' },
    stjernetillegg: { tekst: 'Fag merket * med 1–15 elever: årsrammen økes', formel: '{arsramme} + {stjernetillegg}' },
    beskjeftigelse: { tekst: 'Beskjeftigelse', formel: '{arstimer} ÷ {arsramme} × 100' },
    sum_beskjeftigelse: { tekst: 'Samlet beskjeftigelse', formel: '{beskjeftigelser}' },
    timer_i_perioden_fra_okter: { tekst: 'Økter per uke gjort om til timer i perioden', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    periodenokkel: { tekst: 'Periodenøkkel: periodens andel av skoleåret', formel: '{dager_periode} ÷ {dager_skolear}' },
    perioderamme: { tekst: 'Perioderamme: årsrammen for perioden', formel: '{arsramme} × {periodenokkel}' },
    periodebeskjeftigelse: { tekst: 'Beskjeftigelse i perioden', formel: '{timer} ÷ {perioderamme} × 100' },
    vikartimer: { tekst: 'Vikartimer gjort om til 60-minutters timer', formel: '{okter} × {minutter} ÷ 60' },
    endring_beskjeftigelse: { tekst: 'Økning i beskjeftigelse', formel: '{vikartimer} ÷ {arsramme} × 100' },
    kalkulert_tid: { tekst: 'Kalkulert tid: undervisning med for- og etterarbeid', formel: '{vikartimer} × {konstant} ÷ {arsramme}' },
    timelonn: { tekst: 'Timelønn uten feriepenger', formel: '{arslonn} ÷ {arsverk} × {teller} ÷ {nevner}' },
    lonn: { tekst: 'Lønn for vikartimene', formel: '{kalkulert_tid} × {timelonn}' },
    feriepenger: { tekst: 'Feriepenger i tillegg', formel: '{lonn} × {sats} ÷ 100' },
    samlet_lonn: { tekst: 'Samlet avlønning', formel: '{lonn} + {feriepenger}' },
    funksjonsprosent: { tekst: 'Reduksjonen i prosent av full undervisning', formel: '{reduksjon} ÷ {arsramme} × 100' },
    selvdisponert: { tekst: 'Tid læreren disponerer selv i full stilling', formel: '{arsverk} − {planfestet}' },
    planfestet_okning: { tekst: 'Selvdisponert tid reduseres like mye som undervisningen, og planfestet tid øker tilsvarende', formel: '{selvdisponert} × {funksjonsprosent} ÷ 100' },
    planfestet_ny: { tekst: 'Planfestet arbeidstid', formel: '{planfestet} + {okning}' },
    arbeidsaar_dager: { tekst: 'Arbeidsåret: elevenes skoleår og 6 dager', formel: '{skolear} + {tillegg}' },
    arbeidsaar_uker: { tekst: 'Arbeidsåret i uker', formel: '{dager} ÷ {per_uke}' },
    planfestet_maks: { tekst: 'Høyeste planfestede tid uten å utvide arbeidsåret', formel: '{uker} × {maks_uke}' },
    planfestet_per_uke: { tekst: 'Planfestet tid per uke', formel: '{planfestet} ÷ {uker}' },
    planfestet_per_uke_maks: { tekst: 'Planfestet tid per uke (høyeste tillatte)', formel: '{maks} ÷ {uker}' },
    utvidelse_timer: { tekst: 'Timer over grensen', formel: '{planfestet} − {maks}' },
    utvidelse_dager: { tekst: 'Arbeidsåret utvides med', formel: '{timer} ÷ {per_dag}' },
    stilling: { tekst: 'Stilling i alt', formel: '{beskjeftigelse} + {funksjonsprosent}' },
    arsverk_stilling: { tekst: 'Årsverket for stillingen', formel: '{arsverk} × {stilling} ÷ 100' },
    planfestet_undervisning: { tekst: 'Planfestet tid for undervisningsdelen', formel: '{planfestet} × {beskjeftigelse} ÷ 100' },
    funksjonstid: { tekst: 'Tid til funksjoner og andre oppgaver (planfestet)', formel: '{arsverk} × {funksjonsprosent} ÷ 100' },
    motetid: { tekst: 'Møtetid i skoleåret', formel: '{moter} × {uker}' },
    annen_planfestet: { tekst: 'Annen planfestet tid', formel: '{planfestet_undervisning} − {undervisning} − {motetid}' },
    selvdisponert_stilling: { tekst: 'Tid læreren disponerer selv', formel: '({arsverk} − {planfestet}) × {beskjeftigelse} ÷ 100' },
    arstimer_fra_stilling: { tekst: 'Undervisning i stillingen', formel: '{stilling} × {arsramme} ÷ 100' },
    overtidsprosent: { tekst: 'Beskjeftigelse ut over hel stilling', formel: '{beskjeftigelse} − 100' },
    overtidstimer: { tekst: 'Undervisningstimer i overtid: timene årsrammen er økt med', formel: '{overtidsprosent} × {arsramme} ÷ 100' },
    kalkulert_tid_overtid: { tekst: 'Kalkulert tid: arbeidstimene det betales for', formel: '{timer} × {konstant} ÷ {arsramme}' },
    overtidsbetaling: { tekst: 'Overtidsbetaling: timelønn med 50 % tillegg', formel: '{kalkulert_tid} × {timelonn} × (100 + {tillegg}) ÷ 100' },
  },
  storrelser: {
    undervisningsprosent: 'undervisning',
    funksjon: 'funksjon',
    funksjoner: 'funksjoner',
    samlet_beskjeftigelse: 'samlet beskjeftigelse',
    teknisk_differanse: 'differanse',
    teknisk_timer: 'differanse i årsrammetimer',
    arstimer: 'årstimer',
    arsramme: 'årsramme',
    arsrammer: 'årsrammene',
    arsramme_justert: 'justert årsramme',
    stjernetillegg: 'tillegg',
    elever: 'elever',
    okter_per_uke: 'økter per uke',
    minutter_per_okt: 'minutter per økt',
    uker: 'uker',
    beskjeftigelse: 'beskjeftigelse',
    beskjeftigelser: 'gruppenes beskjeftigelse',
    sum_beskjeftigelse: 'samlet beskjeftigelse',
    timer_i_perioden: 'timer i perioden',
    dager_i_perioden: 'dager i perioden',
    dager_i_skolearet: 'dager i skoleåret',
    periodenokkel: 'periodenøkkel',
    perioderamme: 'perioderamme',
    periodebeskjeftigelse: 'periodebeskjeftigelse',
    vikartimer: 'vikartimer',
    antall_okter: 'økter',
    endring_beskjeftigelse: 'økning',
    timelonn_konstant: 'faktor fra § 12.4',
    kalkulert_tid: 'kalkulert tid',
    arslonn: 'årslønn',
    arsverk: 'årsverk',
    ferie_teller: 'teller',
    ferie_nevner: 'nevner',
    timelonn: 'timelønn',
    lonn: 'lønn',
    feriepengesats: 'feriepengesats',
    feriepenger: 'feriepenger',
    samlet_lonn: 'samlet avlønning',
    reduksjon_arsrammetimer: 'reduksjon',
    arsramme_funksjon: 'årsramme ved funksjon',
    funksjonsprosent: 'funksjonsprosent',
    planfestet: 'planfestet tid',
    selvdisponert: 'selvdisponert tid',
    planfestet_okning: 'økning',
    planfestet_ny: 'planfestet tid',
    skolear_dager: 'skoledager',
    arbeidsaar_tillegg: 'ekstra dager',
    arbeidsaar_dager: 'dager i arbeidsåret',
    arbeidsdager_per_uke: 'dager per uke',
    arbeidsaar_uker: 'uker i arbeidsåret',
    planfestet_maks_uke: 'timer per uke',
    planfestet_maks: 'grense',
    planfestet_per_uke: 'per uke',
    utvidelse_timer: 'timer over grensen',
    timer_per_dag: 'timer per dag',
    utvidelse_dager: 'dager',
    stilling: 'stilling',
    arsverk_stilling: 'årsverk for stillingen',
    planfestet_undervisning: 'planfestet tid for undervisningsdelen',
    funksjonstid: 'funksjonstid',
    moter_per_uke: 'møtetimer per uke',
    skolear_uker: 'uker i skoleåret',
    motetid: 'møtetid',
    annen_planfestet: 'annen planfestet tid',
    selvdisponert_stilling: 'selvdisponert tid',
    overtidsprosent: 'prosent over hel stilling',
    overtidstimer: 'undervisningstimer i overtid',
    overtidstillegg: 'overtidstillegg',
    overtidsbetaling: 'overtidsbetaling',
  },
  enheter: {
    prosent: '%',
    timer: 'timer',
    arsrammetimer: 'årsrammetimer',
    timer_per_uke: 'timer per uke',
    minutter: 'minutter',
    uker: 'uker',
    dager: 'dager',
    okter: 'økter',
    elever: 'elever',
    kroner: 'kr',
    kroner_per_time: 'kr per time',
  },
};
