// UI-tekstar for arbeidstidsmodulen på nynorsk. Typen gjer at ein manglande nøkkel gir byggjefeil.
import type { arbeidstidNb } from './arbeidstid.nb.ts';

type Skjema<T> = { [K in keyof T]: T[K] extends string ? string : Skjema<T[K]> };

export const arbeidstidNn: Skjema<typeof arbeidstidNb> = {
  tittel: 'Arbeidstid',
  skjema: {
    stilling: 'Stilling',
    vikariat: 'Vikariat',
    undervisning: 'Undervisning',
    tid: 'Tid på skulen',
    lonn: 'Løn',
  },
  kalkulatorer: {
    tittel: 'Kalkulatorar',
    flere: 'Fleire kalkulatorar',
    flereUnder: 'Sysselsetjing, vikar og overtid.',
    arbeidsplan: {
      tittel: 'Arbeidsplan',
      kort: 'Arbeidsplan',
      // Den mjuke bindestreken (\u00ad) deler ordet på smale skjermar.
      forside: 'Fag, funksjonar, periode\u00adsysselsetjing, fordeling av arbeidstida og løn.',
      beskrivelse: 'Fag og funksjonar mot stillingsprosenten for heile skuleåret eller ein periode (periodesysselsetjing), med fordelinga av arbeidstida og løn.',
    },
    beskjeftigelse: {
      tittel: 'Sysselsetjing',
      kort: 'Sysselsetjing',
      beskrivelse: 'Undervisningsprosent for eitt eller fleire fag.',
    },
    vikar: {
      tittel: 'Vikartimar',
      kort: 'Vikartimar',
      beskrivelse: 'Auka sysselsetjing for tilsette, eller løn for timevikarar.',
    },
    overtid: {
      tittel: 'Overtid over 100 %',
      kort: 'Overtid',
      beskrivelse: 'Betaling for undervisning utover heil stilling.',
    },
  },
  felles: {
    fortsettArbeidsplan: 'Hald fram i Arbeidsplan med desse faga',
    skrivUt: 'Skriv ut {navn} eller lagre som PDF',
    skrivUtKort: 'Skriv ut eller lagre som PDF',
    ukerHalvaar: 'T.d. for fag som berre går eit halvår.',
    nyttVindu: 'Opne {navn} i nytt vindauge',
    nyttVinduKort: 'Opne i nytt vindauge',
    gruppe: 'Fag {nr}',
    grupper: 'Fag og grupper',
    leggTilGruppe: 'Legg til fag',
    fjernGruppe: 'Fjern fag {nr}',
    fag: 'Fag',
    fagSok: 'T.d. engelsk vg1, R1 eller BAT',
    fagSokHjelp: 'Fag, program, trinn eller fagkode, t.d. «engelsk vg1», «R1» eller «BAT».',
    ingenFagTreff: 'Ingen fag passar. Prøv eit anna ord, eller skriv inn årsramma sjølv.',
    endreFag: 'Endre',
    grepTreff: 'Fag med fagkode frå Udir',
    grepArsramme: 'årsramme {t60}/{t45}',
    grepFlertydig: 'årsramma avheng av program eller trinn',
    grepUkoblet: 'ikkje kopla til årsramme',
    velgProgramTrinn: 'Vel utdanningsprogram og trinn for {fag}',
    velgProgramTrinnHjelp: 'Vedlegg 1 har ulik årsramme for faget på ulike utdanningsprogram eller trinn.',
    ikkeKoblet: '{fag} er ikkje kopla til ei årsramme i vedlegg 1. Søk opp rada i vedlegget, eller skriv inn årsramma sjølv.',
    koblingEksplisitt: 'Årsramme frå koplinga: fagkoden er kopla direkte til rada i vedlegg 1.',
    koblingRegel: 'Årsramme frå koplinga: regel for felles programfag på programmet og trinnet.',
    overstyrtArsramme: 'Overstyrt: du har valt årsramma sjølv. Koplinga gir rad {nr}.',
    valgtSelv: 'Valt sjølv: faget er ikkje kopla til ei årsramme.',
    endreArsramme: 'Vel årsramme sjølv',
    brukKobling: 'Bruk koplinga',
    avbrytOverstyring: 'Avbryt',
    arstimerOverstyrt: 'Overstyrt: Udir har {timer} årstimar for {fagkode}.',
    brukArstimer: 'Bruk {timer}',
    arsrammeKort: 'årsramme {t60}/{t45}',
    manuellValg: 'Skriv inn årsramme sjølv',
    manuellEtikett: 'Årsramme (60 min)',
    manuellStjerne: 'Merkt * i vedlegg 1',
    tilbakeTilSok: 'Søk i vedlegg 1',
    leggTilArsramme: 'Blanda gruppe',
    blandetEtikett: 'Også i timen',
    fjernArsramme: 'Fjern',
    faaElever: '15 eller færre elevar i klassen',
    faaEleverHjelp: 'Fag merkte * i vedlegg 1 får høgare årsramme når klassen har 1–15 elevar.',
    undervisning: 'Timar',
    modusArstimer: 'Årstimar',
    modusTimerPeriode: 'Timar',
    modusOkter: 'Økter/veke',
    arstimer: 'Tal på årstimar',
    arstimerFraGrep: 'Årstimetal for elevane frå Udir ({fagkoder}). Du kan endre det.',
    timerIPerioden: 'Tal på timar i perioden',
    okter: 'Tal på økter per veke',
    minutter: 'Minutt per økt',
    minutterAnnet: 'Anna',
    minutterFritt: 'Minutt',
    uker: 'Veker',
    ukerStandard: 'Heile skuleåret: {uker} veker',
    endreUker: 'Endre talet på veker',
    ukerPeriode: 'Veker i perioden',
    manglerInndata: 'Vel fag og fyll inn timar for å sjå resultatet.',
    stjerne: '*',
    timerKort: '{timer} t',
    delresultat: '{verdi} %',
  },
  resultat: {
    samletBeskjeftigelse: 'Samla sysselsetjing',
    undervisning: 'Undervisning',
    funksjoner: 'Funksjonar',
    stillingsprosent: 'Stilling',
    tekniskUndertid: 'Teknisk undertid',
    variabelLonn: 'Variabel løn',
    tekniskOvertid: 'Teknisk overtid',
    iBalanse: 'Arbeidsplanen går opp',
    beskjeftigelse: 'Sysselsetjing',
    sumBeskjeftigelse: 'Samla sysselsetjing',
    periodebeskjeftigelse: 'Sysselsetjing i perioden',
    endring: 'Auke i sysselsetjing',
    kalkulertTid: 'Kalkulert tid',
    timelonn: 'Timeløn',
    lonn: 'Løn',
    feriepengerTillegg: 'Feriepengar i tillegg',
    utbetaltLonn: 'Løn som blir utbetalt',
    undervisningstimer: 'Undervisningstimar',
    overtidsbetaling: 'Overtidsbetaling',
  },
  advarsler: {
    over_hel_stilling: 'Undervisning og funksjonar er til saman meir enn ei heil stilling.',
    motetid_for_stor: 'Møtetida er meir enn den planfesta tida som er att etter undervisninga og funksjonane. Diagrammet viser då inga anna planfesta tid.',
    uker_fra_dager:
      'Veker i perioden er rekna ut frå dagane (dagar ÷ skuledagar per veke). Har vekene ulikt tal på skuledagar eller ulik timeplan, bør du skrive inn talet på veker eller timane i perioden sjølv.',
    mangler_elevtall: 'Faget er merkt * i vedlegg 1. Skriv inn talet på elevar for å sjå om årsramma skal aukast.',
  },
  feil: {
    regel: 'Utrekninga kunne ikkje gjerast med regelverket for valt dato: {melding}',
  },
  vikar: {
    kortTimer: 'Vikartimane',
    oppsummering: '{okter} økter à {minutter} min',
    type: 'Kven tek vikartimane?',
    fast: 'Tilsett i stilling',
    timevikar: 'Timevikar',
    okter: 'Tal på vikarøkter',
    lonn: 'Løn',
    lonnGarantilonn: 'Garantiløn frå hovudtariffavtalen',
    lonnManuell: 'Eiga årsløn',
    stillingsgruppe: 'Stillingsgruppe',
    ansiennitet: 'Ansiennitet',
    ansiennitetAr: '{ar} år',
    arslonn: 'Årsløn i kroner',
    over60: 'Vikaren er over 60 år (høgare feriepengesats)',
  },
  overtid: {
    beskjeftigelse: 'Samla sysselsetjing i prosent',
    beskjeftigelseHjelp: 'Undervisning og funksjonar til saman, t.d. 110. Det som er over 100 %, blir betalt som overtid.',
    fag: 'Faget overtida gjeld',
    ingenOvertid: 'Sysselsetjinga er ikkje over 100 %, så det er inga overtid.',
    over60: 'Læraren er over 60 år (høgare feriepengesats)',
    forklaringTema: 'Kvifor endrar ikkje faget beløpet?',
    forklaring:
      'Overtidsprosenten blir først gjord om til undervisningstimar i faget (prosent × årsramme ÷ 100). Undervisningstimane blir så gjorde om til kalkulert tid (timar × {konstant} ÷ årsramme), som er arbeidstimane det blir betalt for. Årsramma står i begge stega og går opp. Faget og brytaren for små klassar endrar difor talet på undervisningstimar, men ikkje beløpet: 1 % over heil stilling gir alltid {perProsent} timar kalkulert tid.',
  },
  periode: {
    heleAret: 'Tilsvarande for heile skuleåret',
    ukerFraDager:
      'Tomt felt gir {uker} veker: {dager} dagar ÷ {perUke} skuledagar per veke. Vekene i perioden kan ha ulikt tal på skuledagar (fridagar, feriar) eller ulik timeplan. Skriv inn talet om det avvik.',
    ukerFyllDager: 'Fyll inn dagar i perioden øvst, så blir vekene rekna ut. Du kan også skrive inn talet sjølv.',
    dager: 'Dagar i perioden',
    dagerHjelp: 'Undervisningsdagar etter skuleruta.',
    skolear: 'Dagar i skuleåret',
    skolearHjelp: 'Tomt felt gir {dager} dagar.',
  },
  fordeling: {
    moter: 'Møtetid per veke (timar)',
    visStort: 'Vis stort',
    oppsummering: 'planfesta {planfestet} t, sjølvdisponert {selv} t',
    visMindre: 'Lukk stor vising',
    diagramTittelPeriode: 'Fordeling av arbeidstida i perioden',
    perUkePeriode: 'Per veke er timane delte på {uker} skuleveker i perioden (dagar ÷ 5). Planleggingsdagane ({planlegging} timar) er haldne utanfor.',
    diagramTittel: 'Fordeling av årsverket',
    diagramBeskrivelse: 'Stolpediagram over årsverket på {timer} timar: {deler}.',
    planfestet: 'Planfesta tid',
    tabell: 'Tala i diagrammet',
    del: 'Del',
    timer: 'Timar per år',
    andel: 'Del',
    perUke: 'Per veke',
    sum: 'Årsverk i alt',
    perUkeForklaring: 'Per veke er timane delte på {uker} skuleveker. Planleggingsdagane ({planlegging} timar) er haldne utanfor.',
    perUkeUtvidet:
      'Planfesta tid blir meir enn {maksUke} timar per veke i snitt. Då blir arbeidsåret utvida med {dager} dagar (SFS 2213 punkt 5.3), og per veke er timane utanom planleggingsdagane ({planlegging} timar) delte på {uker} veker.',
    brukAvTiden: 'Kva tida blir brukt til',
    deler: {
      undervisning: 'Undervisning',
      motetid: 'Møtetid',
      annen_planfestet: 'Anna planfesta tid',
      planleggingsdager: 'Planleggings\u00addagar',
      funksjonstid: 'Funksjonar og andre oppgåver',
      selvdisponert: 'Sjølvdisponert tid',
    },
  },
  arbeidsplan: {
    illustrasjon: 'Illustrasjon – ikkje ein arbeidsplan. Ekte arbeidsplanar blir laga i skulen sine eigne system.',
    stilling: 'Stillingsprosent',
    funksjoner: 'Funksjonar',
    funksjonerHjelp:
      'Funksjonar som kontaktlærar blir oppgitt i prosent av full stilling, slik dei står i stillingsplanen. Ein funksjon kan ha berre avsett tid, berre tillegg (0 %) eller begge delar. Tillegg blir slått på ved funksjonen når løna blir rekna ut. Slå av «Utvidar planfesta tid» for funksjonar som blir gitt utan at planfesta tid blir utvida, t.d. kontaktlærar der det er praksis. Det endrar berre diagrammet over arbeidstida.',
    funksjonNr: 'Funksjon {nr}',
    funksjonNavn: 'Namn',
    funksjonNavnPlassholder: 'T.d. kontaktlærar',
    funksjonProsent: 'Prosent',
    funksjonTimer: 'Årsrammetimar',
    funksjonEnhet: 'oppgitt i',
    enhetTimer: 'Timar',
    timerSomProsent: 'Årsrammetimar ÷ {arsramme} = {prosent} % av full stilling.',
    kontaktlaererHint: 'Kontaktlærar: minst {timer} årsrammetimar (SFS 2213 punkt 7.3 b).',
    kontaktlaererBruk: 'Bruk {timer} timar',
    leggTilFunksjon: 'Legg til funksjon',
    fjernFunksjon: 'Fjern funksjon {nr}',
    timerIFag: 'Årsrammetimar i',
    ingenFag: 'Legg inn fag for å sjå differansen i timar.',
    hvertFag: 'Timar i kvart fag',
    hvertFagMangler: 'For å fylle stillinga manglar det så mange årsrammetimar, rekna med årsramma i kvart fag:',
    hvertFagForMye: 'Stillinga er overskriden med så mange årsrammetimar, rekna med årsramma i kvart fag:',
    fagRad: '{fag} (årsramme {arsramme})',
    overtidLenke: 'Rekn ut overtidsbetaling for {prosent} %',
    utvider: 'Utvidar planfesta tid',
    utenUtvidelseMerknad: 'Funksjonar som ikkje utvidar planfesta tid ({prosent} %), er fordelte som undervisninga: ein del planfesta tid og ein del tid læraren disponerer sjølv.',
    tillegg: 'Møte, planleggingsdagar og løn',
    planlegging: 'Timar på planleggingsdagar',
    planleggingHjelp: 'Tomt felt gir {timer} timar (6 dagar à 7,5 timar), som for ein lærar i heil stilling. Skriv inn eit anna tal ved deltid, for ein periode, om skulen har andre planleggingsdagar, eller for lærarar som er 60 år og eldre når ferien blir lagd til planleggingsdagane.',
    planleggingOppsummering: 'planleggingsdagar {timer} t',
    moterHjelp: 'Valfritt. Faste møte i planfesta tid, til diagrammet over arbeidstida.',
    visLonn: 'Rekn ut løn',
    arslonn: 'Årsløn i stillinga',
    arslonnStilling: 'Årsløn i {prosent} % stilling',
    lonnIPerioden: 'Løn i perioden',
    lonnStillingPeriode: 'Løn i {prosent} % stilling i perioden',
    gjelder: 'Arbeidsplanen gjeld',
    heleSkolearet: 'Heile skuleåret',
    enPeriode: 'Ein periode',
    stillingPeriode: 'Stillingsprosent i perioden',
    visProsent: 'Prosent',
    iPerioden: 'I perioden',
    paArsbasis: 'På årsbasis',
    iPeriodenRad: 'I perioden',
    beskjeftigelseArsbasis: 'Samla sysselsetjing på årsbasis',
    timerIPerioden: '{timer} timar i perioden',
    fordelingPeriode: 'Timane gjeld perioden: {dager} av {skolear} undervisningsdagar.',
    lonnIAlt: 'Løn i året',
    sammenligning: {
      stillingen: 'Stillinga, prosent',
      arbeidstid: 'Arbeidstida, timar per år',
      arbeidstidPeriode: 'Arbeidstida, timar i perioden',
      lonn: 'Løn, kroner',
      differanse: 'Over/under stillinga',
      planfestetIAlt: 'Planfesta tid i alt',
      funksjonerKort: 'Funksjonar',
      periode: 'Tala for ein arbeidsplan som gjeld ein periode, gjeld perioden.',
    },
    tilleggNavn: 'Tillegg',
    funksjonerIngen: 'Ingen lagde inn',
    funksjonerOppsummering: '{antall} lagde inn, {prosent} %',
    moterOppsummering: 'møte {timer} t per veke',
    lonnOppsummering: 'løn blir rekna ut',
    tilleggVippe: 'Tillegg i løna',
    tilleggFelt: 'Tillegg per år, funksjon {nr}',
    tilleggRad: 'Tillegg: {funksjon}',
    tilleggKontaktlaerer: 'Fylt inn frå SFS 2213 punkt 9.1: minst {kr} kr i året for kontaktlærar. Skriv inn eit anna beløp om tillegget er høgare.',
    tilleggRadgiver: 'Fylt inn frå SFS 2213 punkt 9.1: minst {kr} kr i året for rådgivar eller sosiallærar. Skriv inn eit anna beløp om tillegget er høgare.',
    tilleggUkjent: 'Fylt inn med beløpet for kontaktlærar i SFS 2213 punkt 9.1 ({kr} kr). Godtgjering for andre funksjonar blir fastsett lokalt. Skriv inn beløpet.',
    tilleggEget: 'Skrive inn sjølv. Tøm feltet for å bruke beløpet frå SFS 2213 punkt 9.1.',
    tilleggHint: 'Tillegg for funksjonar blir slått på ved kvar funksjon under Funksjonar.',
    variabelRad: 'Variabel løn ({timer} timar kalkulert tid)',
    overtidUtenFag: 'Legg inn fag for å rekne ut variabel løn og overtidsbetaling.',
    lonnStillingKort: 'Løn i stillinga',
    fraDato: 'Første dag i perioden',
    tilDato: 'Siste dag i perioden',
    datoHjelp: 'Til løna for perioden. Heile månader gir heil månadsløn, og i brotne månader blir arbeidsdagane rekna ÷ 21,67. Arbeidsdagar er måndag–fredag, også offentlege fridagar, slik Vestland fylkeskommune reknar. Andre arbeidsgivarar kan trekkje frå fridagane.',
    datoFeil: 'Siste dag kan ikkje vere før første dag.',
    lonnsandel: 'Perioden gir {hele} heile månader og {dager} arbeidsdagar i brotne månader, altså {andel} % av årsløna.',
    lonnPeriodeMangler: 'Fyll inn første og siste dag i perioden under «Møte, planleggingsdagar og løn» for å rekne ut løna.',
    lonnMerknadPeriode: 'Løn, tillegg, variabel løn og overtid er det som blir utbetalt for perioden. Løna og tillegga blir rekna frå datoane: heile månader, og arbeidsdagar ÷ 21,67 i brotne månader. Variabel løn og overtid blir rekna med timane i perioden. Feriepengane blir rekna av dette og kjem i tillegg.',
    lonnMerknad: 'Løn, tillegg, variabel løn og overtid er det som blir utbetalt i året. Feriepengane blir rekna av dette og kjem i tillegg.',
    diagramMerknad: 'Diagrammet viser undervisninga og funksjonane som er lagde inn ({prosent} %), som er meir enn stillinga.',
    ikkeFyltMerknad: 'Delen av stillinga som ikkje er fylt med fag og funksjonar ({prosent} %), er rekna med som anna planfesta tid og tid læraren disponerer sjølv.',
  },
  livsfase: {
    tittel: 'Redusert undervisning',
    velg: 'Livsfasetiltak (SFS 2213 punkt 6)',
    hjelp:
      'Læraren har rett til å få redusert undervisninga med inntil {nyutdannet} % det første yrkesåret etter fullført utdanning, inntil {fra57} % frå det kalenderåret læraren fyller 57 år, og inntil {fra60} % frå det kalenderåret læraren fyller 60 år. Reduksjonen blir rekna som ein del av stillinga, som ein funksjon.',
    valg: {
      ingen: 'Ingen',
      nyutdannet: 'Nyutdanna',
      fra57: '57 år',
      fra60: '60 år',
    },
    oppsummering: '{tiltak}, {prosent} %',
    prosent: 'Reduksjon',
    prosentHjelp: 'Inntil {maks} %. Tomt felt gir {maks} %.',
    planfestet: 'Den frigjorde tida blir lagd i planfesta tid, der ho erstattar undervisning. Planfesta tid blir ikkje utvida.',
    fra57:
      'Avtalen seier berre for nyutdanna og lærarar over 60 år at den frigjorde tida blir lagd i planfesta tid. Appen bruker den same regelen for 57-åringar, utan at det står uttrykkeleg i avtaleteksten.',
    fra60: 'For lærarar som er 60 år og eldre er årsverket {arsverk} timar (punkt 4). Skilnaden er {dager} arbeidsdagar ekstra ferie, så arbeidsåret er {dager} dagar kortare. Planfesta tid er same del av årsverket som for andre lærarar. Feriepengesatsen er også høgare.',
    redusert: 'Redusert undervisning',
    feriepenger60: 'Høgare feriepengesats, fordi læraren er 60 år eller eldre (redusert undervisning).',
  },
  varianter: {
    tittel: 'Lagra variantar',
    hjelp: 'Lagre det du har fylt ut, og samanlikn med ei endring. Gi gjerne varianten eit namn, t.d. «Før endring». Du kan ha {maks} variantar per kalkulator. Dei blir berre lagra på denne eininga, og den eldste blir erstatta når lista er full.',
    variant: 'Variant {nr}',
    naa: 'no {differanse}',
    hent: 'Hent',
    slett: 'Slett {navn}',
    slettet: '«{navn}» er sletta.',
    angre: 'Angre',
    angreSletting: 'slettinga av {navn}',
    navn: 'Namn på variant {nr}',
    endreNavn: 'Gi nytt namn: {navn}',
    lagre: 'Lagre variant',
    sammenlign: 'Samanlikn',
    sammenlignTittel: 'Samanlikn to variantar',
    sammenlignHjelp: 'Vel to variantar, eller éin variant og det som er fylt ut no. Endringa er frå 1 til 2.',
    forste: 'Første',
    andre: 'Andre',
    fyltUtNaa: 'Fylt ut no',
    endring: 'Endring',
    okning: 'auke',
    reduksjon: 'reduksjon',
    likt: 'likt',
    bareEndret: 'Vis berre det som er endra',
    ingenEndring: 'Ingenting er endra.',
    lukkSammenligning: 'Lukk samanlikninga',
    likeValg: 'Vel to ulike.',
    del: 'Del {navn} som lenkje',
    delKort: 'Del som lenkje',
    lenke: 'Lenkje til {navn}',
    kopiert: 'Lenkja er kopiert.',
    delt: 'Lenkja er delt.',
    kopierSelv: 'Kopier lenkja over.',
    delHjelp: 'Lenkja har det som er fylt ut og namnet på varianten. Ho blir ikkje lagra nokon stad, men alle som får ho, kan sjå innhaldet. Bruk ikkje namn på personar.',
    deltTittel: 'Opna frå ei delt lenkje',
    deltTittelNavn: 'Opna frå ei delt lenkje: «{navn}»',
    deltTekst: 'Skjemaet er fylt ut frå lenkja. Det er ikkje lagra på denne eininga.',
    deltLagret: 'Lagra som variant på denne eininga.',
    lagreDelt: 'Lagre som variant',
    deltFeil: 'Lenkja kunne ikkje lesast. Ho kan vere ufullstendig. Skjemaet er ikkje endra.',
    lukkMerknad: 'Lukk merknaden',
  },
  grafikk: {
    belop: 'Stolpe for beløpet: {deler}. I alt {sum}.',
    uke: 'Stolpe for ei gjennomsnittleg veke: {planfestet} timar planfesta tid og {selv} timar læraren disponerer sjølv, i alt {total} timar. Streken viser grensa på {maksUke} timar planfesta tid i ei veke.',
    ukePlanfestet: 'Planfesta: {planfestet} t',
    ukeSelv: 'Disponerer sjølv: {selv} t',
    ukeTekst: 'Snitt per skuleveke: {total} timar i alt, {planfestet} timar planfesta, det vil seie {perDag} timar per dag. Enkeltveker kan ha opptil {maksUke} timar planfesta tid, og enkeltdagar opptil {maksDag} timar.',
    arbeidsplan: 'Stolpe for arbeidsplanen: {deler}. Samla {sum} %. Streken viser stillinga på {grense} %.',
    stilling: 'Stolpe for stillinga: {sum} % i alt ({deler}). Streken viser {grense} %.',
    periode: 'Perioden er {dager} av {skolear} undervisningsdagar ({prosent} % av skuleåret).',
  },
  metode: {
    tittel: 'Slik blir det rekna ut',
    ikkeFunnet: 'Metodeskildringa manglar.',
  },
  trinn: {
    sum_funksjon: { tekst: 'Funksjonar til saman', formel: '{funksjoner}' },
    samlet_beskjeftigelse: { tekst: 'Samla sysselsetjing: undervisning og funksjonar', formel: '{undervisning} + {funksjon}' },
    teknisk_differanse: { tekst: 'Differanse mot stillinga: minus er teknisk undertid, pluss er teknisk overtid', formel: '{beskjeftigelse} − {stilling}' },
    teknisk_timer: { tekst: 'Differansen i årsrammetimar i faget', formel: '{differanse} × {arsramme} ÷ 100' },
    arstimer_fra_okter: { tekst: 'Økter per veke gjort om til årstimar', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    laveste_arsramme: { tekst: 'Elevar frå fleire program eller nivå: lågaste årsramme blir brukt', formel: 'lågaste av {arsrammer}' },
    stjernetillegg: { tekst: 'Fag merkte * med 1–15 elevar: årsramma blir auka', formel: '{arsramme} + {stjernetillegg}' },
    beskjeftigelse: { tekst: 'Sysselsetjing', formel: '{arstimer} ÷ {arsramme} × 100' },
    sum_beskjeftigelse: { tekst: 'Samla sysselsetjing', formel: '{beskjeftigelser}' },
    uker_i_perioden: { tekst: 'Veker i perioden, rekna ut frå dagane', formel: '{dager_periode} ÷ {per_uke}' },
    timer_i_perioden_fra_okter: { tekst: 'Økter per veke gjort om til timar i perioden', formel: '{okter} × {minutter} ÷ 60 × {uker}' },
    periodenokkel: { tekst: 'Periodenøkkel: delen av skuleåret perioden utgjer', formel: '{dager_periode} ÷ {dager_skolear}' },
    perioderamme: { tekst: 'Perioderamme: årsramma for perioden', formel: '{arsramme} × {periodenokkel}' },
    periodebeskjeftigelse: { tekst: 'Sysselsetjing i perioden', formel: '{timer} ÷ {perioderamme} × 100' },
    vikartimer: { tekst: 'Vikartimar gjort om til 60-minutts timar', formel: '{okter} × {minutter} ÷ 60' },
    endring_beskjeftigelse: { tekst: 'Auke i sysselsetjing', formel: '{vikartimer} ÷ {arsramme} × 100' },
    kalkulert_tid: { tekst: 'Kalkulert tid: undervisning med før- og etterarbeid', formel: '{vikartimer} × {konstant} ÷ {arsramme}' },
    timelonn: { tekst: 'Timeløn utan feriepengar', formel: '{arslonn} ÷ {arsverk} × {teller} ÷ {nevner}' },
    lonn: { tekst: 'Løn for vikartimane', formel: '{kalkulert_tid} × {timelonn}' },
    feriepenger: { tekst: 'Feriepengar i tillegg', formel: '{lonn} × {sats} ÷ 100' },
    samlet_lonn: { tekst: 'Samla løn', formel: '{lonn} + {feriepenger}' },
    funksjonsprosent: { tekst: 'Reduksjonen i prosent av full undervisning', formel: '{reduksjon} ÷ {arsramme} × 100' },
    selvdisponert: { tekst: 'Tid læraren disponerer sjølv i full stilling', formel: '{arsverk} − {planfestet}' },
    planfestet_okning: { tekst: 'Sjølvdisponert tid blir redusert like mykje som undervisninga, og planfesta tid aukar tilsvarande', formel: '{selvdisponert} × {funksjonsprosent} ÷ 100' },
    planfestet_ny: { tekst: 'Planfesta arbeidstid', formel: '{planfestet} + {okning}' },
    arbeidsaar_dager: { tekst: 'Arbeidsåret: skuleåret til elevane og 6 dagar', formel: '{skolear} + {tillegg}' },
    ekstra_feriedager_60: { tekst: 'Ekstra feriedagar frå 60 år: årsverket er kortare', formel: '({arsverk} − {arsverk_60}) ÷ {per_dag}' },
    arbeidsaar_dager_60: { tekst: 'Arbeidsåret: skuleåret til elevane og 6 dagar, minus ekstra ferie frå 60 år', formel: '{skolear} + {tillegg} − {ferie}' },
    planfestet_60: { tekst: 'Planfesta tid frå 60 år: same del av det kortare årsverket', formel: '{planfestet} × {arsverk_60} ÷ {arsverk}' },
    arbeidsaar_uker: { tekst: 'Arbeidsåret i veker', formel: '{dager} ÷ {per_uke}' },
    planfestet_maks: { tekst: 'Høgaste planfesta tid utan å utvide arbeidsåret', formel: '{uker} × {maks_uke}' },
    planfestet_per_uke: { tekst: 'Planfesta tid per veke', formel: '{planfestet} ÷ {uker}' },
    planfestet_per_uke_maks: { tekst: 'Planfesta tid per veke (høgaste tillatne)', formel: '{maks} ÷ {uker}' },
    utvidelse_timer: { tekst: 'Timar over grensa', formel: '{planfestet} − {maks}' },
    utvidelse_dager: { tekst: 'Arbeidsåret blir utvida med', formel: '{timer} ÷ {per_dag}' },
    stilling: { tekst: 'Stilling i alt', formel: '{beskjeftigelse} + {funksjonsprosent}' },
    arsverk_stilling: { tekst: 'Årsverket for stillinga', formel: '{arsverk} × {stilling} ÷ 100' },
    planfestet_undervisning: { tekst: 'Planfesta tid for undervisningsdelen', formel: '{planfestet} × {beskjeftigelse} ÷ 100' },
    funksjonstid: { tekst: 'Tid til funksjonar og andre oppgåver (planfesta)', formel: '{arsverk} × {funksjonsprosent} ÷ 100' },
    motetid: { tekst: 'Møtetid i skuleåret', formel: '{moter} × {uker}' },
    annen_planfestet: { tekst: 'Anna planfesta tid', formel: '{planfestet_undervisning} − {undervisning} − {motetid}' },
    selvdisponert_stilling: { tekst: 'Tid læraren disponerer sjølv', formel: '({arsverk} − {planfestet}) × {beskjeftigelse} ÷ 100' },
    motetid_i_funksjon: { tekst: 'Møtetid som ikkje får plass i den planfesta tida for undervisninga, blir lagd i funksjonstida', formel: '{motetid} − ({planfestet_undervisning} − {undervisning})' },
    funksjonstid_etter_moter: { tekst: 'Funksjonstid utover møta', formel: '{funksjonstid} − {motetid_i_funksjon}' },
    arslonn_stilling: { tekst: 'Årsløn i stillinga', formel: '{arslonn} × {stilling} ÷ 100' },
    samlet_med_reduksjon: { tekst: 'Samla sysselsetjing med redusert undervisning', formel: '{undervisning} + {funksjon} + {reduksjon}' },
    lonn_i_alt: { tekst: 'Løn i alt: årsløn, tillegg, variabel løn og overtidsbetaling', formel: '{arslonn} + {tillegg} + {variabel} + {overtid}' },
    ikke_fordelt: { tekst: 'Del av stillinga som ikkje er fylt med fag og funksjonar', formel: '{stilling} − {beskjeftigelse} − {funksjoner}' },
    undervisningsdel: { tekst: 'Undervisningsdelen: undervisning og den delen som ikkje er fylt', formel: '{beskjeftigelse} + {ikke_fordelt}' },
    stilling_alle_funksjoner: { tekst: 'Stilling: undervisning og alle funksjonar', formel: '{beskjeftigelse} + {funksjonsprosent} + {funksjon_uten_utvidelse}' },
    funksjonstid_uten_utvidelse: { tekst: 'Planfesta tid for funksjonar som ikkje utvidar planfesta tid', formel: '{planfestet} × {funksjon_uten_utvidelse} ÷ 100' },
    funksjonstid_i_alt: { tekst: 'Funksjonstid i planfesta tid i alt', formel: '{funksjonstid} + {funksjonstid_uten_utvidelse}' },
    selvdisponert_med_funksjon: {
      tekst: 'Tid læraren disponerer sjølv, også for funksjonar som ikkje utvidar planfesta tid',
      formel: '({arsverk} − {planfestet}) × ({beskjeftigelse} + {funksjon_uten_utvidelse}) ÷ 100',
    },
    planfestet_stilling: { tekst: 'Planfesta tid i stillinga', formel: '{planfestet_undervisning} + {funksjonstid}' },
    arbeidsaar_uker_utvidet: { tekst: 'Det utvida arbeidsåret i veker', formel: '{uker} + {dager} ÷ {per_uke}' },
    variabel_prosent: { tekst: 'Variabel løn: sysselsetjing ut over stillinga, opp til heil stilling', formel: '100 − {stilling}' },
    variabel_prosent_differanse: { tekst: 'Variabel løn: sysselsetjing ut over stillinga', formel: '{beskjeftigelse} − {stilling}' },
    variabel_timer: { tekst: 'Variabel løn i årsrammetimar', formel: '{variabel} × {arsramme} ÷ 100' },
    kalkulert_tid_variabel: { tekst: 'Kalkulert tid: arbeidstimane det blir betalt for', formel: '{timer} × {konstant} ÷ {arsramme}' },
    variabel_lonn: { tekst: 'Variabel løn: kalkulert tid × timeløn, som for vikartimar', formel: '{kalkulert_tid} × {timelonn}' },
    arslonn_periode: { tekst: 'Årsløn for stillinga i perioden', formel: '{arslonn} × {stilling} ÷ 100 × {andel}' },
    tillegg_periode: { tekst: 'Tillegg for perioden', formel: '{tillegg} × {andel}' },
    prosent_arsbasis: { tekst: 'Prosenten i perioden på årsbasis', formel: '{prosent} × {periodenokkel}' },
    overtidsprosent_periode: { tekst: 'Sysselsetjing ut over heil stilling i perioden, på årsbasis', formel: '({beskjeftigelse} − 100) × {periodenokkel}' },
    planleggingstimer: { tekst: 'Timar på planleggingsdagar for ein lærar i heil stilling', formel: '{dager} × {per_dag}' },
    lonnsandel_periode: { tekst: 'Del av årsløna for perioden: heile månader, og arbeidsdagar ÷ 21,67 i brotne månader', formel: '({hele_maneder} + {arbeidsdager} ÷ {per_maned}) ÷ 12' },
    overtidsprosent: { tekst: 'Sysselsetjing utover heil stilling', formel: '{beskjeftigelse} − 100' },
    overtidstimer: { tekst: 'Undervisningstimar i overtid: timane årsramma er auka med', formel: '{overtidsprosent} × {arsramme} ÷ 100' },
    kalkulert_tid_overtid: { tekst: 'Kalkulert tid: arbeidstimane det blir betalt for', formel: '{timer} × {konstant} ÷ {arsramme}' },
    overtidsbetaling: { tekst: 'Overtidsbetaling: timeløn med 50 % tillegg', formel: '{kalkulert_tid} × {timelonn} × (100 + {tillegg}) ÷ 100' },
  },
  storrelser: {
    undervisningsprosent: 'undervisning',
    funksjon: 'funksjon',
    funksjoner: 'funksjonar',
    samlet_beskjeftigelse: 'samla sysselsetjing',
    teknisk_differanse: 'differanse',
    teknisk_timer: 'differanse i årsrammetimar',
    arstimer: 'årstimar',
    arsramme: 'årsramme',
    arsrammer: 'årsrammene',
    arsramme_justert: 'justert årsramme',
    stjernetillegg: 'tillegg',
    elever: 'elevar',
    okter_per_uke: 'økter per veke',
    minutter_per_okt: 'minutt per økt',
    uker: 'veker',
    beskjeftigelse: 'sysselsetjing',
    beskjeftigelser: 'sysselsetjinga i gruppene',
    sum_beskjeftigelse: 'samla sysselsetjing',
    timer_i_perioden: 'timar i perioden',
    dager_i_perioden: 'dagar i perioden',
    dager_i_skolearet: 'dagar i skuleåret',
    periodenokkel: 'periodenøkkel',
    perioderamme: 'perioderamme',
    periodebeskjeftigelse: 'periodesysselsetjing',
    vikartimer: 'vikartimar',
    antall_okter: 'økter',
    endring_beskjeftigelse: 'auke',
    timelonn_konstant: 'faktor frå § 12.4',
    kalkulert_tid: 'kalkulert tid',
    arslonn: 'årsløn',
    arsverk: 'årsverk',
    ferie_teller: 'teljar',
    ferie_nevner: 'nemnar',
    timelonn: 'timeløn',
    lonn: 'løn',
    feriepengesats: 'feriepengesats',
    feriepenger: 'feriepengar',
    samlet_lonn: 'samla løn',
    reduksjon_arsrammetimer: 'reduksjon',
    arsramme_funksjon: 'årsramme ved funksjon',
    funksjonsprosent: 'funksjonsprosent',
    planfestet: 'planfesta tid',
    selvdisponert: 'sjølvdisponert tid',
    planfestet_okning: 'auke',
    planfestet_ny: 'planfesta tid',
    skolear_dager: 'skuledagar',
    arbeidsaar_tillegg: 'ekstra dagar',
    arbeidsaar_dager: 'dagar i arbeidsåret',
    arsverk_60: 'årsverk frå 60 år',
    ekstra_feriedager: 'ekstra feriedagar',
    arbeidsdager_per_uke: 'dagar per veke',
    arbeidsaar_uker: 'veker i arbeidsåret',
    planfestet_maks_uke: 'timar per veke',
    planfestet_maks: 'grense',
    planfestet_per_uke: 'per veke',
    utvidelse_timer: 'timar over grensa',
    timer_per_dag: 'timar per dag',
    utvidelse_dager: 'dagar',
    stilling: 'stilling',
    arsverk_stilling: 'årsverk for stillinga',
    planfestet_undervisning: 'planfesta tid for undervisningsdelen',
    funksjonstid: 'funksjonstid',
    moter_per_uke: 'møtetimar per veke',
    skolear_uker: 'veker i skuleåret',
    motetid: 'møtetid',
    annen_planfestet: 'anna planfesta tid',
    selvdisponert_stilling: 'sjølvdisponert tid',
    motetid_i_funksjon: 'møtetid i funksjonstida',
    funksjonstid_etter_moter: 'funksjonstid utover møta',
    arslonn_stilling: 'årsløn i stillinga',
    funksjon_uten_utvidelse: 'funksjonar utan utviding',
    ikke_fordelt: 'ikkje fylt del av stillinga',
    funksjonstillegg: 'tillegg',
    redusert_undervisning: 'redusert undervisning',
    lonn_i_alt: 'løn i alt',
    undervisningsdel: 'undervisningsdel',
    funksjonstid_uten_utvidelse: 'planfesta tid for funksjonar utan utviding',
    funksjonstid_i_alt: 'funksjonstid i alt',
    planfestet_stilling: 'planfesta tid i stillinga',
    arbeidsaar_uker_utvidet: 'veker i det utvida arbeidsåret',
    variabel_prosent: 'variabel løn',
    variabel_timer: 'årsrammetimar med variabel løn',
    variabel_lonn: 'variabel løn',
    planleggingstimer: 'timar på planleggingsdagar',
    arbeidsdager_per_maned: 'arbeidsdagar per månad',
    hele_maneder: 'heile månader',
    arbeidsdager_brutte: 'arbeidsdagar i brotne månader',
    lonnsandel: 'del av året',
    overtidsprosent: 'prosent over heil stilling',
    overtidstimer: 'undervisningstimar i overtid',
    overtidstillegg: 'overtidstillegg',
    overtidsbetaling: 'overtidsbetaling',
  },
  enheter: {
    prosent: '%',
    timer: 'timar',
    arsrammetimer: 'årsrammetimar',
    timer_per_uke: 'timar per veke',
    minutter: 'minutt',
    uker: 'veker',
    dager: 'dagar',
    okter: 'økter',
    elever: 'elevar',
    kroner: 'kr',
    kroner_per_time: 'kr per time',
  },
};
