// UI-tekstar for modulen Eksamen og klage på nynorsk. Same nøklar som eksamen.nb.ts.

export const eksamenNn = {
  tittel: 'Eksamen og klage',
  innledning: 'Eksamen og prøvene i fag- og yrkesopplæringa som sluttvurdering, klage på karakter og datoane gjennom året, etter opplæringsforskrifta kapittel 9 og 10.',
  delEksamen: 'Eksamen og prøver',
  delKlage: 'Klage',
  delDatoer: 'Datoar',
  ikkeFunnet: 'Fann ikkje vegvisaren.',
  eksamen: {
    tittel: 'Eksamen',
    kort: 'Eksamen',
    beskrivelse: 'Trekk og tal på eksamenar, oppmelding, gjennomføring og sensur, særskild tilrettelegging, og utsett, ny og særskild eksamen.',
    innledning: 'Reglane for eksamen i vidaregåande etter opplæringsforskrifta kapittel 9. Datoane står i kalenderen, og klage står i vegvisaren.',
    antall: 'Eksamenar på kvart trinn',
    gangen: 'Frå oppmelding til karakter',
    heleVeien: 'Gjeld heile vegen',
    host: 'Haust',
    var: 'Vår',
    tilrettelegging: 'Tilrettelegging',
    ikkeBestatt: 'Når eleven ikkje består eller ikkje møter',
    merOpplaering: 'Meir opplæring',
    merOpplaeringTekst: 'Retten til meir opplæring i fag som ikkje er bestått, og fristen for å melde seg.',
    videre: 'Vidare',
    iFylket: 'I {fylke}',
    fagarket: 'Fagarket viser om eksamen i faget er sentralt eller lokalt gitt.',
  },
  provene: {
    tittel: 'Fag- og sveineprøva og dei andre prøvene',
    kort: 'Fag- og sveineprøva',
    beskrivelse: 'Prøvene som sluttvurdering for lærlingar og kandidatar: krav, oppmelding, prøvenemnda, karakterar, tilrettelegging, ny prøve og klage.',
    innledning: 'Fag- og sveineprøva, praksisbrevprøva og kompetanseprøva er sluttvurderinga i fag- og yrkesopplæringa. Vegane fram til prøva for lærlingar og kandidatar står i Opplæringstilbod.',
    prover: 'Prøvene',
    gangen: 'Frå krav til resultat',
    heleVeien: 'Gjeld heile vegen',
    ikkeBestatt: 'Når kandidaten ikkje består eller ikkje møter',
    merOpplaering: 'Meir opplæring på Vg3',
    merOpplaeringTekst: 'Retten til meir opplæring når fag- eller sveineprøva ikkje er bestått.',
    videre: 'Vidare',
    opplaeringskontor: 'Opplæringskontora',
    iOpplaeringstilbud: 'I Opplæringstilbod: kontora i kvart fylke',
    klageTekst: 'Klage på «ikkje bestått» på fag- og sveineprøva og dei andre prøvene.',
    udir: 'Fag- og sveineprøver hos Udir',
  },
  klage: {
    kort: 'Klage på karakter',
    beskrivelse: 'Steg for steg: grunngiving, frist, kva skolen kan gjere og klageinstansen.',
  },
  frister: {
    tittel: 'Kalender for eksamen',
    kort: 'Datoar og fristar',
    beskrivelse: 'Oppmelding, trekk, eksamen, sensur og klage, frå august til juli, for elevar, privatistar og lærlingar.',
    neste: 'Neste dato',
    alle: 'Kalender for eksamen',
  },
};
