// UI-tekster for modulen Eksamen og klage på bokmål. eksamen.nn.ts må ha de samme nøklene.

export const eksamenNb = {
  tittel: 'Eksamen og klage',
  innledning: 'Eksamen og prøvene i fag- og yrkesopplæringen som sluttvurdering, klage på karakter og datoene gjennom året, etter opplæringsforskrifta kapittel 9 og 10.',
  ikkeFunnet: 'Fant ikke veiviseren.',
  eksamen: {
    tittel: 'Eksamen',
    kort: 'Eksamen',
    beskrivelse: 'Trekk og antall eksamener, oppmelding, gjennomføring og sensur, særskilt tilrettelegging, og utsatt, ny og særskilt eksamen.',
    innledning: 'Reglene for eksamen i videregående etter opplæringsforskrifta kapittel 9. Datoene står i kalenderen, og klage står i veiviseren.',
    antall: 'Eksamener på hvert trinn',
    gangen: 'Fra oppmelding til karakter',
    heleVeien: 'Gjelder hele veien',
    host: 'Høst',
    var: 'Vår',
    tilrettelegging: 'Tilrettelegging',
    ikkeBestatt: 'Når eleven ikke består eller ikke møter',
    merOpplaering: 'Mer opplæring',
    merOpplaeringTekst: 'Retten til mer opplæring i fag som ikke er bestått, og fristen for å melde seg.',
    videre: 'Videre',
    iFylket: 'I {fylke}',
    fagarket: 'Fagarket viser om eksamen i faget er sentralt eller lokalt gitt.',
  },
  provene: {
    tittel: 'Fag- og svenneprøven og de andre prøvene',
    kort: 'Fag- og svenneprøven',
    beskrivelse: 'Prøvene som sluttvurdering for lærlinger og kandidater: krav, oppmelding, prøvenemnda, karakterer, tilrettelegging, ny prøve og klage.',
    innledning: 'Fag- og svenneprøven, praksisbrevprøven og kompetanseprøven er sluttvurderingen i fag- og yrkesopplæringen. Veiene fram til prøven for lærlinger og kandidater står i Opplæringstilbud.',
    prover: 'Prøvene',
    gangen: 'Fra krav til resultat',
    heleVeien: 'Gjelder hele veien',
    ikkeBestatt: 'Når kandidaten ikke består eller ikke møter',
    merOpplaering: 'Mer opplæring på Vg3',
    merOpplaeringTekst: 'Retten til mer opplæring når fag- eller svenneprøven ikke er bestått.',
    videre: 'Videre',
    opplaeringskontor: 'Opplæringskontorene',
    iOpplaeringstilbud: 'I Opplæringstilbud: kontorene i hvert fylke',
    klageTekst: 'Klage på «ikke bestått» på fag- og svenneprøven og de andre prøvene.',
    udir: 'Fag- og svenneprøver hos Udir',
  },
  klage: {
    kort: 'Klage på karakter',
    beskrivelse: 'Steg for steg: begrunnelse, frist, hva skolen kan gjøre og klageinstansen.',
  },
  frister: {
    tittel: 'Kalender for eksamen',
    kort: 'Datoer og frister',
    beskrivelse: 'Oppmelding, trekk, eksamen, sensur og klage, fra august til juli, for elever, privatister og lærlinger.',
    neste: 'Neste dato',
    alle: 'Kalender for eksamen',
  },
};
