// UI-tekster for fagmodulen på bokmål. fag.nn.ts må ha de samme nøklene.
// Navnene på kodene i vurderingsordningen (trekkordning_2 osv.) er egne oversettelser av titlene i Grep.

export const fagNb = {
  tittel: 'Fag og læreplaner',
  innledning:
    'Fagkoder og læreplaner i videregående opplæring fra Grep, Utdanningsdirektoratets register. Søk på fagnavn eller fagkode, og filtrer på utdanningsprogram, trinn, vurdering og årstimetall.',
  sok: 'Søk etter fag eller fagkode',
  sokPlassholder: 'For eksempel «norsk vg1» eller «HEA2005»',
  filter: 'Filter',
  filterAktive: 'Filter ({antall})',
  nullstill: 'Nullstill filter',
  alle: 'Alle',
  antall: '{antall} fag',
  ettFag: '1 fag',
  ingenTreff: 'Ingen fag passer søket og filteret.',
  ingenVanlige: 'Ingen av de vanlige fagene passer. Se «Vis også».',
  visFlere: 'Vis flere ({antall} til)',
  lasterFeil: 'Fagene kunne ikke lastes. Prøv igjen.',
  hentet: 'Hentet fra Grep {dato}.',
  arstimerKort: '{timer} årstimer',
  visOgsaa: 'Vis også',
  skjulte: '{antall} skjulte fag passer søket.',
  ingenValgt: 'Velg minst én gruppe fag under «Vis også».',
  ingenIValgte: 'Ingen fag i gruppene du har valgt, passer. Se «Vis også».',
  flereTilbud: '{tilbud} og {antall} til',
  klasse: {
    vanlig: 'Vanlige fag ({antall})',
    variant: 'Varianter for særskilte grupper ({antall})',
    bedrift: 'Opplæring i bedrift ({antall})',
    andre: 'Andre fagkoder ({antall})',
  },
  klasseHjelp: {
    vanlig: 'Fagene i det ordinære tilbudet og yrkesfaglig fordypning. Ta bort for å se bare de andre gruppene.',
    variant: 'For eksempel samisk, tegnspråk, kort botid og morsmål.',
    bedrift: 'Lærefag og fag i bedrift.',
    andre: 'Fag uten timetall eller læreplan, vurderingskoder og individuell opplæringsplan.',
  },
  gruppe: '{navn} ({antall})',
  utenLaereplan: 'Uten læreplan',
  gruppenavn: {
    fellesfag: 'Fellesfag',
    felles_programfag: 'Felles programfag',
    valgfritt_programfag: 'Valgfrie programfag',
    yrkesfaglig_fordypning: 'Yrkesfaglig fordypning',
    individuell_opplaeringsplan: 'Individuell opplæringsplan',
    annet: 'Andre',
  },
  felt: {
    program: 'Utdanningsprogram',
    trinn: 'Trinn',
    type: 'Fagtype',
    vurdering: 'Vurderingsordning',
    eksamensform: 'Eksamensform',
    timer: 'Årstimetall',
  },
  fagtype: {
    fellesfag: 'Fellesfag',
    felles_programfag: 'Felles programfag',
    valgfritt_programfag: 'Valgfritt programfag',
    yrkesfaglig_fordypning: 'Yrkesfaglig fordypning',
    individuell_opplaeringsplan: 'Individuell opplæringsplan',
    annet: 'Annet',
  },
  trinn: {
    Vg1: 'Vg1',
    Vg2: 'Vg2',
    Vg3: 'Vg3',
    Bedrift: 'Opplæring i bedrift',
  },
  side: {
    ikkeFunnet: 'Fant ikke faget.',
    tilbakeTilListen: 'Til fag og læreplaner',
    fagkode: 'Fagkode',
    fagtype: 'Fagtype',
    trinn: 'Trinn',
    arstimer: 'Årstimetall',
    arstimerVerdi: '{timer} timer à 60 minutter',
    arsramme: 'Årsramme',
    arsrammeVerdi: '{t60} timer ({t45} i 45-minutters enheter)',
    arsrammeAvhenger: 'Avhenger av program og trinn.',
    arsrammeVis: 'Se alle {antall}',
    arsrammeProgramVerdi: '{t60} ({t45})',
    arsrammeHjelp: 'Bygger på appens tolkning av vedlegg 1 til SFS 2213.',
    regnUt: 'Regn ut i Arbeidsplan',
    nokkeltall: 'Årstimetall og årsramme',
    merker: 'Fagkode, fagtype og trinn',
    timerEnhet: 'timer à 60 minutter',
    arsrammeEnhet: 'timer à 60 minutter ({t45} à 45)',
    arsrammeVarierer: 'Varierer',
    alleYrkesfaglige: 'Alle yrkesfaglige utdanningsprogram',
    alleStudieforberedende: 'Alle studieforberedende utdanningsprogram',
    omBegrep: 'Om begrepet {begrep}',
    kompetansemaalSeksjon: 'Kompetansemål og læreplan',
    yffOverskrift: 'Om yrkesfaglig fordypning',
    lesMer: 'Les mer i begrepsbanken',
    omProgramomrade: 'Hva er et programområde?',
    arstimerMangler: 'Ikke oppgitt i Grep',
    program: 'Utdanningsprogram',
    programomrader: 'Inngår i tilbud ({antall})',
    vurdering: 'Vurderingsordning',
    vurderingIngress: 'Vurderingsordningen i læreplanen står nedenfor.',
    elev: 'Elever',
    privatist: 'Privatister',
    standpunkt: 'Standpunktkarakter',
    ja: 'Ja',
    nei: 'Nei',
    eksamen: 'Eksamen',
    eksamensordning: 'Eksamensordning',
    eksamensform: 'Eksamensform på vitnemålet',
    uttrykk: 'Vurderingsuttrykk',
    ingenVurdering: 'Grep oppgir ingen vurderingsordning for faget.',
    laereplan: 'Læreplan',
    udirLenke: 'Læreplanen på udir.no',
    ingenLaereplan: 'Faget har ingen gjeldende læreplan (LK20) i Grep.',
    lasterLaereplan: 'Laster læreplanen …',
    laereplanFeil: 'Læreplanen kunne ikke lastes. Sjekk nettforbindelsen og prøv igjen.',
    fastsatt: 'Fastsatt på {spraak}. Teksten fra læreplanen er gjengitt uoversatt.',
    kompetansemaal: 'Kompetansemål',
    underveis: 'Underveisvurdering',
    standpunktvurdering: 'Standpunktvurdering',
    vurderingsordningLaereplan: 'Vurderingsordning i læreplanen',
    ingenMaal: 'Læreplanen har ingen kompetansemål for faget i Grep.',
    erstatter: 'Erstatter',
    utgattDato: 'utgått {dato}',
    utgatt: 'utgått',
    brukesSammen: 'Brukes sammen med',
    nyLaereplan: 'Læreplanen {gammel} er erstattet av {ny}.',
    utgattKode: 'Fagkoden {kode} er utgått.',
    erstattetAv: 'Den er erstattet av:',
  },
  erstattetSok: '{kode} er utgått. Den er erstattet av:',
  spraak: {
    nob: 'bokmål',
    nno: 'nynorsk',
    sme: 'nordsamisk',
    sma: 'sørsamisk',
    smj: 'lulesamisk',
    eng: 'engelsk',
  },
  vurdering: {
    standpunkt: 'Standpunktkarakter',
    trekkordning_1: 'Ingen eksamen',
    trekkordning_2: 'Trekkfag til eksamen',
    trekkordning_3: 'Obligatorisk eksamen',
    trekkordning_saerskilt_eksamen: 'Bare særskilt eksamen',
  },
  eksamensform: {
    eksamensform_1: 'Ingen eksamen',
    eksamensform_2: 'Skriftlig',
    eksamensform_3: 'Muntlig',
    eksamensform_4: 'Praktisk',
    eksamensform_5: 'Muntlig-praktisk',
    eksamensform_6: 'Fagprøve',
    eksamensform_7: 'Svenneprøve',
  },
  eksamensordning: {
    eksamensordning_1: 'Ingen eksamen',
    eksamensordning_3: 'Muntlig-praktisk',
    eksamensordning_4: 'Praktisk',
    eksamensordning_5: 'Skriftlig',
    eksamensordning_6: 'Skriftlig eller muntlig',
    eksamensordning_7: 'Skriftlig eller muntlig-praktisk',
    eksamensordning_8: 'Skriftlig og/eller muntlig',
    eksamensordning_9: 'Skriftlig og eventuelt muntlig',
    eksamensordning_10: 'Hovedmål, eventuelt sidemål og eventuelt muntlig',
    eksamensordning_11: 'Tverrfaglig praktisk',
    eksamensordning_12: 'Tverrfaglig skriftlig',
    eksamensordning_13: 'Muntlig',
    eksamensordning_14: 'Fagprøve',
    eksamensordning_15: 'Fagprøve og skriftlig',
    eksamensordning_17: 'Svenneprøve',
    eksamensordning_18: 'Svenneprøve og skriftlig',
    eksamensordning_19: 'Skriftlig og muntlig',
    eksamensordning_20: 'Skriftlig og muntlig-praktisk',
    eksamensordning_21: 'Hovedmål og sidemål skriftlig, og muntlig',
    eksamensordning_22: 'Skriftlig og tverrfaglig praktisk',
    eksamensordning_23: 'Skriftlig og tverrfaglig skriftlig',
    eksamensordning_25: 'Skriftlig eller praktisk',
    eksamensordning_26: 'Skriftlig og praktisk',
    eksamensordning_27: 'Skriftlig og/eller muntlig-praktisk',
  },
  uttrykk: {
    vurderingsuttrykk_tall: 'Tallkarakter',
    vurderingsuttrykk_tall_eller_fritatt: 'Tallkarakter eller fritatt',
    vurderingsuttrykk_bestaatt_ikke_bestaatt: 'Bestått / ikke bestått',
    vurderingsuttrykk_bestaatt_meget_godt_bestaatt_ikke_bestaatt: 'Bestått meget godt / bestått / ikke bestått',
    vurderingsuttrykk_godkjent_ikke_godkjent: 'Godkjent / ikke godkjent',
    vurderingsuttrykk_deltatt: 'Deltatt',
  },
};
