// UI-tekstar for fagmodulen på nynorsk. Må ha dei same nøklane som fag.nb.ts.
import type { fagNb } from './fag.nb.ts';

type Skjema<T> = { [K in keyof T]: T[K] extends string ? string : Skjema<T[K]> };

export const fagNn: Skjema<typeof fagNb> = {
  tittel: 'Fag og læreplanar',
  innledning:
    'Fagkodar og læreplanar i vidaregåande opplæring frå Grep, registeret til Utdanningsdirektoratet. Søk på fagnamn eller fagkode, og filtrer på utdanningsprogram, trinn, vurdering og årstimetal.',
  sok: 'Søk etter fag eller fagkode',
  sokPlassholder: 'Til dømes «norsk vg1» eller «HEA2005»',
  filter: 'Filter',
  filterAktive: 'Filter ({antall})',
  nullstill: 'Nullstill filteret',
  alle: 'Alle',
  antall: '{antall} fag',
  ettFag: '1 fag',
  ingenTreff: 'Ingen fag passar med søket og filteret.',
  ingenVanlige: 'Ingen av dei vanlege faga passar. Sjå «Vis òg».',
  visFlere: 'Vis fleire ({antall} til)',
  lasterFeil: 'Faga kunne ikkje lastast. Prøv igjen.',
  hentet: 'Henta frå Grep {dato}.',
  arstimerKort: '{timer} årstimar',
  visOgsaa: 'Vis òg',
  skjulte: '{antall} skjulte fag passar søket.',
  ingenValgt: 'Vel minst éi gruppe fag under «Vis òg».',
  ingenIValgte: 'Ingen fag i gruppene du har valt, passar. Sjå «Vis òg».',
  flereTilbud: '{tilbud} og {antall} til',
  klasse: {
    vanlig: 'Vanlege fag ({antall})',
    variant: 'Variantar for særskilde grupper ({antall})',
    bedrift: 'Opplæring i bedrift ({antall})',
    andre: 'Andre fagkodar ({antall})',
  },
  klasseHjelp: {
    vanlig: 'Faga i det ordinære tilbodet og yrkesfagleg fordjuping. Ta bort for å sjå berre dei andre gruppene.',
    variant: 'Til dømes samisk, teiknspråk, kort butid og morsmål.',
    bedrift: 'Lærefag og fag i bedrift.',
    andre: 'Fag utan timetal eller læreplan, vurderingskodar og individuell opplæringsplan.',
  },
  gruppe: '{navn} ({antall})',
  utenLaereplan: 'Utan læreplan',
  gruppenavn: {
    fellesfag: 'Fellesfag',
    felles_programfag: 'Felles programfag',
    valgfritt_programfag: 'Valfrie programfag',
    yrkesfaglig_fordypning: 'Yrkesfagleg fordjuping',
    individuell_opplaeringsplan: 'Individuell opplæringsplan',
    annet: 'Andre',
  },
  felt: {
    program: 'Utdanningsprogram',
    trinn: 'Trinn',
    type: 'Fagtype',
    vurdering: 'Vurderingsordning',
    eksamensform: 'Eksamensform',
    timer: 'Årstimetal',
  },
  fagtype: {
    fellesfag: 'Fellesfag',
    felles_programfag: 'Felles programfag',
    valgfritt_programfag: 'Valfritt programfag',
    yrkesfaglig_fordypning: 'Yrkesfagleg fordjuping',
    individuell_opplaeringsplan: 'Individuell opplæringsplan',
    annet: 'Anna',
  },
  trinn: {
    Vg1: 'Vg1',
    Vg2: 'Vg2',
    Vg3: 'Vg3',
    Vg4: 'Vg4',
    Bedrift: 'Opplæring i bedrift',
  },
  side: {
    ikkeFunnet: 'Fann ikkje faget.',
    tilbakeTilListen: 'Til fag og læreplanar',
    fagkode: 'Fagkode',
    fagtype: 'Fagtype',
    trinn: 'Trinn',
    arstimer: 'Årstimetal',
    arstimerVerdi: '{timer} timar à 60 minutt',
    arsramme: 'Årsramme',
    arsrammeVerdi: '{t60} timar ({t45} i 45-minutts einingar)',
    arsrammeAvhenger: 'Avheng av program og trinn.',
    arsrammeVis: 'Sjå alle {antall}',
    arsrammeProgramVerdi: '{t60} ({t45})',
    regnUt: 'Rekn ut i Arbeidsplan',
    regnUtKort: 'Arbeidsplan',
    nokkeltall: 'Årstimetal og årsramme',
    merker: 'Fagkode, fagtype og trinn',
    timerEnhet: 'timar à 60 minutt',
    arsrammeEnhet: 'timar à 60 minutt ({t45} à 45)',
    arsrammeVarierer: 'Varierer',
    alleYrkesfaglige: 'Alle yrkesfaglege utdanningsprogram',
    alleStudieforberedende: 'Alle studieførebuande utdanningsprogram',
    omBegrep: 'Om omgrepet {begrep}',
    kompetansemaalSeksjon: 'Kompetansemål og læreplan',
    yffOverskrift: 'Om yrkesfagleg fordjuping',
    lesMer: 'Les meir i omgrepsbanken',
    omProgramomrade: 'Kva er eit programområde?',
    arstimerMangler: 'Ikkje oppgitt i Grep',
    program: 'Utdanningsprogram',
    programomrader: 'Inngår i tilbod ({antall})',
    vurdering: 'Vurderingsordning',
    vurderingIngress: 'Vurderingsordninga i læreplanen står nedanfor.',
    elev: 'Elevar',
    privatist: 'Privatistar',
    standpunkt: 'Standpunktkarakter',
    ja: 'Ja',
    nei: 'Nei',
    eksamen: 'Eksamen',
    eksamensordning: 'Eksamensordning',
    eksamensform: 'Eksamensform på vitnemålet',
    uttrykk: 'Vurderingsuttrykk',
    ingenVurdering: 'Grep oppgir inga vurderingsordning for faget.',
    laereplan: 'Læreplan',
    udirLenke: 'Læreplanen på udir.no',
    ingenLaereplan: 'Faget har ingen gjeldande læreplan (LK20) i Grep.',
    lasterLaereplan: 'Lastar læreplanen …',
    laereplanFeil: 'Læreplanen kunne ikkje lastast. Sjekk nettsambandet og prøv igjen.',
    fastsatt: 'Fastsett på {spraak}. Teksten frå læreplanen er gjengitt utan omsetjing.',
    kompetansemaal: 'Kompetansemål',
    underveis: 'Undervegsvurdering',
    standpunktvurdering: 'Standpunktvurdering',
    tilVurdering: 'Undervegs- og sluttvurdering i faget',
    vurderingsordningLaereplan: 'Vurderingsordning i læreplanen',
    ingenMaal: 'Læreplanen har ingen kompetansemål for faget i Grep.',
    erstatter: 'Erstattar',
    utgattDato: 'gått ut {dato}',
    utgatt: 'gått ut',
    ndla: 'På NDLA',
    ndlaHjelp: 'Læringsressursar for faget hos Nasjonal digital læringsarena.',
    brukesSammen: 'Blir brukt saman med',
    nyLaereplan: 'Læreplanen {gammel} er erstatta av {ny}.',
    utgattKode: 'Fagkoden {kode} har gått ut.',
    erstattetAv: 'Han er erstatta av:',
    fravaerOgEksamen: 'Fråvær og eksamen',
    iVurdering: 'I Vurdering',
    fravaersgrense: 'Fråværsgrense',
    fravaersgrenseVerdi: '{timer} timar',
    fravaersgrenseAndel: '{prosent} % av {arstimer}',
    tilFravaer: 'Fråværskalkulatoren for faget',
    eksamenGitt: 'Eksamen',
    gitt: { sentral: 'Sentralt gitt', lokal: 'Lokalt gitt' },
    sensur: { sentral: 'sentral sensur', lokal: 'lokal sensur' },
    fagmerknader: 'Fagmerknader',
    avvikVigo: 'Grep og VIGO er usamde om faget. Appen bruker Grep.',
    avvikTimer: 'Årstimetal i VIGO: {verdi}',
    avvikElev: 'Eksamen for elevar i VIGO: {verdi}',
    avvikPrivatist: 'Eksamen for privatistar i VIGO: {verdi}',
    avvikTom: 'ikkje oppgitt',
  },
  erstattetSok: '{kode} har gått ut. Han er erstatta av:',
  spraak: {
    nob: 'bokmål',
    nno: 'nynorsk',
    sme: 'nordsamisk',
    sma: 'sørsamisk',
    smj: 'lulesamisk',
    eng: 'engelsk',
  },
  vurdering: {
    standpunkt: 'Standpunktkarakter',
    trekkordning_1: 'Ingen eksamen',
    trekkordning_2: 'Trekkfag til eksamen',
    trekkordning_3: 'Obligatorisk eksamen',
    trekkordning_saerskilt_eksamen: 'Berre særskild eksamen',
  },
  eksamensform: {
    eksamensform_1: 'Ingen eksamen',
    eksamensform_2: 'Skriftleg',
    eksamensform_3: 'Munnleg',
    eksamensform_4: 'Praktisk',
    eksamensform_5: 'Munnleg-praktisk',
    eksamensform_6: 'Fagprøve',
    eksamensform_7: 'Sveineprøve',
  },
  eksamensordning: {
    eksamensordning_1: 'Ingen eksamen',
    eksamensordning_3: 'Munnleg-praktisk',
    eksamensordning_4: 'Praktisk',
    eksamensordning_5: 'Skriftleg',
    eksamensordning_6: 'Skriftleg eller munnleg',
    eksamensordning_7: 'Skriftleg eller munnleg-praktisk',
    eksamensordning_8: 'Skriftleg og/eller munnleg',
    eksamensordning_9: 'Skriftleg og eventuelt munnleg',
    eksamensordning_10: 'Hovudmål, eventuelt sidemål og eventuelt munnleg',
    eksamensordning_11: 'Tverrfagleg praktisk',
    eksamensordning_12: 'Tverrfagleg skriftleg',
    eksamensordning_13: 'Munnleg',
    eksamensordning_14: 'Fagprøve',
    eksamensordning_15: 'Fagprøve og skriftleg',
    eksamensordning_17: 'Sveineprøve',
    eksamensordning_18: 'Sveineprøve og skriftleg',
    eksamensordning_19: 'Skriftleg og munnleg',
    eksamensordning_20: 'Skriftleg og munnleg-praktisk',
    eksamensordning_21: 'Hovudmål og sidemål skriftleg, og munnleg',
    eksamensordning_22: 'Skriftleg og tverrfagleg praktisk',
    eksamensordning_23: 'Skriftleg og tverrfagleg skriftleg',
    eksamensordning_25: 'Skriftleg eller praktisk',
    eksamensordning_26: 'Skriftleg og praktisk',
    eksamensordning_27: 'Skriftleg og/eller munnleg-praktisk',
  },
  uttrykk: {
    vurderingsuttrykk_tall: 'Talkarakter',
    vurderingsuttrykk_tall_eller_fritatt: 'Talkarakter eller fritatt',
    vurderingsuttrykk_bestaatt_ikke_bestaatt: 'Bestått / ikkje bestått',
    vurderingsuttrykk_bestaatt_meget_godt_bestaatt_ikke_bestaatt: 'Bestått mykje godt / bestått / ikkje bestått',
    vurderingsuttrykk_godkjent_ikke_godkjent: 'Godkjend / ikkje godkjend',
    vurderingsuttrykk_deltatt: 'Delteke',
  },
};
