// UI-tekstar for fylkessida (fase 6, pakke 4, avgjerd 061) på nynorsk. Same nøklar som fylker.nb.ts.
export const fylkerNn = {
  tittel: 'Fylka',
  innledning: 'Det fylkeskommunen avgjer sjølv, står på sidene til fylket. Vel fylket for å sjå lenkjene, dei lokale forskriftene frå Lovdata, og skulane og opplæringskontora i fylket.',
  fylkeInnledning: 'Det fylkeskommunen avgjer sjølv: lenkjer til sidene til fylket, dei lokale forskriftene frå Lovdata, og skulane og opplæringskontora i fylket.',
  ukjent: 'Fann ikkje fylket. Vel eit fylke i lista.',
  hosFylket: 'Hos fylkeskommunen',
  hosFylketNavn: '{navn}',
  ingenLenker: 'Appen har ingen lenkjer til sidene i dette fylket enno.',
  ikkeBekreftet: 'Nettstaden stengjer for automatisk sjekk, så lenkja kan vere utdatert.',
  lokale: 'Lokale forskrifter',
  ingenLokale: 'Appen har ingen lokale forskrifter for dette fylket enno.',
  skolenesRegler: 'Skulane sine eigne reglar',
  antallSkoler: '{antall} skular',
  skolerOgKontor: 'Skular og opplæringskontor',
  skoler: 'Vidaregåande skular i {fylke}',
  skolerTekst: 'Skulane og tilboda, med nettside.',
  kontor: 'Opplæringskontor godkjende i {fylke}',
  kontorTekst: 'Kontora som er godkjende for lærlingar i fylket.',
  datoer: 'Datoar og klage',
  kalenderInntak: 'Kalender for inntak',
  kalenderInntakTekst: 'Fristane for søknad og inntak.',
  kalenderEksamen: 'Kalender for eksamen',
  kalenderEksamenTekst: 'Eksamensdatoane, også dei fylket har sjølv.',
  klage: 'Klage på karakter',
  klageTekst: 'Kven som behandlar klaga, og fristane.',
  sjekket: 'Lenkjene til sidene til fylka blir sjekka kvar veke.',
  forside: 'Vidaregåande opplæring',
  temaer: {
    forside: 'Vidaregåande opplæring',
    inntak: 'Søknad og inntak',
    'klage-inntak': 'Klage på inntak',
    sprak: 'Særskild språkopplæring',
    tilrettelegging: 'Tilrettelegging og PPT',
    eksamen: 'Eksamen',
    'klage-standpunkt': 'Klage på standpunktkarakter',
    privatist: 'Privatist',
    fagprove: 'Fag- og sveineprøva',
  },
  boks: {
    tittel: '{navn}',
    utenFylke: 'Hos fylkeskommunen',
    altOm: 'Alt om {fylke}',
    byttFylke: 'Byt fylke',
    visHos: 'Vis sida hos',
    velg: 'Vel fylke',
    velgIInnstillinger: 'Vel fylket ditt i innstillingane',
  },
};
