// UI-tekster for fylkessiden (fase 6, pakke 4, avgjørelse 061) på bokmål. fylker.nn.ts må ha de samme nøklene.
export const fylkerNb = {
  tittel: 'Fylkene',
  innledning: 'Det fylkeskommunen bestemmer selv, står på sidene til fylket. Velg fylket for å se lenkene, de lokale forskriftene fra Lovdata og skolene og opplæringskontorene i fylket.',
  fylkeInnledning: 'Det fylkeskommunen bestemmer selv: lenker til fylkets sider, de lokale forskriftene fra Lovdata og skolene og opplæringskontorene i fylket.',
  ukjent: 'Fant ikke fylket. Velg et fylke i listen.',
  hosFylket: 'Hos fylkeskommunen',
  hosFylketNavn: '{navn}',
  ingenLenker: 'Appen har ingen lenker til sidene i dette fylket ennå.',
  ikkeBekreftet: 'Nettstedet stenger for automatisk sjekk, så lenken kan være utdatert.',
  lokale: 'Lokale forskrifter',
  ingenLokale: 'Appen har ingen lokale forskrifter for dette fylket ennå.',
  skolenesReglerAntall: 'Skolenes egne regler ({antall})',
  antallSkoler: '{antall} skoler',
  skolerOgKontor: 'Skoler og opplæringskontor',
  skoler: 'Videregående skoler i {fylke}',
  skolerTekst: 'Skolene og tilbudene, med nettside.',
  kontor: 'Opplæringskontor godkjent i {fylke}',
  kontorTekst: 'Kontorene som er godkjent for lærlinger i fylket.',
  datoer: 'Datoer og klage',
  kalenderInntak: 'Kalender for inntak',
  kalenderInntakTekst: 'Fristene for søknad og inntak.',
  kalenderEksamen: 'Kalender for eksamen',
  kalenderEksamenTekst: 'Eksamensdatoene, også fylkets egne.',
  klage: 'Klage på karakter',
  klageTekst: 'Hvem som behandler klagen, og fristene.',
  sjekket: 'Lenkene til fylkenes sider sjekkes hver uke.',
  forside: 'Videregående opplæring',
  temaer: {
    forside: 'Videregående opplæring',
    inntak: 'Søknad og inntak',
    'klage-inntak': 'Klage på inntak',
    sprak: 'Særskilt språkopplæring',
    tilrettelegging: 'Tilrettelegging og PPT',
    eksamen: 'Eksamen',
    'klage-standpunkt': 'Klage på standpunktkarakter',
    privatist: 'Privatist',
    fagprove: 'Fag- og svenneprøven',
  },
  boks: {
    tittel: '{navn}',
    utenFylke: 'Hos fylkeskommunen',
    altOm: 'Alt om {fylke}',
    byttFylke: 'Bytt fylke',
    visHos: 'Vis siden hos',
    velg: 'Velg fylke',
    velgIInnstillinger: 'Velg fylket ditt i innstillingene',
  },
};
