// UI-tekster for modulen Inntak på bokmål. inntak.nn.ts må ha de samme nøklene.

export const inntakNb = {
  tittel: 'Inntak',
  innledning: 'Rettigheter og søkerkategorier ved inntak til videregående opplæring, etter opplæringslova og opplæringsforskrifta. Hvert steg viser fristene og paragrafene i regelverket.',
  veivisere: 'Veivisere',
  bareNasjonalt: 'Viser de nasjonale reglene. Fylket kan ha lokale regler om inntak.',
  velgFylke: 'Velg fylke',
  lokaleMed: 'Viser også de lokale reglene om inntak i {fylke}.',
  lokaleMangler: 'Viser de nasjonale reglene. Appen har ikke lokale regler om inntak for {fylke} ennå. Se fylkets lokale forskrift om inntak.',
  ikkeFunnet: 'Fant ikke veiviseren.',
  frister: {
    tittel: 'Søknad og frister gjennom året',
    kort: 'Frister',
    beskrivelse: 'Søknadsfrister, svar, ventelister og klage ved inntak til videregående.',
    innledning: 'Fristene ved inntak til videregående opplæring, fra oktober til september. Trykk på en frist for å lese mer.',
    filter: 'Vis fristene for',
    filtre: { alle: 'Alle', ungdom: 'Ungdom', voksne: 'Voksne', fortrinn: 'Fortrinnsrett og individuell behandling' },
    grupper: { ungdom: 'Ungdom', voksne: 'Voksne', fortrinn: 'Fortrinnsrett' },
    aaret: 'Året med ett blikk',
    ingen: 'ingen frister',
    enFrist: '1 frist',
    flereFrister: '{antall} frister',
    naa: 'Nå',
    nasjonal: 'Nasjonal',
    heleAret: 'Hele året',
    neste: 'Neste frist',
    alle: 'Alle fristene gjennom året',
    tomt: 'Ingen frister for dette valget.',
  },
};
