// UI-tekster for modulen Inntak på bokmål. inntak.nn.ts må ha de samme nøklene.

export const inntakNb = {
  tittel: 'Inntak',
  innledning: 'Rettigheter og søkerkategorier ved inntak til videregående opplæring, etter opplæringslova og opplæringsforskrifta. Hvert steg viser fristene og paragrafene i regelverket.',
  veivisere: 'Veivisere',
  bareNasjonalt: 'Viser de nasjonale reglene. Fylket kan ha lokale regler om inntak.',
  velgFylke: 'Velg fylke',
  lokaleMed: 'Viser også de lokale reglene om inntak i {fylke}.',
  lokaleMangler: 'Viser de nasjonale reglene. Appen har ikke lokale regler om inntak for {fylke} ennå. Se fylkets lokale forskrift om inntak.',
  ikkeFunnet: 'Fant ikke veiviseren.',
  frister: {
    tittel: 'Kalender for inntak',
    kort: 'Frister',
    beskrivelse: 'Søknadsfrister, svar, ventelister og klage ved inntak til videregående.',
    innledning: 'Fristene ved inntak til videregående opplæring, fra oktober til september. Trykk på en frist for å lese mer.',
    filter: 'Vis fristene for',
    filtre: { alle: 'Alle', ungdom: 'Ungdom', voksne: 'Voksne', fortrinn: 'Fortrinnsrett og individuell behandling' },
    grupper: { ungdom: 'Ungdom', voksne: 'Voksne', fortrinn: 'Fortrinnsrett' },
    aaret: 'Året med ett blikk',
    ingen: 'ingen frister',
    enFrist: '1 frist',
    flereFrister: '{antall} frister',
    naa: 'Nå',
    nasjonal: 'Nasjonal',
    heleAret: 'Hele året',
    neste: 'Neste frist',
    alle: 'Kalender for inntak',
    tomt: 'Ingen frister for dette valget.',
  },
  poeng: {
    tittel: 'Poengberegning',
    beskrivelse: 'Regn ut karakterpoengene til Vg1, Vg2 og Vg3, med utregningen og reglene.',
    innledning: 'Legg inn karakterene, så regner kalkulatoren ut poengsummen etter opplæringsforskrifta. Tomme felt teller ikke. Karakterene lagres ikke.',
    sokerTil: 'Søker til',
    deler: {
      standpunkt: 'Standpunkt',
      eksamen: 'Eksamen',
      valgfag: 'Valgfag',
      tillegg: 'Tilleggspoeng',
      vg1: 'Karakterer fra Vg1',
      vg2: 'Karakterer fra Vg2',
    },
    fag: {
      norskHovedmal: 'Norsk skriftlig hovedmål',
      norskSidemal: 'Norsk skriftlig sidemål',
      norskMuntlig: 'Norsk muntlig',
      matematikk: 'Matematikk',
      naturfag: 'Naturfag',
      engelsk: 'Engelsk',
      samfunnsfag: 'Samfunnsfag',
      krle: 'KRLE',
      kunstOgHandverk: 'Kunst og håndverk',
      musikk: 'Musikk',
      matOgHelse: 'Mat og helse',
      kroppsoving: 'Kroppsøving',
      fremmedsprak: 'Fremmedspråk, fordypning eller arbeidslivsfag',
    },
    fagKilde: 'Fagene med standpunkt på vitnemålet fra grunnskolen',
    eksamenNr: 'Eksamen {nr}',
    leggTilEksamen: 'Legg til eksamen',
    valgfagNr: 'Valgfag {nr}',
    valgfagErstattet: 'Fag fra videregående i stedet for valgfag',
    vurdering: { tom: '–', IV: 'IV', IM: 'IM', fritak: 'Fritak', deltatt: 'Deltatt' },
    vurderingLang: { IV: 'IV, ikke vurderingsgrunnlag', IM: 'IM, ikke møtt', fritak: 'Fritak', deltatt: 'Deltatt eller bestått' },
    type: { standpunkt: 'Standpunkt', eksamen: 'Eksamen', halvar: 'Halvår' },
    typeEtikett: 'Type karakter {nr}',
    karakterEtikett: 'Karakter {nr}',
    annen: 'Annen karakter',
    annenEtikett: 'Annen karakter {nr}, privatist eller annet løp',
    annenHjelp: 'Privatist eller annet løp. Den beste teller.',
    fjernAnnen: 'Fjern annen karakter {nr}',
    erstattet: 'Samme fag har ny vurdering på Vg2',
    flereRader: 'Flere karakterer',
    tilleggIngen: 'Ingen tilleggspoeng',
    /** Navnet på gruppen i nøkkelen tilleggspoeng_<gruppe>_<nr> i fylkets regelfil. Grupper uten navn her får «Tilleggspoeng». */
    tilleggsgruppe: { mdd: 'Musikk, dans og drama', idrett: 'Idrettsfag' },
    tilleggValg: '{gruppe}: {poeng} poeng',
    tilleggGenerell: 'Tilleggspoeng: {poeng} poeng',
    tilleggHjelp: 'Bare for noen utdanningsprogram på Vg1. Se reglene under.',
    resultat: {
      tittel: 'Poengsum',
      samlet: 'Poengsum med tilleggspoeng',
      sammendrag: 'Gjennomsnitt {snitt} × {faktor}',
      tom: 'Legg inn karakterene for å se poengsummen.',
    },
    steg: {
      karakterer: 'Karakterer som teller',
      karaktererVerdi: '{antall}, sum {sum}',
      null: 'IV eller IM, teller med 0',
      utelatt: 'Ikke med',
      valgfag: 'Valgfag, gjennomsnitt som én karakter',
      beste: 'Fag der den beste av to karakterer er brukt',
      snitt: 'Gjennomsnitt',
      avrunding: 'Avrundet til {desimaler} desimaler',
      poeng: 'Poengsum',
      tillegg: 'Tilleggspoeng',
      samlet: 'Poengsum med tilleggspoeng',
    },
    utelatt: {
      fritak: '{antall} fritak',
      deltatt: '{antall} deltatt eller bestått',
      halvar_erstattet: '{antall} halvår fra Vg1',
      valgfag_erstattet: '{antall} valgfag',
    },
    individuell: {
      Vg1: 'Søkeren mangler karakter i mer enn halvparten av fagene. Da skal søkeren behandles individuelt, ikke etter poeng (opplæringsforskrifta § 4-20).',
      Vg2: 'Søkeren har ingen tallkarakterer. Da skal søkeren behandles individuelt, ikke etter poeng (opplæringsforskrifta § 4-26).',
    },
    lop: {
      tittel: 'Løp',
      vg1: 'Utdanningsprogram på Vg1',
      vg2: 'Programområde på Vg2',
      blankt: 'Blankt ark',
      hjelp: 'Fagene og typen karakter (standpunkt eller halvår) fylles inn fra fag- og timefordelingen og læreplanene. Sjekk mot karakterutskriften, og endre det som ikke stemmer. Programfag legges inn på de tomme radene.',
      program: {
        ST: 'Studiespesialisering', ID: 'Idrettsfag', MD: 'Musikk, dans og drama', KD: 'Kunst, design og arkitektur', ME: 'Medier og kommunikasjon',
        BA: 'Bygg- og anleggsteknikk', EL: 'Elektro og datateknologi', FD: 'Frisør, blomster, interiør og eksponeringsdesign', HS: 'Helse- og oppvekstfag',
        DT: 'Håndverk, design og produktutvikling', IM: 'Informasjonsteknologi og medieproduksjon', NA: 'Naturbruk', RM: 'Restaurant- og matfag',
        SR: 'Salg, service og reiseliv', TP: 'Teknologi- og industrifag',
      },
      fellesfag: {
        norsk: 'Norsk', matematikk: 'Matematikk', naturfag: 'Naturfag', engelsk: 'Engelsk', fremmedsprak: 'Fremmedspråk', samfunnskunnskap: 'Samfunnskunnskap',
        geografi: 'Geografi', historie: 'Historie', kroppsoving: 'Kroppsøving', yff: 'Yrkesfaglig fordypning',
      },
      kilder: 'Hvor fagene og typen kommer fra',
    },
    regler: 'Slik regnes poengene',
    kort: 'Poengberegning til Vg1, Vg2 og Vg3',
    kalkulator: 'Kalkulator',
  },
};
