// UI-tekstar for modulen Inntak på nynorsk. Må ha dei same nøklane som inntak.nb.ts.
import type { inntakNb } from './inntak.nb.ts';

export const inntakNn: typeof inntakNb = {
  tittel: 'Inntak',
  innledning: 'Rettar og søkjarkategoriar ved inntak til vidaregåande opplæring, etter opplæringslova og opplæringsforskrifta. Kvart steg viser fristane og paragrafane i regelverket.',
  veivisere: 'Vegvisarar',
  bareNasjonalt: 'Viser dei nasjonale reglane. Fylket kan ha lokale reglar om inntak.',
  velgFylke: 'Vel fylke',
  lokaleMed: 'Viser også dei lokale reglane om inntak i {fylke}.',
  lokaleMangler: 'Viser dei nasjonale reglane. Appen har ikkje lokale reglar om inntak for {fylke} enno. Sjå den lokale forskrifta om inntak i fylket.',
  ikkeFunnet: 'Fann ikkje vegvisaren.',
  frister: {
    tittel: 'Søknad og fristar gjennom året',
    kort: 'Fristar',
    beskrivelse: 'Søknadsfristar, svar, ventelister og klage ved inntak til vidaregåande.',
    innledning: 'Fristane ved inntak til vidaregåande opplæring, frå oktober til september. Trykk på ein frist for å lese meir.',
    filter: 'Vis fristane for',
    filtre: { alle: 'Alle', ungdom: 'Ungdom', voksne: 'Vaksne', fortrinn: 'Fortrinnsrett og individuell behandling' },
    grupper: { ungdom: 'Ungdom', voksne: 'Vaksne', fortrinn: 'Fortrinnsrett' },
    aaret: 'Året med eitt blikk',
    ingen: 'ingen fristar',
    enFrist: '1 frist',
    flereFrister: '{antall} fristar',
    naa: 'No',
    nasjonal: 'Nasjonal',
    heleAret: 'Heile året',
    neste: 'Neste frist',
    alle: 'Alle fristane gjennom året',
    tomt: 'Ingen fristar for dette valet.',
  },
  poeng: {
    tittel: 'Poengutrekning',
    beskrivelse: 'Rekn ut karakterpoenga til Vg1, Vg2 og Vg3, med utrekninga og reglane.',
    innledning: 'Legg inn karakterane, så reknar kalkulatoren ut poengsummen etter opplæringsforskrifta. Tomme felt tel ikkje. Karakterane blir ikkje lagra.',
    sokerTil: 'Søkjer til',
    deler: {
      standpunkt: 'Standpunkt',
      eksamen: 'Eksamen',
      valgfag: 'Valfag',
      tillegg: 'Tilleggspoeng',
      vg1: 'Karakterar frå Vg1',
      vg2: 'Karakterar frå Vg2',
    },
    fag: {
      norskHovedmal: 'Norsk skriftleg hovudmål',
      norskSidemal: 'Norsk skriftleg sidemål',
      norskMuntlig: 'Norsk munnleg',
      matematikk: 'Matematikk',
      naturfag: 'Naturfag',
      engelsk: 'Engelsk',
      samfunnsfag: 'Samfunnsfag',
      krle: 'KRLE',
      kunstOgHandverk: 'Kunst og handverk',
      musikk: 'Musikk',
      matOgHelse: 'Mat og helse',
      kroppsoving: 'Kroppsøving',
      fremmedsprak: 'Framandspråk, fordjuping eller arbeidslivsfag',
    },
    fagKilde: 'Faga med standpunkt på vitnemålet frå grunnskolen',
    eksamenNr: 'Eksamen {nr}',
    leggTilEksamen: 'Legg til eksamen',
    valgfagNr: 'Valfag {nr}',
    valgfagErstattet: 'Fag frå vidaregåande i staden for valfag',
    vurdering: { tom: '–', IV: 'IV', IM: 'IM', fritak: 'Fritak', deltatt: 'Delteke' },
    vurderingLang: { IV: 'IV, ikkje vurderingsgrunnlag', IM: 'IM, ikkje møtt', fritak: 'Fritak', deltatt: 'Delteke eller bestått' },
    type: { standpunkt: 'Standpunkt', eksamen: 'Eksamen', halvar: 'Halvår' },
    typeEtikett: 'Type karakter {nr}',
    karakterEtikett: 'Karakter {nr}',
    annen: 'Annan karakter',
    annenEtikett: 'Annan karakter {nr}, privatist eller anna løp',
    annenHjelp: 'Privatist eller anna løp. Den beste tel.',
    fjernAnnen: 'Fjern annan karakter {nr}',
    erstattet: 'Same fag har halvår på Vg2',
    flereRader: 'Fleire karakterar',
    tilleggIngen: 'Ingen tilleggspoeng',
    /** Navnet på gruppen i nøkkelen tilleggspoeng_<gruppe>_<nr> i fylkets regelfil. Grupper uten navn her får «Tilleggspoeng». */
    tilleggsgruppe: { mdd: 'Musikk, dans og drama', idrett: 'Idrettsfag' },
    tilleggValg: '{gruppe}: {poeng} poeng',
    tilleggGenerell: 'Tilleggspoeng: {poeng} poeng',
    tilleggHjelp: 'Berre for nokre utdanningsprogram på Vg1. Sjå reglane under.',
    resultat: {
      tittel: 'Poengsum',
      samlet: 'Poengsum med tilleggspoeng',
      sammendrag: 'Gjennomsnitt {snitt} × {faktor}',
      tom: 'Legg inn karakterane for å sjå poengsummen.',
    },
    steg: {
      karakterer: 'Karakterar som tel',
      karaktererVerdi: '{antall}, sum {sum}',
      null: 'IV eller IM, tel med 0',
      utelatt: 'Ikkje med',
      valgfag: 'Valfag, gjennomsnitt som éin karakter',
      beste: 'Fag der den beste av to karakterar er brukt',
      snitt: 'Gjennomsnitt',
      avrunding: 'Avrunda til {desimaler} desimalar',
      poeng: 'Poengsum',
      tillegg: 'Tilleggspoeng',
      samlet: 'Poengsum med tilleggspoeng',
    },
    utelatt: {
      fritak: '{antall} fritak',
      deltatt: '{antall} delteke eller bestått',
      halvar_erstattet: '{antall} halvår frå Vg1',
      valgfag_erstattet: '{antall} valfag',
    },
    individuell: {
      Vg1: 'Søkjaren manglar karakter i meir enn halvparten av faga. Då skal søkjaren behandlast individuelt, ikkje etter poeng (opplæringsforskrifta § 4-20).',
      Vg2: 'Søkjaren har ingen talkarakterar. Då skal søkjaren behandlast individuelt, ikkje etter poeng (opplæringsforskrifta § 4-26).',
    },
    lop: {
      tittel: 'Løp',
      vg1: 'Utdanningsprogram på Vg1',
      vg2: 'Programområde på Vg2',
      blankt: 'Blankt ark',
      hjelp: 'Faga og typen karakter (standpunkt eller halvår) blir fylte inn frå fag- og timefordelinga og læreplanane. Sjekk mot karakterutskrifta, og endre det som ikkje stemmer. Programfag legg du inn på dei tomme radene.',
      program: {
        ST: 'Studiespesialisering', ID: 'Idrettsfag', MD: 'Musikk, dans og drama', KD: 'Kunst, design og arkitektur', ME: 'Medium og kommunikasjon',
        BA: 'Bygg- og anleggsteknikk', EL: 'Elektro og datateknologi', FD: 'Frisør, blomar, interiør og eksponeringsdesign', HS: 'Helse- og oppvekstfag',
        DT: 'Handverk, design og produktutvikling', IM: 'Informasjonsteknologi og medieproduksjon', NA: 'Naturbruk', RM: 'Restaurant- og matfag',
        SR: 'Sal, service og reiseliv', TP: 'Teknologi- og industrifag',
      },
      fellesfag: {
        norsk: 'Norsk', matematikk: 'Matematikk', naturfag: 'Naturfag', engelsk: 'Engelsk', fremmedsprak: 'Framandspråk', samfunnskunnskap: 'Samfunnskunnskap',
        geografi: 'Geografi', historie: 'Historie', kroppsoving: 'Kroppsøving', yff: 'Yrkesfagleg fordjuping',
      },
      kilder: 'Kvar faga og typen kjem frå',
    },
    regler: 'Slik blir poenga rekna ut',
    kort: 'Poengutrekning til Vg1, Vg2 og Vg3',
    kalkulator: 'Kalkulator',
  },
};
