// UI-tekster for kalenderen (fase 6, pakke 5, avgjørelse 066) på bokmål. kalender.nn.ts må ha de samme nøklene.
export const kalenderNb = {
  tittel: 'Kalender',
  innledning: 'Fristene og datoene fra hele appen, med skoleruta i fylket ditt og endringer i regelverket som kommer. Trykk på en dato for å lese mer.',
  visning: { etikett: 'Vis', rullende: 'Neste tolv måneder', rullendeKort: 'Tolv måneder', skolear: 'Skoleåret' },
  skolearEtikett: 'Velg skoleår',
  filter: {
    vis: 'Filter: {valg}',
    alleTemaer: 'alle temaer',
    tema: 'Tema',
    hvem: 'Hvem det gjelder',
    alle: 'Alle',
  },
  temaer: { inntak: 'Inntak', vurdering: 'Vurdering', eksamen: 'Eksamen', skolerute: 'Skolerute', regelverk: 'Regelverk' },
  grupper: { elever: 'Elever', privatister: 'Privatister', laerlinger: 'Lærlinger', voksne: 'Voksne', fortrinnsrett: 'Fortrinnsrett' },
  aaretRullende: 'Året fremover med ett blikk',
  aaretSkolear: 'Skoleåret {aar} med ett blikk',
  ingen: 'ingen datoer',
  enDato: '1 dato',
  flereDatoer: '{antall} datoer',
  ingenDatoer: 'Ingen datoer.',
  idag: 'I dag, {dato}',
  iLopetAv: 'I løpet av {maned}',
  til: 'til {dato}',
  heleAret: 'Gjelder hele året',
  heleAretUnder: 'Fristene her har ingen dato. De regnes fra noe annet, eller gjelder hele tiden.',
  ikkeKjent: 'Datoene for eksamen i {aar} er ikke kjent ennå. Eksamen står med måneden.',
  tomt: 'Ingen datoer for dette valget.',
  lesMer: 'Les mer i appen',
  lasterLenker: 'Henter lenkene …',
  kilde: 'Eksamensdatoene fra Udir og fylkeskommunene hentes hver uke. Udirs dato gjelder når kildene er uenige.',
  hentet: 'Hentet {dato}.',
  eksamensplan: 'Eksamensplanen hos Udir',
  endringerRegjeringen: 'Endringer i lover og regler (regjeringen.no)',
  nyttUdir: 'Nytt til barnehage- og skolestart (Udir)',
  neste: 'Neste datoer',
  nesteSammendrag: '{dato}: {tittel}',
  heleKalenderen: 'Hele kalenderen',
  ingenNeste: 'Ingen datoer de neste tolv månedene.',
  skolerute: {
    merknad: 'Skoleruta for {fylke} er fra fylkets forskrift. Datoene ved den enkelte skolen kan avvike.',
    vertskommune: 'Forskriften sier at skolene som hovedregel følger skoleruta til vertskommunen.',
    ingen: 'Appen har ikke skoleruta for {fylke}. Den står på sidene til fylkeskommunen.',
    fraForskriften: 'Fra skoleruta for {skolear}:',
    sisteForJul: 'Siste skoledag før jul',
    sisteForPaske: 'Siste skoledag før påske',
    forskrift: 'Skoleruta for {skolear}',
    typer: {
      'forste-skoledag': 'Første skoledag',
      'siste-skoledag': 'Siste skoledag',
      hostferie: 'Høstferie',
      juleferie: 'Juleferie',
      vinterferie: 'Vinterferie',
      paskeferie: 'Påskeferie',
      'forste-etter-jul': 'Første skoledag etter jul',
      'forste-etter-paske': 'Første skoledag etter påske',
      elevfri: 'Elevfri dag',
      planlegging: 'Planleggingsdag, fri for elevene',
      helligdag: 'Helligdag',
      annet: 'Skolerute',
    },
  },
  inntak: {
    fraFylket: 'Fra fylkeskommunens side:',
    uke: 'uke {uke}',
    omtrent: 'omtrent',
    felt: {
      fortrinnsinntak: 'Svar på søknad om fortrinnsrett',
      'svarfrist-fortrinn': 'Svarfrist etter fortrinnsinntaket',
      'forste-inntak': 'Første inntak: svar på søknaden',
      'svarfrist-forste': 'Svarfrist etter første inntak',
      'andre-inntak': 'Andre inntak',
      'svarfrist-andre': 'Svarfrist etter andre inntak',
      'tredje-inntak': 'Tredje inntak',
      'svarfrist-tredje': 'Svarfrist etter tredje inntak',
      'skolene-overtar': 'Skolene tar over ventelistene',
    },
  },
  regelverk: {
    tittel: 'Endring i {hva} gjelder',
    og: 'og',
    tekstDato: 'Endringen i {hva} ble vedtatt ved {lov} og gjelder fra {dato}.',
    tekstUtenDato: 'Endringen i {hva} er vedtatt ved {lov}, men gjelder ikke ennå ({naar}).',
    teksten: 'Teksten i Regelverk endres når endringen gjelder.',
    ikkeSatt: 'Dato ikke satt',
    udatert: 'Vedtatt, ikke satt i kraft ennå',
    udatertUnder: 'Endringene får dato når ikrafttredelsen kunngjøres i Norsk Lovtidend.',
    kunngjoring: 'Kunngjøringen av {lov} hos Lovdata',
  },
};
