// UI-tekstar for kalenderen (fase 6, pakke 5, avgjerd 066) på nynorsk. Same nøklar som kalender.nb.ts.
export const kalenderNn = {
  tittel: 'Kalender',
  innledning: 'Fristane og datoane frå heile appen, med skuleruta i fylket ditt og endringar i regelverket som kjem. Trykk på ein dato for å lese meir.',
  visning: { etikett: 'Vis', rullende: 'Neste tolv månader', rullendeKort: 'Tolv månader', skolear: 'Skuleåret' },
  skolearEtikett: 'Vel skuleår',
  filter: {
    vis: 'Filter: {valg}',
    alleTemaer: 'alle tema',
    tema: 'Tema',
    hvem: 'Kven det gjeld',
    alle: 'Alle',
  },
  temaer: { inntak: 'Inntak', vurdering: 'Vurdering', eksamen: 'Eksamen', skolerute: 'Skulerute', regelverk: 'Regelverk' },
  grupper: { elever: 'Elevar', privatister: 'Privatistar', laerlinger: 'Lærlingar', voksne: 'Vaksne', fortrinnsrett: 'Fortrinnsrett' },
  aaretRullende: 'Året framover med eitt blikk',
  aaretSkolear: 'Skuleåret {aar} med eitt blikk',
  ingen: 'ingen datoar',
  enDato: '1 dato',
  flereDatoer: '{antall} datoar',
  ingenDatoer: 'Ingen datoar.',
  idag: 'I dag, {dato}',
  iLopetAv: 'I løpet av {maned}',
  til: 'til {dato}',
  heleAret: 'Gjeld heile året',
  heleAretUnder: 'Fristane her har ingen dato. Dei blir rekna frå noko anna, eller gjeld heile tida.',
  ikkeKjent: 'Datoane for eksamen i {aar} er ikkje kjende enno. Eksamen står med månaden.',
  tomt: 'Ingen datoar for dette valet.',
  lesMer: 'Les meir i appen',
  lasterLenker: 'Hentar lenkjene …',
  kilde: 'Eksamensdatoane frå Udir og fylkeskommunane blir henta kvar veke. Datoen frå Udir gjeld når kjeldene er usamde.',
  hentet: 'Henta {dato}.',
  eksamensplan: 'Eksamensplanen hos Udir',
  endringerRegjeringen: 'Endringar i lover og reglar (regjeringen.no)',
  nyttUdir: 'Nytt til barnehage- og skulestart (Udir)',
  neste: 'Neste datoar',
  nesteSammendrag: '{dato}: {tittel}',
  heleKalenderen: 'Heile kalenderen',
  ingenNeste: 'Ingen datoar dei neste tolv månadene.',
};
