// UI-tekstar for kalenderen (fase 6, pakke 5, avgjerd 066) på nynorsk. Same nøklar som kalender.nb.ts.
export const kalenderNn = {
  tittel: 'Kalender',
  innledning: 'Fristane og datoane frå heile appen. Trykk på ein dato for å lese meir.',
  visning: { etikett: 'Vis', rullende: 'Neste tolv månader', rullendeKort: 'Tolv månader', skolear: 'Skuleåret', skolearAar: 'Skuleåret {aar}' },
  skolearEtikett: 'Vel skuleår',
  filter: {
    tittel: 'Filtrer kalenderen',
    alleTemaer: 'Alle tema',
    alleGrupper: 'Alle grupper',
    tema: 'Tema',
    hvem: 'Kven det gjeld',
    alle: 'Alle',
  },
  temaer: { inntak: 'Inntak', vurdering: 'Vurdering', eksamen: 'Eksamen', skolerute: 'Skulerute', regelverk: 'Regelverk' },
  grupper: { elever: 'Elevar', privatister: 'Privatistar', laerlinger: 'Lærlingar', voksne: 'Vaksne', fortrinnsrett: 'Fortrinnsrett' },
  aaretRullende: 'Året framover med eitt blikk',
  aaretSkolear: 'Skuleåret {aar} med eitt blikk',
  ingen: 'ingen datoar',
  enDato: '1 dato',
  flereDatoer: '{antall} datoar',
  ingenDatoer: 'Ingen datoar.',
  idag: 'I dag, {dato}',
  iLopetAv: 'I løpet av {maned}',
  til: 'til {dato}',
  heleAret: 'Gjeld heile året',
  heleAretUnder: 'Fristane her har ingen dato. Dei blir rekna frå noko anna, eller gjeld heile tida.',
  ikkeKjent: 'Datoane for eksamen i {aar} er ikkje kjende enno. Eksamen står med månaden.',
  tomt: 'Ingen datoar for dette valet.',
  lasterLenker: 'Hentar lenkjene …',
  kilde: 'Eksamensdatoane frå Udir og fylkeskommunane blir henta kvar veke. Datoen frå Udir gjeld når kjeldene er usamde.',
  hentet: 'Henta {dato}.',
  eksamensplan: 'Eksamensplanen hos Udir',
  endringerRegjeringen: 'Endringar i lover og reglar (regjeringen.no)',
  nyttUdir: 'Nytt til barnehage- og skulestart (Udir)',
  neste: 'Neste datoar',
  nesteSammendrag: '{dato}: {tittel}',
  heleKalenderen: 'Heile kalenderen',
  ingenNeste: 'Ingen datoar dei neste tolv månadene.',
  skolerute: {
    merknad: 'Skuleruta er frå forskrifta for {fylke}. Skulen din kan ha andre datoar.',
    vertskommune: 'Forskrifta seier at skulane som hovudregel følgjer skuleruta til vertskommunen.',
    ingen: 'Appen har ikkje skuleruta for {fylke}. Ho står på sidene til fylkeskommunen.',
    fraForskriften: 'Frå skuleruta for {skolear}:',
    sisteForJul: 'Siste skuledag før jul',
    sisteForPaske: 'Siste skuledag før påske',
    forskrift: 'Skuleruta for {skolear}',
    typer: {
      'forste-skoledag': 'Første skuledag',
      'siste-skoledag': 'Siste skuledag',
      hostferie: 'Haustferie',
      juleferie: 'Juleferie',
      vinterferie: 'Vinterferie',
      paskeferie: 'Påskeferie',
      'forste-etter-jul': 'Første skuledag etter jul',
      'forste-etter-paske': 'Første skuledag etter påske',
      elevfri: 'Elevfri dag',
      planlegging: 'Planleggingsdag, fri for elevane',
      helligdag: 'Heilagdag',
      annet: 'Skulerute',
    },
  },
  inntak: {
    fraFylket: 'Frå sida til fylkeskommunen:',
    uke: 'veke {uke}',
    forbehold: { ca: 'ca.', senest: 'seinast', begynnelsen: 'byrjinga av {maned}', midten: 'midten av {maned}', slutten: 'slutten av {maned}' },
    svarfrist: 'Svarfristen er {frist}.',
    aarAntatt: 'Sida seier ikkje kva år datoen gjeld. Appen reknar med at han gjeld inntaket i {aar}.',
    felt: {
      fortrinnsinntak: 'Svar på søknad om fortrinnsrett',
      'svarfrist-fortrinn': 'Svarfrist etter fortrinnsinntaket',
      'forste-inntak': 'Første inntak: svar på søknaden',
      'svarfrist-forste': 'Svarfrist etter første inntak',
      'andre-inntak': 'Andre inntak',
      'svarfrist-andre': 'Svarfrist etter andre inntak',
      'tredje-inntak': 'Tredje inntak',
      'svarfrist-tredje': 'Svarfrist etter tredje inntak',
      'skolene-overtar': 'Skulane tek over ventelistene',
    },
  },
  regelverk: {
    tittel: 'Endring i {hva} gjeld',
    og: 'og',
    tekstDato: 'Endringa i {hva} vart vedteken ved {lov} og gjeld frå {dato}.',
    tekstUtenDato: 'Endringa i {hva} er vedteken ved {lov}, men gjeld ikkje enno ({naar}).',
    teksten: 'Teksten i Regelverk blir endra når endringa gjeld.',
    ikkeSatt: 'Dato ikkje sett',
    udatert: 'Vedteke, ikkje sett i kraft enno',
    udatertUnder: 'Endringane får dato når iverksetjinga blir kunngjord i Norsk Lovtidend.',
    kunngjoring: 'Kunngjeringa av {lov} hos Lovdata',
  },
};
