// UI-tekster for kalenderen (fase 6, pakke 5, avgjørelse 066) på bokmål. kalender.nn.ts må ha de samme nøklene.
export const kalenderNb = {
  tittel: 'Kalender',
  innledning: 'Fristene og datoene fra hele appen, med skoleruta i fylket ditt og endringer i regelverket som kommer. Trykk på en dato for å lese mer.',
  visning: { etikett: 'Vis', rullende: 'Neste tolv måneder', rullendeKort: 'Tolv måneder', skolear: 'Skoleåret' },
  skolearEtikett: 'Velg skoleår',
  filter: {
    vis: 'Filter: {valg}',
    alleTemaer: 'alle temaer',
    tema: 'Tema',
    hvem: 'Hvem det gjelder',
    alle: 'Alle',
  },
  temaer: { inntak: 'Inntak', vurdering: 'Vurdering', eksamen: 'Eksamen', skolerute: 'Skolerute', regelverk: 'Regelverk' },
  grupper: { elever: 'Elever', privatister: 'Privatister', laerlinger: 'Lærlinger', voksne: 'Voksne', fortrinnsrett: 'Fortrinnsrett' },
  aaretRullende: 'Året fremover med ett blikk',
  aaretSkolear: 'Skoleåret {aar} med ett blikk',
  ingen: 'ingen datoer',
  enDato: '1 dato',
  flereDatoer: '{antall} datoer',
  ingenDatoer: 'Ingen datoer.',
  idag: 'I dag, {dato}',
  iLopetAv: 'I løpet av {maned}',
  til: 'til {dato}',
  heleAret: 'Gjelder hele året',
  heleAretUnder: 'Fristene her har ingen dato. De regnes fra noe annet, eller gjelder hele tiden.',
  ikkeKjent: 'Datoene for eksamen i {aar} er ikke kjent ennå. Eksamen står med måneden.',
  tomt: 'Ingen datoer for dette valget.',
  lesMer: 'Les mer i appen',
  lasterLenker: 'Henter lenkene …',
  kilde: 'Eksamensdatoene fra Udir og fylkeskommunene hentes hver uke. Udirs dato gjelder når kildene er uenige.',
  hentet: 'Hentet {dato}.',
  eksamensplan: 'Eksamensplanen hos Udir',
  endringerRegjeringen: 'Endringer i lover og regler (regjeringen.no)',
  nyttUdir: 'Nytt til barnehage- og skolestart (Udir)',
  neste: 'Neste datoer',
  nesteSammendrag: '{dato}: {tittel}',
  heleKalenderen: 'Hele kalenderen',
  ingenNeste: 'Ingen datoer de neste tolv månedene.',
};
