// UI-tekstar for dei lokale reglane til brukaren (fase 9) på nynorsk. Same nøklar som lokaleregler.nb.ts.

export const lokaleReglerNn = {
  legend: 'Lokale reglar',
  forklaring: 'Gjeld det andre reglar hos dykk? Legg inn ein regel i tillegg til dei nasjonale, eller ein verdi som gjeld i staden for den nasjonale. Han gjeld med ein gong for deg og blir berre lagra på denne eininga.',
  velgFylke: 'Vel fylke, og gjerne skule, for å leggje inn lokale reglar.',
  dine: 'Reglane dine',
  ingen: 'Du har ikkje lagt inn nokon lokale reglar.',
  leggInn: 'Legg inn ein lokal regel',
  godkjente: 'Godkjend for {sted}',
  godkjenteTekst: 'Kontrollert av eigar og i appen for alle som har valt {sted}:',
  godkjentMelding: '«{tittel}» er godkjend og står no i appen for alle som har valt {sted}. Kopien din er bytt ut.',
  rad: {
    verdi: '{sted} · {verdi} i staden for {nasjonal}',
    regel: '{sted} · i tillegg, på {tema}',
  },
  status: {
    egen: 'Ikkje meldt inn',
    innmeldt: 'Meldt inn {dato}',
    godkjent: 'Godkjend {dato}',
  },
  merke: {
    egen: 'Din eigen',
    egenVerdi: 'din eigen verdi',
    ikkeKontrollert: 'ikkje kontrollert',
  },
  verdier: {
    planfestet_timer: 'Planfesta arbeidstid per år',
    kontaktlaerer_reduksjon: 'Redusert årsramme for kontaktlærar',
    godtgjoring_kontaktlaerer: 'Godtgjering for kontaktlærar',
    godtgjoring_radgiver: 'Godtgjering for rådgivar',
    skolear_dager: 'Undervisningsdagar i skuleåret',
  },
  tema: {
    skoleregler: 'Skulereglar',
    eksamen: 'Eksamen',
    fravaer: 'Fråversgrensa',
    arbeidstid: 'Arbeidstid',
    inntak: 'Inntak',
  },
  skjema: {
    tittelNy: 'Ny lokal regel',
    tittelEndre: 'Endre lokal regel',
    ingress: 'Regelen gjeld med ein gong for deg, merkt som din eigen og ikkje kontrollert. Han blir berre lagra på denne eininga. Meld han inn, så kan han bli kontrollert og gjelde for alle som har valt {sted}.',
    del: {
      hva: 'Kva gjeld regelen?',
      hvor: 'Kvar gjeld han?',
      regel: 'Regelen',
      dato: 'Dato og dokumentasjon',
    },
    hva: {
      verdi: 'Eit tal i kalkulatorane',
      regel: 'Ein regel på ei side',
      verdiHjelp: 'T.d. planfesta arbeidstid etter ein lokal avtale. Kalkulatorane bruker verdien din i staden for den nasjonale.',
      regelHjelp: 'T.d. reglane skulen har for mobil. Regelen står på sida du vel, i tillegg til dei nasjonale reglane.',
    },
    hvorHjelp: 'Regelen gjeld for deg så lenge du har valt {sted} under «Fylke og skule».',
    verdi: 'Verdi',
    nasjonal: 'Nasjonalt: {verdi} ({kilde})',
    verdiHos: 'Verdien hos dykk',
    tema: 'Sida regelen står på',
    tittel: 'Tittel',
    tekst: 'Regelen med eigne ord',
    tekstHjelp: 'Skriv kort og med eigne ord. Ikkje skriv namn eller andre personopplysningar.',
    gjelderFra: 'Gjeld frå (valfritt)',
    gjelderTil: 'Gjeld til (valfritt)',
    lenke: 'Lenkje til kjelda (valfritt)',
    lenkeHjelp: 'T.d. ordensreglementet til skulen eller ei side hos fylkeskommunen.',
    merknad: 'Om kjelda (valfritt)',
    merknadHjelp: 'T.d. «Lokal avtale om arbeidstid, datert 12.08.2026». Har du eit dokument, legg du det ved e-posten når du melder inn regelen. Det blir ikkje lagra i appen.',
    lagtInn: 'Lagd inn {dato}',
    lagre: 'Lagre',
    lagreMeld: 'Lagre og meld inn',
    slett: 'Slett regelen',
    slettBekreft: 'Vil du slette regelen på denne eininga?',
    lagret: 'Regelen er lagra og gjeld for deg.',
    mangler: 'Fyll inn verdien, eller tittelen og regelen.',
  },
  meld: {
    tittel: 'Meld inn regelen',
    tekst: '«Lagre og meld inn» opnar e-postprogrammet ditt med regelen i fast form. Du ser e-posten før han blir send, og appen sender ingenting sjølv.',
    steg1: 'Eigaren får e-posten og kontrollerer regelen mot kjelda.',
    steg2: 'Godkjend kjem regelen med i neste versjon av appen, for alle som har valt {sted}.',
    steg3: 'Kopien din blir bytt ut med den godkjende.',
    offentlig: 'Det som blir godkjent, blir offentleg. Dokument du legg ved, blir ikkje lagde ut. Ta ikkje med namn eller underskrifter.',
    vis: 'Slik ser e-posten ut',
    emne: 'Lokal regel til {app}: {tittel} ({kode})',
    mal: 'Skriv gjerne nokre ord om regelen her (valfritt):',
    skille: '--- Ikkje endre linjene under ---',
    vedlegg: 'Legg ved dokumentasjon om du har. Ta ikkje med namn eller underskrifter.',
  },
  forhandsvisning: 'Slik blir han',
  endre: 'Endre',
  skisse: {
    tittel: 'Lokale reglar (skisse)',
    ingress: 'Skissa til fase 9 viser korleis dei eigne reglane til brukaren ser ut på sidene og i kalkulatorane, og korleis dei blir skilde frå godkjende reglar. Ho finst berre i testversjonen.',
    paSiden: 'På ei side',
    paSidenTekst: 'Skulereglar, delen «Eigne reglar for skulen» når Slåtthaug vgs er vald.',
    skolensRegler: 'Eigne reglar for skulen',
    iKalkulatoren: 'I ein kalkulator',
    iKalkulatorenTekst: 'Arbeidsplan med planfesta tid frå ein lokal avtale. Utrekninga er opna.',
    resultat: 'Planfesta tid per år',
    stegPlanfestet: 'Planfesta arbeidstid ved skulen',
    stegUke: 'Planfesta tid per veke i arbeidsåret',
    nasjonaltVar: 'Nasjonalt: {verdi}',
    iInnstillinger: 'I Innstillingar',
    iInnstillingerTekst: 'Delen «Lokale reglar» står rett under «Fylke og skule».',
    ordensreglement: 'Ordensreglement for Slåtthaug vidaregåande skule',
    etterGodkjenning: 'Etter godkjenning:',
    apneInnstillinger: 'Opne Innstillingar',
  },
};
