// UI-tekster for brukerens lokale regler (fase 9) på bokmål. lokaleregler.nn.ts må ha de samme nøklene.

export const lokaleReglerNb = {
  legend: 'Lokale regler',
  forklaring: 'Gjelder det andre regler hos dere? Legg inn en regel i tillegg til de nasjonale, eller en verdi som gjelder i stedet for den nasjonale. Den gjelder med en gang for deg og lagres bare på denne enheten.',
  velgFylke: 'Velg fylke, og gjerne skole, for å legge inn lokale regler.',
  dine: 'Dine regler',
  ingen: 'Du har ikke lagt inn noen lokale regler.',
  leggInn: 'Legg inn en lokal regel',
  godkjente: 'Godkjent for stedet du har valgt',
  godkjenteTekst: 'Kontrollert av eier og i appen for alle som har valgt samme fylke eller skole.',
  godkjentMelding: '«{tittel}» er godkjent og står nå i appen for alle som har valgt {sted}. Din kopi er byttet ut.',
  andreSted: 'Gjelder {sted}. Velg {sted} under «Fylke og skole» for å bruke den.',
  lukk: 'Lukk',
  rad: {
    verdi: '{sted} · {verdi} i stedet for {nasjonal}',
    regel: '{sted} · i tillegg, på {tema}',
  },
  status: {
    egen: 'Ikke meldt inn',
    innmeldt: 'Meldt inn {dato}',
    godkjent: 'Godkjent {dato}',
    utlopt: 'Gikk ut {dato}',
  },
  merke: {
    egen: 'Din egen',
    egenVerdi: 'din egen verdi',
    ikkeKontrollert: 'ikke kontrollert',
  },
  verdier: {
    planfestet_timer: 'Planfestet arbeidstid per år',
    kontaktlaerer_reduksjon: 'Kontaktlærer: redusert undervisning',
    godtgjoring_kontaktlaerer: 'Kontaktlærer: godtgjøring',
    godtgjoring_radgiver: 'Rådgiver: godtgjøring',
    skolear_dager: 'Undervisningsdager i skoleåret',
  },
  tema: {
    skoleregler: 'Skoleregler',
    eksamen: 'Eksamen',
    fravaer: 'Fraværsgrensen',
    arbeidstid: 'Arbeidstid',
    inntak: 'Inntak',
  },
  annen: {
    arbeidstid: 'En annen regel om arbeidstid',
    skoleregler: 'En regel om orden og oppførsel',
    fravaer: 'En regel om fravær',
    eksamen: 'En regel om eksamen',
    inntak: 'En regel om inntak',
  },
  lokalfot: {
    tekst: 'Lokal regel for {sted}, kontrollert {dato}.',
    sporsmal: 'Feil eller endret?',
    lenke: 'Endre for deg eller meld inn',
    egen: 'Din egen verdi for {sted}, ikke kontrollert.',
  },
  skjema: {
    tittelNy: 'Ny lokal regel',
    tittelEndre: 'Endre lokal regel',
    ingress: 'Regelen gjelder med en gang for deg, merket som din egen og ikke kontrollert. Den lagres bare på denne enheten. Meld den inn, så kan den bli kontrollert og gjelde for alle som har valgt {sted}.',
    del: {
      tema: 'Hva gjelder endringen?',
      hva: 'Hva vil du endre?',
      hvor: 'Hvor gjelder den?',
      regel: 'Regelen',
      dato: 'Dato og dokumentasjon',
    },
    hva: {
      verdiHjelp: 'Kalkulatorene bruker verdien hos dere i stedet for den nasjonale.',
      regelHjelp: 'Regelen står på siden {side}, i tillegg til de nasjonale reglene.',
    },
    enhet: 'Oppgi i',
    prosent: 'Prosent',
    timer: 'Årsrammetimer',
    somProsent: '= {prosent} av en stilling ({timer} av {ramme} årsrammetimer for funksjoner)',
    somTimer: '= {timer} årsrammetimer',
    nasjonalProsent: 'Nasjonalt: minst {timer} årsrammetimer, altså {prosent} av en stilling ({kilde})',
    endrerGodkjent: 'Du endrer regelen som er godkjent for {sted}. Din versjon gjelder for deg i stedet for den godkjente. Meld den inn hvis den godkjente er feil eller har endret seg.',
    hvorHjelp: 'Regelen gjelder for deg så lenge du har valgt {sted} under «Fylke og skole».',
    verdi: 'Verdi',
    nasjonal: 'Nasjonalt: {verdi} ({kilde})',
    verdiHos: 'Verdien hos dere',
    tema: 'Siden regelen står på',
    tittel: 'Tittel',
    tekst: 'Regelen med egne ord',
    tekstHjelp: 'Skriv kort og med egne ord. Ikke skriv navn eller andre personopplysninger.',
    gjelderFra: 'Gjelder fra (valgfritt)',
    gjelderTil: 'Gjelder til (valgfritt)',
    lenke: 'Lenke til kilden (valgfritt)',
    lenkeHjelp: 'F.eks. skolens ordensreglement eller en side hos fylkeskommunen.',
    merknad: 'Om kilden (valgfritt)',
    merknadHjelp: 'F.eks. «Lokal avtale om arbeidstid, datert 12.08.2026». Har du et dokument, legger du det ved e-posten når du melder inn regelen. Det lagres ikke i appen.',
    lagtInn: 'Lagt inn {dato}',
    lagre: 'Lagre',
    lagreMeld: 'Lagre og meld inn',
    slett: 'Slett regelen',
    slettBekreft: 'Vil du slette regelen på denne enheten?',
    lagret: 'Regelen er lagret og gjelder for deg.',
    mangler: 'Fyll inn verdien, eller tittelen og regelen.',
    ugyldigLenke: 'Lenken må begynne med https://.',
    ugyldigDato: '«Gjelder fra» må være før «Gjelder til».',
    utlopt: 'Regelen har gått ut og brukes ikke lenger. Endre datoene eller slett den.',
    meldPaNytt: 'Lagre og meld inn på nytt',
  },
  meld: {
    tittel: 'Meld inn regelen',
    tekst: '«Lagre og meld inn» åpner e-postprogrammet ditt med regelen i fast form. Du ser e-posten før den sendes, og appen sender ingenting selv.',
    steg1: 'Eier får e-posten og kontrollerer regelen mot kilden.',
    steg2: 'Godkjent kommer regelen i appen for alle som har valgt {sted}, vanligvis samme dag.',
    steg3: 'Din kopi byttes ut med den godkjente.',
    offentlig: 'Det som godkjennes, blir offentlig. Dokumenter du legger ved, legges ikke ut. Ta ikke med navn eller underskrifter.',
    sendtTittel: 'E-posten er laget',
    sendtTekst: 'Den er åpnet i e-postprogrammet ditt, men kan ligge bak nettleseren, f.eks. i Outlook. Send den derfra. Regelen er lagret og gjelder for deg. Har du ikke et e-postprogram, kopierer du e-posten og sender den fra e-posten din i nettleseren.',
    apnePaNytt: 'Åpne e-posten på nytt',
    kopier: 'Kopier e-posten',
    kopiert: 'E-posten er kopiert, med adressen øverst. Lim den inn i en ny e-post.',
    kopiFeil: 'E-posten kunne ikke kopieres. Bruk «Åpne e-posten på nytt».',
    vis: 'Slik ser e-posten ut',
    emne: 'Lokal regel til {app}: {tittel} ({kode})',
    mal: 'Skriv gjerne noen ord om regelen her (valgfritt):',
    skille: '--- Ikke endre linjene under ---',
    vedlegg: 'Legg ved dokumentasjon hvis du har. Ta ikke med navn eller underskrifter.',
  },
  kopi: {
    egen: 'Verdien er din egen for {sted}, ikke kontrollert.',
    godkjent: 'Lokal regel for {sted}, kontrollert {dato}.',
  },
  side: {
    tittel: 'Lokale regler for {sted}',
    leggInn: 'Legg inn en lokal regel',
    leggInnTekst: 'Gjelder det egne regler hos dere?',
    kilde: 'Kilde: {navn}',
    ikkeOffentlig: '{navn} (ikke offentlig)',
  },
  nasjonaltVar: 'Nasjonalt: {verdi}',
  forhandsvisning: 'Slik blir den',
  endre: 'Endre',
};
