// UI-tekster for brukerens lokale regler (fase 9) på bokmål. lokaleregler.nn.ts må ha de samme nøklene.

export const lokaleReglerNb = {
  legend: 'Lokale regler',
  forklaring: 'Gjelder det andre regler hos dere? Legg inn en regel i tillegg til de nasjonale, eller en verdi som gjelder i stedet for den nasjonale. Den gjelder med en gang for deg og lagres bare på denne enheten.',
  velgFylke: 'Velg fylke, og gjerne skole, for å legge inn lokale regler.',
  dine: 'Dine regler',
  ingen: 'Du har ikke lagt inn noen lokale regler.',
  leggInn: 'Legg inn en lokal regel',
  godkjente: 'Godkjent for {sted}',
  godkjenteTekst: 'Kontrollert av eier og i appen for alle som har valgt {sted}:',
  godkjentMelding: '«{tittel}» er godkjent og står nå i appen for alle som har valgt {sted}. Din kopi er byttet ut.',
  rad: {
    verdi: '{sted} · {verdi} i stedet for {nasjonal}',
    regel: '{sted} · i tillegg, på {tema}',
  },
  status: {
    egen: 'Ikke meldt inn',
    innmeldt: 'Meldt inn {dato}',
    godkjent: 'Godkjent {dato}',
  },
  merke: {
    egen: 'Din egen',
    egenVerdi: 'din egen verdi',
    ikkeKontrollert: 'ikke kontrollert',
  },
  verdier: {
    planfestet_timer: 'Planfestet arbeidstid per år',
    kontaktlaerer_reduksjon: 'Redusert årsramme for kontaktlærer',
    godtgjoring_kontaktlaerer: 'Godtgjøring for kontaktlærer',
    godtgjoring_radgiver: 'Godtgjøring for rådgiver',
    skolear_dager: 'Undervisningsdager i skoleåret',
  },
  tema: {
    skoleregler: 'Skoleregler',
    eksamen: 'Eksamen',
    fravaer: 'Fraværsgrensen',
    arbeidstid: 'Arbeidstid',
    inntak: 'Inntak',
  },
  skjema: {
    tittelNy: 'Ny lokal regel',
    tittelEndre: 'Endre lokal regel',
    ingress: 'Regelen gjelder med en gang for deg, merket som din egen og ikke kontrollert. Den lagres bare på denne enheten. Meld den inn, så kan den bli kontrollert og gjelde for alle som har valgt {sted}.',
    del: {
      hva: 'Hva gjelder regelen?',
      hvor: 'Hvor gjelder den?',
      regel: 'Regelen',
      dato: 'Dato og dokumentasjon',
    },
    hva: {
      verdi: 'Et tall i kalkulatorene',
      regel: 'En regel på en side',
      verdiHjelp: 'F.eks. planfestet arbeidstid etter en lokal avtale. Kalkulatorene bruker din verdi i stedet for den nasjonale.',
      regelHjelp: 'F.eks. skolens regler for mobil. Regelen står på siden du velger, i tillegg til de nasjonale reglene.',
    },
    hvorHjelp: 'Regelen gjelder for deg så lenge du har valgt {sted} under «Fylke og skole».',
    verdi: 'Verdi',
    nasjonal: 'Nasjonalt: {verdi} ({kilde})',
    verdiHos: 'Verdien hos dere',
    tema: 'Siden regelen står på',
    tittel: 'Tittel',
    tekst: 'Regelen med egne ord',
    tekstHjelp: 'Skriv kort og med egne ord. Ikke skriv navn eller andre personopplysninger.',
    gjelderFra: 'Gjelder fra (valgfritt)',
    gjelderTil: 'Gjelder til (valgfritt)',
    lenke: 'Lenke til kilden (valgfritt)',
    lenkeHjelp: 'F.eks. skolens ordensreglement eller en side hos fylkeskommunen.',
    merknad: 'Om kilden (valgfritt)',
    merknadHjelp: 'F.eks. «Lokal avtale om arbeidstid, datert 12.08.2026». Har du et dokument, legger du det ved e-posten når du melder inn regelen. Det lagres ikke i appen.',
    lagtInn: 'Lagt inn {dato}',
    lagre: 'Lagre',
    lagreMeld: 'Lagre og meld inn',
    slett: 'Slett regelen',
    slettBekreft: 'Vil du slette regelen på denne enheten?',
    lagret: 'Regelen er lagret og gjelder for deg.',
    mangler: 'Fyll inn verdien, eller tittelen og regelen.',
  },
  meld: {
    tittel: 'Meld inn regelen',
    tekst: '«Lagre og meld inn» åpner e-postprogrammet ditt med regelen i fast form. Du ser e-posten før den sendes, og appen sender ingenting selv.',
    steg1: 'Eier får e-posten og kontrollerer regelen mot kilden.',
    steg2: 'Godkjent kommer regelen med i neste versjon av appen, for alle som har valgt {sted}.',
    steg3: 'Din kopi byttes ut med den godkjente.',
    offentlig: 'Det som godkjennes, blir offentlig. Dokumenter du legger ved, legges ikke ut. Ta ikke med navn eller underskrifter.',
    vis: 'Slik ser e-posten ut',
    emne: 'Lokal regel til {app}: {tittel} ({kode})',
    mal: 'Skriv gjerne noen ord om regelen her (valgfritt):',
    skille: '--- Ikke endre linjene under ---',
    vedlegg: 'Legg ved dokumentasjon hvis du har. Ta ikke med navn eller underskrifter.',
  },
  forhandsvisning: 'Slik blir den',
  endre: 'Endre',
  skisse: {
    tittel: 'Lokale regler (skisse)',
    ingress: 'Skissen til fase 9 viser hvordan brukerens egne regler ser ut på sidene og i kalkulatorene, og hvordan de skilles fra godkjente regler. Den finnes bare i testversjonen.',
    paSiden: 'På en side',
    paSidenTekst: 'Skoleregler, delen «Skolens egne regler» når Slåtthaug vgs er valgt.',
    skolensRegler: 'Skolens egne regler',
    iKalkulatoren: 'I en kalkulator',
    iKalkulatorenTekst: 'Arbeidsplan med planfestet tid fra en lokal avtale. Utregningen er åpnet.',
    resultat: 'Planfestet tid per år',
    stegPlanfestet: 'Planfestet arbeidstid ved skolen',
    stegUke: 'Planfestet tid per uke i arbeidsåret',
    nasjonaltVar: 'Nasjonalt: {verdi}',
    iInnstillinger: 'I Innstillinger',
    iInnstillingerTekst: 'Delen «Lokale regler» står rett under «Fylke og skole».',
    ordensreglement: 'Ordensreglement for Slåtthaug vidaregåande skule',
    etterGodkjenning: 'Etter godkjenning:',
    apneInnstillinger: 'Åpne Innstillinger',
  },
};
