// UI-tekstar for dei lokale reglane til brukaren (fase 9) på nynorsk. Same nøklar som lokaleregler.nb.ts.

export const lokaleReglerNn = {
  legend: 'Lokale reglar',
  forklaring: 'Gjeld det andre reglar hos dykk? Legg inn ein regel i tillegg til dei nasjonale, eller ein verdi som gjeld i staden for den nasjonale. Han gjeld med ein gong for deg og blir berre lagra på denne eininga.',
  velgFylke: 'Vel fylke, og gjerne skule, for å leggje inn lokale reglar.',
  dine: 'Reglane dine',
  ingen: 'Du har ikkje lagt inn nokon lokale reglar.',
  leggInn: 'Legg inn ein lokal regel',
  godkjente: 'Godkjend for staden du har valt',
  godkjenteTekst: 'Kontrollert av eigar og i appen for alle som har valt same fylke eller skule.',
  godkjentMelding: '«{tittel}» er godkjend og står no i appen for alle som har valt {sted}. Kopien din er bytt ut.',
  andreSted: 'Gjeld {sted}. Vel {sted} under «Fylke og skule» for å bruke han.',
  lukk: 'Lukk',
  rad: {
    verdi: '{sted} · {verdi} i staden for {nasjonal}',
    regel: '{sted} · i tillegg, på {tema}',
  },
  status: {
    egen: 'Ikkje meldt inn',
    innmeldt: 'Meldt inn {dato}',
    godkjent: 'Godkjend {dato}',
    utlopt: 'Gjekk ut {dato}',
  },
  merke: {
    egen: 'Din eigen',
    egenVerdi: 'din eigen verdi',
    ikkeKontrollert: 'ikkje kontrollert',
  },
  verdier: {
    planfestet_timer: 'Planfesta arbeidstid per år',
    kontaktlaerer_reduksjon: 'Kontaktlærar: redusert undervisning',
    godtgjoring_kontaktlaerer: 'Kontaktlærar: godtgjering',
    godtgjoring_radgiver: 'Rådgivar: godtgjering',
    skolear_dager: 'Undervisningsdagar i skuleåret',
  },
  tema: {
    skoleregler: 'Skulereglar',
    eksamen: 'Eksamen',
    fravaer: 'Fråversgrensa',
    arbeidstid: 'Arbeidstid',
    inntak: 'Inntak',
  },
  annen: {
    arbeidstid: 'Ein annan regel om arbeidstid',
    skoleregler: 'Ein regel om orden og åtferd',
    fravaer: 'Ein regel om fråvær',
    eksamen: 'Ein regel om eksamen',
    inntak: 'Ein regel om inntak',
  },
  lokalfot: {
    tekst: 'Lokal regel for {sted}, kontrollert {dato}.',
    sporsmal: 'Feil eller endra?',
    lenke: 'Endre for deg eller meld inn',
    egen: 'Din eigen verdi for {sted}, ikkje kontrollert.',
  },
  skjema: {
    tittelNy: 'Ny lokal regel',
    tittelEndre: 'Endre lokal regel',
    ingress: 'Regelen gjeld med ein gong for deg, merkt som din eigen og ikkje kontrollert. Han blir berre lagra på denne eininga. Meld han inn, så kan han bli kontrollert og gjelde for alle som har valt {sted}.',
    del: {
      tema: 'Kva gjeld endringa?',
      hva: 'Kva vil du endre?',
      hvor: 'Kvar gjeld han?',
      regel: 'Regelen',
      dato: 'Dato og dokumentasjon',
    },
    hva: {
      verdiHjelp: 'Kalkulatorane bruker verdien hos dykk i staden for den nasjonale.',
      regelHjelp: 'Regelen står på sida {side}, i tillegg til dei nasjonale reglane.',
    },
    enhet: 'Oppgi i',
    prosent: 'Prosent',
    timer: 'Årsrammetimar',
    somProsent: '= {prosent} av ei stilling ({timer} av {ramme} årsrammetimar for funksjonar)',
    somTimer: '= {timer} årsrammetimar',
    nasjonalProsent: 'Nasjonalt: minst {timer} årsrammetimar, altså {prosent} av ei stilling ({kilde})',
    endrerGodkjent: 'Du endrar regelen som er godkjend for {sted}. Versjonen din gjeld for deg i staden for den godkjende. Meld han inn om den godkjende er feil eller har endra seg.',
    hvorHjelp: 'Regelen gjeld for deg så lenge du har valt {sted} under «Fylke og skule».',
    verdi: 'Verdi',
    nasjonal: 'Nasjonalt: {verdi} ({kilde})',
    verdiHos: 'Verdien hos dykk',
    tema: 'Sida regelen står på',
    tittel: 'Tittel',
    tekst: 'Regelen med eigne ord',
    tekstHjelp: 'Skriv kort og med eigne ord. Ikkje skriv namn eller andre personopplysningar.',
    gjelderFra: 'Gjeld frå (valfritt)',
    gjelderTil: 'Gjeld til (valfritt)',
    lenke: 'Lenkje til kjelda (valfritt)',
    lenkeHjelp: 'T.d. ordensreglementet til skulen eller ei side hos fylkeskommunen.',
    merknad: 'Om kjelda (valfritt)',
    merknadHjelp: 'T.d. «Lokal avtale om arbeidstid, datert 12.08.2026». Har du eit dokument, legg du det ved e-posten når du melder inn regelen. Det blir ikkje lagra i appen.',
    lagtInn: 'Lagd inn {dato}',
    lagre: 'Lagre',
    lagreMeld: 'Lagre og meld inn',
    slett: 'Slett regelen',
    slettBekreft: 'Vil du slette regelen på denne eininga?',
    lagret: 'Regelen er lagra og gjeld for deg.',
    mangler: 'Fyll inn verdien, eller tittelen og regelen.',
    ugyldigLenke: 'Lenkja må byrje med https://.',
    ugyldigDato: '«Gjeld frå» må vere før «Gjeld til».',
    utlopt: 'Regelen har gått ut og blir ikkje brukt lenger. Endre datoane eller slett han.',
    meldPaNytt: 'Lagre og meld inn på nytt',
  },
  meld: {
    tittel: 'Meld inn regelen',
    tekst: '«Lagre og meld inn» opnar e-postprogrammet ditt med regelen i fast form. Du ser e-posten før han blir send, og appen sender ingenting sjølv.',
    steg1: 'Eigaren får e-posten og kontrollerer regelen mot kjelda.',
    steg2: 'Godkjend kjem regelen i appen for alle som har valt {sted}, vanlegvis same dagen.',
    steg3: 'Kopien din blir bytt ut med den godkjende.',
    offentlig: 'Det som blir godkjent, blir offentleg. Dokument du legg ved, blir ikkje lagde ut. Ta ikkje med namn eller underskrifter.',
    sendtTittel: 'E-posten er laga',
    sendtTekst: 'Han er opna i e-postprogrammet ditt, men kan liggje bak nettlesaren, t.d. i Outlook. Send han derifrå. Regelen er lagra og gjeld for deg. Har du ikkje eit e-postprogram, kopierer du e-posten og sender han frå e-posten din i nettlesaren.',
    apnePaNytt: 'Opne e-posten på nytt',
    kopier: 'Kopier e-posten',
    kopiert: 'E-posten er kopiert, med adressa øvst. Lim han inn i ein ny e-post.',
    kopiFeil: 'E-posten kunne ikkje kopierast. Bruk «Opne e-posten på nytt».',
    vis: 'Slik ser e-posten ut',
    emne: 'Lokal regel til {app}: {tittel} ({kode})',
    mal: 'Skriv gjerne nokre ord om regelen her (valfritt):',
    skille: '--- Ikkje endre linjene under ---',
    vedlegg: 'Legg ved dokumentasjon om du har. Ta ikkje med namn eller underskrifter.',
  },
  kopi: {
    egen: 'Verdien er din eigen for {sted}, ikkje kontrollert.',
    godkjent: 'Lokal regel for {sted}, kontrollert {dato}.',
  },
  side: {
    tittel: 'Lokale reglar for {sted}',
    leggInn: 'Legg inn ein lokal regel',
    leggInnTekst: 'Gjeld det eigne reglar hos dykk?',
    kilde: 'Kjelde: {navn}',
    ikkeOffentlig: '{navn} (ikkje offentleg)',
  },
  nasjonaltVar: 'Nasjonalt: {verdi}',
  forhandsvisning: 'Slik blir han',
  endre: 'Endre',
};
