// UI-tekstar for modulen Lov og forskrift på nynorsk. Same nøklar som lov.nb.ts.
import type { lovNb } from './lov.nb.ts';

export const lovNn: typeof lovNb = {
  tittel: 'Lov og forskrift',
  innledning: 'Opplæringslova, opplæringsforskrifta og andre reglar som gjeld vidaregåande opplæring, med søk i heile teksten. Teksten er henta frå Lovdata og blir vist slik han er fastsett.',
  sokAlle: 'Søk i lov og forskrift',
  sok: 'Søk i {navn}',
  antallTreff: '{antall} paragrafar passar med søket.',
  ettTreff: 'Éin paragraf passar med søket.',
  ingenTreff: 'Ingen paragrafar passar med søket.',
  flereTreff: 'Viser dei {antall} første. Skriv fleire ord for å finne færre.',
  lover: 'Lover',
  forskrifter: 'Forskrifter',
  lokale: 'Lokale forskrifter i {fylke}',
  lokaleUtenFylke: 'Lokale forskrifter',
  velgFylke: 'Vel fylke for å sjå lokale forskrifter, til dømes om inntak og skulereglar.',
  velgFylkeLenke: 'Vel fylke',
  ingenLokale: 'Appen har ingen lokale forskrifter for {fylke} enno.',
  gjelderFylke: 'Gjeld berre {fylke}.',
  malform: { nb: 'bokmål', nn: 'nynorsk' },
  fastsatt: 'Fastsett på {malform}',
  kapitler: 'kapittel {liste}',
  heleTeksten: 'heile teksten',
  og: 'og',
  antallParagrafer: '{antall} paragrafar',
  antallKapitler: '{antall} kapittel',
  hentet: 'Teksten er henta frå Lovdata {dato}.',
  sistEndret: 'Siste endring gjeld frå {dato}.',
  lovdata: 'Les på Lovdata',
  lovdataParagraf: 'Les {paragraf} på Lovdata',
  lasterFeil: 'Klarte ikkje å laste teksten.',
  ikkeFunnet: 'Fann ikkje dokumentet.',
  paragrafIkkeFunnet: 'Fann ikkje {paragraf} i utvalet av {navn}. Han kan stå i eit kapittel som ikkje er med.',
  utvalg: 'Utval: {liste}. Kapittel som berre gjeld grunnskolen, er ikkje med.',
  utvalgEnkel: 'Utval: {liste}.',
  heleDokumentet: 'Heile dokumentet er med.',
  endringer: 'Endringar',
  fotnoter: 'Fotnotar',
  fotnote: 'Fotnote {nr}',
  omBegrep: {
    lov: 'Om omgrepet lov',
    forskrift: 'Om omgrepet forskrift',
    paragraf: 'Om paragraf og ledd',
  },
};
