// UI-tekstar for modulen Regelverk (lov, forskrift og avtalar) på nynorsk. Same nøklar som lov.nb.ts.
import type { lovNb } from './lov.nb.ts';

export const lovNn: typeof lovNb = {
  tittel: 'Regelverk',
  innledning: 'Lover, forskrifter og avtalar som gjeld vidaregåande opplæring, med søk i heile teksten. Lov- og forskriftsteksten er henta frå Lovdata og blir vist slik han er fastsett. Avtalane er skrivne med eigne ord, med lenke til avtaleteksten.',
  sokAlle: 'Søk i regelverket',
  sok: 'Søk i {navn}',
  antallTreff: '{antall} treff.',
  ettTreff: 'Eitt treff.',
  ingenTreff: 'Ingen treff.',
  flereTreff: 'Viser dei {antall} første. Skriv fleire ord for å finne færre.',
  lover: 'Lover',
  avtaler: 'Avtalar',
  egneOrd: 'Skrive med eigne ord',
  antallBestemmelser: '{antall} føresegner',
  avtaleMerknad: 'Føresegnene er skrivne med eigne ord og er ikkje avtaleteksten. Avtalen gjeld i KS-området. Les avtaleteksten før du brukar ei føresegn.',
  lesAvtalen: 'Les avtaleteksten hos KS',
  bestemmelseIkkeFunnet: 'Fann ikkje føresegna i {navn}.',
  forskrifter: 'Forskrifter',
  lokale: 'Lokale forskrifter i {fylke}',
  privatskoler: 'Privatskular',
  privatskoleMerke: 'Privatskule',
  privatskoleHjelp: 'Gjeld skular godkjende etter privatskolelova. Slå på «Privatskule» i innstillingane for å sjå dei først og sjå reglane for privatskular i appen.',
  privatskoleSkoleregler: 'Privatskular har eigne skulereglar etter privatskolelova § 5A-7. Dei er ikkje lokale forskrifter og står ikkje i Lovdata. Spør skulen.',
  lokaleUtenFylke: 'Lokale forskrifter',
  velgFylke: 'Vel fylke for å sjå lokale forskrifter, til dømes om inntak og skulereglar.',
  velgFylkeLenke: 'Vel fylke',
  ingenLokale: 'Appen har ingen lokale forskrifter for {fylke} enno.',
  gjelderFylke: 'Gjeld berre {fylke}.',
  malform: { nb: 'bokmål', nn: 'nynorsk' },
  iKraft: 'I kraft {dato}',
  iKraftPeriode: 'Gjeld {fra}–{til}',
  endret: 'endra {dato}',
  iKraftSetning: 'I kraft frå {dato}.',
  skolenDin: 'Skulen din',
  gjelderSkole: 'Gjeld berre skulen.',
  fastsatt: 'Fastsett på {malform}',
  kapitler: 'kapittel {liste}',
  heleTeksten: 'heile teksten',
  og: 'og',
  antallParagrafer: '{antall} paragrafar',
  antallKapitler: '{antall} kapittel',
  hentet: 'Teksten er henta frå Lovdata {dato}.',
  sistEndret: 'Siste endring gjeld frå {dato}.',
  lovdata: 'Les på Lovdata',
  lovdataParagraf: 'Les {paragraf} på Lovdata',
  lasterFeil: 'Klarte ikkje å laste teksten.',
  ikkeFunnet: 'Fann ikkje dokumentet.',
  paragrafIkkeFunnet: 'Fann ikkje {paragraf} i utvalet av {navn}. Han kan stå i eit kapittel som ikkje er med.',
  utvalg: 'Utval: {liste}. Kapittel som berre gjeld grunnskolen, er ikkje med.',
  utvalgEnkel: 'Utval: {liste}.',
  heleDokumentet: 'Heile dokumentet er med.',
  endringer: 'Endringar',
  fotnoter: 'Fotnotar',
  fotnote: 'Fotnote {nr}',
};
