// UI-tekster for modulen Regelverk (lov, forskrift og avtaler) på bokmål. lov.nn.ts må ha de samme nøklene.

export const lovNb = {
  tittel: 'Regelverk',
  innledning: 'Lover, forskrifter og avtaler som gjelder videregående opplæring, med søk i hele teksten. Lov- og forskriftsteksten er hentet fra Lovdata og vises slik den er fastsatt. Avtalene er skrevet med egne ord, med lenke til avtaleteksten.',
  sokAlle: 'Søk i regelverket',
  sok: 'Søk i {navn}',
  antallTreff: '{antall} treff.',
  ettTreff: 'Ett treff.',
  ingenTreff: 'Ingen treff.',
  flereTreff: 'Viser de {antall} første. Skriv flere ord for å finne færre.',
  lover: 'Lover',
  avtaler: 'Avtaler',
  egneOrd: 'Skrevet med egne ord',
  antallBestemmelser: '{antall} bestemmelser',
  avtaleMerknad: 'Bestemmelsene er skrevet med egne ord og er ikke avtaleteksten. Avtalen gjelder i KS-området. Les avtaleteksten før du bruker en bestemmelse.',
  lesAvtalen: 'Les avtaleteksten hos KS',
  bestemmelseIkkeFunnet: 'Fant ikke bestemmelsen i {navn}.',
  forskrifter: 'Forskrifter',
  lokale: 'Lokale forskrifter i {fylke}',
  privatskoler: 'Privatskoler',
  privatskoleMerke: 'Privatskole',
  privatskoleHjelp: 'Gjelder skoler godkjent etter privatskolelova. Slå på «Privatskole» i innstillingene for å se dem først og se reglene for privatskoler i appen.',
  privatskoleSkoleregler: 'Privatskoler har egne skoleregler etter privatskolelova § 5A-7. De er ikke lokale forskrifter og står ikke i Lovdata. Spør skolen.',
  lokaleUtenFylke: 'Lokale forskrifter',
  velgFylke: 'Velg fylke for å se lokale forskrifter, for eksempel om inntak og skoleregler.',
  velgFylkeLenke: 'Velg fylke',
  ingenLokale: 'Appen har ingen lokale forskrifter for {fylke} ennå.',
  gjelderFylke: 'Gjelder bare {fylke}.',
  malform: { nb: 'bokmål', nn: 'nynorsk' },
  iKraft: 'I kraft {dato}',
  iKraftPeriode: 'Gjelder {fra}–{til}',
  endret: 'endret {dato}',
  iKraftSetning: 'I kraft fra {dato}.',
  skolenDin: 'Skolen din',
  gjelderSkole: 'Gjelder bare skolen.',
  fastsatt: 'Fastsatt på {malform}',
  kapitler: 'kapittel {liste}',
  heleTeksten: 'hele teksten',
  og: 'og',
  antallParagrafer: '{antall} paragrafer',
  antallKapitler: '{antall} kapitler',
  hentet: 'Teksten er hentet fra Lovdata {dato}.',
  sistEndret: 'Siste endring gjelder fra {dato}.',
  lovdata: 'Les på Lovdata',
  lovdataParagraf: 'Les {paragraf} på Lovdata',
  lasterFeil: 'Klarte ikke å laste teksten.',
  ikkeFunnet: 'Fant ikke dokumentet.',
  paragrafIkkeFunnet: 'Fant ikke {paragraf} i utvalget av {navn}. Den kan stå i et kapittel som ikke er med.',
  utvalg: 'Utvalg: {liste}. Kapitler som bare gjelder grunnskolen, er ikke med.',
  utvalgEnkel: 'Utvalg: {liste}.',
  heleDokumentet: 'Hele dokumentet er med.',
  endringer: 'Endringer',
  fotnoter: 'Fotnoter',
  fotnote: 'Fotnote {nr}',
};
