// UI-tekster for modulen Lov og forskrift på bokmål. lov.nn.ts må ha de samme nøklene.

export const lovNb = {
  tittel: 'Lov og forskrift',
  innledning: 'Opplæringslova, opplæringsforskrifta og andre regler som gjelder videregående opplæring, med søk i hele teksten. Teksten er hentet fra Lovdata og vises slik den er fastsatt.',
  sokAlle: 'Søk i lov og forskrift',
  sok: 'Søk i {navn}',
  antallTreff: '{antall} paragrafer passer søket.',
  ettTreff: 'Én paragraf passer søket.',
  ingenTreff: 'Ingen paragrafer passer søket.',
  flereTreff: 'Viser de {antall} første. Skriv flere ord for å finne færre.',
  dokumenter: 'Lover og forskrifter',
  lov: 'Lov',
  forskrift: 'Forskrift',
  malform: { nb: 'bokmål', nn: 'nynorsk' },
  fastsatt: 'Fastsatt på {malform}',
  kapitler: 'kapittel {liste}',
  heleTeksten: 'hele teksten',
  og: 'og',
  antallParagrafer: '{antall} paragrafer',
  antallKapitler: '{antall} kapitler',
  hentet: 'Teksten er hentet fra Lovdata {dato}.',
  sistEndret: 'Siste endring gjelder fra {dato}.',
  lovdata: 'Les på Lovdata',
  lovdataParagraf: 'Les {paragraf} på Lovdata',
  lasterFeil: 'Klarte ikke å laste teksten.',
  ikkeFunnet: 'Fant ikke dokumentet.',
  paragrafIkkeFunnet: 'Fant ikke {paragraf} i utvalget av {navn}. Den kan stå i et kapittel som ikke er med.',
  utvalg: 'Utvalg: {liste}. Kapitler som bare gjelder grunnskolen, er ikke med.',
  utvalgEnkel: 'Utvalg: {liste}.',
  heleDokumentet: 'Hele dokumentet er med.',
  endringer: 'Endringer',
  fotnoter: 'Fotnoter',
  fotnote: 'Fotnote {nr}',
  omBegrep: {
    lov: 'Om begrepet lov',
    forskrift: 'Om begrepet forskrift',
    paragraf: 'Om paragraf og ledd',
  },
};
