// UI-tekstar for Nyheiter (fase 7b) på nynorsk. Same nøklar som nyheter.nb.ts.

export const nyheterNn = {
  tittel: 'Nyheiter',
  lovdata: 'Vedteken endring i {hva}',
  sisteNytt: 'Siste nytt',
  innledning: 'Det siste frå styresmaktene, fagpressa og organisasjonane i skulen, valt ut for vidaregåande. Nyheitene blir henta kvar dag, og lenkjene går til kjeldene.',
  laster: 'Lastar nyheitene …',
  feil: 'Klarte ikkje å laste nyheitene.',
  ingen: 'Ingen saker med dette filteret.',
  visEldre: 'Vis eldre saker ({antall})',
  ingenNyere: 'Ingen saker dei siste 30 dagane med dette filteret.',
  ingenNye: 'Ingen nye saker',
  sammendrag: '{dato}: {tittel}',
  hentet: 'Sist oppdatert {tid}.',
  alle: 'Alle nyheitene',
  les: 'Les saka hos {kilde}',
  lukk: 'Skjul ingressen til «{tittel}»',
  skjulIngress: 'Skjul ingressen',
  tilbake: 'Tilbake til nyheitene',
  apnesHos: 'blir opna hos {kilde}',
  iDag: 'I dag',
  iGaar: 'I går',
  antall: '{antall} saker',
  typer: {
    myndighet: 'Styresmakt',
    fagpresse: 'Fagpresse',
    organisasjon: 'Interessepart',
    forskning: 'Forsking',
    media: 'Nyheitsmedium',
  },
  filter: {
    tittel: 'Filter',
    hvem: 'Kven',
    alle: 'Alle',
    myndighet: 'Styresmakter',
    fagpresse: 'Fagpresse',
    organisasjon: 'Organisasjonar',
    forskning: 'Forsking',
    media: 'Medium',
    kilde: 'Kjelde',
    alleKilder: 'Alle kjeldene',
    sammendrag: '{hvem} · {kilde}',
    forside: 'Filtrer på kven eller kjelde …',
    knapp: 'Filtrer',
    forsideEtikett: 'Filtrer nyheitene på kven eller kjelde',
    visAlle: 'Vis alle',
  },
  om: {
    tittel: 'Om nyheitene',
    utvalg: 'Styresmaktene, Statsforvaltaren og media skriv også om barnehage, grunnskule og høgare utdanning. Frå dei står berre saker med ord som handlar om vidaregåande, eller om skule utan å nemne dei andre delane av utdanninga.',
    interesseparter: 'Organisasjonane er interesseparter. Utdanningsnytt er fagpresse, gitt ut av Utdanningsforbundet.',
    fylke: 'Nyheitene frå Statsforvaltaren står når du har valt fylke.',
    velgFylke: 'Vel fylke',
    ingenBilder: 'Appen hentar berre tittel, dato, lenkje og ingress. Trykk på ei sak for å sjå ingressen, og ein gong til for å lese saka hos kjelda.',
  },
  kildene: {
    tittel: 'Kjeldene ({antall})',
    feilet: 'Kunne ikkje hentast sidan {dato}. Sakene frå før står.',
    tom: 'Gav ingen saker sidan {dato}. Sakene frå før står.',
  },
  ks: {
    tittel: 'Nytt frå KS',
    tekst: 'KS er arbeidsgivarpart i SFS 2213. Nyheitene frå KS blir ikkje henta inn i appen.',
    lenke: 'Løn og arbeidsgivar hos KS',
  },
};
