// UI-tekster for Nyheter (fase 7b) på bokmål. nyheter.nn.ts må ha de samme nøklene.

export const nyheterNb = {
  tittel: 'Nyheter',
  lovdata: 'Vedtatt endring i {hva}',
  sisteNytt: 'Siste nytt',
  innledning: 'Det siste fra myndighetene, fylkeskommunene, fagpressen, forskningen og organisasjonene i skolen, valgt ut for videregående. Nyhetene hentes hver dag, og lenkene går til kildene.',
  laster: 'Laster nyhetene …',
  feil: 'Klarte ikke å laste nyhetene.',
  ingen: 'Ingen saker med dette filteret.',
  visEldre: 'Vis eldre saker ({antall})',
  ingenNyere: 'Ingen saker de siste 30 dagene med dette filteret.',
  ingenNye: 'Ingen nye saker',
  sammendrag: '{dato}: {tittel}',
  hentet: 'Sist oppdatert {tid}.',
  alle: 'Alle nyhetene',
  les: 'Les saken hos {kilde}',
  lukk: 'Skjul ingressen til «{tittel}»',
  skjulIngress: 'Skjul ingressen',
  tilbake: 'Tilbake til nyhetene',
  apnesHos: 'åpnes hos {kilde}',
  iDag: 'I dag',
  iGaar: 'I går',
  antall: '{antall} saker',
  typer: {
    myndighet: 'Myndighet',
    fagpresse: 'Fagpresse',
    organisasjon: 'Interessepart',
    forskning: 'Forskning',
    media: 'Nyhetsmedium',
  },
  filter: {
    tittel: 'Filter',
    hvem: 'Hvem',
    alle: 'Alle',
    myndighet: 'Myndigheter',
    fagpresse: 'Fagpresse',
    organisasjon: 'Organisasjoner',
    forskning: 'Forskning',
    media: 'Medier',
    fylke: 'Fylke',
    ingenFylke: 'Ingen (bare nasjonale)',
    alleFylker: 'Alle fylkene',
    mittFylke: '{fylke} (ditt fylke)',
    kilde: 'Kilde',
    alleKilder: 'Alle kildene',
    sammendrag: '{hvem} · {kilde}',
    forside: 'Filtrer på hvem eller kilde …',
    knapp: 'Filtrer',
    forsideEtikett: 'Filtrer nyhetene på hvem eller kilde',
    visAlle: 'Vis alle',
  },
  om: {
    tittel: 'Om nyhetene',
    utvalg: 'Myndighetene, Statsforvalteren, fylkeskommunene og forskningen skriver også om barnehage, grunnskole og høyere utdanning. Fra dem står bare saker med ord som handler om videregående, eller om skole uten å nevne de andre delene av utdanningen.',
    interesseparter: 'Organisasjonene er interesseparter. Utdanningsnytt er fagpresse, utgitt av Utdanningsforbundet.',
    fylke: 'Nyhetene fra Statsforvalteren og fylkeskommunen står for fylket du har valgt. Under «Fylke» kan du se nyhetene fra et annet fylke eller fra alle.',
    velgFylke: 'Velg fylke',
    ingenBilder: 'Appen henter bare tittel, dato, lenke og ingress. Trykk på en sak for å se ingressen, og en gang til for å lese saken hos kilden.',
  },
  kildene: {
    tittel: 'Kildene ({antall})',
    feilet: 'Kunne ikke hentes siden {dato}. Sakene fra før står.',
    tom: 'Ga ingen saker siden {dato}. Sakene fra før står.',
  },
  ks: {
    tittel: 'Nytt fra KS',
    tekst: 'KS er arbeidsgiverpart i SFS 2213. Nyhetene fra KS hentes ikke inn i appen.',
    lenke: 'Lønn og arbeidsgiver hos KS',
  },
};
