// UI-tekster for modulen Opplæringsløp på bokmål. opplaeringslop.nn.ts må ha de samme nøklene.

export const opplaeringslopNb = {
  tittel: 'Opplæringsløp',
  innledning: 'Utdanningsprogrammene, tilbudene på hvert trinn og fagene og timene i hvert tilbud, etter Udirs fag- og timefordeling.',
  skolear: 'Fag og timer for skoleåret {skolear}.',
  lasterFeil: 'Tilbudene kunne ikke lastes. Prøv igjen.',
  ikkeFunnet: 'Fant ikke tilbudet.',
  brodsmuler: 'Plassering',
  oversikt: {
    sok: 'Søk etter tilbud eller kode',
    antallTreff: '{antall} tilbud passer søket.',
    ingenTreff: 'Ingen tilbud passer søket.',
  },
  gruppe: {
    studieforberedende: 'Studieforberedende utdanningsprogram',
    yrkesfaglig: 'Yrkesfaglige utdanningsprogram',
    pabygging: 'Påbygging til generell studiekompetanse',
  },
  program: {
    lopHjelp: 'Hvert tilbud fører videre til tilbudene på neste trinn. Trykk på et tilbud for fag og timer.',
    varianter: 'For særskilte skoler',
    variantHjelp: 'Steinerskoler, Montessoriskoler og tyske skoler har egne programområder i Grep.',
    utenfor: 'Andre programområder i programmet',
    utenforHjelp: 'Grep oppgir ikke hva disse bygger på.',
    visVidere: 'Vis {antall} tilbud på {trinn}',
    skjulVidere: 'Skjul tilbudene på {trinn}',
    visVidereBlandet: 'Vis {antall} tilbud videre',
    skjulVidereBlandet: 'Skjul tilbudene videre',
  },
  sted: {
    skole: 'I skole',
    bedrift: 'I bedrift',
    ukjent: 'Ukjent sted',
  },
  tilbud: {
    timer: '{timer} timer',
    timerHjelp: 'Timer à 60 minutter per år etter rundskrivet Udir-1.',
    sammensetning: 'Slik er timene fordelt',
    kategori: {
      fellesfag: 'Fellesfag',
      felles_programfag: 'Felles programfag',
      fordypning: 'Programfag til fordypning',
      valgfritt: 'Programfag til valg',
      yff: 'Yrkesfaglig fordypning',
      opphenting: 'Yrkesfaglig opphenting',
      vurdering: 'Vurdering',
      alternativ: 'Alternativ for særskilte grupper',
    },
    velgEnKort: 'velg én:',
    velgAntall: 'Velg {antall} fag',
    blantFag: 'blant {antall} fag',
    utvalgFlereTrinnKort: 'Fag over flere trinn',
    utvalgValgKort: 'Fag til valg',
    vurderingskoder: 'Vurderingskoder',
    eksamen: 'Vurdering og eksamen',
    andreFag: 'Andre fag',
    rolleValg: '{kategori}, ett av flere valg',
    tilArbeidsplan: 'Regn ut i Arbeidsplan',
    tilArbeidsplanHjelp: 'Fellesfag og felles programfag med fast fagkode blir lagt inn med årstimene, hvert fag som egen gruppe. Fjern fagene du ikke underviser i, og legg inn fag eleven velger, selv.',
    avvik: {
      fellesfagTimer: 'Rundskrivet har {rundskriv} timer i {linje}. Fagkodene i Grep har {grep} timer.',
      ingenFagkode: 'Grep har ingen fagkode for {linje} i dette tilbudet.',
      ingenProgramfag: 'Grep har ingen felles programfag for dette tilbudet. Timene er fra rundskrivet.',
      programfagTimer: 'Rundskrivet har {rundskriv} timer. Fagene i Grep har til sammen {grep}.',
      ingenFellesfag: 'Grep kobler ingen fellesfag til dette tilbudet. Timene er fra rundskrivet.',
      sum: 'Delene i rundskrivet har til sammen {sum} timer, men rundskrivet oppgir {totalt} i alt.',
    },
    antallFag: '{antall} fag',
    sokFag: 'Søk etter fag',
    ingenFag: 'Ingen fag passer søket.',
    tilpasningerTittel: 'Tilpassede ordninger',
    velgEn: 'velg én av {antall}',
    alternativer: 'Alternativer for særskilte grupper',
    rekkefolge: 'I rekkefølge',
    andreKoder: 'Andre koder',
    lantFra: 'Fagkodene er hentet fra {tilbud}.',
    byggerPaa: 'Bygger på',
    kryssFra: 'Kryssløp fra',
    videre: 'Videre',
    pabygging: 'Påbygging',
    kryssTil: 'Kryssløp til',
    tilpasningTotal: '{timer} timer i alt',
    tilpasningTotalOrdinart: '{timer} timer i alt (ordinært {ordinart})',
    tilpasningHjelp: 'Rundskrivet har egne kolonner for noen elevgrupper. Her står bare fagene der timene er annerledes enn i den ordinære fordelingen.',
    tilpasningNavn: {
      samisk: 'Elever med samisk',
      tegnsprak: 'Elever med tegnspråk',
      medStudiespesialisering: 'Elever som har vg1 studiespesialisering',
      utenFremmedsprak: 'Elever uten fremmedspråk fra grunnskolen',
    },
    tilpasningGruppe: { ikkeMed: 'Fag som ikke er med', kommerTil: 'Fag som kommer til', endret: 'Andre timer' },
    tilpasningFag: '{linje} ({timer} timer)',
    tilpasningEndret: '{linje}: {fra} → {til} timer',
    bedrift: 'Opplæringen skjer i bedrift. Fag- og timefordelingen i rundskrivet gjelder ikke.',
    utenTabell: 'Rundskrivet har ingen tabell for dette programområdet.',
    vilbliOverskrift: 'Vilbli',
    vilbli: 'Skoler og lærebedrifter',
    vilbliFylke: 'Skoler og lærebedrifter i {fylke}',
    vilbliFordeling: 'Fag- og timefordelingen på Vilbli',
    vilbliHjelp: 'Vilbli er fylkeskommunenes tjeneste for søkere. Velg fylke under Innstillinger for å se skolene i fylket.',
    omProgramomrade: 'Om begrepet programområde',
  },
};
