// UI-tekster for modulen Opplæringstilbud (id opplaeringslop) på bokmål. opplaeringslop.nn.ts må ha de samme nøklene.

export const opplaeringslopNb = {
  tittel: 'Opplæringstilbud',
  innledning: 'Opplæringstilbudet i videregående: utdanningsprogrammene og løpene videre, skolene og tilbudene deres, og opplæringskontorene i fylket.',
  skolear: 'Fag og timer for skoleåret {skolear}.',
  lasterFeil: 'Tilbudene kunne ikke lastes. Prøv igjen.',
  ikkeFunnet: 'Fant ikke tilbudet.',
  dinSkole: 'Din skole',
  registre: 'Skoler og opplæringskontorer',
  tilbudVedSkolen: 'Tilbudene ved {skole}',
  visning: {
    etikett: 'Vis tilbud',
    skole: 'Min skole',
    alle: 'Alle',
    viser: 'Viser tilbudene ved {skole}.',
    velgSkole: 'Velg skole under Innstillinger, så ser du tilbudene ved skolen din.',
    velgSkoleLenke: 'Velg skole',
    ukjentSkole: 'utdanning.no viser ikke tilbudene ved {skole}, så alle tilbud vises.',
    ingenIProgram: '{skole} har ingen tilbud i dette utdanningsprogrammet.',
    visAlle: 'Vis alle tilbud',
    antallVedSkolen: '{antall} tilbud ved skolen',
    etVedSkolen: 'Ett tilbud ved skolen',
    vedSkolenDin: '{antall} ved skolen din',
    vedSkolenLenger: 'ved skolen din lenger ut i løpet',
    programmerTittel: 'Utdanningsprogram ved skolen',
  },
  skoler: {
    tittel: 'Skoler og tilbud',
    innledning: 'Skolene i videregående og programområdene de tilbyr, etter utdanning.no.',
    tilbudSok: 'Finn skolene som har et tilbud',
    tilbudPlassholder: 'For eksempel «Vg2 realfag»',
    tilbudIngen: 'Ingen skoler har et tilbud som passer søket.',
    sok: 'Søk etter skole eller sted',
    fylke: 'Fylke',
    alleFylker: 'Alle fylker',
    program: 'Utdanningsprogram',
    alleProgram: 'Alle utdanningsprogram',
    tilbud: 'Har {tilbud}',
    fjernTilbud: 'Fjern',
    antall: '{antall} skoler',
    en: 'Én skole',
    ingen: 'Ingen skoler passer.',
    privat: 'Privat',
    antallTilbud: '{antall} tilbud',
    nettside: 'Nettsiden til skolen',
    nettsideKort: 'Nettsiden',
    skolereglerKort: 'Skolens regler',
    fagfordelingKort: 'Fag- og timefordeling',
    tilbudVedSkolen: 'Opplæringstilbud ved skolen ({antall})',
    visFlere: 'Vis flere skoler',
    hentet: 'Etter utdanning.no, hentet {dato}. Skolen du har valgt under Innstillinger, er koblet med skolenummeret i VIGO.',
    utenTilbud: 'utdanning.no viser ingen tilbud ved skolen.',
    alleVedSkolen: 'Vis alle tilbudene ved skolen ({antall})',
    bareLopet: 'Vis bare løpet for {tilbud}',
    bareProgram: 'Vis bare {program}',
    heleLandet: 'Søk i hele landet ({antall})',
  },
  kontor: {
    tittel: 'Opplæringskontorer',
    innledning: 'Opplæringskontorene som er godkjent i fylket, etter registeret til Udir for fag- og yrkesopplæring (NOR).',
    sok: 'Søk etter kontor eller kommune',
    hjelp: 'NOR sier ikke hvilke lærefag kontorene har. Navnet sier ofte hvilken bransje kontoret er for, og siden om kontoret på utdanning.no har mer, blant annet medlemsbedriftene.',
    utdanning: 'Kontoret på utdanning.no',
    heleLandet: 'Søk i hele landet ({antall})',
    iFylket: '{antall} i {fylke}',
    antall: '{antall} opplæringskontorer',
    ingen: 'Ingen opplæringskontorer passer.',
    visFlere: 'Vis flere kontorer',
    godkjentFylker: 'Godkjent i {antall} fylker',
    godkjentFylke: 'Godkjent i {fylke}',
    laerlinger: '{antall} lærlinger',
    nettside: 'Nettsiden til kontoret',
    hentet: 'Etter NOR (Udir), hentet {dato}.',
  },
  fagbrev: {
    tittel: 'Lærlinger og kandidater',
    innledning: 'Lærling, lærekandidat, praksisbrevkandidat, praksiskandidat og kandidat for fagbrev på jobb: hva hver vei består av, hvem som melder opp, fellesfagene, og hvordan man bytter underveis. Veiene ender i fag- og svennebrev, praksisbrev eller kompetansebevis. Prøven står i Vurdering.',
    inngang: '{antall} veier',
    inngangTekst: 'Lærling, lærekandidat, praksisbrevkandidat og praksiskandidat: veiene og bytte underveis.',
    faner: 'Velg visning',
    fane: { veiene: 'Veiene', sammenlign: 'Sammenlign', bytte: 'Bytte vei' },
    maal: 'Målet',
    maalValg: { fagbrev: 'Fag- eller svennebrev', fagbrevKort: 'Fagbrev', praksisbrev: 'Praksisbrev', kompetansebevis: 'Kompetansebevis' },
    utenFellesfag: 'Bare veier uten krav om fellesfag',
    antallVeier: '{antall} veier',
    del: { skole: 'Skole', bedrift: 'Kontrakt i bedrift', praksis: 'Praksis i arbeidslivet', prove: 'Prøven' },
    stegene: 'Stegene',
    kontrakt: 'Kontrakt',
    prove: 'Prøven',
    melderOpp: 'Melder opp',
    fellesfag: 'Fellesfag',
    dokumentasjon: 'Dokumentasjon',
    voksne: 'Voksne (kapittel 18)',
    kilde: 'Kilde',
    lesMer: 'Mer om {rolle}',
    lesMerTekst: 'Kommer fra og veien videre',
    velgA: 'Første vei',
    velgB: 'Andre vei',
    fellesfagListe: 'Fellesfagene i alle veiene',
    fellesfagListeTekst: 'Hvilke veier som krever bestått fellesfag, og hvilke som ikke gjør det.',
    fellesfagKrav: { ja: 'Må være bestått', nei: 'Trengs ikke', plan: 'Står i planen for kandidaten' },
    hvorErDu: 'Hvor er du nå?',
    veieneVidere: 'Veiene videre fra {fra}',
    vilkar: 'Vilkår',
    kommerFra: 'Kommer fra',
    veienVidere: 'Veien videre',
    iVurdering: 'I Vurdering',
    proveTekst: 'Krav, oppmelding, prøvenemnda, karakterer, ny prøve og klage.',
    iOpplaeringstilbud: 'I Opplæringstilbud',
    veieneHit: 'Veiene hit',
    veieneHitTekst: '{antall} veier i Opplæringstilbud, fra lærling til praksiskandidat.',
    proveFor: { fagbrev: 'Til fag- eller svenneprøven', praksisbrev: 'Til praksisbrevprøven', kompetansebevis: 'Til kompetanseprøven' },
    omVeien: 'Om veien',
    mockup: 'Mockup til eier: innholdet er et utkast og er ikke kontrollert.',
  },
  lop: {
    tittel: 'Opplæringsløp',
    innledning: 'Utdanningsprogrammene, tilbudene på hvert trinn og fagene og timene i hvert tilbud, etter Udirs fag- og timefordeling. Velg et program for å se løpet fra Vg1 til Vg3 og lærefag.',
  },
  inngang: {
    program: '{antall} utdanningsprogram',
    programSkole: '{antall} utdanningsprogram ved {skole}',
    programTekst: 'Løpet fra Vg1 til Vg3 og lærefag, med fag og timer i hvert tilbud.',
    skoler: '{antall} skoler',
    skolerFylke: '{antall} skoler i {fylke}',
    skolerTekst: 'Finn skolene som har et tilbud, og tilbudene ved hver skole.',
    kontorTekst: 'Med nettside og lenke til kontoret på utdanning.no.',
  },
  oversikt: {
    sok: 'Søk etter tilbud, kode eller skole',
    antallTreffBegge: '{tilbud} tilbud og {skoler} skoler passer søket.',
    antallTreff: '{antall} tilbud passer søket.',
    ingenTreff: 'Ingen tilbud eller skoler passer søket.',
    program: 'Utdanningsprogram og løp',
    skoler: 'Skoler ({antall})',
    alleSkoler: 'Se alle {antall} skolene i oppslaget',
  },
  gruppe: {
    studieforberedende: 'Studieforberedende utdanningsprogram',
    yrkesfaglig: 'Yrkesfaglige utdanningsprogram',
    pabygging: 'Påbygging til generell studiekompetanse',
  },
  program: {
    lopHjelp: 'Hvert tilbud fører videre til tilbudene på neste trinn. Trykk på et tilbud for fag og timer.',
    varianter: 'For særskilte skoler',
    variantHjelp: 'Steinerskoler, Montessoriskoler og tyske skoler har egne programområder i Grep.',
    utenfor: 'Andre programområder i programmet',
    utenforHjelp: 'Grep oppgir ikke hva disse bygger på.',
    visVidere: 'Vis {antall} tilbud på {trinn}',
    skjulVidere: 'Skjul tilbudene på {trinn}',
    visVidereBlandet: 'Vis {antall} tilbud videre',
    skjulVidereBlandet: 'Skjul tilbudene videre',
  },
  sted: {
    skole: 'I skole',
    bedrift: 'I bedrift',
    ukjent: 'Ukjent sted',
  },
  tilbud: {
    timer: '{timer} timer',
    timerHjelp: 'Timer à 60 minutter per år etter rundskrivet Udir-1.',
    sammensetning: 'Slik er timene fordelt',
    kategori: {
      fellesfag: 'Fellesfag',
      felles_programfag: 'Felles programfag',
      fordypning: 'Programfag til fordypning',
      valgfritt: 'Programfag til valg',
      yff: 'Yrkesfaglig fordypning',
      opphenting: 'Yrkesfaglig opphenting',
      vurdering: 'Vurdering',
      alternativ: 'Alternativ for særskilte grupper',
    },
    erstatning: '{fag} er programfag på {timer} timer. Velger eleven ett av dem i stedet for {fellesfag}, må eleven ta et ekstra programfag i tillegg (Udir-1, punkt 3.3.1.4).',
    iStedet: 'Eleven kan i stedet velge det studieforberedende tilbudet, {fag}. Det har {timer} timer i stedet for {linjetimer} (Udir-1, punkt 3.5).',
    eller: 'eller',
    velgEnKort: 'velg én:',
    velgAntall: 'Velg {antall} fag',
    blantFag: 'blant {antall} fag',
    utvalgFlereTrinnKort: 'Fag over flere trinn',
    utvalgValgKort: 'Fag til valg',
    vurderingskoder: 'Vurderingskoder',
    eksamen: 'Vurdering og eksamen',
    andreFag: 'Andre fag',
    rolleValg: '{kategori}, ett av flere valg',
    tilArbeidsplan: 'Regn ut i Arbeidsplan',
    tilArbeidsplanHjelp: 'Fellesfag og felles programfag blir lagt inn med årstimene, hvert fag som egen gruppe. Der eleven velger mellom fag (f.eks. 1P eller 1T, et fremmedspråk, eller dekk eller maskin), blir det første lagt inn. Fjern fagene du ikke underviser i, bytt fag der det trengs, og legg inn programfag til fordypning og valg selv.',
    avvik: {
      fellesfagTimer: 'Rundskrivet har {rundskriv} timer i {linje}. Fagkodene i Grep har {grep} timer.',
      ingenFagkode: 'Grep har ingen fagkode for {linje} i dette tilbudet.',
      ingenProgramfag: 'Grep har ingen felles programfag for dette tilbudet. Timene er fra rundskrivet.',
      programfagTimer: 'Rundskrivet har {rundskriv} timer. Fagene i Grep har til sammen {grep}.',
      ingenFellesfag: 'Grep kobler ingen fellesfag til dette tilbudet. Timene er fra rundskrivet.',
      sum: 'Delene i rundskrivet har til sammen {sum} timer, men rundskrivet oppgir {totalt} i alt.',
    },
    antallFag: '{antall} fag',
    sokFag: 'Søk etter fag',
    ingenFag: 'Ingen fag passer søket.',
    tilpasningerTittel: 'Tilpassede ordninger',
    velgEn: 'velg én av {antall}',
    alternativer: 'Alternativer for særskilte grupper',
    rekkefolge: 'I rekkefølge',
    andreKoder: 'Andre koder',
    lantFra: 'Fagkodene er hentet fra {tilbud}.',
    byggerPaa: 'Bygger på',
    kryssFra: 'Kryssløp fra',
    videre: 'Videre',
    pabygging: 'Påbygging',
    kryssTil: 'Kryssløp til',
    opphenting: {
      tittel: 'Vg2 på yrkesfag',
      tekst: 'Etter dette tilbudet kan eleven begynne på Vg2 i et yrkesfaglig utdanningsprogram og ta et opphentingsfag der. Det gjelder {antall} programområder på Vg2. Faget er',
      sok: 'Søk etter Vg2 på yrkesfag',
      ingenTreff: 'Ingen programområder passer søket.',
      antall: '{antall} treff',
      flere: '… og {antall} til. Skriv mer for å se dem.',
      fra: 'Fra studieforberedende Vg1 med {fag}',
    },
    tilpasningTotal: '{timer} timer i alt',
    tilpasningTotalOrdinart: '{timer} timer i alt (ordinært {ordinart})',
    tilpasningHjelp: 'Rundskrivet har egne kolonner for noen elevgrupper. Her står bare fagene der timene er annerledes enn i den ordinære fordelingen.',
    tilpasningNavn: {
      samisk: 'Elever med samisk',
      tegnsprak: 'Elever med tegnspråk',
      medStudiespesialisering: 'Elever som har vg1 studiespesialisering',
      utenFremmedsprak: 'Elever uten fremmedspråk fra grunnskolen',
    },
    tilpasningGruppe: { ikkeMed: 'Fag som ikke er med', kommerTil: 'Fag som kommer til', endret: 'Andre timer' },
    tilpasningFag: '{linje} ({timer} timer)',
    tilpasningEndret: '{linje}: {fra} → {til} timer',
    bedrift: 'Opplæringen skjer i bedrift. Fag- og timefordelingen i rundskrivet gjelder ikke.',
    utenTabell: 'Rundskrivet har ingen tabell for dette programområdet.',
    skolerOverskrift: 'Skoler med tilbudet',
    dinSkoleHar: '{skole} har tilbudet.',
    dinSkoleHarIkke: '{skole} har ikke tilbudet.',
    skolerFylke: '{antall} skoler i {fylke}',
    skolerFylkeEn: 'Én skole i {fylke}',
    ingenSkolerFylke: 'Ingen skoler i {fylke} har tilbudet.',
    skolerLandet: '{antall} skoler i hele landet',
    skolerLandetEn: 'Én skole i hele landet',
    ingenSkoler: 'utdanning.no viser ingen skoler med tilbudet.',
    skolerHjelp: 'Etter utdanning.no, hentet hver uke.',
    yrkerOverskrift: 'Yrker',
    yrkerHjelp: 'Yrkene og teksten er fra utdanning.no og er åpne data (NLOD). Teksten vedlikeholdes på utdanning.no.',
    utdanningsbeskrivelse: '{tittel} på utdanning.no',
    kontorOverskrift: 'Opplæringskontorer',
    kontorFylke: '{antall} opplæringskontorer godkjent i {fylke}',
    kontorLandet: '{antall} opplæringskontorer i hele landet',
    kontorHjelp: 'Registeret til Udir (NOR) sier ikke hvilke lærefag kontorene har, så listen viser alle kontorene i fylket.',
    vilbliOverskrift: 'Vilbli',
    ikkeI: 'Står ikke i {kilder}',
    og: 'og',
    uenigTittel: 'Kildene er ikke enige om alle løpene',
    uenigTekst: 'Løpene her er fra Grep, læreplandatabasen til Udir. VIGO, som fylkeskommunene bruker til inntak, og utdanning.no viser også løpene. Når en av dem ikke har et løp som de andre har, står det ved løpet. Merknaden sier bare at kildene er uenige, ikke hvem som har rett.',
    vilbliUtdanningOverskrift: 'Vilbli og utdanning.no',
    utdanningLenke: 'Tilbudet på utdanning.no',
    lopkilde: { grep: 'Grep', vigo: 'VIGO', utdanning: 'utdanning.no' },
    vilbli: 'Skoler og lærebedrifter',
    vilbliFylke: 'Skoler og lærebedrifter i {fylke}',
    vilbliFordeling: 'Fag- og timefordelingen på Vilbli',
    vilbliHjelp: 'Vilbli er fylkeskommunenes tjeneste for søkere. Velg fylke under Innstillinger for å se skolene i fylket.',
    omProgramomrade: 'Om begrepet programområde',
  },
};
