// UI-tekster for modulen Opplæringstilbud (id opplaeringslop) på nynorsk. Må ha dei same nøklane som opplaeringslop.nb.ts.

export const opplaeringslopNn = {
  tittel: 'Opplæringstilbod',
  innledning: 'Opplæringstilbodet i vidaregåande: utdanningsprogramma og løpa vidare, skulane og tilboda deira, og opplæringskontora i fylket.',
  skolear: 'Fag og timar for skuleåret {skolear}.',
  lasterFeil: 'Tilboda kunne ikkje lastast. Prøv igjen.',
  ikkeFunnet: 'Fann ikkje tilbodet.',
  dinSkole: 'Skulen din',
  registre: 'Skular og opplæringskontor',
  tilbudVedSkolen: 'Tilboda ved {skole}',
  visning: {
    etikett: 'Vis tilbod',
    skole: 'Min skule',
    alle: 'Alle',
    viser: 'Viser tilboda ved {skole}.',
    velgSkole: 'Vel skule under Innstillingar, så ser du tilboda ved skulen din.',
    velgSkoleLenke: 'Vel skule',
    ukjentSkole: 'utdanning.no viser ikkje tilboda ved {skole}, så alle tilbod blir viste.',
    ingenIProgram: '{skole} har ingen tilbod i dette utdanningsprogrammet.',
    visAlle: 'Vis alle tilbod',
    antallVedSkolen: '{antall} tilbod ved skulen',
    etVedSkolen: 'Eitt tilbod ved skulen',
    vedSkolenDin: '{antall} ved skulen din',
    vedSkolenLenger: 'ved skulen din lenger ut i løpet',
    programmerTittel: 'Utdanningsprogram ved skulen',
  },
  skoler: {
    tittel: 'Skular og tilbod',
    innledning: 'Skulane i vidaregåande og programområda dei tilbyr, etter utdanning.no.',
    tilbudSok: 'Finn skulane som har eit tilbod',
    tilbudPlassholder: 'Til dømes «Vg2 realfag»',
    tilbudIngen: 'Ingen skular har eit tilbod som passar søket.',
    sok: 'Søk etter skule eller stad',
    fylke: 'Fylke',
    alleFylker: 'Alle fylke',
    program: 'Utdanningsprogram',
    alleProgram: 'Alle utdanningsprogram',
    tilbud: 'Har {tilbud}',
    fjernTilbud: 'Fjern',
    antall: '{antall} skular',
    en: 'Éin skule',
    ingen: 'Ingen skular passar.',
    privat: 'Privat',
    antallTilbud: '{antall} tilbod',
    nettside: 'Nettsida til skulen',
    nettsideKort: 'Nettsida',
    skolereglerKort: 'Skulen sine reglar',
    fagfordelingKort: 'Fag- og timefordeling',
    tilbudVedSkolen: 'Opplæringstilbod ved skulen ({antall})',
    visFlere: 'Vis fleire skular',
    hentet: 'Etter utdanning.no, henta {dato}. Skulen du har valt under Innstillingar, er kopla med skulenummeret i VIGO.',
    utenTilbud: 'utdanning.no viser ingen tilbod ved skulen.',
    alleVedSkolen: 'Vis alle tilboda ved skulen ({antall})',
    bareLopet: 'Vis berre løpet for {tilbud}',
    bareProgram: 'Vis berre {program}',
    heleLandet: 'Søk i heile landet ({antall})',
  },
  kontor: {
    tittel: 'Opplæringskontor',
    innledning: 'Opplæringskontora som er godkjende i fylket, etter registeret til Udir for fag- og yrkesopplæring (NOR).',
    sok: 'Søk etter kontor eller kommune',
    hjelp: 'NOR seier ikkje kva lærefag kontora har. Namnet seier ofte kva bransje kontoret er for, og sida om kontoret på utdanning.no har meir, mellom anna medlemsbedriftene.',
    utdanning: 'Kontoret på utdanning.no',
    heleLandet: 'Søk i heile landet ({antall})',
    iFylket: '{antall} i {fylke}',
    antall: '{antall} opplæringskontor',
    ingen: 'Ingen opplæringskontor passar.',
    visFlere: 'Vis fleire kontor',
    godkjentFylker: 'Godkjend i {antall} fylke',
    godkjentFylke: 'Godkjend i {fylke}',
    laerlinger: '{antall} lærlingar',
    nettside: 'Nettsida til kontoret',
    hentet: 'Etter NOR (Udir), henta {dato}.',
  },
  fagbrev: {
    tittel: 'Lærlingar og kandidatar',
    innledning: 'Lærling, lærekandidat, praksisbrevkandidat, praksiskandidat og kandidat for fagbrev på jobb: kva kvar veg består av, kven som melder opp, fellesfaga og korleis ein byter undervegs. Vegane endar i fag- og sveinebrev, praksisbrev eller kompetansebevis. Prøva står i Vurdering.',
    inngang: '{antall} vegar',
    inngangTekst: 'Lærling, lærekandidat, praksisbrevkandidat og praksiskandidat: vegane og byte undervegs.',
    faner: 'Vel vising',
    fane: { veiene: 'Vegane', sammenlign: 'Samanlikn', bytte: 'Byte veg' },
    maal: 'Målet',
    maalValg: { fagbrev: 'Fag- eller sveinebrev', fagbrevKort: 'Fagbrev', praksisbrev: 'Praksisbrev', kompetansebevis: 'Kompetansebevis' },
    utenFellesfag: 'Berre vegar utan krav om fellesfag',
    antallVeier: '{antall} vegar',
    enVei: '1 veg',
    del: { skole: 'Skule', bedrift: 'Kontrakt i bedrift', praksis: 'Praksis i arbeidslivet', prove: 'Prøva' },
    stegene: 'Stega',
    kontrakt: 'Kontrakt',
    prove: 'Prøva',
    melderOpp: 'Melder opp',
    fellesfag: 'Fellesfag',
    dokumentasjon: 'Dokumentasjon',
    voksne: 'Vaksne (kapittel 18)',
    lesMer: 'Meir om {rolle}',
    lesMerTekst: 'Kjem frå og vegen vidare',
    velgA: 'Første veg',
    velgB: 'Andre veg',
    fellesfagListe: 'Fellesfaga i alle vegane',
    fellesfagListeTekst: 'Kva vegar som krev bestått fellesfag, og kva som ikkje gjer det.',
    fellesfagKrav: { ja: 'Må vere bestått', nei: 'Trengst ikkje', ingen: 'Ingen eigen regel' },
    hvorErDu: 'Kvar er du no?',
    veieneVidere: 'Vegane vidare frå {fra}',
    vilkar: 'Vilkår',
    kommerFra: 'Kjem frå',
    veienVidere: 'Vegen vidare',
    iVurdering: 'I Vurdering',
    proveTekst: 'Krav, oppmelding, prøvenemnda, karakterar, ny prøve og klage.',
    iOpplaeringstilbud: 'I Opplæringstilbod',
    veieneHit: 'Vegane hit',
    veieneHitTekst: '{antall} vegar i Opplæringstilbod, frå lærling til praksiskandidat.',
    proveFor: { fagbrev: 'Til fag- eller sveineprøva', praksisbrev: 'Til praksisbrevprøva', kompetansebevis: 'Til kompetanseprøva' },
    omVeien: 'Om vegen',
    ikkeFunnet: 'Fann ikkje vegen.',
    alleVeier: 'Sjå alle vegane for lærlingar og kandidatar',
    sokTekst: 'Vegane til fag- og sveinebrev, praksisbrev og kompetansebevis, og byte undervegs.',
  },
  lop: {
    tittel: 'Opplæringsløp',
    innledning: 'Utdanningsprogramma, tilboda på kvart trinn og faga og timane i kvart tilbod, etter fag- og timefordelinga til Udir. Vel eit program for å sjå løpet frå Vg1 til Vg3 og lærefag.',
  },
  inngang: {
    program: '{antall} utdanningsprogram',
    programSkole: '{antall} utdanningsprogram ved {skole}',
    programTekst: 'Løpet frå Vg1 til Vg3 og lærefag, med fag og timar i kvart tilbod.',
    skoler: '{antall} skular',
    skolerFylke: '{antall} skular i {fylke}',
    skolerTekst: 'Finn skulane som har eit tilbod, og tilboda ved kvar skule.',
    kontorTekst: 'Med nettside og lenkje til kontoret på utdanning.no.',
  },
  oversikt: {
    sok: 'Søk etter tilbod, kode eller skule',
    antallTreffBegge: '{tilbud} tilbod og {skoler} skular passar søket.',
    antallTreff: '{antall} tilbod passar søket.',
    ingenTreff: 'Ingen tilbod eller skular passar søket.',
    program: 'Utdanningsprogram og løp',
    skoler: 'Skular ({antall})',
    alleSkoler: 'Sjå alle dei {antall} skulane i oppslaget',
  },
  gruppe: {
    studieforberedende: 'Studieførebuande utdanningsprogram',
    yrkesfaglig: 'Yrkesfaglege utdanningsprogram',
    pabygging: 'Påbygging til generell studiekompetanse',
  },
  program: {
    lopHjelp: 'Kvart tilbod fører vidare til tilboda på neste trinn. Trykk på eit tilbod for fag og timar.',
    varianter: 'For særskilde skular',
    variantHjelp: 'Steinerskular, Montessoriskular og tyske skular har eigne programområde i Grep.',
    utenfor: 'Andre programområde i programmet',
    utenforHjelp: 'Grep oppgir ikkje kva desse byggjer på.',
    visVidere: 'Vis {antall} tilbod på {trinn}',
    skjulVidere: 'Skjul tilboda på {trinn}',
    visVidereBlandet: 'Vis {antall} tilbod vidare',
    skjulVidereBlandet: 'Skjul tilboda vidare',
  },
  sted: {
    skole: 'I skule',
    bedrift: 'I bedrift',
    ukjent: 'Ukjend stad',
  },
  tilbud: {
    timer: '{timer} timar',
    timerHjelp: 'Timar à 60 minutt per år etter rundskrivet Udir-1.',
    sammensetning: 'Slik er timane fordelte',
    kategori: {
      fellesfag: 'Fellesfag',
      felles_programfag: 'Felles programfag',
      fordypning: 'Programfag til fordjuping',
      valgfritt: 'Programfag til val',
      yff: 'Yrkesfagleg fordjuping',
      opphenting: 'Yrkesfagleg opphenting',
      vurdering: 'Vurdering',
      alternativ: 'Alternativ for særskilde grupper',
    },
    erstatning: '{fag} er programfag på {timer} timar. Vel eleven eitt av dei i staden for {fellesfag}, må eleven ta eit ekstra programfag i tillegg (Udir-1, punkt 3.3.1.4).',
    iStedet: 'Eleven kan i staden velje det studieførebuande tilbodet, {fag}. Det har {timer} timar i staden for {linjetimer} (Udir-1, punkt 3.5).',
    eller: 'eller',
    velgEnKort: 'vel ein:',
    velgAntall: 'Vel {antall} fag',
    blantFag: 'blant {antall} fag',
    utvalgFlereTrinnKort: 'Fag over fleire trinn',
    utvalgValgKort: 'Fag til val',
    vurderingskoder: 'Vurderingskodar',
    eksamen: 'Vurdering og eksamen',
    andreFag: 'Andre fag',
    rolleValg: '{kategori}, eitt av fleire val',
    tilArbeidsplan: 'Rekn ut i Arbeidsplan',
    tilArbeidsplanHjelp: 'Fellesfag og felles programfag blir lagde inn med årstimane, kvart fag som eiga gruppe. Der eleven vel mellom fag (t.d. 1P eller 1T, eit framandspråk, eller dekk eller maskin), blir det første lagt inn. Fjern faga du ikkje underviser i, byt fag der det trengst, og legg inn programfag til fordjuping og val sjølv.',
    avvik: {
      fellesfagTimer: 'Rundskrivet har {rundskriv} timar i {linje}. Fagkodane i Grep har {grep} timar.',
      ingenFagkode: 'Grep har ingen fagkode for {linje} i dette tilbodet.',
      ingenProgramfag: 'Grep har ingen felles programfag for dette tilbodet. Timane er frå rundskrivet.',
      programfagTimer: 'Rundskrivet har {rundskriv} timar. Faga i Grep har til saman {grep}.',
      ingenFellesfag: 'Grep koplar ingen fellesfag til dette tilbodet. Timane er frå rundskrivet.',
      sum: 'Delane i rundskrivet har til saman {sum} timar, men rundskrivet oppgir {totalt} i alt.',
    },
    antallFag: '{antall} fag',
    sokFag: 'Søk etter fag',
    ingenFag: 'Ingen fag passar søket.',
    tilpasningerTittel: 'Tilpassa ordningar',
    velgEn: 'vel ein av {antall}',
    alternativer: 'Alternativ for særskilde grupper',
    rekkefolge: 'I rekkjefølgje',
    andreKoder: 'Andre kodar',
    lantFra: 'Fagkodane er henta frå {tilbud}.',
    byggerPaa: 'Byggjer på',
    kryssFra: 'Kryssløp frå',
    videre: 'Vidare',
    pabygging: 'Påbygging',
    kryssTil: 'Kryssløp til',
    opphenting: {
      tittel: 'Vg2 på yrkesfag',
      tekst: 'Etter dette tilbodet kan eleven byrje på Vg2 i eit yrkesfagleg utdanningsprogram og ta eit opphentingsfag der. Det gjeld {antall} programområde på Vg2. Faget er',
      sok: 'Søk etter Vg2 på yrkesfag',
      ingenTreff: 'Ingen programområde passar søket.',
      antall: '{antall} treff',
      flere: '… og {antall} til. Skriv meir for å sjå dei.',
      fra: 'Frå studieførebuande Vg1 med {fag}',
    },
    tilpasningTotal: '{timer} timar i alt',
    tilpasningTotalOrdinart: '{timer} timar i alt (ordinært {ordinart})',
    tilpasningHjelp: 'Rundskrivet har eigne kolonnar for nokre elevgrupper. Her står berre faga der timane er annleis enn i den ordinære fordelinga.',
    tilpasningNavn: {
      samisk: 'Elevar med samisk',
      tegnsprak: 'Elevar med teiknspråk',
      medStudiespesialisering: 'Elevar som har vg1 studiespesialisering',
      utenFremmedsprak: 'Elevar utan framandspråk frå grunnskulen',
    },
    tilpasningGruppe: { ikkeMed: 'Fag som ikkje er med', kommerTil: 'Fag som kjem til', endret: 'Andre timar' },
    tilpasningFag: '{linje} ({timer} timar)',
    tilpasningEndret: '{linje}: {fra} → {til} timar',
    bedrift: 'Opplæringa skjer i bedrift. Fag- og timefordelinga i rundskrivet gjeld ikkje.',
    utenTabell: 'Rundskrivet har ingen tabell for dette programområdet.',
    skolerOverskrift: 'Skular med tilbodet',
    dinSkoleHar: '{skole} har tilbodet.',
    dinSkoleHarIkke: '{skole} har ikkje tilbodet.',
    skolerFylke: '{antall} skular i {fylke}',
    skolerFylkeEn: 'Éin skule i {fylke}',
    ingenSkolerFylke: 'Ingen skular i {fylke} har tilbodet.',
    skolerLandet: '{antall} skular i heile landet',
    skolerLandetEn: 'Éin skule i heile landet',
    ingenSkoler: 'utdanning.no viser ingen skular med tilbodet.',
    skolerHjelp: 'Etter utdanning.no, henta kvar veke.',
    yrkerOverskrift: 'Yrke',
    yrkerHjelp: 'Yrka og teksten er frå utdanning.no og er opne data (NLOD). Teksten blir halden ved like på utdanning.no.',
    utdanningsbeskrivelse: '{tittel} på utdanning.no',
    kontorOverskrift: 'Opplæringskontor',
    kontorFylke: '{antall} opplæringskontor godkjende i {fylke}',
    kontorLandet: '{antall} opplæringskontor i heile landet',
    kontorHjelp: 'Registeret til Udir (NOR) seier ikkje kva lærefag kontora har, så lista viser alle kontora i fylket.',
    vilbliOverskrift: 'Vilbli',
    bareI: 'Står berre i {kilde}',
    ikkeI: 'Står ikkje i {kilder}',
    og: 'og',
    uenigTittel: 'Kjeldene er ikkje samde om alle løpa',
    uenigTekst: 'Løpa her står i minst éi av tre kjelder: Grep (læreplandatabasen til Udir), VIGO (som fylkeskommunane bruker til inntak) og utdanning.no. Når berre éi kjelde har eit løp, eller ei kjelde manglar eit løp dei andre har, står det ved løpet. Merknaden seier berre at kjeldene er usamde, ikkje kven som har rett.',
    vilbliUtdanningOverskrift: 'Vilbli og utdanning.no',
    utdanningLenke: 'Tilbodet på utdanning.no',
    lopkilde: { grep: 'Grep', vigo: 'VIGO', utdanning: 'utdanning.no' },
    vilbli: 'Skular og lærebedrifter',
    vilbliFylke: 'Skular og lærebedrifter i {fylke}',
    vilbliFordeling: 'Fag- og timefordelinga på Vilbli',
    vilbliHjelp: 'Vilbli er tenesta til fylkeskommunane for søkjarar. Vel fylke under Innstillingar for å sjå skulane i fylket.',
    omProgramomrade: 'Om omgrepet programområde',
  },
};
