// UI-tekster for modulen Opplæringsløp på nynorsk. Må ha dei same nøklane som opplaeringslop.nb.ts.

export const opplaeringslopNn = {
  tittel: 'Opplæringsløp',
  innledning:
    'Tilboda i vidaregåande: utdanningsprogramma, programområda på kvart trinn og faga og timane i kvart tilbod, etter fag- og timefordelinga til Udir.',
  skolear: 'Fag og timar for skuleåret {skolear}.',
  lasterFeil: 'Tilboda kunne ikkje lastast. Prøv igjen.',
  ikkeFunnet: 'Fann ikkje tilbodet.',
  gruppe: {
    studieforberedende: 'Studieførebuande utdanningsprogram',
    yrkesfaglig: 'Yrkesfaglege utdanningsprogram',
    pabygging: 'Påbygging til generell studiekompetanse',
  },
  program: {
    lop: 'Løpet',
    lopHjelp: 'Kvart tilbod fører vidare til tilboda på neste trinn. Trykk på eit tilbod for fag og timar.',
    varianter: 'For særskilde skular',
    variantHjelp: 'Steinerskular, Montessoriskular og tyske skular har eigne programområde i Grep.',
    utenfor: 'Andre programområde i programmet',
    utenforHjelp: 'Grep oppgir ikkje kva desse byggjer på.',
    videre: 'vidare til',
  },
  sted: {
    skole: 'I skule',
    bedrift: 'I bedrift',
    ukjent: 'Ukjend stad',
  },
  tilbud: {
    timer: '{timer} timar',
    timerHjelp: 'Timar à 60 minutt per år etter rundskrivet Udir-1.',
    fagOgTimer: 'Fag og timar',
    sum: 'Sum',
    velgEn: 'Vel ein av {antall}',
    vurdering: 'Vurdering',
    alternativer: 'Alternativ for særskilde grupper ({antall})',
    utvalgFlereTrinn: '{timer} timar frå fag over fleire trinn',
    utvalgValg: '{timer} timar: vel {antall}',
    utvalgValgFritt: '{timer} timar frå desse faga',
    rekkefolge: 'I rekkjefølgje',
    plassValgfritt: '{antall} fag à 140 timar, vald blant {kandidater} programfag',
    plassFordypning: '{antall} fag à 140 timar, vald blant {kandidater} programfag til fordjuping',
    plassUtenAntall: 'Vald blant {kandidater} fag',
    anbefalt: 'Fagkoden med timetalet for trinnet',
    andreKoder: 'Andre kodar ({antall})',
    lantFra: 'Fagkodane er henta frå {tilbud}.',
    byggerPaa: 'Byggjer på',
    kryssFra: 'Kryssløp frå',
    videre: 'Vidare',
    pabygging: 'Påbygging',
    kryssTil: 'Kryssløp til',
    tilpasninger: 'Tilpassa ordningar ({antall})',
    tilpasningTotal: '{timer} timar i alt',
    tilpasningLinje: '{linje}: {fra} → {til}',
    bedrift: 'Opplæringa skjer i bedrift. Fag- og timefordelinga i rundskrivet gjeld ikkje.',
    utenTabell: 'Rundskrivet har ingen tabell for dette programområdet.',
    vilbliOverskrift: 'Vilbli',
    vilbli: 'Skular og lærebedrifter',
    vilbliFylke: 'Skular og lærebedrifter i {fylke}',
    vilbliFordeling: 'Fag- og timefordelinga på Vilbli',
    vilbliHjelp: 'Vilbli er tenesta til fylkeskommunane for søkjarar. Vel fylke under Innstillingar for å sjå skulane i fylket.',
    omProgramomrade: 'Om omgrepet programområde',
  },
};
