// UI-tekster for modulen Opplæringsløp på bokmål. opplaeringslop.nn.ts må ha de samme nøklene.

export const opplaeringslopNb = {
  tittel: 'Opplæringsløp',
  innledning:
    'Tilbudene i videregående: utdanningsprogrammene, programområdene på hvert trinn og fagene og timene i hvert tilbud, etter Udirs fag- og timefordeling.',
  skolear: 'Fag og timer for skoleåret {skolear}.',
  lasterFeil: 'Tilbudene kunne ikke lastes. Prøv igjen.',
  ikkeFunnet: 'Fant ikke tilbudet.',
  gruppe: {
    studieforberedende: 'Studieforberedende utdanningsprogram',
    yrkesfaglig: 'Yrkesfaglige utdanningsprogram',
    pabygging: 'Påbygging til generell studiekompetanse',
  },
  program: {
    lop: 'Løpet',
    lopHjelp: 'Hvert tilbud fører videre til tilbudene på neste trinn. Trykk på et tilbud for fag og timer.',
    varianter: 'For særskilte skoler',
    variantHjelp: 'Steinerskoler, Montessoriskoler og tyske skoler har egne programområder i Grep.',
    utenfor: 'Andre programområder i programmet',
    utenforHjelp: 'Grep oppgir ikke hva disse bygger på.',
    videre: 'videre til',
  },
  sted: {
    skole: 'I skole',
    bedrift: 'I bedrift',
    ukjent: 'Ukjent sted',
  },
  tilbud: {
    timer: '{timer} timer',
    timerHjelp: 'Timer à 60 minutter per år etter rundskrivet Udir-1.',
    fagOgTimer: 'Fag og timer',
    sum: 'Sum',
    velgEn: 'Velg én av {antall}',
    vurdering: 'Vurdering',
    alternativer: 'Alternativer for særskilte grupper ({antall})',
    utvalgFlereTrinn: '{timer} timer fra fag over flere trinn',
    utvalgValg: '{timer} timer: velg {antall}',
    utvalgValgFritt: '{timer} timer fra disse fagene',
    rekkefolge: 'I rekkefølge',
    plassValgfritt: '{antall} fag à 140 timer, velges blant {kandidater} programfag',
    plassFordypning: '{antall} fag à 140 timer, velges blant {kandidater} programfag til fordypning',
    plassUtenAntall: 'Velges blant {kandidater} fag',
    anbefalt: 'Fagkoden med timetallet for trinnet',
    andreKoder: 'Andre koder ({antall})',
    lantFra: 'Fagkodene er hentet fra {tilbud}.',
    byggerPaa: 'Bygger på',
    kryssFra: 'Kryssløp fra',
    videre: 'Videre',
    pabygging: 'Påbygging',
    kryssTil: 'Kryssløp til',
    tilpasninger: 'Tilpassede ordninger ({antall})',
    tilpasningTotal: '{timer} timer i alt',
    tilpasningLinje: '{linje}: {fra} → {til}',
    bedrift: 'Opplæringen skjer i bedrift. Fag- og timefordelingen i rundskrivet gjelder ikke.',
    utenTabell: 'Rundskrivet har ingen tabell for dette programområdet.',
    vilbliOverskrift: 'Vilbli',
    vilbli: 'Skoler og lærebedrifter',
    vilbliFylke: 'Skoler og lærebedrifter i {fylke}',
    vilbliFordeling: 'Fag- og timefordelingen på Vilbli',
    vilbliHjelp: 'Vilbli er fylkeskommunenes tjeneste for søkere. Velg fylke under Innstillinger for å se skolene i fylket.',
    omProgramomrade: 'Om begrepet programområde',
  },
};
