// UI-tekster for modulen Skolemiljø på nynorsk. Same nøklar som skolemiljo.nb.ts.

export const skolemiljoNn = {
  tittel: 'Skulemiljø',
  innledning: 'Retten til eit trygt og godt skulemiljø og resultata frå Elevundersøkinga, aktivitetsplikta steg for steg og skulereglane i fylket og på skulen. Kvart steg viser kven som har ansvaret, kva som skal dokumenterast og paragrafane i regelverket.',
  rettenOgResultatene: 'Retten og resultata',
  veivisere: 'Vegvisarar',
  oppslag: 'Oppslag',
  ikkeFunnet: 'Fann ikkje sida.',
  kapittel12: {
    tittel: 'Eit trygt og godt skulemiljø',
    kort: 'Eit trygt og godt skulemiljø',
    beskrivelse: 'Opplæringslova kapittel 12: retten, pliktene til skulen, statsforvaltaren, det fysiske miljøet og ansvaret.',
    innledning: 'Opplæringslova kapittel 12 gir alle elevar rett til eit trygt og godt skulemiljø, og skulen pliktar å sørgje for det. Her er kapittelet paragraf for paragraf, med eigne ord.',
    deler: {
      retten: { tittel: 'Retten', paragrafer: '§§ 12-1 og 12-2', tekst: 'Alle elevar har rett til eit trygt og godt skulemiljø. Opplevinga til eleven avgjer.' },
      plikter: { tittel: 'Pliktene til skulen', paragrafer: '§§ 12-3 til 12-5', tekst: 'Nulltoleranse, førebygging og aktivitetsplikt.' },
      statsforvalteren: { tittel: 'Statsforvaltaren', paragrafer: '§ 12-6', tekst: 'Eleven og foreldra kan melde saka når skulen ikkje gjer nok.' },
      fysisk: { tittel: 'Det fysiske miljøet', paragrafer: '§ 12-7', tekst: 'Ein arbeidsplass som er tilpassa behova til eleven.' },
      ansvar: { tittel: 'Ansvar', paragrafer: '§§ 12-8 til 12-10', tekst: 'Tvangsmulkt, straff og omvend bevisbyrde.' },
    },
    delplikter: 'Dei fem delpliktene',
    delplikt: { folgeMed: 'Følgje med', gripeInn: 'Gripe inn', meldeFra: 'Melde frå', undersoke: 'Undersøkje', tiltak: 'Setje inn tiltak' },
    dokumentere: 'Heile vegen: dokumentere',
    gangen: 'Vegen til statsforvaltaren',
    gang: {
      rektor: 'Ta saka opp med rektor',
      uke: 'Vent minst ei veke',
      melde: 'Meld saka til statsforvaltaren',
      vedtak: 'Vedtak med frist',
      klage: 'Klage til Udir, tvangsmulkt dersom vedtaket ikkje blir følgt',
    },
    hengerSammen: 'Heng saman med',
    veiviser: 'Vegvisaren «Aktivitetsplikta»',
    veiviserTekst: 'Steg for steg for den som arbeider på skulen, rektor og eleven.',
    skoleregler: 'Skulereglar',
    skolereglerTekst: 'Reaksjonar, bortvising og pålagt skulebyte.',
    elevundersokelsen: 'Elevundersøkinga',
    elevundersokelsenTekst: 'Mobbing og læringsmiljøet på skulen, i fylket og i landet.',
    lesKapittelet: 'Les kapittel 12 i Regelverk',
  },
  skoleregler: {
    tittel: 'Skulereglar',
    kort: 'Skulereglar',
    beskrivelse: 'Reaksjonar, bortvising og saksbehandling: reglane i lova og i skulereglane i fylket og på skulen.',
    innledning: 'Skulereglane er ei forskrift fylkeskommunen gir. Ho seier kva rettar og plikter elevane har, og kan seie kva tiltak skulen kan bruke når elevar bryt reglane, og korleis sakene blir behandla. Her står reglane i lova, og paragrafane om reaksjonar og saksbehandling i skulereglane for fylket og skulen du har valt.',
    iLoven: 'I lova',
    iFylket: 'Skulereglane i {fylke}',
    iFylketUten: 'Skulereglane i fylket',
    velgFylke: 'Vel fylke for å sjå paragrafane om reaksjonar og saksbehandling i skulereglane i fylket.',
    velgFylkeLenke: 'Vel fylke',
    ingenFylke: 'Appen har ikkje skulereglane for {fylke}.',
    lesHele: 'Les heile skulereglane',
    voksne: 'Skulereglane for vaksne i {fylke}',
    skolensRegler: 'Eigne reglar for skulen',
    skolensReglerTekst: 'Skulen kan ha eigne reglar i tillegg til fylket sine. Står dei i Lovdata, finn du dei her.',
    skolenHar: 'Reglar for {skole}',
    skolenHarIkke: 'Appen har ingen eigne reglar for {skole} frå Lovdata. Skulen kan likevel ha reglar som ikkje er kunngjorde som forskrift.',
    velgSkole: 'Vel skule i innstillingane for å sjå dei eigne reglane til skulen, når dei står i Lovdata.',
    privatskole: 'Privatskular',
    videre: 'Vidare',
    aktivitetsplikten: 'Aktivitetsplikta',
    aktivitetspliktenTekst: 'Når ein elev ikkje har det trygt og godt: følgje med, gripe inn, melde frå, undersøkje og setje inn tiltak.',
    ordenOgOppforsel: 'Orden og oppførsel',
    ordenOgOppforselTekst: 'Vurderinga i orden og oppførsel har skulereglane som grunnlag.',
    alleForskrifter: 'Alle lokale forskrifter',
    alleForskrifterTekst: 'Skulereglar, inntak og skulerute for fylket i Regelverk.',
  },
  elevundersokelsen: {
    tittel: 'Elevundersøkinga',
    kort: 'Elevundersøkinga',
    beskrivelse: 'Mobbing, trivsel og læringsmiljø på skulen, i fylket og i landet, med året før.',
    innledning: 'Resultata frå Elevundersøkinga i vidaregåande, frå statistikkbanken til Udir. Samanlikn skulen, fylket og landet, eller andre skular og fylke, for alle, offentlege eller private skular. Tala for året før står ved sida av.',
    sammenlign: 'Samanlikn',
    serie: 'Serie {nr}',
    ingen: 'Ingen',
    landet: 'Heile landet',
    fylker: 'Fylka',
    skolerI: 'Skular i {fylke}',
    skoler: 'Skulane',
    sokPlassholder: 'Søk etter skule eller fylke',
    treff: 'Treff',
    ingenTreff: 'Ingen treff. Prøv ein del av namnet, t.d. «Slåtthaug» eller «Vestland».',
    skrivForSkoler: 'Skriv for å søkje blant {antall} skular.',
    flereTreff: '{antall} skular til. Skriv meir for å finne dei.',
    beste: 'best i rada',
    besteForklaring: 'Ramme rundt talet er det beste i rada.',
    eierformKort: { a: 'alle skular', o: 'offentlege skular', p: 'private skular' },
    trinn: 'Trinn',
    trinnValg: { t0: 'Vg1', t1: 'Vg2', t2: 'Vg3' },
    visning: 'Vis',
    diagram: 'Diagram',
    tabell: 'Tabell',
    skolear: 'Skuleåret {naa}, med {foer} til samanlikning',
    mobbing: 'Mobbing',
    mobbingTekst: 'Delen elevar som svarar at dei er blitt mobba 2 eller 3 gonger i månaden eller oftare dei siste månadene, i prosent. Lågare er betre. «Mobbing på skulen» tel kvar elev éin gong, så delane kan ikkje leggjast saman.',
    indekser: 'Læringsmiljøet',
    indekserTekst: 'Indeksane går frå 1 til 5. Høgare er betre. Punktet er i år, og ringen året før.',
    iFjor: 'året før {verdi}',
    endring: '{tegn}{verdi} frå året før',
    uendret: 'som året før',
    skjermet: 'Skjerma',
    skjermetTekst: 'Udir har skjerma talet fordi få elevar står bak det.',
    ingenTall: 'Ingen tal',
    ingenTallTekst: 'Ingen tal for dette trinnet eller skuleåret.',
    prosent: '{verdi} %',
    prosentpoeng: '{verdi} prosentpoeng',
    antall: '{antall} svar',
    kortnavn: {
      EUIndeks_1398: 'Mobbing på skulen',
      EUSpoersmaal_Q11811: 'Mobba av andre elevar',
      EUSpoersmaal_Q11816: 'Mobba digitalt',
      EUSpoersmaal_Q11824: 'Mobba av vaksne på skulen',
    },
    beskrivelser: {
      EUIndeks_1379: 'Korleis elevane trivst på skulen.',
      EUIndeks_1380: 'Støtte frå lærarane, både fagleg og som person.',
      EUIndeks_1381: 'Interesse, støtte og oppmuntring heimanfrå.',
      EUIndeks_1382: 'Om elevane veit kva dei skal lære, får gode tilbakemeldingar og er med og vurderer arbeidet sitt.',
      EUIndeks_1383: 'Om klassen synest skulearbeidet er viktig, og om det er rom for å gjere feil.',
      EUIndeks_1384: 'Om elevane meistrar undervisninga, leksene og arbeidet på skulen.',
      EUIndeks_1385: 'Interesse og lyst til å lære.',
      EUIndeks_1386: 'Om elevane kan påverke arbeidet med faga, reglane i klassen og elevrådsarbeidet.',
      EUIndeks_1387: 'Om elevane kjenner reglane, og om dei vaksne reagerer likt når reglane blir brotne.',
      EUIndeks_1389: 'Rådgivinga elevane fekk på ungdomsskulen. Berre Vg1.',
      EUIndeks_1378: 'Om elevane får nok utfordringar på skulen.',
    },
    omTallene: 'Om tala',
    om: {
      kilde: 'Tala er henta frå statistikkbanken til Udir kvar veke. Elevundersøkinga er obligatorisk for Vg1 og frivillig for Vg2 og Vg3. Ho blir gjennomført om hausten, og resultata blir offentlege i desember.',
      trinn: 'Udir oppgir tala per trinn, ikkje for skulen samla. Appen reknar ikkje ut eigne snitt.',
      skjermet: 'Tal som færre enn 20 elevar står bak (30 for mobbing), er skjerma av Udir og blir viste som «Skjerma». Appen viser aldri eit skjerma tal og reknar ikkje ut tal som kan avsløre det.',
      eierform: 'Landet og fylka kan visast for alle, offentlege eller private skular. Ein skule blir vist for seg.',
      ingenEnkeltelever: 'Appen hentar berre tala Udir publiserer for skulane, fylka og landet. Det er ingen tal om enkeltelevar.',
    },
    skjermingsregler: 'Reglane til Udir for skjerming',
    statistikkbanken: 'Offentlege resultat for vidaregåande hos Udir',
    laster: 'Lastar resultata …',
    feil: 'Klarte ikkje å laste resultata.',
    tabellTittel: 'Resultata for {trinn}, {naa} (året før i parentes)',
    sporsmal: 'Spørsmål eller indeks',
    kortOm: 'Kort om {navn}',
    kortOmTekst: '{trinn}, skuleåret {naa}, samanlikna med {mot}.',
    sterkest: 'Sterkast',
    svakest: 'Svakast',
    sammenlignetMed: '{mot}: {verdi}',
    ingenFakta: 'Ingen tal for {navn} på {trinn}. Vel eit anna trinn.',
    velgSkole: 'Vel skule eller fylke i innstillingane, så står dei viktigaste tala for skulen her.',
    tilInnstillinger: 'Til innstillingane',
    bedreFjor: 'betre enn året før',
    svakereFjor: 'svakare enn året før',
    bedreEnn: 'betre enn {mot}',
    svakereEnn: 'svakare enn {mot}',
    tabellForklaring: '▲ er betre og ▼ svakare enn året før. For mobbing er lågare betre.',
  },
};
