// UI-tekster for modulen Skolemiljø på bokmål. skolemiljo.nn.ts må ha de samme nøklene.

export const skolemiljoNb = {
  tittel: 'Skolemiljø',
  innledning: 'Aktivitetsplikten trinn for trinn, skolereglene i fylket og på skolen, og hva eleven kan gjøre når skolen ikke gjør nok. Hvert steg viser hvem som har ansvaret, hva som skal dokumenteres og paragrafene i regelverket.',
  veivisere: 'Veivisere',
  oppslag: 'Oppslag',
  ikkeFunnet: 'Fant ikke siden.',
  aktivitetsplikten: {
    tittel: 'Aktivitetsplikten',
    beskrivelse: 'Når en elev ikke har det trygt og godt: hva den som arbeider på skolen, rektor og eleven gjør.',
  },
  skoleregler: {
    tittel: 'Skoleregler',
    kort: 'Skoleregler',
    beskrivelse: 'Reaksjoner, bortvisning og saksbehandling: reglene i loven og i skolereglene i fylket og på skolen.',
    innledning: 'Skolereglene er en forskrift fylkeskommunen gir. Den sier hvilke rettigheter og plikter elevene har, og kan si hvilke tiltak skolen kan bruke når elever bryter reglene, og hvordan sakene behandles. Her står reglene i loven, og paragrafene om reaksjoner og saksbehandling i skolereglene for fylket og skolen du har valgt.',
    iLoven: 'I loven',
    iFylket: 'Skolereglene i {fylke}',
    iFylketUten: 'Skolereglene i fylket',
    velgFylke: 'Velg fylke for å se paragrafene om reaksjoner og saksbehandling i skolereglene i fylket.',
    velgFylkeLenke: 'Velg fylke',
    ingenFylke: 'Appen har ikke skolereglene for {fylke}.',
    lesHele: 'Les hele skolereglene',
    voksne: 'Skolereglene for voksne i {fylke}',
    skolensRegler: 'Skolens egne regler',
    skolensReglerTekst: 'Skolen kan ha egne regler i tillegg til fylkets. Står de i Lovdata, finner du dem her.',
    skolenHar: 'Regler for {skole}',
    skolenHarIkke: 'Appen har ingen egne regler for {skole} fra Lovdata. Skolen kan likevel ha regler som ikke er kunngjort som forskrift.',
    velgSkole: 'Velg skole i innstillingene for å se skolens egne regler, når de står i Lovdata.',
    privatskole: 'Privatskoler',
    videre: 'Videre',
    aktivitetsplikten: 'Aktivitetsplikten',
    aktivitetspliktenTekst: 'Når en elev ikke har det trygt og godt: følge med, gripe inn, melde fra, undersøke og sette inn tiltak.',
    ordenOgOppforsel: 'Orden og oppførsel',
    ordenOgOppforselTekst: 'Vurderingen i orden og oppførsel har skolereglene som grunnlag.',
    alleForskrifter: 'Alle lokale forskrifter',
    alleForskrifterTekst: 'Skoleregler, inntak og skolerute for fylket i Regelverk.',
  },
  elevundersokelsen: {
    tittel: 'Elevundersøkelsen',
    kort: 'Elevundersøkelsen',
    beskrivelse: 'Mobbing, trivsel og læringsmiljø på skolen, i fylket og i landet, med året før.',
    innledning: 'Resultatene fra Elevundersøkelsen i videregående, fra Udirs statistikkbank. Sammenlign skolen, fylket og landet, eller andre skoler og fylker, for alle, offentlige eller private skoler. Tallene for året før står ved siden av.',
    sammenlign: 'Sammenlign',
    serie: 'Serie {nr}',
    ingen: 'Ingen',
    landet: 'Hele landet',
    fylker: 'Fylkene',
    skolerI: 'Skoler i {fylke}',
    eierformKort: { a: 'alle skoler', o: 'offentlige skoler', p: 'private skoler' },
    trinn: 'Trinn',
    trinnValg: { t0: 'Vg1', t1: 'Vg2', t2: 'Vg3' },
    visning: 'Vis',
    diagram: 'Diagram',
    tabell: 'Tabell',
    skolear: 'Skoleåret {naa}, med {foer} til sammenligning',
    mobbing: 'Mobbing',
    mobbingTekst: 'Andelen elever som svarer at de er blitt mobbet 2 eller 3 ganger i måneden eller oftere de siste månedene, i prosent. Lavere er bedre. «Mobbing på skolen» teller hver elev én gang, så andelene kan ikke legges sammen.',
    indekser: 'Læringsmiljøet',
    indekserTekst: 'Indeksene går fra 1 til 5. Høyere er bedre. Punktet er i år, og ringen året før.',
    iFjor: 'året før {verdi}',
    endring: '{tegn}{verdi} fra året før',
    uendret: 'som året før',
    skjermet: 'Skjermet',
    skjermetTekst: 'Udir har skjermet tallet fordi få elever står bak det.',
    ingenTall: 'Ingen tall',
    ingenTallTekst: 'Ingen tall for dette trinnet eller skoleåret.',
    prosent: '{verdi} %',
    prosentpoeng: '{verdi} prosentpoeng',
    antall: '{antall} svar',
    kortnavn: {
      EUIndeks_1398: 'Mobbing på skolen',
      EUSpoersmaal_Q11811: 'Mobbet av andre elever',
      EUSpoersmaal_Q11816: 'Mobbet digitalt',
      EUSpoersmaal_Q11824: 'Mobbet av voksne på skolen',
    },
    beskrivelser: {
      EUIndeks_1379: 'Hvordan elevene trives på skolen.',
      EUIndeks_1380: 'Støtte fra lærerne, både faglig og som person.',
      EUIndeks_1381: 'Interesse, støtte og oppmuntring hjemmefra.',
      EUIndeks_1382: 'Om elevene vet hva de skal lære, får gode tilbakemeldinger og er med og vurderer arbeidet sitt.',
      EUIndeks_1383: 'Om klassen synes skolearbeidet er viktig, og om det er rom for å gjøre feil.',
      EUIndeks_1384: 'Om elevene mestrer undervisningen, leksene og arbeidet på skolen.',
      EUIndeks_1385: 'Interesse og lyst til å lære.',
      EUIndeks_1386: 'Om elevene kan påvirke arbeidet med fagene, reglene i klassen og elevrådsarbeidet.',
      EUIndeks_1387: 'Om elevene kjenner reglene, og om de voksne reagerer likt når reglene brytes.',
      EUIndeks_1389: 'Rådgivingen elevene fikk på ungdomsskolen. Bare Vg1.',
      EUIndeks_1378: 'Om elevene får nok utfordringer på skolen.',
    },
    omTallene: 'Om tallene',
    om: {
      kilde: 'Tallene er hentet fra Udirs statistikkbank hver uke. Elevundersøkelsen er obligatorisk for Vg1 og frivillig for Vg2 og Vg3. Den gjennomføres om høsten, og resultatene blir offentlige i desember.',
      trinn: 'Udir oppgir tallene per trinn, ikke for skolen samlet. Appen regner ikke ut egne snitt.',
      skjermet: 'Tall som færre enn 20 elever står bak (30 for mobbing), er skjermet av Udir og vises som «Skjermet». Appen viser aldri et skjermet tall og regner ikke ut tall som kan avsløre det.',
      eierform: 'Landet og fylkene kan vises for alle, offentlige eller private skoler. En skole vises for seg.',
      ingenEnkeltelever: 'Appen henter bare tallene Udir publiserer for skolene, fylkene og landet. Det er ingen tall om enkeltelever.',
    },
    skjermingsregler: 'Udirs regler for skjerming',
    statistikkbanken: 'Offentlige resultater for videregående hos Udir',
    laster: 'Laster resultatene …',
    feil: 'Klarte ikke å laste resultatene.',
    tabellTittel: 'Resultatene for {trinn}, {naa} (året før i parentes)',
    sporsmal: 'Spørsmål eller indeks',
  },
};
