// UI-tekster for modulen Skolemiljø på nynorsk. Same nøklar som skolemiljo.nb.ts.

export const skolemiljoNn = {
  tittel: 'Aktivitetsplikt og skulereglar',
  innledning: 'Retten til eit trygt og godt skulemiljø, aktivitetsplikta steg for steg og skulereglane i fylket og på skulen. Kvart steg viser kven som har ansvaret, kva som skal dokumenterast og paragrafane i regelverket.',
  rettenOgResultatene: 'Retten og pliktene',
  oppslag: 'Oppslag',
  ikkeFunnet: 'Fann ikkje sida.',
  kapittel12: {
    tittel: 'Eit trygt og godt skulemiljø',
    kort: 'Eit trygt og godt skulemiljø',
    beskrivelse: 'Opplæringslova kapittel 12: retten, pliktene til skulen, statsforvaltaren, det fysiske miljøet og ansvaret.',
    innledning: 'Opplæringslova kapittel 12 gir alle elevar rett til eit trygt og godt skulemiljø, og skulen pliktar å sørgje for det. Her er kapittelet paragraf for paragraf, med eigne ord.',
    deler: {
      retten: { tittel: 'Retten', paragrafer: '§§ 12-1 og 12-2', tekst: 'Alle elevar har rett til eit trygt og godt skulemiljø. Opplevinga til eleven avgjer.' },
      plikter: { tittel: 'Pliktene til skulen', paragrafer: '§§ 12-3 til 12-5', tekst: 'Nulltoleranse, førebygging og aktivitetsplikt.' },
      statsforvalteren: { tittel: 'Statsforvaltaren', paragrafer: '§ 12-6', tekst: 'Eleven og foreldra kan melde saka når skulen ikkje gjer nok.' },
      fysisk: { tittel: 'Det fysiske miljøet', paragrafer: '§ 12-7', tekst: 'Ein arbeidsplass som er tilpassa behova til eleven.' },
      ansvar: { tittel: 'Ansvar', paragrafer: '§§ 12-8 til 12-10', tekst: 'Tvangsmulkt, straff og omvend bevisbyrde.' },
    },
    delplikter: 'Dei fem delpliktene',
    delplikt: { folgeMed: 'Følgje med', gripeInn: 'Gripe inn', meldeFra: 'Melde frå', undersoke: 'Undersøkje', tiltak: 'Setje inn tiltak' },
    dokumentere: 'Heile vegen: dokumentere',
    gangen: 'Vegen til statsforvaltaren',
    gang: {
      rektor: 'Ta saka opp med rektor',
      uke: 'Vent minst ei veke',
      melde: 'Meld saka til statsforvaltaren',
      vedtak: 'Vedtak med frist',
      klage: 'Klage til Udir, tvangsmulkt dersom vedtaket ikkje blir følgt',
    },
    hengerSammen: 'Heng saman med',
    veiviser: 'Vegvisaren «Aktivitetsplikta»',
    veiviserTekst: 'Steg for steg for den som arbeider på skulen, rektor og eleven.',
    skoleregler: 'Skulereglar',
    skolereglerTekst: 'Reaksjonar, bortvising og pålagt skulebyte.',
    elevundersokelsen: 'Elevundersøkinga',
    elevundersokelsenTekst: 'Mobbing og læringsmiljøet på skulen, i fylket og i landet.',
    lesKapittelet: 'Les kapittel 12 i Regelverk',
  },
  skoleregler: {
    tittel: 'Skulereglar',
    kort: 'Skulereglar',
    beskrivelse: 'Reaksjonar, bortvising og saksbehandling: reglane i lova og i skulereglane i fylket og på skulen.',
    innledning: 'Skulereglane er ei forskrift fylkeskommunen gir. Ho seier kva rettar og plikter elevane har, og kan seie kva tiltak skulen kan bruke når elevar bryt reglane, og korleis sakene blir behandla. Her står reglane i lova, og paragrafane om reaksjonar og saksbehandling i skulereglane for fylket og skulen du har valt.',
    iLoven: 'I lova',
    iFylket: 'Skulereglane i {fylke}',
    iFylketUten: 'Skulereglane i fylket',
    velgFylke: 'Vel fylke for å sjå paragrafane om reaksjonar og saksbehandling i skulereglane i fylket.',
    velgFylkeLenke: 'Vel fylke',
    ingenFylke: 'Appen har ikkje skulereglane for {fylke}.',
    lesHele: 'Les heile skulereglane',
    voksne: 'Skulereglane for vaksne i {fylke}',
    skolensRegler: 'Eigne reglar for skulen',
    skolensReglerTekst: 'Skulen kan ha eigne reglar i tillegg til fylket sine. Står dei i Lovdata, finn du dei her.',
    skolenHar: 'Reglar for {skole}',
    skolenHarIkke: 'Appen har ingen eigne reglar for {skole} frå Lovdata. Skulen kan likevel ha reglar som ikkje er kunngjorde som forskrift.',
    velgSkole: 'Vel skule i innstillingane for å sjå dei eigne reglane til skulen, når dei står i Lovdata.',
    privatskole: 'Privatskular',
    videre: 'Vidare',
    aktivitetsplikten: 'Aktivitetsplikta',
    aktivitetspliktenTekst: 'Når ein elev ikkje har det trygt og godt: følgje med, gripe inn, melde frå, undersøkje og setje inn tiltak.',
    ordenOgOppforsel: 'Orden og oppførsel',
    ordenOgOppforselTekst: 'Vurderinga i orden og oppførsel har skulereglane som grunnlag.',
    alleForskrifter: 'Alle lokale forskrifter',
    alleForskrifterTekst: 'Skulereglar, inntak og skulerute for fylket i Regelverk.',
  },
};
