// UI-tekster for modulen Skolemiljø på bokmål. skolemiljo.nn.ts må ha de samme nøklene.

export const skolemiljoNb = {
  tittel: 'Aktivitetsplikt og skoleregler',
  innledning: 'Retten til et trygt og godt skolemiljø, aktivitetsplikten trinn for trinn og skolereglene i fylket og på skolen. Hvert steg viser hvem som har ansvaret, hva som skal dokumenteres og paragrafene i regelverket.',
  rettenOgResultatene: 'Retten og pliktene',
  veivisere: 'Veivisere',
  oppslag: 'Oppslag',
  ikkeFunnet: 'Fant ikke siden.',
  kapittel12: {
    tittel: 'Et trygt og godt skolemiljø',
    kort: 'Et trygt og godt skolemiljø',
    beskrivelse: 'Opplæringslova kapittel 12: retten, skolens plikter, statsforvalteren, det fysiske miljøet og ansvaret.',
    innledning: 'Opplæringslova kapittel 12 gir alle elever rett til et trygt og godt skolemiljø, og skolen plikter å sørge for det. Her er kapittelet paragraf for paragraf, med egne ord.',
    deler: {
      retten: { tittel: 'Retten', paragrafer: '§§ 12-1 og 12-2', tekst: 'Alle elever har rett til et trygt og godt skolemiljø. Elevens opplevelse avgjør.' },
      plikter: { tittel: 'Skolens plikter', paragrafer: '§§ 12-3 til 12-5', tekst: 'Nulltoleranse, forebygging og aktivitetsplikt.' },
      statsforvalteren: { tittel: 'Statsforvalteren', paragrafer: '§ 12-6', tekst: 'Eleven og foreldrene kan melde saken når skolen ikke gjør nok.' },
      fysisk: { tittel: 'Det fysiske miljøet', paragrafer: '§ 12-7', tekst: 'En arbeidsplass som er tilpasset elevens behov.' },
      ansvar: { tittel: 'Ansvar', paragrafer: '§§ 12-8 til 12-10', tekst: 'Tvangsmulkt, straff og omvendt bevisbyrde.' },
    },
    delplikter: 'De fem delpliktene',
    delplikt: { folgeMed: 'Følge med', gripeInn: 'Gripe inn', meldeFra: 'Melde fra', undersoke: 'Undersøke', tiltak: 'Sette inn tiltak' },
    dokumentere: 'Hele veien: dokumentere',
    gangen: 'Veien til statsforvalteren',
    gang: {
      rektor: 'Ta saken opp med rektor',
      uke: 'Vent minst en uke',
      melde: 'Meld saken til statsforvalteren',
      vedtak: 'Vedtak med frist',
      klage: 'Klage til Udir, tvangsmulkt hvis vedtaket ikke følges',
    },
    hengerSammen: 'Henger sammen med',
    veiviser: 'Veiviseren «Aktivitetsplikten»',
    veiviserTekst: 'Steg for steg for den som arbeider på skolen, rektor og eleven.',
    skoleregler: 'Skoleregler',
    skolereglerTekst: 'Reaksjoner, bortvisning og pålagt skolebytte.',
    elevundersokelsen: 'Elevundersøkelsen',
    elevundersokelsenTekst: 'Mobbing og læringsmiljøet på skolen, i fylket og i landet.',
    lesKapittelet: 'Les kapittel 12 i Regelverk',
  },
  skoleregler: {
    tittel: 'Skoleregler',
    kort: 'Skoleregler',
    beskrivelse: 'Reaksjoner, bortvisning og saksbehandling: reglene i loven og i skolereglene i fylket og på skolen.',
    innledning: 'Skolereglene er en forskrift fylkeskommunen gir. Den sier hvilke rettigheter og plikter elevene har, og kan si hvilke tiltak skolen kan bruke når elever bryter reglene, og hvordan sakene behandles. Her står reglene i loven, og paragrafene om reaksjoner og saksbehandling i skolereglene for fylket og skolen du har valgt.',
    iLoven: 'I loven',
    iFylket: 'Skolereglene i {fylke}',
    iFylketUten: 'Skolereglene i fylket',
    velgFylke: 'Velg fylke for å se paragrafene om reaksjoner og saksbehandling i skolereglene i fylket.',
    velgFylkeLenke: 'Velg fylke',
    ingenFylke: 'Appen har ikke skolereglene for {fylke}.',
    lesHele: 'Les hele skolereglene',
    voksne: 'Skolereglene for voksne i {fylke}',
    skolensRegler: 'Skolens egne regler',
    skolensReglerTekst: 'Skolen kan ha egne regler i tillegg til fylkets. Står de i Lovdata, finner du dem her.',
    skolenHar: 'Regler for {skole}',
    skolenHarIkke: 'Appen har ingen egne regler for {skole} fra Lovdata. Skolen kan likevel ha regler som ikke er kunngjort som forskrift.',
    velgSkole: 'Velg skole i innstillingene for å se skolens egne regler, når de står i Lovdata.',
    privatskole: 'Privatskoler',
    videre: 'Videre',
    aktivitetsplikten: 'Aktivitetsplikten',
    aktivitetspliktenTekst: 'Når en elev ikke har det trygt og godt: følge med, gripe inn, melde fra, undersøke og sette inn tiltak.',
    ordenOgOppforsel: 'Orden og oppførsel',
    ordenOgOppforselTekst: 'Vurderingen i orden og oppførsel har skolereglene som grunnlag.',
    alleForskrifter: 'Alle lokale forskrifter',
    alleForskrifterTekst: 'Skoleregler, inntak og skolerute for fylket i Regelverk.',
  },
};
