// UI-tekster for modulen Skolemiljø på nynorsk. Same nøklar som skolemiljo.nb.ts.

export const skolemiljoNn = {
  tittel: 'Skulemiljø',
  innledning: 'Aktivitetsplikta steg for steg, skulereglane i fylket og på skulen, og kva eleven kan gjere når skulen ikkje gjer nok. Kvart steg viser kven som har ansvaret, kva som skal dokumenterast og paragrafane i regelverket.',
  veivisere: 'Vegvisarar',
  oppslag: 'Oppslag',
  ikkeFunnet: 'Fann ikkje sida.',
  skoleregler: {
    tittel: 'Skulereglar',
    kort: 'Skulereglar',
    beskrivelse: 'Reaksjonar, bortvising og saksbehandling: reglane i lova og i skulereglane i fylket og på skulen.',
    innledning: 'Skulereglane er ei forskrift fylkeskommunen gir. Ho seier kva rettar og plikter elevane har, og kan seie kva tiltak skulen kan bruke når elevar bryt reglane, og korleis sakene blir behandla. Her står reglane i lova, og paragrafane om reaksjonar og saksbehandling i skulereglane for fylket og skulen du har valt.',
    iLoven: 'I lova',
    iFylket: 'Skulereglane i {fylke}',
    iFylketUten: 'Skulereglane i fylket',
    velgFylke: 'Vel fylke for å sjå paragrafane om reaksjonar og saksbehandling i skulereglane i fylket.',
    velgFylkeLenke: 'Vel fylke',
    ingenFylke: 'Appen har ikkje skulereglane for {fylke}.',
    lesHele: 'Les heile skulereglane',
    voksne: 'Skulereglane for vaksne i {fylke}',
    skolensRegler: 'Eigne reglar for skulen',
    skolensReglerTekst: 'Skulen kan ha eigne reglar i tillegg til fylket sine. Står dei i Lovdata, finn du dei her.',
    skolenHar: 'Reglar for {skole}',
    skolenHarIkke: 'Appen har ingen eigne reglar for {skole} frå Lovdata. Skulen kan likevel ha reglar som ikkje er kunngjorde som forskrift.',
    velgSkole: 'Vel skule i innstillingane for å sjå dei eigne reglane til skulen, når dei står i Lovdata.',
    privatskole: 'Privatskular',
    videre: 'Vidare',
    aktivitetsplikten: 'Aktivitetsplikta',
    aktivitetspliktenTekst: 'Når ein elev ikkje har det trygt og godt: følgje med, gripe inn, melde frå, undersøkje og setje inn tiltak.',
    ordenOgOppforsel: 'Orden og oppførsel',
    ordenOgOppforselTekst: 'Vurderinga i orden og oppførsel har skulereglane som grunnlag.',
    alleForskrifter: 'Alle lokale forskrifter',
    alleForskrifterTekst: 'Skulereglar, inntak og skulerute for fylket i Regelverk.',
  },
};
