// UI-tekstar for modulen Vidaregåande i tal på nynorsk. Same nøklar som statistikk.nb.ts.

export const statistikkNn = {
  tittel: 'Vidaregåande i tal',
  innledning: 'Søkjarar, elevar, læreplass, gjennomføring, fråvær og eksamen i fylket og i landet, frå statistikkbanken til Udir. Tala blir henta kvar veke.',
  sted: 'Vis tal for',
  landet: 'Heile landet',
  iTall: '{sted} i tal',
  laster: 'Lastar tala …',
  feil: 'Klarte ikkje å laste tala.',
  skjermet: 'Skjerma',
  ingenTall: 'Ingen tal',
  prosent: '{verdi} %',
  dager: '{verdi} dagar',
  endring: '{tegn}{verdi} % frå {aar}',
  poeng: '{tegn}{verdi} prosentpoeng frå {aar}',
  somIFjor: 'som i {aar}',
  landetVerdi: 'landet {verdi}',
  merLenke: 'Meir i Vidaregåande i tal',
  kilde: 'Kjelde: statistikkbanken til Udir. Inneheld data under NLOD.',
  nokkeltall: {
    sokere: 'Søkjarar {aar}',
    sokereUnder: 'per 1. mars',
    elever: 'Elevar {skolear}',
    eleverUnder: 'på {skoler} skular',
    laereplass: 'Fekk læreplass',
    laereplassUnder: 'av søkjarane til læreplass, desember {aar}',
    kontrakter: 'Lærekontraktar',
    kontrakterUnder: 'løpande, {aar}',
  },
  rangering: {
    tittel: 'Fekk læreplass, fylke for fylke',
    tekst: 'Delen søkjarar til læreplass som hadde lærekontrakt i desember {aar}.',
    plass: '{sted} er nr. {plass} av {antall}.',
    plassFylke: '{sted} er nr. {plass} av {antall} fylke på delen søkjarar som fekk læreplass.',
    landet: 'Landet {verdi}',
  },
  program: {
    tittel: 'Søkjarar per utdanningsprogram',
    tekst: 'Skule og læreplass, per 1. mars {aar}. Streken er {fjor}.',
    studieforberedende: 'Studieførebuande',
    yrkesfag: 'Yrkesfag',
    innhold: 'Flest søkjarar: {program} ({antall}).',
  },
  hosten: {
    tittel: 'Læreplass gjennom hausten',
    tekst: 'Delen søkjarar til læreplass med lærekontrakt i august, oktober og desember {aar}.',
    innhold: '{maned}: {verdier}.',
  },
  gjennomforing: {
    tittel: 'Gjennomføring',
    del: 'Gjennomføring og fråvær',
    innhold: 'Gjennomført {gjennomforing}, fråvær {fravaer}.',
    tekst: 'Delen som fullførte og bestod innan fem eller seks år, for elevane som starta på vg1 i {kull}.',
    beregnet: 'Udir oppgir kulla som starta før 2020, på fylka den gongen. Appen reknar dei om til dagens fylke med tala for dei gamle fylka.',
    fagbrev: 'Fag- eller sveinebrev fem år etter start i lære',
    fagbrevTekst: 'Lærlingane som starta i lære i {kull}.',
    ingenFagbrev: 'Ingen tal for {sted}: lærlingane i {kull} starta i eit fylke som seinare er delt.',
  },
  fravaer: {
    tittel: 'Fråvær',
    tekst: 'Median fråvær i dagar, skuleåret {skolear}.',
    total: 'Totalt fråvær',
    vitnemal: 'På vitnemålet',
  },
  eksamen: {
    tittel: 'Skriftleg eksamen',
    tekst: 'Gjennomsnittleg karakter i dei største fellesfaga, skuleåret {skolear}{forelopig}.',
    forelopig: ' (førebelse tal)',
    fag: 'Fag',
    innhold: 'Snittkarakter i {antall} fellesfag.',
    kort: {
      NOR1267: 'Norsk hovudmål, Vg3 studieførebuande',
      NOR1262: 'Norsk, Vg2 yrkesfag',
      ENG1007: 'Engelsk, Vg1 studieførebuande',
      ENG1009: 'Engelsk, Vg1 yrkesfag',
    },
  },
  fylkene: {
    tittel: 'Fylka side om side',
    tekst: 'Dei siste tala for kvart fylke. Fylket du har valt, er markert. Trykk på ein kolonne for å sortere.',
    vis: 'Vis og sorter etter',
    innhold: 'Søkjarar, elevar, læreplass, gjennomføring og fråvær for kvart fylke.',
    fylke: 'Fylke',
    sokere: 'Søkjarar',
    elever: 'Elevar',
    laereplass: 'Læreplass',
    gjennomforing: 'Gjennomført',
    fravaer: 'Fråvær',
  },
  boks: {
    inntak: 'Søkjarar i {sted}',
    inntakTekst: '{antall} søkte vidaregåande i {aar}, {endring}. {laereplass} av dei søkte læreplass.',
    laerling: 'Læreplass i {sted}',
    laerlingTekst: '{andel} av søkjarane til læreplass hadde kontrakt i desember {aar} (landet {landet}). {kontrakter} lærekontraktar løper.',
    fravaer: 'Fråvær i {sted}',
    fravaerTekst: 'Median totalt fråvær var {dager} skuleåret {skolear} (landet {landet}).',
    fravaerSkole: '{skole}: {dager}.',
    eksamen: 'Eksamen i {sted}',
  },
  skolen: {
    tittel: 'Skulen i tal',
    elever: 'Elevar {skolear}',
    fravaer: 'Fråvær {skolear}',
    fravaerVerdi: '{dager}',
    fravaerUnder: 'median',
    elevundersokelsen: 'Elevundersøkinga for skulen',
  },
  forside: {
    sammendrag: '{sokere} søkjarar · {laereplass} fekk læreplass',
    sted: 'Tal for {sted}',
    stripe: 'Fekk læreplass i fylka, desember {aar}.',
    stripePlass: '{sted} er nr. {plass} av {antall}.',
    stripeBeskrivelse: 'Delen søkjarar som fekk læreplass i dei {antall} fylka, frå {min} til {maks}. Landet {landet}.',
    skole: '{antall} elevar på {skole}',
    mer: 'Alle tala i Vidaregåande i tal',
  },
};
