// UI-tekster for modulen Videregående i tall på bokmål. statistikk.nn.ts må ha de samme nøklene.

export const statistikkNb = {
  tittel: 'Videregående i tall',
  innledning: 'Tall om videregående i fylket og i landet, fra Udirs statistikkbank og SSB. Tallene hentes hver uke.',
  sted: 'Vis tall for',
  landet: 'Hele landet',
  /** Inni en setning, f.eks. «Lærerne i videregående i hele landet». */
  landetITekst: 'hele landet',
  iTall: '{sted} i tall',
  laster: 'Laster tallene …',
  feil: 'Klarte ikke å laste tallene.',
  skjermet: 'Skjermet',
  ingenTall: 'Ingen tall',
  prosent: '{verdi} %',
  dager: '{verdi} dager',
  endring: '{tegn}{verdi} % fra {aar}',
  poeng: '{tegn}{verdi} prosentpoeng fra {aar}',
  somIFjor: 'som i {aar}',
  landetVerdi: 'landet {verdi}',
  merLenke: 'Mer i Videregående i tall',
  kilde: 'Kilde: Udirs statistikkbank. Inneholder data under NLOD.',
  kildeBegge: 'Kilde: Udirs statistikkbank (NLOD) og SSB (CC BY 4.0).',
  nokkeltall: {
    sokere: 'Søkere {aar}',
    sokereUnder: 'per 1. mars',
    elever: 'Elever {skolear}',
    eleverUnder: 'på {skoler} skoler',
    laereplass: 'Fikk læreplass',
    laereplassUnder: 'av søkerne til læreplass, desember {aar}',
    kontrakter: 'Lærekontrakter',
    kontrakterUnder: 'løpende, {aar}',
  },
  rangering: {
    tittel: 'Fikk læreplass, fylke for fylke',
    tekst: 'Andelen søkere til læreplass som hadde lærekontrakt i desember {aar}.',
    plass: '{sted} er nr. {plass} av {antall}.',
    plassFylke: '{sted} er nr. {plass} av {antall} fylker på andelen søkere som fikk læreplass.',
    landet: 'Landet {verdi}',
  },
  program: {
    tittel: 'Søkere per utdanningsprogram',
    tekst: 'Skole og læreplass, per 1. mars {aar}. Streken er {fjor}.',
    studieforberedende: 'Studieforberedende',
    yrkesfag: 'Yrkesfag',
    innhold: 'Flest søkere: {program} ({antall}).',
  },
  hosten: {
    tittel: 'Læreplass gjennom høsten',
    tekst: 'Andelen søkere til læreplass med lærekontrakt i august, oktober og desember {aar}.',
    innhold: '{maned}: {verdier}.',
  },
  gjennomforing: {
    tittel: 'Gjennomføring',
    del: 'Gjennomføring og fravær',
    innhold: 'Gjennomført {gjennomforing}, fravær {fravaer}.',
    tekst: 'Andelen som fullførte og besto innen fem eller seks år, for elevene som startet på vg1 i {kull}.',
    beregnet: 'Udir oppgir kullene som startet før 2020, på fylkene den gang. Appen regner dem om til dagens fylker med tallene for de gamle fylkene.',
    fagbrev: 'Fag- eller svennebrev fem år etter start i lære',
    fagbrevTekst: 'Lærlingene som startet i lære i {kull}.',
    ingenFagbrev: 'Ingen tall for {sted}: lærlingene i {kull} startet i et fylke som senere er delt.',
  },
  fravaer: {
    tittel: 'Fravær',
    tekst: 'Median fravær i dager, skoleåret {skolear}.',
    total: 'Totalt fravær',
    vitnemal: 'På vitnemålet',
  },
  eksamen: {
    tittel: 'Skriftlig eksamen',
    tekst: 'Gjennomsnittlig karakter i de største fellesfagene, skoleåret {skolear}{forelopig}.',
    forelopig: ' (foreløpige tall)',
    fag: 'Fag',
    innhold: 'Snittkarakter i {antall} fellesfag.',
    kort: {
      NOR1267: 'Norsk hovedmål, Vg3 studieforberedende',
      NOR1262: 'Norsk, Vg2 yrkesfag',
      ENG1007: 'Engelsk, Vg1 studieforberedende',
      ENG1009: 'Engelsk, Vg1 yrkesfag',
    },
  },
  fylkene: {
    tittel: 'Fylkene side om side',
    tekst: 'De siste tallene for hvert fylke. Fylket du har valgt, er markert. Trykk på en kolonne for å sortere.',
    vis: 'Vis og sorter etter',
    innhold: 'Søkere, elever, læreplass, gjennomføring og fravær for hvert fylke.',
    fylke: 'Fylke',
    sokere: 'Søkere',
    elever: 'Elever',
    laereplass: 'Læreplass',
    gjennomforing: 'Gjennomført',
    fravaer: 'Fravær',
  },
  boks: {
    inntak: 'Søkere i {sted}',
    inntakTekst: '{antall} søkte videregående i {aar}, {endring}. {laereplass} av dem søkte læreplass.',
    laerling: 'Læreplass i {sted}',
    laerlingTekst: '{andel} av søkerne til læreplass hadde kontrakt i desember {aar} (landet {landet}). {kontrakter} lærekontrakter løper.',
    fravaer: 'Fravær i {sted}',
    fravaerTekst: 'Median totalt fravær var {dager} skoleåret {skolear} (landet {landet}).',
    fravaerSkole: '{skole}: {dager}.',
    eksamen: 'Eksamen i {sted}',
  },
  skolen: {
    tittel: 'Skolen i tall',
    elever: 'Elever {skolear}',
    fravaer: 'Fravær {skolear}',
    fravaerVerdi: '{dager}',
    fravaerUnder: 'median',
    elevundersokelsen: 'Elevundersøkelsen for skolen',
  },
  forside: {
    sammendrag: '{sokere} søkere · {laereplass} fikk læreplass',
    sted: 'Tall for {sted}',
    stedLandet: 'Tall for hele landet',
    velgFylke: 'Velg fylke for å se hvor fylket ditt ligger blant fylkene',
    stripe: 'Fikk læreplass i fylkene, desember {aar}.',
    stripePlass: '{sted} er nr. {plass} av {antall}.',
    stripeBeskrivelse: 'Andelen søkere som fikk læreplass i de {antall} fylkene, fra {min} til {maks}. Landet {landet}.',
    skole: '{antall} elever på {skole}',
    mer: 'Alle tallene i Videregående i tall',
  },
  // Videregående i tall med tallene fra SSB (eier 08.10.2026, avgjørelse 090).
  utforsk: 'Utforsk tallene',
  merke: 'Videregående i tall',
  tema: {
    faner: 'Temaene i Videregående i tall',
    ungdom: { navn: 'Ungdom og søkere', kort: 'Ungdom', tekst: 'Ungdomskullene, søkerne og grunnskolepoengene' },
    skolen: { navn: 'Skolen', kort: 'Skolen', tekst: 'Lærerne, pengene, fraværet og eksamen' },
    fullforing: { navn: 'Læreplass og fullføring', kort: 'Fullføring', tekst: 'Læreplass, gjennomføring og unge utenfor arbeid og utdanning' },
    kull: '16–18-åringer til {aar}',
    poeng: 'grunnskolepoeng',
    laerere60: 'av lærerne er 60+',
    fravaer: 'fravær per elev',
    fullforer: 'fullfører',
    utenfor: 'unge utenfor',
  },
  kortFortalt: {
    tittel: 'Kort fortalt',
    kull: '16–18-åringer i {sted} fra {fra} til {til} ({naa} → {da})',
    sokere: 'søkte videregående i {aar}, flest til {program}',
    deltakelse: 'av 16–18-åringene er elev, lærling eller lærekandidat ({aar})',
    elever: 'elever i videregående skole, skoleåret {skolear}',
    laerere60: 'av de {antall} lærerne er 60 år eller eldre ({aar})',
    perElev: 'per elev til utdanning i skole ({aar})',
    laereplass: 'av søkerne til læreplass hadde kontrakt i desember {aar}',
    gjennomforing: 'fullførte og besto innen fem eller seks år (startet på vg1 i {kull})',
    utenfor: 'av 15–29-åringene er verken i arbeid, utdanning eller opplæring ({aar})',
  },
  om: {
    tittel: 'Hvor tallene kommer fra',
    udir: 'Søkere, elever, læreplass, gjennomføring, fravær og eksamen. Tallene gjelder skolen eleven går på.',
    ssb: 'Befolkningen, ungdomskullene, lærerne, pengene og unge utenfor arbeid og utdanning. Tallene gjelder fylket der folk bor.',
    oppdatering: 'Tallene hentes hver uke. Udir og SSB publiserer de fleste tallene en gang i året.',
  },
  ssb: {
    merke: 'SSB',
    udirMerke: 'Udir',
    kilde: 'Kilde: SSB.',
    kildeAar: 'Kilde: SSB, {aar}.',
    kildeboks: 'Statistikkbanken: ungdomskull, unge utenfor, grunnskolepoeng, KOSTRA, lærere og deltakelse',
    kr: '{verdi} kr',
    tusenKr: '{verdi} 000 kr',
    registrert: 'Registrert',
    framskrevet: 'Framskrevet',
    landet: 'Hele landet {verdi}',
    kull: {
      tittel: 'Ungdomskullene',
      figur: '16–18-åringene nå og framover',
      tekst: 'Antall 16–18-åringer i {sted}, registrert {fra}–{reg} og framskrevet til {til} (SSBs hovedalternativ, stiplet).',
      endring: 'fra {fra} til {til}',
      landet: 'hele landet',
      sammePeriode: 'samme periode',
      fylkene: 'Endring til {til}, fylke for fylke',
      innhold: '{endring} % fra {fra} til {til}',
      merknad: 'Tabell 07459 og 14746. Framskrivingen blir justert når SSB lager en ny.',
      etikett: '16–18-åringer i {sted}, {fra}–{til}',
    },
    utenfor: {
      tittel: 'Utenfor arbeid og utdanning',
      figur: 'Unge utenfor arbeid og utdanning',
      tekst: 'Andelen 15–29-åringer i {sted} som verken er i arbeid, utdanning eller opplæring.',
      forelopig: 'Tallene for {aar} er foreløpige.',
      personer: '{antall} personer, {aar}',
      alder: 'Etter alder, {aar}',
      aldersgruppe: '{fra}–{til} år',
      innvandrere: 'Innvandrere',
      ovrige: 'Alle andre',
      merknad: 'Tabell 13563 og 13556. Fylket der de unge bor. Serien har et brudd fra 2020 til 2021.',
      innhold: '{verdi} av 15–29-åringene',
      etikett: 'Andel utenfor arbeid og utdanning, {sted} og landet, {fra}–{til}',
    },
    poeng: {
      tittel: 'Grunnskolepoeng',
      tekst: 'Gjennomsnittlige grunnskolepoeng for elevene som gikk ut av 10. trinn våren {aar}. Poengene avgjør inntaket der det er konkurranse om plassene.',
      jenter: 'jenter',
      gutter: 'gutter',
      fraFjor: '{endring} fra {aar}',
      snitt: 'snittet våren {aar}',
      merknad: 'Tabell 07495. Poengene for 2020–2022 bygger bare på standpunkt.',
      etikett: 'Grunnskolepoeng, fylke for fylke, {aar}',
      innhold: '{verdi} i snitt',
    },
    deltakelse: {
      tittel: 'Hvem går i videregående',
      figur: '16–18-åringer i videregående',
      tekst: 'Andelen av 16–18-åringene i {sted} som var elev, lærling eller lærekandidat høsten {aar}.',
      hoved: 'i videregående opplæring',
      visning: 'Vis tallene',
      fylkene: 'Fylkene',
      bakgrunn: 'Etter bakgrunn',
      med: 'Med innvandringsbakgrunn',
      ovrige: 'Alle andre',
      landet: 'For hele landet: innvandrere {innvandrere} og norskfødte med innvandrerforeldre {norskfodte}.',
      merknad: 'Tabell 12274 og 09382. Fylket der ungdommene bor.',
      etikett: 'Andel 16–18-åringer i videregående, fylke for fylke, {aar}',
      innhold: '{verdi} går i videregående',
    },
    laerere: {
      tittel: 'Lærerne',
      figur: 'Lærerne i videregående',
      tekst: 'Lærere i videregående skole i {sted}, november {aar}, etter alder.',
      laerere: 'lærere',
      kvinner: '{verdi} kvinner',
      over60: 'er 60 år eller eldre',
      pedagogisk: 'har pedagogisk utdanning',
      under30: 'Under 30',
      fra30: '30–49',
      fra50: '50–59',
      fra60: '60 og eldre',
      alder: 'Lærerne etter alder',
      utvikling: 'Andelen 60 år og eldre, {fra}–{til}',
      merknad: 'Tabell 12091 og 12697. Fylket lærerne arbeider i.',
      innhold: '{antall} lærere, {andel} er 60 år eller eldre',
      etikett: 'Andel lærere 60 år og eldre, {sted} og landet, {fra}–{til}',
    },
    kostnad: {
      tittel: 'Penger per elev',
      figur: 'Hva fylkeskommunen bruker per elev',
      tekst: 'Netto driftsutgifter til utdanning i skole per elev i {aar}, uten gjesteelever.',
      perElev: 'per elev',
      perLaerer: 'elever per lærerårsverk',
      merknad: 'KOSTRA, tabell 12399 og 12609. Tallene for et år kan bli justert i juni året etter.',
      innhold: '{verdi} per elev',
      etikett: 'Utgifter per elev, fylke for fylke, {aar}',
    },
    boks: {
      inntak: 'Søkere og ungdomskull i {sted}',
      kull: '16–18-åringene: {naa} i {fra} og {da} i {til} ({endring} %).',
      poeng: 'Grunnskolepoeng i {sted}',
      utenfor: 'Unge utenfor arbeid og utdanning i {sted}',
      utenforEtikett: 'av {fra}–{til}-åringene',
      laerere: 'Lærerne i videregående i {sted}',
    },
  },
};
