// UI-tekstar for modulen Vidaregåande i tal på nynorsk. Same nøklar som statistikk.nb.ts.

export const statistikkNn = {
  tittel: 'Vidaregåande i tal',
  innledning: 'Tal om vidaregåande i fylket og i landet, frå statistikkbanken til Udir og SSB. Tala blir henta kvar veke.',
  sted: 'Vis tal for',
  landet: 'Heile landet',
  iTall: '{sted} i tal',
  laster: 'Lastar tala …',
  feil: 'Klarte ikkje å laste tala.',
  skjermet: 'Skjerma',
  ingenTall: 'Ingen tal',
  prosent: '{verdi} %',
  dager: '{verdi} dagar',
  endring: '{tegn}{verdi} % frå {aar}',
  poeng: '{tegn}{verdi} prosentpoeng frå {aar}',
  somIFjor: 'som i {aar}',
  landetVerdi: 'landet {verdi}',
  merLenke: 'Meir i Vidaregåande i tal',
  kilde: 'Kjelde: statistikkbanken til Udir. Inneheld data under NLOD.',
  kildeBegge: 'Kjelde: statistikkbanken til Udir (NLOD) og SSB (CC BY 4.0).',
  nokkeltall: {
    sokere: 'Søkjarar {aar}',
    sokereUnder: 'per 1. mars',
    elever: 'Elevar {skolear}',
    eleverUnder: 'på {skoler} skular',
    laereplass: 'Fekk læreplass',
    laereplassUnder: 'av søkjarane til læreplass, desember {aar}',
    kontrakter: 'Lærekontraktar',
    kontrakterUnder: 'løpande, {aar}',
  },
  rangering: {
    tittel: 'Fekk læreplass, fylke for fylke',
    tekst: 'Delen søkjarar til læreplass som hadde lærekontrakt i desember {aar}.',
    plass: '{sted} er nr. {plass} av {antall}.',
    plassFylke: '{sted} er nr. {plass} av {antall} fylke på delen søkjarar som fekk læreplass.',
    landet: 'Landet {verdi}',
  },
  program: {
    tittel: 'Søkjarar per utdanningsprogram',
    tekst: 'Skule og læreplass, per 1. mars {aar}. Streken er {fjor}.',
    studieforberedende: 'Studieførebuande',
    yrkesfag: 'Yrkesfag',
    innhold: 'Flest søkjarar: {program} ({antall}).',
  },
  hosten: {
    tittel: 'Læreplass gjennom hausten',
    tekst: 'Delen søkjarar til læreplass med lærekontrakt i august, oktober og desember {aar}.',
    innhold: '{maned}: {verdier}.',
  },
  gjennomforing: {
    tittel: 'Gjennomføring',
    del: 'Gjennomføring og fråvær',
    innhold: 'Gjennomført {gjennomforing}, fråvær {fravaer}.',
    tekst: 'Delen som fullførte og bestod innan fem eller seks år, for elevane som starta på vg1 i {kull}.',
    beregnet: 'Udir oppgir kulla som starta før 2020, på fylka den gongen. Appen reknar dei om til dagens fylke med tala for dei gamle fylka.',
    fagbrev: 'Fag- eller sveinebrev fem år etter start i lære',
    fagbrevTekst: 'Lærlingane som starta i lære i {kull}.',
    ingenFagbrev: 'Ingen tal for {sted}: lærlingane i {kull} starta i eit fylke som seinare er delt.',
  },
  fravaer: {
    tittel: 'Fråvær',
    tekst: 'Median fråvær i dagar, skuleåret {skolear}.',
    total: 'Totalt fråvær',
    vitnemal: 'På vitnemålet',
  },
  eksamen: {
    tittel: 'Skriftleg eksamen',
    tekst: 'Gjennomsnittleg karakter i dei største fellesfaga, skuleåret {skolear}{forelopig}.',
    forelopig: ' (førebelse tal)',
    fag: 'Fag',
    innhold: 'Snittkarakter i {antall} fellesfag.',
    kort: {
      NOR1267: 'Norsk hovudmål, Vg3 studieførebuande',
      NOR1262: 'Norsk, Vg2 yrkesfag',
      ENG1007: 'Engelsk, Vg1 studieførebuande',
      ENG1009: 'Engelsk, Vg1 yrkesfag',
    },
  },
  fylkene: {
    tittel: 'Fylka side om side',
    tekst: 'Dei siste tala for kvart fylke. Fylket du har valt, er markert. Trykk på ein kolonne for å sortere.',
    vis: 'Vis og sorter etter',
    innhold: 'Søkjarar, elevar, læreplass, gjennomføring og fråvær for kvart fylke.',
    fylke: 'Fylke',
    sokere: 'Søkjarar',
    elever: 'Elevar',
    laereplass: 'Læreplass',
    gjennomforing: 'Gjennomført',
    fravaer: 'Fråvær',
  },
  boks: {
    inntak: 'Søkjarar i {sted}',
    inntakTekst: '{antall} søkte vidaregåande i {aar}, {endring}. {laereplass} av dei søkte læreplass.',
    laerling: 'Læreplass i {sted}',
    laerlingTekst: '{andel} av søkjarane til læreplass hadde kontrakt i desember {aar} (landet {landet}). {kontrakter} lærekontraktar løper.',
    fravaer: 'Fråvær i {sted}',
    fravaerTekst: 'Median totalt fråvær var {dager} skuleåret {skolear} (landet {landet}).',
    fravaerSkole: '{skole}: {dager}.',
    eksamen: 'Eksamen i {sted}',
  },
  skolen: {
    tittel: 'Skulen i tal',
    elever: 'Elevar {skolear}',
    fravaer: 'Fråvær {skolear}',
    fravaerVerdi: '{dager}',
    fravaerUnder: 'median',
    elevundersokelsen: 'Elevundersøkinga for skulen',
  },
  forside: {
    sammendrag: '{sokere} søkjarar · {laereplass} fekk læreplass',
    sted: 'Tal for {sted}',
    stedLandet: 'Tal for heile landet',
    velgFylke: 'Vel fylke for å sjå kvar fylket ditt ligg blant fylka',
    stripe: 'Fekk læreplass i fylka, desember {aar}.',
    stripePlass: '{sted} er nr. {plass} av {antall}.',
    stripeBeskrivelse: 'Delen søkjarar som fekk læreplass i dei {antall} fylka, frå {min} til {maks}. Landet {landet}.',
    skole: '{antall} elevar på {skole}',
    mer: 'Alle tala i Vidaregåande i tal',
  },
  // Vidaregåande i tal med tala frå SSB (eigar 08.10.2026, avgjerd 090).
  utforsk: 'Utforsk tala',
  merke: 'Vidaregåande i tal',
  tema: {
    faner: 'Tema i Vidaregåande i tal',
    ungdom: { navn: 'Ungdom og søkjarar', kort: 'Ungdom', tekst: 'Ungdomskulla, søkjarane og grunnskulepoenga' },
    skolen: { navn: 'Skulen', kort: 'Skulen', tekst: 'Lærarane, pengane, fråværet og eksamen' },
    fullforing: { navn: 'Læreplass og fullføring', kort: 'Fullføring', tekst: 'Læreplass, gjennomføring og unge utanfor arbeid og utdanning' },
    kull: '16–18-åringar til {aar}',
    poeng: 'grunnskulepoeng',
    laerere60: 'av lærarane er 60+',
    fravaer: 'fråvær per elev',
    fullforer: 'fullfører',
    utenfor: 'unge utanfor',
  },
  kortFortalt: {
    tittel: 'Kort fortalt',
    kull: '16–18-åringar i {sted} frå {fra} til {til} ({naa} → {da})',
    sokere: 'søkte vidaregåande i {aar}, flest til {program}',
    deltakelse: 'av 16–18-åringane er elev, lærling eller lærekandidat ({aar})',
    elever: 'elevar i vidaregåande skule, skuleåret {skolear}',
    laerere60: 'av dei {antall} lærarane er 60 år eller eldre ({aar})',
    perElev: 'per elev til utdanning i skule ({aar})',
    laereplass: 'av søkjarane til læreplass hadde kontrakt i desember {aar}',
    gjennomforing: 'fullførte og bestod innan fem eller seks år (byrja på vg1 i {kull})',
    utenfor: 'av 15–29-åringane er verken i arbeid, utdanning eller opplæring ({aar})',
  },
  om: {
    tittel: 'Kvar tala kjem frå',
    udir: 'Søkjarar, elevar, læreplass, gjennomføring, fråvær og eksamen. Tala gjeld skulen eleven går på.',
    ssb: 'Befolkninga, ungdomskulla, lærarane, pengane og unge utanfor arbeid og utdanning. Tala gjeld fylket der folk bur.',
    oppdatering: 'Tala blir henta kvar veke. Udir og SSB publiserer dei fleste tala ein gong i året.',
  },
  ssb: {
    merke: 'SSB',
    udirMerke: 'Udir',
    kilde: 'Kjelde: SSB.',
    kildeAar: 'Kjelde: SSB, {aar}.',
    kildeboks: 'Statistikkbanken: ungdomskull, unge utanfor, grunnskulepoeng, KOSTRA, lærarar og deltaking',
    kr: '{verdi} kr',
    tusenKr: '{verdi} 000 kr',
    registrert: 'Registrert',
    framskrevet: 'Framskrive',
    landet: 'Heile landet {verdi}',
    kull: {
      tittel: 'Ungdomskulla',
      figur: '16–18-åringane no og framover',
      tekst: 'Talet på 16–18-åringar i {sted}, registrert {fra}–{reg} og framskrive til {til} (hovudalternativet til SSB, stipla).',
      endring: 'frå {fra} til {til}',
      landet: 'heile landet',
      sammePeriode: 'same periode',
      fylkene: 'Endring til {til}, fylke for fylke',
      innhold: '{endring} % frå {fra} til {til}',
      merknad: 'Tabell 07459 og 14746. Framskrivinga blir justert når SSB lagar ei ny.',
      etikett: '16–18-åringar i {sted}, {fra}–{til}',
    },
    utenfor: {
      tittel: 'Utanfor arbeid og utdanning',
      figur: 'Unge utanfor arbeid og utdanning',
      tekst: 'Delen 15–29-åringar i {sted} som verken er i arbeid, utdanning eller opplæring.',
      forelopig: 'Tala for {aar} er førebelse.',
      personer: '{antall} personar, {aar}',
      alder: 'Etter alder, {aar}',
      aldersgruppe: '{fra}–{til} år',
      innvandrere: 'Innvandrarar',
      ovrige: 'Alle andre',
      merknad: 'Tabell 13563 og 13556. Fylket der dei unge bur. Serien har eit brot frå 2020 til 2021.',
      innhold: '{verdi} av 15–29-åringane',
      etikett: 'Del utanfor arbeid og utdanning, {sted} og landet, {fra}–{til}',
    },
    poeng: {
      tittel: 'Grunnskulepoeng',
      tekst: 'Gjennomsnittlege grunnskulepoeng for elevane som gjekk ut av 10. trinn våren {aar}. Poenga avgjer inntaket der det er konkurranse om plassane.',
      jenter: 'jenter',
      gutter: 'gutar',
      fraFjor: '{endring} frå {aar}',
      snitt: 'snittet våren {aar}',
      merknad: 'Tabell 07495. Poenga for 2020–2022 byggjer berre på standpunkt.',
      etikett: 'Grunnskulepoeng, fylke for fylke, {aar}',
      innhold: '{verdi} i snitt',
    },
    deltakelse: {
      tittel: 'Kven går i vidaregåande',
      figur: '16–18-åringar i vidaregåande',
      tekst: 'Delen av 16–18-åringane i {sted} som var elev, lærling eller lærekandidat hausten {aar}.',
      hoved: 'i vidaregåande opplæring',
      visning: 'Vis tala',
      fylkene: 'Fylka',
      bakgrunn: 'Etter bakgrunn',
      med: 'Med innvandringsbakgrunn',
      ovrige: 'Alle andre',
      landet: 'For heile landet: innvandrarar {innvandrere} og norskfødde med innvandrarforeldre {norskfodte}.',
      merknad: 'Tabell 12274 og 09382. Fylket der ungdommane bur.',
      etikett: 'Del 16–18-åringar i vidaregåande, fylke for fylke, {aar}',
      innhold: '{verdi} går i vidaregåande',
    },
    laerere: {
      tittel: 'Lærarane',
      figur: 'Lærarane i vidaregåande',
      tekst: 'Lærarar i vidaregåande skule i {sted}, november {aar}, etter alder.',
      laerere: 'lærarar',
      kvinner: '{verdi} kvinner',
      over60: 'er 60 år eller eldre',
      pedagogisk: 'har pedagogisk utdanning',
      under30: 'Under 30',
      fra30: '30–49',
      fra50: '50–59',
      fra60: '60 og eldre',
      alder: 'Lærarane etter alder',
      utvikling: 'Delen 60 år og eldre, {fra}–{til}',
      merknad: 'Tabell 12091 og 12697. Fylket lærarane arbeider i.',
      innhold: '{antall} lærarar, {andel} er 60 år eller eldre',
      etikett: 'Del lærarar 60 år og eldre, {sted} og landet, {fra}–{til}',
    },
    kostnad: {
      tittel: 'Pengar per elev',
      figur: 'Kva fylkeskommunen bruker per elev',
      tekst: 'Netto driftsutgifter til utdanning i skule per elev i {aar}, utan gjesteelevar.',
      perElev: 'per elev',
      perLaerer: 'elevar per lærarårsverk',
      merknad: 'KOSTRA, tabell 12399 og 12609. Tala for eit år kan bli justerte i juni året etter.',
      innhold: '{verdi} per elev',
      etikett: 'Utgifter per elev, fylke for fylke, {aar}',
    },
    boks: {
      inntak: 'Søkjarar og ungdomskull i {sted}',
      kull: '16–18-åringane: {naa} i {fra} og {da} i {til} ({endring} %).',
      poeng: 'Grunnskulepoeng i {sted}',
      utenfor: 'Unge utanfor arbeid og utdanning i {sted}',
      utenforEtikett: 'av {fra}–{til}-åringane',
      laerere: 'Lærarane i vidaregåande i {sted}',
    },
  },
};
