// UI-tekster for modulen Videregående i tall på bokmål. statistikk.nn.ts må ha de samme nøklene.

export const statistikkNb = {
  tittel: 'Videregående i tall',
  innledning: 'Søkere, elever, læreplass, gjennomføring, fravær og eksamen i fylket og i landet, fra Udirs statistikkbank. Tallene hentes hver uke.',
  sted: 'Vis tall for',
  landet: 'Hele landet',
  iTall: '{sted} i tall',
  laster: 'Laster tallene …',
  feil: 'Klarte ikke å laste tallene.',
  skjermet: 'Skjermet',
  ingenTall: 'Ingen tall',
  prosent: '{verdi} %',
  dager: '{verdi} dager',
  endring: '{tegn}{verdi} % fra {aar}',
  poeng: '{tegn}{verdi} prosentpoeng fra {aar}',
  somIFjor: 'som i {aar}',
  landetVerdi: 'landet {verdi}',
  merLenke: 'Mer i Videregående i tall',
  kilde: 'Kilde: Udirs statistikkbank. Inneholder data under NLOD.',
  nokkeltall: {
    sokere: 'Søkere {aar}',
    sokereUnder: 'per 1. mars',
    elever: 'Elever {skolear}',
    eleverUnder: 'på {skoler} skoler',
    laereplass: 'Fikk læreplass',
    laereplassUnder: 'av søkerne til læreplass, desember {aar}',
    kontrakter: 'Lærekontrakter',
    kontrakterUnder: 'løpende, {aar}',
  },
  rangering: {
    tittel: 'Fikk læreplass, fylke for fylke',
    tekst: 'Andelen søkere til læreplass som hadde lærekontrakt i desember {aar}.',
    plass: '{sted} er nr. {plass} av {antall}.',
    plassFylke: '{sted} er nr. {plass} av {antall} fylker på andelen søkere som fikk læreplass.',
    landet: 'Landet {verdi}',
  },
  program: {
    tittel: 'Søkere per utdanningsprogram',
    tekst: 'Skole og læreplass, per 1. mars {aar}. Streken er {fjor}.',
    studieforberedende: 'Studieforberedende',
    yrkesfag: 'Yrkesfag',
    innhold: 'Flest søkere: {program} ({antall}).',
  },
  hosten: {
    tittel: 'Læreplass gjennom høsten',
    tekst: 'Andelen søkere til læreplass med lærekontrakt i august, oktober og desember {aar}.',
    innhold: '{maned}: {verdier}.',
  },
  gjennomforing: {
    tittel: 'Gjennomføring',
    del: 'Gjennomføring og fravær',
    innhold: 'Gjennomført {gjennomforing}, fravær {fravaer}.',
    tekst: 'Andelen som fullførte og besto innen fem eller seks år, for elevene som startet på vg1 i {kull}.',
    beregnet: 'Udir oppgir kullene som startet før 2020, på fylkene den gang. Appen regner dem om til dagens fylker med tallene for de gamle fylkene.',
    fagbrev: 'Fag- eller svennebrev fem år etter start i lære',
    fagbrevTekst: 'Lærlingene som startet i lære i {kull}.',
    ingenFagbrev: 'Ingen tall for {sted}: lærlingene i {kull} startet i et fylke som senere er delt.',
  },
  fravaer: {
    tittel: 'Fravær',
    tekst: 'Median fravær i dager, skoleåret {skolear}.',
    total: 'Totalt fravær',
    vitnemal: 'På vitnemålet',
  },
  eksamen: {
    tittel: 'Skriftlig eksamen',
    tekst: 'Gjennomsnittlig karakter i de største fellesfagene, skoleåret {skolear}{forelopig}.',
    forelopig: ' (foreløpige tall)',
    fag: 'Fag',
    innhold: 'Snittkarakter i {antall} fellesfag.',
    kort: {
      NOR1267: 'Norsk hovedmål, Vg3 studieforberedende',
      NOR1262: 'Norsk, Vg2 yrkesfag',
      ENG1007: 'Engelsk, Vg1 studieforberedende',
      ENG1009: 'Engelsk, Vg1 yrkesfag',
    },
  },
  fylkene: {
    tittel: 'Fylkene side om side',
    tekst: 'De siste tallene for hvert fylke. Fylket du har valgt, er markert. Trykk på en kolonne for å sortere.',
    vis: 'Vis og sorter etter',
    innhold: 'Søkere, elever, læreplass, gjennomføring og fravær for hvert fylke.',
    fylke: 'Fylke',
    sokere: 'Søkere',
    elever: 'Elever',
    laereplass: 'Læreplass',
    gjennomforing: 'Gjennomført',
    fravaer: 'Fravær',
  },
  boks: {
    inntak: 'Søkere i {sted}',
    inntakTekst: '{antall} søkte videregående i {aar}, {endring}. {laereplass} av dem søkte læreplass.',
    laerling: 'Læreplass i {sted}',
    laerlingTekst: '{andel} av søkerne til læreplass hadde kontrakt i desember {aar} (landet {landet}). {kontrakter} lærekontrakter løper.',
    fravaer: 'Fravær i {sted}',
    fravaerTekst: 'Median totalt fravær var {dager} skoleåret {skolear} (landet {landet}).',
    fravaerSkole: '{skole}: {dager}.',
    eksamen: 'Eksamen i {sted}',
  },
  skolen: {
    tittel: 'Skolen i tall',
    elever: 'Elever {skolear}',
    fravaer: 'Fravær {skolear}',
    fravaerVerdi: '{dager}',
    fravaerUnder: 'median',
    elevundersokelsen: 'Elevundersøkelsen for skolen',
  },
  forside: {
    sammendrag: '{sokere} søkere · {laereplass} fikk læreplass',
    sokere: 'Søkere {aar}',
    laereplass: 'Fikk læreplass, desember {aar}',
    plass: 'Nr. {plass} av {antall} fylker',
    laereplassLandet: 'Av søkerne til læreplass',
    elever: 'Elever {skolear}',
    eleverUnder: 'På {skoler} skoler',
    skoleUnder: 'Elever {skolear}',
  },
};
