// UI-tekster for modulen Vurdering på bokmål. vurdering.nn.ts må ha de samme nøklene.

export const vurderingNb = {
  tittel: 'Vurdering',
  innledning: 'Vurdering i fag og i orden og oppførsel i videregående opplæring, etter opplæringsforskrifta kapittel 9 og 10: hva karakteren bygger på, underveis- og sluttvurdering, fravær, eksamen, prøvene i fag- og yrkesopplæringen og klage på karakter.',
  delFag: 'Vurdering i fag',
  delFravaer: 'Fravær',
  delOrden: 'Orden og oppførsel',
  delEksamen: 'Eksamen og klage',
  // Boksen på forsiden (eier 06.10.2026).
  eksamenOgKlage: { tittel: 'Eksamen og klage', beskrivelse: 'Trekk, oppmelding, sensur og tilrettelegging, og klage på karakter.' },
  ikkeFunnet: 'Fant ikke veiviseren.',
  underveisSlutt: {
    tittel: 'Underveis- og sluttvurdering',
    kort: 'Underveis- og sluttvurdering',
    beskrivelse: 'Hvordan kompetansemålene vurderes, og reglene for underveis- og sluttvurdering, med vurderingsteksten i læreplanen for faget.',
    innledning: 'All vurdering før opplæringen i faget er slutt, er underveisvurdering. Sluttvurderingen er standpunkt, eksamen og prøvene i fag- og yrkesopplæringen. Grunnlaget er alltid kompetansemålene i læreplanen.',
    skolearet: 'Skoleåret i et fag som avsluttes',
    figurTittel: 'Skoleåret med underveisvurdering, halvårsvurdering, eksamen og standpunkt',
    underveis: 'Underveisvurdering',
    heleAaret: 'hele året',
    halvaar: 'Halvårsvurdering',
    eksamen: 'Eksamen',
    standpunkt: 'Standpunkt',
    maneder: 'aug,sep,okt,nov,des,jan,feb,mar,apr,mai,jun',
    tegnUnderveis: 'Underveisvurdering, hele året',
    tegnHalvaar: 'Halvårsvurdering, midt i perioden',
    tegnEksamen: 'Eksamen, datoene fra Udir',
    tegnStandpunkt: 'Standpunkt, senest dagen før sensur',
    forskjellen: 'Forskjellen',
    // Med mykt bindestrek, så ordet kan deles på smal skjerm.
    venstre: 'Underveis\u00advurdering',
    hoyre: 'Slutt\u00advurdering',
    prinsipper: 'Slik vurderes kompetansemålene',
    iLaereplanen: 'I læreplanen for faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'For eksempel «engelsk vg1» eller «ENG1007»',
    velgFag: 'Velg et fag for å se hva læreplanen sier om underveis- og standpunktvurdering.',
    ingenFag: 'Ingen fag passer søket.',
    underveisTekst: 'Underveisvurdering',
    standpunktTekst: 'Standpunktvurdering',
    ingenTekst: 'Læreplanen har ingen egen tekst om vurdering for dette faget.',
    tilFagarket: 'Hele læreplanen på fagarket: {fag}',
    fraGrep: 'Fra læreplanen {kode} i Grep.',
    annetFag: 'Velg et annet fag',
    lasterFeil: 'Læreplanen kunne ikke lastes. Prøv igjen.',
  },
  orden: {
    tittel: 'Orden og oppførsel',
    kort: 'Orden og oppførsel',
    beskrivelse: 'Skolereglene, karakterene G, Ng og Lg, varsel, standpunkt og klage.',
    innledning: 'Orden og oppførsel vurderes for seg, med skolereglene som grunnlag. Det skal ikke trekkes inn i vurderingen i fag, og kompetanse i fag skal ikke trekkes inn her.',
    iFylket: 'I {fylke}',
  },
  fravaer: {
    tittel: 'Fraværsgrensen',
    kort: 'Fraværsgrensen',
    beskrivelse: 'Hvor mye fravær eleven kan ha i et fag, i timer og økter, med rektors skjønn opp til 15 prosent og en sjekk av fraværet.',
    innledning: 'Eleven kan ikke ha mer enn 10 prosent fravær i et fag for å få standpunktkarakter. Velg faget eller skriv inn årstimetallet, og velg hvor lange øktene er.',
    faget: 'Faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'For eksempel «engelsk vg1» eller «ENG1007»',
    ingenFag: 'Ingen fag med årstimetall passer søket.',
    annetFag: 'Velg et annet fag',
    ellerTimer: 'Eller skriv inn årstimetallet',
    timer: 'Årstimetall',
    timerHjelp: 'Klokketimer i faget det skoleåret. Har fylket et eget, høyere timetall, eller får eleven mer opplæring med færre timer, skriv inn det tallet.',
    fraGrep: '{timer} timer i Grep',
    endreTimer: 'Skriv inn et annet timetall',
    brukGrep: 'Bruk timene fra Grep',
    okter: 'Øktene',
    oktlengde: 'Lengde på øktene',
    minutter: '{antall} min',
    annen: 'Annen',
    annenEtikett: 'Minutter per økt',
    heleAaret: 'Hele årstimetallet brukes alltid, også når eleven begynner sent eller bytter fag. I et nytt fag starter fraværet på null.',
    timerEnhet: '{antall} timer',
    oktEnhet: '{antall} økter',
    resultat: {
      tittel: 'Fraværsgrensen',
      tom: 'Velg et fag eller skriv inn årstimetallet.',
      sammendrag: 'Innenfor med {innenfor}. Over med {over}.',
      grense: '10 %',
      skjonn: '15 %',
      innenfor: 'Innenfor med ({enhet})',
      over: 'Over med ({enhet})',
      timer: 'timer',
      okter: 'økter',
      opptil: 'Rektors skjønn opp til',
      tabell: 'Grensen i timer og økter',
      klokketimer: 'Klokketimer',
    },
    steg: {
      arstimer: 'Årstimetall i faget',
      grense: 'Fraværsgrensen, 10 %',
      okter: 'Omregnet til økter på {minutter} min',
      innenfor: 'Innenfor grensen, hele økter',
      skjonn: 'Rektors skjønn, 15 %',
      skjonnOkter: 'Omregnet til økter på {minutter} min',
      skjonnInnenfor: 'Rektors skjønn, hele økter',
      innenforVerdi: '{innenfor} (over med {over})',
    },
    sjekk: {
      tittel: 'Sjekk fraværet',
      hjelp: 'Valgfritt. Skriv inn fraværet eleven har i faget, i økter på {minutter} minutter. Ingenting lagres.',
      hjelpTimer: 'Valgfritt. Skriv inn fraværet eleven har i faget, i klokketimer. Ingenting lagres.',
      udokumentert: 'Udokumentert fravær',
      udokumentertHjelp: 'Uten dokumentasjon, eller av andre grunner enn dem i forskriften, for eksempel bortvisning.',
      helse: 'Helsefravær',
      helseHjelp: 'Alt helserelatert fravær i faget, med egenmelding, legeerklæring eller uten dokumentasjon.',
      helseEtter: 'Av dette: etter at grensen ble nådd',
      helseEtterHjelp: 'Dokumentert av helsepersonell, eller med egenmelding når helsepersonell har dokumentert en tilstand som gir høyere risiko for fravær. Helsefravær før grensen ble nådd teller, også med legeerklæring.',
      delHelse: 'Noe av helsefraværet kom etter at grensen ble nådd, og er dokumentert av helsepersonell',
      andre: 'Dokumentert med andre grunner',
      andreListe: 'Grunnene som gjelder',
      andreHjelp: 'Velferd, lovpålagt oppmøte og de andre grunnene i § 9-8 b–i.',
      teller: 'Teller mot grensen',
      samlet: 'Alt fraværet',
      prosent: '{prosent} % av årstimetallet',
      prosentKort: '{prosent} %',
      iTimer: '{timer} klokketimer',
      stolpe: 'Fraværet som teller: {prosent} prosent av årstimetallet. Alt fraværet: {samlet} prosent. Grensen er 10 prosent, og rektors skjønn går til 15 prosent.',
      helseEtterTeller: 'Grensen var ikke nådd. Helsefravær teller til grensen er nådd, så {antall} av øktene med helsefravær «etter grensen» teller likevel.',
      helseEtterTellerTimer: 'Grensen var ikke nådd. Helsefravær teller til grensen er nådd, så {antall} av timene med helsefravær «etter grensen» teller likevel.',
      utfall: {
        innenfor: 'Innenfor grensen',
        skjonn: 'Mellom 10 og 15 prosent',
        over: 'Over 15 prosent',
      },
      utfallTekst: {
        innenfor: 'Eleven kan få karakter hvis faglæreren har nok grunnlag.',
        skjonn: 'Rektor kan avgjøre at eleven likevel får karakter, når årsaken gjør det klart urimelig at grensen skal gjelde. Faglæreren må ha nok grunnlag.',
        over: 'Eleven kan ikke få standpunktkarakter, eller halvårsvurdering med karakter ved slutten av skoleåret i et gjennomgående fag.',
      },
      iv: 'Det føres IV (ikke vurderingsgrunnlag) med fagmerknaden «{navn}»',
      varsel: 'Eleven kan ikke miste karakteren uten å ha fått skriftlig varsel i forkant.',
    },
    regler: 'Slik regnes grensen',
    veiviserKort: 'Varsel, vedtak og karakter',
    veiviserKortTekst: 'Steg for steg i veiviseren «Grunnlag for vurdering»',
  },
  eksamen: {
    tittel: 'Eksamen',
    kort: 'Eksamen',
    beskrivelse: 'Trekk og antall eksamener, oppmelding, gjennomføring og sensur, særskilt tilrettelegging, og utsatt, ny og særskilt eksamen.',
    innledning: 'Reglene for eksamen i videregående etter opplæringsforskrifta kapittel 9. Datoene står i kalenderen, og klage står i veiviseren.',
    antall: 'Eksamener på hvert trinn',
    gangen: 'Fra oppmelding til karakter',
    heleVeien: 'Gjelder hele veien',
    host: 'Høst',
    var: 'Vår',
    tilrettelegging: 'Tilrettelegging',
    ikkeBestatt: 'Når eleven ikke består eller ikke møter',
    merOpplaering: 'Mer opplæring',
    merOpplaeringTekst: 'Retten til mer opplæring i fag som ikke er bestått, og fristen for å melde seg.',
    videre: 'Videre',
    iFylket: 'I {fylke}',
    fagarket: 'Fagarket viser om eksamen i faget er sentralt eller lokalt gitt.',
  },
  provene: {
    tittel: 'Fag- og svenneprøven og de andre prøvene',
    kort: 'Fag- og svenneprøven',
    beskrivelse: 'Prøvene som sluttvurdering for lærlinger og kandidater: krav, oppmelding, prøvenemnda, karakterer, tilrettelegging, ny prøve og klage.',
    innledning: 'Fag- og svenneprøven, praksisbrevprøven og kompetanseprøven er sluttvurderingen i fag- og yrkesopplæringen. Veiene fram til prøven for lærlinger og kandidater står i Opplæringstilbud.',
    prover: 'Prøvene',
    gangen: 'Fra krav til resultat',
    heleVeien: 'Gjelder hele veien',
    ikkeBestatt: 'Når kandidaten ikke består eller ikke møter',
    merOpplaering: 'Mer opplæring på Vg3',
    merOpplaeringTekst: 'Retten til mer opplæring når fag- eller svenneprøven ikke er bestått.',
    videre: 'Videre',
    opplaeringskontor: 'Opplæringskontorene',
    iOpplaeringstilbud: 'I Opplæringstilbud: kontorene i hvert fylke',
    klageTekst: 'Klage på «ikke bestått» på fag- og svenneprøven og de andre prøvene.',
    udir: 'Fag- og svenneprøver hos Udir',
  },
  klage: {
    kort: 'Klage på karakter',
    beskrivelse: 'Steg for steg: begrunnelse, frist, hva skolen kan gjøre og klageinstansen.',
  },
  frister: {
    tittel: 'Kalender for eksamen',
    kort: 'Datoer og frister',
    beskrivelse: 'Oppmelding, trekk, eksamen, sensur og klage, fra august til juli, for elever, privatister og lærlinger.',
    neste: 'Neste dato',
    alle: 'Kalender for eksamen',
  },
  iRegelverket: 'I regelverket ({antall})',
};
