// UI-tekstar for modulen Vurdering på nynorsk. Same nøklar som vurdering.nb.ts.

export const vurderingNn = {
  tittel: 'Vurdering',
  innledning: 'Vurdering i fag og i orden og oppførsel i vidaregåande opplæring, etter opplæringsforskrifta kapittel 9: kva karakteren byggjer på, undervegs- og sluttvurdering, fritak og fråvær, og kva skolen gjer når eleven står i fare for ikkje å få karakter.',
  delFag: 'Vurdering i fag',
  delOrden: 'Orden og oppførsel',
  ikkeFunnet: 'Fann ikkje vegvisaren.',
  underveisSlutt: {
    tittel: 'Undervegs- og sluttvurdering',
    kort: 'Undervegs- og sluttvurdering',
    beskrivelse: 'Korleis kompetansemåla blir vurderte, og reglane for undervegs- og sluttvurdering, med vurderingsteksten i læreplanen for faget.',
    innledning: 'All vurdering før opplæringa i faget er slutt, er undervegsvurdering. Sluttvurderinga er standpunkt, eksamen og prøvene i fag- og yrkesopplæringa. Grunnlaget er alltid kompetansemåla i læreplanen.',
    skolearet: 'Skoleåret i eit fag som blir avslutta',
    figurTittel: 'Skoleåret med undervegsvurdering, halvårsvurdering, eksamen og standpunkt',
    underveis: 'Undervegs',
    heleAaret: 'heile året',
    halvaar: 'Halvår',
    eksamen: 'Eksamen',
    standpunkt: 'Standpunkt',
    maneder: 'aug,sep,okt,nov,des,jan,feb,mar,apr,mai,jun',
    tegnUnderveis: 'Undervegsvurdering, heile året',
    tegnHalvaar: 'Halvårsvurdering, midt i perioden',
    tegnEksamen: 'Eksamen, datoane frå Udir',
    tegnStandpunkt: 'Standpunkt, seinast dagen før sensur',
    forskjellen: 'Skilnaden',
    venstre: 'Undervegs',
    hoyre: 'Slutt',
    prinsipper: 'Slik blir kompetansemåla vurderte',
    iLaereplanen: 'I læreplanen for faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'Til dømes «engelsk vg1» eller «ENG1007»',
    velgFag: 'Vel eit fag for å sjå kva læreplanen seier om undervegs- og standpunktvurdering.',
    ingenFag: 'Ingen fag passar med søket.',
    underveisTekst: 'Undervegsvurdering',
    standpunktTekst: 'Standpunktvurdering',
    ingenTekst: 'Læreplanen har ingen eigen tekst om vurdering for dette faget.',
    tilFagarket: 'Heile læreplanen på fagarket: {fag}',
    fraGrep: 'Frå læreplanen {kode} i Grep.',
    annetFag: 'Vel eit anna fag',
    lasterFeil: 'Læreplanen kunne ikkje lastast. Prøv igjen.',
  },
  orden: {
    tittel: 'Orden og oppførsel',
    kort: 'Orden og oppførsel',
    beskrivelse: 'Skolereglane, karakterane G, Ng og Lg, varsel, standpunkt og klage.',
    innledning: 'Orden og oppførsel blir vurdert for seg, med skolereglane som grunnlag. Det skal ikkje trekkjast inn i vurderinga i fag, og kompetanse i fag skal ikkje trekkjast inn her.',
    iFylket: 'I {fylke}',
  },
  iRegelverket: 'I regelverket ({antall})',
};
