// UI-tekster for modulen Vurdering på bokmål. vurdering.nn.ts må ha de samme nøklene.

export const vurderingNb = {
  tittel: 'Vurdering',
  innledning: 'Vurdering i fag og i orden og oppførsel i videregående opplæring, etter opplæringsforskrifta kapittel 9: hva karakteren bygger på, underveis- og sluttvurdering, fritak og fravær, og hva skolen gjør når eleven står i fare for å ikke få karakter.',
  delFag: 'Vurdering i fag',
  delOrden: 'Orden og oppførsel',
  ikkeFunnet: 'Fant ikke veiviseren.',
  underveisSlutt: {
    tittel: 'Underveis- og sluttvurdering',
    kort: 'Underveis- og sluttvurdering',
    beskrivelse: 'Hvordan kompetansemålene vurderes, og reglene for underveis- og sluttvurdering, med vurderingsteksten i læreplanen for faget.',
    innledning: 'All vurdering før opplæringen i faget er slutt, er underveisvurdering. Sluttvurderingen er standpunkt, eksamen og prøvene i fag- og yrkesopplæringen. Grunnlaget er alltid kompetansemålene i læreplanen.',
    skolearet: 'Skoleåret i et fag som avsluttes',
    figurTittel: 'Skoleåret med underveisvurdering, halvårsvurdering, eksamen og standpunkt',
    underveis: 'Underveisvurdering',
    heleAaret: 'hele året',
    halvaar: 'Halvårsvurdering',
    eksamen: 'Eksamen',
    standpunkt: 'Standpunkt',
    maneder: 'aug,sep,okt,nov,des,jan,feb,mar,apr,mai,jun',
    tegnUnderveis: 'Underveisvurdering, hele året',
    tegnHalvaar: 'Halvårsvurdering, midt i perioden',
    tegnEksamen: 'Eksamen, datoene fra Udir',
    tegnStandpunkt: 'Standpunkt, senest dagen før sensur',
    forskjellen: 'Forskjellen',
    // Med mykt bindestrek, så ordet kan deles på smal skjerm.
    venstre: 'Underveis\u00advurdering',
    hoyre: 'Slutt\u00advurdering',
    prinsipper: 'Slik vurderes kompetansemålene',
    iLaereplanen: 'I læreplanen for faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'For eksempel «engelsk vg1» eller «ENG1007»',
    velgFag: 'Velg et fag for å se hva læreplanen sier om underveis- og standpunktvurdering.',
    ingenFag: 'Ingen fag passer søket.',
    underveisTekst: 'Underveisvurdering',
    standpunktTekst: 'Standpunktvurdering',
    ingenTekst: 'Læreplanen har ingen egen tekst om vurdering for dette faget.',
    tilFagarket: 'Hele læreplanen på fagarket: {fag}',
    fraGrep: 'Fra læreplanen {kode} i Grep.',
    annetFag: 'Velg et annet fag',
    lasterFeil: 'Læreplanen kunne ikke lastes. Prøv igjen.',
  },
  orden: {
    tittel: 'Orden og oppførsel',
    kort: 'Orden og oppførsel',
    beskrivelse: 'Skolereglene, karakterene G, Ng og Lg, varsel, standpunkt og klage.',
    innledning: 'Orden og oppførsel vurderes for seg, med skolereglene som grunnlag. Det skal ikke trekkes inn i vurderingen i fag, og kompetanse i fag skal ikke trekkes inn her.',
    iFylket: 'I {fylke}',
  },
  iRegelverket: 'I regelverket ({antall})',
};
