// UI-tekstar for modulen Vurdering på nynorsk. Same nøklar som vurdering.nb.ts.

export const vurderingNn = {
  tittel: 'Vurdering',
  innledning: 'Vurdering i fag og i orden og oppførsel i vidaregåande opplæring, etter opplæringsforskrifta kapittel 9: kva karakteren byggjer på, undervegs- og sluttvurdering, fritak og fråvær, og kva skolen gjer når eleven står i fare for ikkje å få karakter.',
  delFag: 'Vurdering i fag',
  delFravaer: 'Fråvær',
  delOrden: 'Orden og oppførsel',
  ikkeFunnet: 'Fann ikkje vegvisaren.',
  underveisSlutt: {
    tittel: 'Undervegs- og sluttvurdering',
    kort: 'Undervegs- og sluttvurdering',
    beskrivelse: 'Korleis kompetansemåla blir vurderte, og reglane for undervegs- og sluttvurdering, med vurderingsteksten i læreplanen for faget.',
    innledning: 'All vurdering før opplæringa i faget er slutt, er undervegsvurdering. Sluttvurderinga er standpunkt, eksamen og prøvene i fag- og yrkesopplæringa. Grunnlaget er alltid kompetansemåla i læreplanen.',
    skolearet: 'Skoleåret i eit fag som blir avslutta',
    figurTittel: 'Skoleåret med undervegsvurdering, halvårsvurdering, eksamen og standpunkt',
    underveis: 'Undervegsvurdering',
    heleAaret: 'heile året',
    halvaar: 'Halvårsvurdering',
    eksamen: 'Eksamen',
    standpunkt: 'Standpunkt',
    maneder: 'aug,sep,okt,nov,des,jan,feb,mar,apr,mai,jun',
    tegnUnderveis: 'Undervegsvurdering, heile året',
    tegnHalvaar: 'Halvårsvurdering, midt i perioden',
    tegnEksamen: 'Eksamen, datoane frå Udir',
    tegnStandpunkt: 'Standpunkt, seinast dagen før sensur',
    forskjellen: 'Skilnaden',
    // Med mykt bindestrek, så ordet kan deles på smal skjerm.
    venstre: 'Undervegs\u00advurdering',
    hoyre: 'Slutt\u00advurdering',
    prinsipper: 'Slik blir kompetansemåla vurderte',
    iLaereplanen: 'I læreplanen for faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'Til dømes «engelsk vg1» eller «ENG1007»',
    velgFag: 'Vel eit fag for å sjå kva læreplanen seier om undervegs- og standpunktvurdering.',
    ingenFag: 'Ingen fag passar med søket.',
    underveisTekst: 'Undervegsvurdering',
    standpunktTekst: 'Standpunktvurdering',
    ingenTekst: 'Læreplanen har ingen eigen tekst om vurdering for dette faget.',
    tilFagarket: 'Heile læreplanen på fagarket: {fag}',
    fraGrep: 'Frå læreplanen {kode} i Grep.',
    annetFag: 'Vel eit anna fag',
    lasterFeil: 'Læreplanen kunne ikkje lastast. Prøv igjen.',
  },
  orden: {
    tittel: 'Orden og oppførsel',
    kort: 'Orden og oppførsel',
    beskrivelse: 'Skolereglane, karakterane G, Ng og Lg, varsel, standpunkt og klage.',
    innledning: 'Orden og oppførsel blir vurdert for seg, med skolereglane som grunnlag. Det skal ikkje trekkjast inn i vurderinga i fag, og kompetanse i fag skal ikkje trekkjast inn her.',
    iFylket: 'I {fylke}',
  },
  fravaer: {
    tittel: 'Fråværsgrensa',
    kort: 'Fråværsgrensa',
    beskrivelse: 'Kor mykje fråvær eleven kan ha i eit fag, i timar og økter, med skjønet til rektor opp til 15 prosent og ein sjekk av fråværet.',
    innledning: 'Eleven kan ikkje ha meir enn 10 prosent fråvær i eit fag for å få standpunktkarakter. Vel faget eller skriv inn årstimetalet, og vel kor lange øktene er.',
    faget: 'Faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'Til dømes «engelsk vg1» eller «ENG1007»',
    ingenFag: 'Ingen fag med årstimetal passar søket.',
    annetFag: 'Vel eit anna fag',
    ellerTimer: 'Eller skriv inn årstimetalet',
    timer: 'Årstimetal',
    timerHjelp: 'Klokketimar i faget det skoleåret. Har fylket eit eige, høgare timetal, eller får eleven meir opplæring med færre timar, skriv inn det talet.',
    fraGrep: '{timer} timar i Grep',
    endreTimer: 'Skriv inn eit anna timetal',
    brukGrep: 'Bruk timane frå Grep',
    okter: 'Øktene',
    oktlengde: 'Lengd på øktene',
    minutter: '{antall} min',
    annen: 'Anna',
    annenEtikett: 'Minutt per økt',
    heleAaret: 'Heile årstimetalet blir alltid brukt, også når eleven byrjar seint eller byter fag. I eit nytt fag startar fråværet på null.',
    timerEnhet: '{antall} timar',
    oktEnhet: '{antall} økter',
    resultat: {
      tittel: 'Fråværsgrensa',
      tom: 'Vel eit fag eller skriv inn årstimetalet.',
      sammendrag: 'Innanfor med {innenfor}. Over med {over}.',
      grense: '10 %',
      skjonn: '15 %',
      innenfor: 'Innanfor med ({enhet})',
      over: 'Over med ({enhet})',
      timer: 'timar',
      okter: 'økter',
      opptil: 'Skjønet til rektor opp til',
      tabell: 'Grensa i timar og økter',
      klokketimer: 'Klokketimar',
    },
    steg: {
      arstimer: 'Årstimetal i faget',
      grense: 'Fråværsgrensa, 10 %',
      okter: 'Rekna om til økter på {minutter} min',
      innenfor: 'Innanfor grensa, heile økter',
      skjonn: 'Skjønet til rektor, 15 %',
      skjonnOkter: 'Rekna om til økter på {minutter} min',
      skjonnInnenfor: 'Skjønet til rektor, heile økter',
      innenforVerdi: '{innenfor} (over med {over})',
    },
    sjekk: {
      tittel: 'Sjekk fråværet',
      hjelp: 'Valfritt. Skriv inn fråværet eleven har i faget, i økter på {minutter} minutt. Ingenting blir lagra.',
      hjelpTimer: 'Valfritt. Skriv inn fråværet eleven har i faget, i klokketimar. Ingenting blir lagra.',
      udokumentert: 'Udokumentert fråvær',
      udokumentertHjelp: 'Utan dokumentasjon, eller av andre grunnar enn dei i forskrifta, til dømes bortvising.',
      helse: 'Helsefråvær',
      helseHjelp: 'Alt helserelatert fråvær i faget, med eigenmelding, legeerklæring eller utan dokumentasjon.',
      helseEtter: 'Av dette: etter at grensa vart nådd',
      helseEtterHjelp: 'Dokumentert av helsepersonell, eller med eigenmelding når helsepersonell har dokumentert ein tilstand som gir høgare risiko for fråvær. Helsefråvær før grensa vart nådd tel, også med legeerklæring.',
      delHelse: 'Noko av helsefråværet kom etter at grensa vart nådd, og er dokumentert av helsepersonell',
      andre: 'Dokumentert med andre grunnar',
      andreListe: 'Grunnane som gjeld',
      andreHjelp: 'Velferd, lovpålagt oppmøte og dei andre grunnane i § 9-8 b–i.',
      teller: 'Tel mot grensa',
      samlet: 'Alt fråværet',
      prosent: '{prosent} % av årstimetalet',
      prosentKort: '{prosent} %',
      iTimer: '{timer} klokketimar',
      stolpe: 'Fråværet som tel: {prosent} prosent av årstimetalet. Alt fråværet: {samlet} prosent. Grensa er 10 prosent, og skjønet til rektor går til 15 prosent.',
      helseEtterTeller: 'Grensa var ikkje nådd. Helsefråvær tel til grensa er nådd, så {antall} av øktene med helsefråvær «etter grensa» tel likevel.',
      helseEtterTellerTimer: 'Grensa var ikkje nådd. Helsefråvær tel til grensa er nådd, så {antall} av timane med helsefråvær «etter grensa» tel likevel.',
      utfall: {
        innenfor: 'Innanfor grensa',
        skjonn: 'Mellom 10 og 15 prosent',
        over: 'Over 15 prosent',
      },
      utfallTekst: {
        innenfor: 'Eleven kan få karakter dersom faglæraren har nok grunnlag.',
        skjonn: 'Rektor kan avgjere at eleven likevel får karakter, når årsaka gjer det klart urimeleg at grensa skal gjelde. Faglæraren må ha nok grunnlag.',
        over: 'Eleven kan ikkje få standpunktkarakter, eller halvårsvurdering med karakter ved slutten av skoleåret i eit gjennomgåande fag.',
      },
      iv: 'Det blir ført IV (ikkje vurderingsgrunnlag) med fagmerknaden «{navn}»',
      varsel: 'Eleven kan ikkje miste karakteren utan å ha fått skriftleg varsel på førehand.',
    },
    regler: 'Slik blir grensa rekna',
    tilVeiviser: 'Varsel, vedtak og grunnlag for karakter: vegvisaren «Grunnlag for vurdering»',
  },
  iRegelverket: 'I regelverket ({antall})',
};
