// UI-tekster for modulen Vurdering på bokmål. vurdering.nn.ts må ha de samme nøklene.

export const vurderingNb = {
  tittel: 'Vurdering',
  innledning: 'Vurdering i fag og i orden og oppførsel i videregående opplæring, etter opplæringsforskrifta kapittel 9 og 10: hva karakteren bygger på, underveis- og sluttvurdering og fravær. Eksamen, prøvene og klage på karakter står i Eksamen og klage.',
  delFag: 'Vurdering i fag',
  delKalkulator: 'Kalkulator',
  delOrden: 'Orden og oppførsel',
  delVeiviser: 'Veiviser',
  ikkeFunnet: 'Fant ikke veiviseren.',
  underveisSlutt: {
    tittel: 'Underveis- og sluttvurdering',
    kort: 'Underveis- og sluttvurdering',
    beskrivelse: 'Hvordan kompetansemålene vurderes, og reglene for underveis- og sluttvurdering, med vurderingsteksten i læreplanen for faget.',
    innledning: 'All vurdering før opplæringen i faget er slutt, er underveisvurdering. Sluttvurderingen er standpunkt, eksamen og prøvene i fag- og yrkesopplæringen. Grunnlaget er alltid kompetansemålene i læreplanen.',
    skolearet: 'Skoleåret i et fag som avsluttes',
    figurTittel: 'Skoleåret med underveisvurdering, halvårsvurdering, eksamen og standpunkt',
    underveis: 'Underveisvurdering',
    heleAaret: 'hele året',
    halvaar: 'Halvårsvurdering',
    eksamen: 'Eksamen',
    standpunkt: 'Standpunkt',
    maneder: 'aug,sep,okt,nov,des,jan,feb,mar,apr,mai,jun',
    tegnUnderveis: 'Underveisvurdering, hele året',
    tegnHalvaar: 'Halvårsvurdering, midt i perioden',
    tegnEksamen: 'Eksamen, datoene fra Udir',
    tegnStandpunkt: 'Standpunkt, senest dagen før sensur',
    forskjellen: 'Forskjellen',
    // Med mykt bindestrek, så ordet kan deles på smal skjerm.
    venstre: 'Underveis\u00advurdering',
    hoyre: 'Slutt\u00advurdering',
    prinsipper: 'Slik vurderes kompetansemålene',
    iLaereplanen: 'I læreplanen for faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'For eksempel «engelsk vg1» eller «ENG1007»',
    velgFag: 'Velg et fag for å se hva læreplanen sier om underveis- og standpunktvurdering.',
    ingenFag: 'Ingen fag passer søket.',
    underveisTekst: 'Underveisvurdering',
    standpunktTekst: 'Standpunktvurdering',
    ingenTekst: 'Læreplanen har ingen egen tekst om vurdering for dette faget.',
    tilFagarket: 'Hele læreplanen på fagarket: {fag}',
    fraGrep: 'Fra læreplanen {kode} i Grep.',
    annetFag: 'Velg et annet fag',
    lasterFeil: 'Læreplanen kunne ikke lastes. Prøv igjen.',
  },
  orden: {
    tittel: 'Orden og oppførsel',
    kort: 'Orden og oppførsel',
    beskrivelse: 'Skolereglene, karakterene G, Ng og Lg, varsel, standpunkt og klage.',
    innledning: 'Orden og oppførsel vurderes for seg, med skolereglene som grunnlag. Det skal ikke trekkes inn i vurderingen i fag, og kompetanse i fag skal ikke trekkes inn her.',
    iFylket: 'I {fylke}',
  },
  fravaer: {
    tittel: 'Fraværsgrensen',
    kort: 'Fraværsgrensen',
    beskrivelse: 'Hvor mye fravær eleven kan ha i et fag, i timer og økter, med rektors skjønn opp til 15 prosent og en sjekk av fraværet.',
    innledning: 'Eleven kan ikke ha mer enn 10 prosent fravær i et fag for å få standpunktkarakter. Velg faget eller skriv inn årstimetallet, og velg hvor lange øktene er.',
    faget: 'Faget',
    sokFag: 'Søk etter fag eller fagkode',
    sokPlassholder: 'For eksempel «engelsk vg1» eller «ENG1007»',
    ingenFag: 'Ingen fag med årstimetall passer søket.',
    annetFag: 'Velg et annet fag',
    ellerTimer: 'Eller skriv inn årstimetallet',
    timer: 'Årstimetall',
    timerHjelp: 'Klokketimer i faget det skoleåret. Har fylket et eget, høyere timetall, eller får eleven mer opplæring med færre timer, skriv inn det tallet.',
    fraGrep: '{timer} timer i Grep',
    endreTimer: 'Skriv inn et annet timetall',
    brukGrep: 'Bruk timene fra Grep',
    okter: 'Øktene',
    oktlengde: 'Lengde på øktene',
    minutter: '{antall} min',
    annen: 'Annen',
    annenEtikett: 'Minutter per økt',
    heleAaret: 'Hele årstimetallet brukes alltid, også når eleven begynner sent eller bytter fag. I et nytt fag starter fraværet på null.',
    timerEnhet: '{antall} timer',
    oktEnhet: '{antall} økter',
    resultat: {
      tittel: 'Fraværsgrensen',
      tom: 'Velg et fag eller skriv inn årstimetallet.',
      sammendrag: 'Innenfor med {innenfor}. Over med {over}.',
      grense: '10 %',
      skjonn: '15 %',
      innenfor: 'Innenfor med ({enhet})',
      over: 'Over med ({enhet})',
      timer: 'timer',
      okter: 'økter',
      opptil: 'Rektors skjønn opp til',
      tabell: 'Grensen i timer og økter',
      klokketimer: 'Klokketimer',
    },
    steg: {
      arstimer: 'Årstimetall i faget',
      grense: 'Fraværsgrensen, 10 %',
      okter: 'Omregnet til økter på {minutter} min',
      innenfor: 'Innenfor grensen, hele økter',
      skjonn: 'Rektors skjønn, 15 %',
      skjonnOkter: 'Omregnet til økter på {minutter} min',
      skjonnInnenfor: 'Rektors skjønn, hele økter',
      innenforVerdi: '{innenfor} (over med {over})',
    },
    sjekk: {
      tittel: 'Sjekk fraværet',
      hjelp: 'Valgfritt. Skriv inn fraværet eleven har i faget, i økter på {minutter} minutter. Ingenting lagres.',
      hjelpTimer: 'Valgfritt. Skriv inn fraværet eleven har i faget, i klokketimer. Ingenting lagres.',
      udokumentert: 'Udokumentert fravær',
      udokumentertHjelp: 'Uten dokumentasjon, eller av andre grunner enn dem i forskriften, for eksempel bortvisning.',
      helse: 'Helsefravær',
      helseHjelp: 'Alt helserelatert fravær i faget, med egenmelding, legeerklæring eller uten dokumentasjon.',
      helseEtter: 'Av dette: etter at grensen ble nådd',
      helseEtterHjelp: 'Dokumentert av helsepersonell, eller med egenmelding når helsepersonell har dokumentert en tilstand som gir høyere risiko for fravær. Helsefravær før grensen ble nådd teller, også med legeerklæring.',
      delHelse: 'Noe av helsefraværet kom etter at grensen ble nådd, og er dokumentert av helsepersonell',
      andre: 'Dokumentert med andre grunner',
      andreListe: 'Grunnene som gjelder',
      andreHjelp: 'Velferd, lovpålagt oppmøte og de andre grunnene i § 9-8 b–i.',
      teller: 'Teller mot grensen',
      samlet: 'Alt fraværet',
      prosent: '{prosent} % av årstimetallet',
      prosentKort: '{prosent} %',
      iTimer: '{timer} klokketimer',
      stolpe: 'Fraværet som teller: {prosent} prosent av årstimetallet. Alt fraværet: {samlet} prosent. Grensen er 10 prosent, og rektors skjønn går til 15 prosent.',
      helseEtterTeller: 'Grensen var ikke nådd. Helsefravær teller til grensen er nådd, så {antall} av øktene med helsefravær «etter grensen» teller likevel.',
      helseEtterTellerTimer: 'Grensen var ikke nådd. Helsefravær teller til grensen er nådd, så {antall} av timene med helsefravær «etter grensen» teller likevel.',
      utfall: {
        innenfor: 'Innenfor grensen',
        skjonn: 'Mellom 10 og 15 prosent',
        over: 'Over 15 prosent',
      },
      utfallTekst: {
        innenfor: 'Eleven kan få karakter hvis faglæreren har nok grunnlag.',
        skjonn: 'Rektor kan avgjøre at eleven likevel får karakter, når årsaken gjør det klart urimelig at grensen skal gjelde. Faglæreren må ha nok grunnlag.',
        over: 'Eleven kan ikke få standpunktkarakter, eller halvårsvurdering med karakter ved slutten av skoleåret i et gjennomgående fag.',
      },
      iv: 'Det føres IV (ikke vurderingsgrunnlag) med fagmerknaden «{navn}»',
      varsel: 'Eleven kan ikke miste karakteren uten å ha fått skriftlig varsel i forkant.',
    },
    regler: 'Slik regnes grensen',
    veiviserKort: 'Varsel, vedtak og karakter',
    veiviserKortTekst: 'Steg for steg i veiviseren «Grunnlag for vurdering»',
  },
  iRegelverket: 'I regelverket ({antall})',
};
